### ISSUE TITLE
[REQUEST] - LootSheetNPC5e compatibility

### ISSUE THREAD

**Issue by ravingdragoon** [fantasycalendar/FoundryVTT-ItemPiles#10]
**Is your feature request related to a problem? Please describe.**
I am frustrated at not being able to change the actor type from a character to an NPC, even when setting the actor type to "npc" instead of "character" in the settings.

**Describe the solution you'd like**
Ideally I would like to be able to set the module up so that by default it drops an item as a loot sheet.

**Describe alternatives you've considered**
Setting the actor type to NPC and then converting to loot sheet. This does not currently work as I cannot change the actor type.

**Comment by Haxxer** [comment]
You can change the default setting to NPC, then delete the default item pile to make it recreate itself as an NPC, whose sheet you can then change manually. Does this solve your problem?

**Comment by ravingdragoon** [comment]
Yes, it did solve the problem. I missed deleting the already created actor after changing the actor type to NPC.
