### ISSUE TITLE
[BUG] - Private trades for players not working - Worlds Without Number system

### ISSUE THREAD

**Issue by StevenR123** [fantasycalendar/FoundryVTT-ItemPiles#102]
**Describe the bug**
Private trades between players does not work.
Public trades works, and private trades with GM work,

**To Reproduce**
1. As a player initiate a private trade with another player
2. Put item or currency up for trade
3. Accept on both ends

**Expected behavior**
Trade windows disappear without anything being traded or a private chat card being made.

**Setup:**
 - Foundry Version: 0.8.9
 - System Version: Worlds Without Number 0.9.9c
 - Item Piles Version: 1.4.8
 - Browser & version Google Chrome 101.0.4951.67

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - Advanced Macros
 - Backgroundless Pins
 - Better Text Drawings
 - Combat Utility Belt
 - DFreds Droppables
 - Drag Ruler
 - GM Notes
 - Health Estimate
 - Initiative Double Click
 - Less Fog
 - lib - Color Settings
 - Lib: Document Sheet Registrar
 - Map Coordinates
 - Monk's Enhanced Journal
 - Monk's Scene Navigation
 - Pin Cushion
 - Pings
 - Point of Interest Teleporter
 - PopOut!
 - Settings Extender
 - Simple Calendar
 - Simplefog - Manual Fog of War
 - Split Journal
 - The Forge: More Awesomeness
 - The Furnace
 - Turn Marker
 - Universal Battlemap Importer

**Additional context**
Public trades between players works.
Private trades between GM and players works.

**Comment by Haxxer** [comment]
After some investigation, this is due to the GM being the only one who can authorize trades between users. Private trades lets no one know of this fact, even after completion, but due to the aforementioned limitation, the trade simply gets ignored.
