### ISSUE TITLE
[REQUEST] - Reduction in the value of objects

### ISSUE THREAD

**Issue by Kaitiou** [fantasycalendar/FoundryVTT-ItemPiles#103]
My players have a habit of looting ALL the equipment of the enemies. By selling it to an NPC (for example, those that are created with the "MerchantSheetNPC" or "Loot Sheet NPC 5e" modules), they quickly make a small fortune that they shouldn't be getting, since it's second-hand equipment and, according to the manual, "most of the time it will be worthless."

Well, "worthless" sounds excessive to me, but I do think they should be able to sell it for much less, maybe 10-15% of its value.

And this is where I think your module can bring GREAT value: the module could allow you to configure the pile to reduce the value of items by percentage when you transfer them to your inventory. I imagine it as a global "value percentage" setting (editable from module properties) and an optional value in each item pile, which would overwrite the general value.
Let's imagine that a lootable goblin carries a 25 GP scimitar, and you want the player to only be able to sell it for 10% of its value: you set up the sheet for it and then, when picked up, the item would go into his inventory with the same properties as the original, but reducing its value to 2' 5GP.

Moreover, it would be ideal if, in the transfer process, I added a suffix to the name of the item, such as "Long sword [2nd hand]", to quickly distinguish when you are going to sell trash from the normal valuables.

Please consider it, I think it would be very helpful. Thank you!

**Comment by Haxxer** [comment]
I am creating a merchant-type item pile that will be able to handle something selling things, which will be native to the Item Piles system.

However, "trash" items is not something that is system agnostic and highly subjective, as every system dictates how its items are set up, not Item Piles. Thus, it would be far from feasible to make something that covers [every system that Item Piles supports](https://github.com/fantasycalendar/FoundryVTT-ItemPiles#natively-supported-systems).

However, I would recommend looking into the [API and hooks](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/wiki). With this, you could create a world script that would look at items and then reduce the value of items as they get transferred.

**Comment by Kaitiou** [comment]
Nice answer, thank you so much :)
