### ISSUE TITLE
[REQUEST] Option to remove items from the list if 0 remaining

### ISSUE THREAD

**Issue by Duckrollz** [fantasycalendar/FoundryVTT-ItemPiles#104]
**Is your feature request related to a problem? Please describe.**
This does not refer to the already existing feature of deleting an empty pile, but for longer term containers that are taken from and added to often, like a player stronghold or ship cargo. These piles get big and if an item type is added once it can never be removed again, even by the GM. 

**Describe the solution you'd like**
A tick box for removing the listing when the number of items reaches 0, rather than displaying that there are none left remaining. 

**Describe alternatives you've considered**
Alternatively just a way for a GM to delete the listing. 

**Additional context**
This can also be useful when setting up a treasure chest, players open it to find 0 swords and 1 spear, this can be confusing as from their perspective it never had a sword in it in the first place, the GM just changed their mind when putting the loot into the container for them.

**Comment by Haxxer** [comment]
This is then a bug rather than a request. Please open a bug report and a detailed description how to reproduce this.

**Comment by Duckrollz** [comment]
I'm confused as to how this is a bug, as the text displayed is "None left..." suggesting that the number of items being 0 was anticipated already and it was decided to leave the item listing in on purpose.

**Comment by Haxxer** [comment]
Apologies, I misunderstood your query. This was a deliberate design choice as to not change the height of the item list, preventing multiple users interacting with the item from causing others to take the wrong item.

If player 1 wants to take item 1, and player 2 wants to take item 2, if item 1 is removed from the list when player 1 takes it, player 2's cursor is now over item 3, which they could accidentally take.

I'll evaluate the request, but you can certainly see how it would be a problem, yes?

**Comment by Duckrollz** [comment]
Yes, absolutely. Perhaps a GM function to trim the list of empty items only if no players are viewing it? Or an option to lock the list for players, then trim it?
