### ISSUE TITLE
[BUG] - unable to complete trade on PF2

### ISSUE THREAD

**Issue by jpmiers** [fantasycalendar/FoundryVTT-ItemPiles#105]
**Describe the bug**
Items do not transfer upon accepting a trade. Issue is only reproducible on a single world. Other pf2 worlds have no issues and function normally. Module list is identical in all worlds.

**To Reproduce**
1. Go to request trade
2. select user to trade with and send trade request
3. drag and drop item into popup and hit accept
4. Player 2 accepts trade
5. chat message changes to trade completed. Trade popup closes. Item does not get transfered and error populates in console log.

**Expected behavior**
The item negotiated for in the trade window should be transferred to the other character sheet.

**Screenshots**
![image](https://user-images.githubusercontent.com/90874471/170847965-42e9f121-2c07-479d-bd3a-5fe26b8845a6.png)

**Setup:**
 - Foundry Version: v9.269
 - System Version: pathfinder 2nd edition: 3.10.4.11747
 - Item Piles Version: 1.4.8
 - Chrome 101.0.4951.67

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**
I have tried reinstalling item piles on foundry. Issue with same world persists.

**Comment by Haxxer** [comment]
I believe this has been fixed in 2.0.0 and onwards
