### ISSUE TITLE
[BUG] - Actor sheet UI doesn't open for players

### ISSUE THREAD

**Issue by King-Wedgie** [fantasycalendar/FoundryVTT-ItemPiles#106]
**Describe the bug**
Actor sheet UI doesn't display for players, only the default Item Piles UI.

**To Reproduce**
1) Join session as a player
2) Ctrl + double-click an item pile

**Setup:**
 - **Foundry** v9.269
 - Tested in **Mausritter** 0.1.4 and **DnD5e** 1.6.2
 - **Piles** v1.4.8
 - **Firefox** 101.0; **Chrome** 102.0.5005.63

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**
Works fine for GMs, so I assume it's a socketlib issue

**Comment by Haxxer** [comment]
Are the players owners of the actor?

**Comment by King-Wedgie** [comment]
Owners of their respective character tokens, yes; owners of the item pile actor, no. Setting the the players as owners of the pile does give them access to the default actor UI but also gives them the usual editing power that being an owner gives.

I now realize I may be asking for a use case that isn't exactly covered by Item Piles. This is specifically for the Mausritter system, as it uses individual item cards that you drag around on a grid to represent inventory rather than a list with a quantity attached for each item.
![image](https://user-images.githubusercontent.com/73143074/172029656-0eb96e9a-7cf4-4b07-acfa-376eaa8ceaeb.png)
![image](https://user-images.githubusercontent.com/73143074/172029749-79703c9f-5a4f-4c45-a0b3-62bd4eab8134.png)
The intention is that the players would open the pile and drag items directly out of the storage sheet onto their character sheets. I've been looking for a module that would let players do this without giving them full editing permissions, but it only just occurred to me that items cards can only be moved around by the actor owner. May have to give the system developer a ping about implementing what I'm thinking of.

**Comment by Haxxer** [comment]
Yes, only owners of the item piles and the actors have the permission to interact with them as such. Closing ticket :)
