### ISSUE TITLE
[SYSTEM] - Forbidden Lands

### ISSUE THREAD

**Issue by aMediocreDad** [fantasycalendar/FoundryVTT-ItemPiles#109]
> **Note** **Ref:** https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/issues/221

# **[Forbidden Lands](https://foundryvtt.com/packages/forbidden-lands)**

### **Currencies**:

- **Name**: "Gold",
    - **Path**: `data.currency.gold`,
    - **Image**: "icons/commodities/currency/coin-embossed-crown-gold.webp"
- **Name**: "Silver",
    - **Path**: `data.currency.silver`,
    - **Image**: "icons/commodities/currency/coin-engraved-moon-silver.webp"
- **Name**: "Copper",
    - **Path**: `data.currency.copper`,
    - **Image**: "icons/commodities/currency/coin-engraved-waves-copper.webp"

**Comment by Haxxer** [comment]
Added in 2.0.3
