### ISSUE TITLE
[BUG] - Item Piles doesn't seem to work with DFreds Droppables

### ISSUE THREAD

**Issue by HonzoNebro** [fantasycalendar/FoundryVTT-ItemPiles#11]
**Describe the bug**
ItemPiles doesn't seem to work with DFreds-Droppables

**To Reproduce**
1. Create a DnD5e world, and activate both Item Piles and DFreds Droppanles, Drefs will require libWrapper
2. Open the item compendium and drag an item to the canvas
3. Nothing will happend, a popup error will be shown
4. In console, you'll see an arror like this one

**Expected behavior**
No issues?

**Screenshots**
https://i.imgur.com/y834YE1.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge (chromium)
 - Version 96.0.1054.62 64 bits

**Comment by Haxxer** [comment]
I assume you didn't try without DFred's Droppables, because the error persists without it enabled. This is because I hadn't considered dropping items from compendiums, but I'll fix this in 1.0.3.

**Comment by HonzoNebro** [comment]
You are correct, it wortks from a character sheet. Didn't know that was the "expected" way of using it.

**Comment by Haxxer** [comment]
Fixed in 1.0.3
