### ISSUE TITLE
[WFRP 4ed] Improvements

### ISSUE THREAD

**Issue by GregorHak** [fantasycalendar/FoundryVTT-ItemPiles#110]
With v1.4.6 ItemPiles work for Warhammer 4ed, but background image look poorly (see image). Also, Container items do not work, you can't pack bottle to chest etc.. Items like: Weapon, Ammunition, Armor and Trapping work well. Can you deal with it?
![obraz](https://user-images.githubusercontent.com/99994770/178581019-3996f3d6-e421-48ce-8202-a15935bfab95.png)
![obraz](https://user-images.githubusercontent.com/99994770/178581037-728db0d7-94f7-4c4c-bd5d-c1d5f8f3b6a1.png)

**Comment by Haxxer** [comment]
Please follow the bug report ticket template.
