### ISSUE TITLE
[BUG] - [WFRP 4ed] background and Container items

### ISSUE THREAD

**Issue by GregorHak** [fantasycalendar/FoundryVTT-ItemPiles#111]
**Describe the bug**
With v1.4.6 ItemPiles work for Warhammer 4ed, but background image look poorly (see image). Also, Container items do not work, you can't pack bottle to chest etc.. Items like: Weapon, Ammunition, Armor and Trapping work well.

**Expected behavior**
Change background and add possibility to drop Container items in ItemPile

**Screenshots**
![obraz](https://user-images.githubusercontent.com/99994770/178603980-056e40bb-5017-4f1e-9fee-6fd2b1250bc0.png)
![obraz](https://user-images.githubusercontent.com/99994770/178603995-57908e4f-a1ba-4c82-b05d-c64c86e946cd.png)

**Setup:**
 - Foundry Version: [e.g. 9.269]
 - System Version: [e.g. Warhammer 4ed 5.3.0]
 - Item Piles Version: [e.g. 1.4.8]

**Comment by Haxxer** [comment]
Container was specifically excluded by BrotherAxel here:
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/69

If you still want to include it, you can modify the item filters in the module settings.

As for the styling of the window, it seems that WFRP4e has some heavy styling baked into the system, which the module cannot take into account, as it supports many systems already.

**Comment by StevenEvans1966** [comment]
can I recommend https://github.com/cswendrowski/FoundryVTT-Custom-CSS this can be used to fix the issue

**Comment by Haxxer** [comment]
Closing as won't fix.
