### ISSUE TITLE
[REQUEST] - Support for PF2e Mystifying

### ISSUE THREAD

**Issue by Vaizt** [fantasycalendar/FoundryVTT-ItemPiles#113]
**Is your feature request related to a problem? Please describe.**

As a GM, this module is a pretty nice addition, especially when one of your players has a character than can craft and hand things out daily. However, in PF2e players have to identify their items and it takes time to do so. You might even trade it to someone else to hold on to for them to identify later. However, when you try to trade these mystified items, it will instead tell you what the item is.

**Describe the solution you'd like**

Simply check and apply mystification when present, allowing players to trade mystified items in PF2e without spoiling the item for them.

**Describe alternatives you've considered**

**Additional context**

**Comment by Haxxer** [comment]
Fixed in 2.2.2
