### ISSUE TITLE
[BUG] New tokens are always inserted empty item-piles flags

### ISSUE THREAD

**Issue by mkahvi** [fantasycalendar/FoundryVTT-ItemPiles#114]
**Describe the bug**
The module inserts empty flag object to all tokens.

**To Reproduce**
1. Create a token.

**Expected behavior**
No empty flags to pad data pointlessly.

**Screenshots**

![Screenshot 2022-07-23 214415](https://user-images.githubusercontent.com/8120158/180618793-c3372f34-3cd1-4138-9581-568f04fa7fc4.png)

**Setup:**
 - Foundry Version: 9.269
 - System Version: PF1 0.81.0
 - Item Piles Version: 1.4.8
 - Browser & version Electron

**Active modules:**
 - Item Piles
 - libwrapper

**Additional context**
Unlinked tokens are most obvious with this since they get it in the overrides.

**Comment by Haxxer** [comment]
Is this a problem? Does it affect your performance?

**Comment by mkahvi** [comment]
It's mostly unnecessary data padding for tokens. Not much, but it can stack up with large worlds for no good reason.
