### ISSUE TITLE
[BUG] - Item Piles does not work propperly on PF1e

### ISSUE THREAD

**Issue by ZzinnerGamer** [fantasycalendar/FoundryVTT-ItemPiles#115]
Item Piles icon doesn't show up on pc or npc sheets and the macros doesnt work at all, everything is needed to be set manually on sheet configuration.

![item piless](https://user-images.githubusercontent.com/57156790/183201203-9d4a40ed-7c5d-4bc3-a4ca-a47a60d79337.gif)

![imagen](https://user-images.githubusercontent.com/57156790/183197381-a0daf19f-4c60-4829-afff-a63b8b5ad52b.png)

![imagen](https://user-images.githubusercontent.com/57156790/183195557-551c2cca-19e0-4f34-8613-c76baa730e42.png)

![imagen](https://user-images.githubusercontent.com/57156790/183193523-6856f824-5504-4651-907e-c1e068de98dc.png)

![imagen](https://user-images.githubusercontent.com/57156790/183187135-f1906bc6-d5b7-4f1a-a769-bdcdae1e0372.png)

**Setup:**
 - Foundry Version: [9.269]
 - System Version: [Pathfinder 1e 0.81.1]
 - Item Piles Version: [1.4.8]
 - Browser & version [Foundry Launcher]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - Tidy UI - Game Settings

**Comment by Haxxer** [comment]
Cannot reproduce in 0.81.1 of PF1;

![image](https://user-images.githubusercontent.com/12858387/183222411-90c0af09-9c36-4782-ac12-9d6d5e86db72.png)

I would recommend reinstalling Item Piles

**Comment by Haxxer** [comment]
Confirmed to be caused by Libwrapper.
