### ISSUE TITLE
[REQUEST] - Execute macro first time the pile is opened

### ISSUE THREAD

**Issue by FeelTheWay** [fantasycalendar/FoundryVTT-ItemPiles#116]
**The problem**
I have a macro who generate a random loot from a Loot Table to populate the Pile
But the macro is executed every time an action is fired by the pile. (Open, close, get etc)

**The new feature **
Have a macro that will be fired only the first time the pile is opened by a token.

**Comment by Haxxer** [comment]
If you add `console.log(args)`, you can see the action that caused the macro to be executed. You will have to filter when you want this to happen. Closing as intended.

**Comment by FeelTheWay** [comment]
args is not defined.

**Comment by Haxxer** [comment]
Do you have the Advanced Macros module installed and active? Foundry doesn't send `args` by default.

**Comment by FeelTheWay** [comment]
Oh yes it's ok now :) Thank you.
