### ISSUE TITLE
[BUG] - Item Pile puts other items of the npc as loot 

### ISSUE THREAD

**Issue by valhallatoys** [fantasycalendar/FoundryVTT-ItemPiles#117]
converting an npc to item pile not only puts the inventory but also the class, feats and abilities of the creature as loot

**To Reproduce**
1. select npc 
2. use macro the macro to convert in to an item pile [ if (!canvas.tokens.controlled.length) return;
ItemPiles.API.turnTokensIntoItemPiles(canvas.tokens.controlled)]

**Expected behavior**
just put the inventary on the loot not the feats, class and abilities 

**Screenshots**
![image](https://user-images.githubusercontent.com/37681655/185005841-1cf7efcd-f367-455c-ab75-d962251e218d.png) this is the inventory that should only appear in item pile.

![image](https://user-images.githubusercontent.com/37681655/185005990-16c6f581-5434-4e2a-bfe7-71c73d9742b7.png)
and this is the result of turn into itempile 

**Setup:**
 - Foundry Version: 9.269
 - System Version: 3.5e SRD 0.99.13
 - Item Piles Version: 1.4.8
 - Browser & version Opera GX LVL 4 (core: 89.0.4447.64)

**Active modules:**
![image](https://user-images.githubusercontent.com/37681655/185006482-2b34cbd0-4efb-47ad-94c0-1946a8f4e6b4.png)

![image](https://user-images.githubusercontent.com/37681655/185006516-986bb48b-e56b-4836-96b3-956fbf280582.png)

![image](https://user-images.githubusercontent.com/37681655/185006552-0df0604e-2a45-4f4a-8626-26fb593121ad.png)

**Comment by Haxxer** [comment]
This is intended behaviour. Please configure the module with the proper settings to detect the right items.
