### ISSUE TITLE
[REQUEST] - Make the 'open lid' sound audible to all players, not just the person opening. 

### ISSUE THREAD

**Issue by nirurin** [fantasycalendar/FoundryVTT-ItemPiles#119]
I have a typical zelda-style chest opening sound set up when looting a chest, but it only plays for the person who opens it first. Everyone else just gets... silence. 

I could set it to an 'on interact' macro instead, but then it -also- plays when they close the chest, which isn't ideal lol.

**Comment by Haxxer** [comment]
If you use advanced macros, Item Piles also passes along an `args` parameter to macros executed by it, you can then filter by that. However, I will make sounds play for everyone.

**Comment by nirurin** [comment]
Thank you. I'm back to using monks journal for loot (with MATT) but I think
using item piles for it would be tidier. I'd just like the sounds to work!
Will it be in a v9 update or only v10?
