### ISSUE TITLE
[REQUEST-SYSTEM SUPPORT] Star Wars: Saga Edition

### ISSUE THREAD

**Issue by xBassimon** [fantasycalendar/FoundryVTT-ItemPiles#122]
# **[https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition]**

### **Actor Class Type**: "character"

*The actor class type is the type of actor that will be used for the default item pile actor that is created on first item drop.*

D&D5e system example: `character`

### **Item Quantity Attribute**: "this.data.data.quantity"

*The item quantity attribute is the path to the attribute on items that denote how many of that item that exists.*

D&D5e system example: `data.quantity`

### **Item Filters**: "affiliation, background, class, beast quality, destiny, feat, forcePower, forceRegimen, forceSecret, forceTechnique, species, talent, template, trait, vehicleSystem, "

*Item filters actively remove items from the item pile inventory UI that users cannot loot, such as spells, feats, and classes.*

D&D5e system example: `spell, feat, class`

### **Item Similarities**: type, name, strippable, hasPrerequisites, modifiable, hasLevels

*Item similarities determines how item piles detect similarities and differences in the system.*

D&D5e system example: `name, type`

### **Currencies**:

*Currencies in item piles are a list of names, attribute paths, and images - the attribute path is relative to the actor.data.*

- **Name**: Credits
    - **Path**: actor.credits
    - **Image**: ----
    
D&D5e system example:

- **Name**: "Platinum Coins",
    - **Path**: "data.currency.pp",
    - **Image**: "icons/commodities/currency/coin-inset-snail-silver.webp"
- **Name**: "Gold Coins",
    - **Path**: "data.currency.gp",
    - **Image**: "icons/commodities/currency/coin-embossed-crown-gold.webp"
- **Name**: "Electrum Coins",
    - **Path**: "data.currency.ep",
    - **Image**: "icons/commodities/currency/coin-inset-copper-axe.webp"
- **Name**: "Silver Coins",
    - **Path**: "data.currency.sp",
    - **Image**: "icons/commodities/currency/coin-engraved-moon-silver.webp"
- **Name**: "Copper Coins",
    - **Path**: "data.currency.cp",
    - **Image**: "icons/commodities/currency/coin-engraved-waves-copper.webp"

**Comment by Haxxer** [comment]
Added in 2.0.3
