### ISSUE TITLE
[BUG] - Show pile to players opens the sheet for the GM but not for the players

### ISSUE THREAD

**Issue by riccisi** [fantasycalendar/FoundryVTT-ItemPiles#124]
**Describe the bug**
After configuring an actor as item pile -> merchant, if you try to open for the players, his sheet it is displayed to the GM but not to the players

**To Reproduce**
1. Open an actor sheet
2. Click on item pile configuration
3. Check 'enable' on the item pile main settings and 'is merchant' in the merchant settings
4. Click on 'Update item piles' and close both windows.
5. Click on 'Item piles:  Show pile to players' on the right click menu of the configured actor.
6. The sheet is displayed for the GM but not to the players.

**Expected behavior**
The sheet should be displayed for the connected players.

**Screenshots**
![CleanShot 2022-09-09 at 15 59 10@2x](https://user-images.githubusercontent.com/6490765/189369037-e73bc4f1-3bff-45d5-8c4a-c11d3456b52e.png)

**Setup:**
 - Foundry Version: [e.g. 9.269]
 - System Version: [e.g. DND5e 1.6.2]
 - Item Piles Version: [e.g. 2.0.1]
 - Brave Browser [Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (x86_64)](https://brave.com/latest/)

**Comment by Haxxer** [comment]
Fixed in 2.0.3
