### ISSUE TITLE
ITEM PILES IS NOT FOUNDRY V10 COMPATIBLE

### ISSUE THREAD

**Issue by Haxxer** [fantasycalendar/FoundryVTT-ItemPiles#126]
That's it. That's the bug. Please do not create bugs relating to Foundry V10.

**Comment by gubacelar** [comment]
It's something on the roadmap?

**Comment by Haxxer** [comment]
I released 2.0.0 yesterday. Please give me some time.

**Comment by gubacelar** [comment]
sorry I didn't mean it. I love your modules and I know the development process is hard. You are an awesome developer.

**Comment by RavenknightDM** [comment]
This mod is why I'm staying with 9. :P

**Comment by leemahn** [comment]
Same here.  I'm not updated to v10 of Foundry VTT until Item Piles is supportive of it.  I have too many "piles" on my maps to abandon them.

**Comment by Haxxer** [comment]
The more the V9 version can be tested by you guys, the faster I can get on updating Item Piles for V10 :)

**Comment by leemahn** [comment]
> The more the V9 version can be tested by you guys, the faster I can get on updating Item Piles for V10 :)

Are you needing more input from v9 experiences to help you complete updates to v10 compatibility?

I can tell you one thing I've found - if you try to "Split X Ways" when there are items (not just currency) in the pile... the items never transfer to anyone.  At least they have not for any of my players.

They can take items directly.  It's just the "Split" option (even when sharing items is turned on) that doesn't work.

**Comment by Haxxer** [comment]
Thank you, issues like these should ideally be created on this repository so that I know about them and can easily fix them

**Comment by leemahn** [comment]
> Thank you, issues like these should ideally be reported on this repository as a bug ticket so that I know about them and can easily fix them

Ah yes.. fair.  So, are you in need of more v9 input before you'll be able to move up to v10?

**Comment by Haxxer** [comment]
Precisely. I rewrote the _entire_ module with the 2.0.0 update. If I leave any bugs in the V9 version, it's going to become increasingly hard to bug fix both a V9 and a V10 version, as not everyone is going to be switching to V10 immediately. I would like to do good by the community and stabilize Item Piles in V9 before I start on the V10 version.

**Comment by leemahn** [comment]
> Precisely. I rewrote the _entire_ module with the 2.0.0 update. If I leave any bugs in the V9 version, it's going to become increasingly hard to bug fix both a V9 and a V10 version, as not everyone is going to be switching to V10 immediately. I would like to do good by the community and stabilize Item Piles in V9 before I start on the V10 version.

Understand.  Well, other than that one bug - that's all *I* have ever seen.  The rest seems to work as expected.

As I mentioned, I use your module so much that I cannot upgrade to v10 of Foundry until your module is ready.  It's the only one I have on at least my personal list that shows as not v10 compatible yet.

**Comment by benbarbour** [comment]
How are you collecting v9 feedback? I mean, are you just waiting for bugs to come in, or are you soliciting testers somewhere to "sign off" on the current feature set?

**Comment by Haxxer** [comment]
I'm waiting for people to find bugs as they find em - I do this for fun, completely for free, on my limited free time, so I've not gone through the effort of solicitating or paying testers.

Bugs can be reported through the normal way of github issues:
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/new/choose

**Comment by leemahn** [comment]
> I'm waiting for people to find bugs as they find em - I do this for fun, completely for free, on my limited free time, so I've not gone through the effort of solicitating or paying testers.

Totally get that.  And, frankly, I'd be willing to pay a reasonable amount as a fee to use your module.  It's VERY helpful.  And being a fellow developer/development manager I TOTALLY get that this isn't easy and consumes a LARGE amount of your time.

Perhaps it's time to start making a few dollars from it?  Not suggesting a huge amount.  But hey, if you can get a hundred people to pony up $10 each, that's better than $0.

**Comment by Haxxer** [comment]
I would love to - how would you suggest making that happen, beyond already having this at the top of the repo:

![image](https://user-images.githubusercontent.com/12858387/191608804-06326ab6-4e29-4b7c-8145-ad2b15587d76.png)

And this in the module settings:

![image](https://user-images.githubusercontent.com/12858387/191608882-93300e3a-a761-403b-8a9f-b695fe595ace.png)

**Comment by leemahn** [comment]
Honestly, you're going to have to make it required to get people to pay regularly.  I'm not sure that $10/mo is the right way to go... but maybe $25/year, or something like that?  Or offer some tiers - if you have other options/modules available to add.

I'd pay $25/year for it... no problem at all.

**Comment by Haxxer** [comment]
Gating an already free module behind a paywall will make the community bring out the torches and pitchforks, doubt that would be a good idea. Regardless, this has wildly diverged from the v10 topic at hand.

Item Piles v10 will be ready when it is ready™

**Comment by leemahn** [comment]
I respectfully disagree.  Now is the PERFECT time to raise this spectre.  So long as the module supports v9 of Foundry for free, paying some amount to get the upgrades to v10 support (and maybe a feature or two - probably something you've already been thinking to do) would be very timely.

**Comment by Haxxer** [comment]
Item piles for v10 has now been released. Item piles will remain free.

**Comment by leemahn** [comment]
The module still shows as not compatible for V10.  And, the installable version on Foundry is still the v9 version.

**Comment by Haxxer** [comment]
@leemahn ???
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/040654808ba0b33e02c5f94cca722fab33344713/module.json#L7

**Comment by Haxxer** [comment]
![Screenshot_20221005-060547](https://user-images.githubusercontent.com/12858387/193985424-09e5e928-f3f1-422f-a7e0-53982a07f2ee.png)

**Comment by leemahn** [comment]
Here's where I was looking:

***@***.***

***@***.***
Lee Fuller
Expert in Virtual Broadcast Events, Event Directing, Audio/Video Editing and Recording


Phone/Text: 951-216-3560
Email:  ***@***.******@***.***>

**Comment by Haxxer** [comment]
Whatever you posted, @leemahn, did not contain any information related to item piles, and contained your personal information. I removed it for safety's sake.

**Comment by leemahn** [comment]
> Whatever you posted, @leemahn, did not contain any information related to item piles, and contained your personal information. I removed it for safety's sake.

Uhm... that's odd.  I don't remember posting anything beyond the last post above.  Can you tell me what it was?  I'm a bit concerned about how my personal information would be posted.

**Comment by Haxxer** [comment]
> Uhm... that's odd. I don't remember posting anything beyond the last post above. Can you tell me what it was? I'm a bit concerned about how my personal information would be posted.

Something sent through your email address, I'd check recently sent emails

**Comment by leemahn** [comment]
> > Uhm... that's odd. I don't remember posting anything beyond the last post above. Can you tell me what it was? I'm a bit concerned about how my personal information would be posted.
> 
> Something sent through your email address, I'd check recently sent emails

Oh!  That was my mistake.  Yes - that sounds like my email signature.  My apologies for that.  I should have realized it would not be parsed out..  It was a response showing where I saw the information about Item Piles not being v10 ready.  However, that's a moot issue now.  All is well.

Thanks for catching that and removing it!
