### ISSUE TITLE
Items entered in manually don't show price and give an error.

### ISSUE THREAD

**Issue by Soundwavesghost** [fantasycalendar/FoundryVTT-ItemPiles#128]
**Describe the bug**
When dragging and item into a actor with Merchant enabled the price of the item does not show up and a console error is generated.

**To Reproduce**
1. Drag an item into the open merchant window
2. Open console
3. See error message

**Expected behavior**
Price to purchase X amount of item.

**Screenshots**
![image](https://user-images.githubusercontent.com/5963543/189462421-357b1f98-53a1-458f-bb79-2ffa076b04ca.png)

![image](https://user-images.githubusercontent.com/5963543/189462308-fc9210d2-fd4b-4ca8-97e4-2bb32b8e8cb6.png)
![image](https://user-images.githubusercontent.com/5963543/189462313-649006d3-b02c-41cd-8e4e-ca5094dca7f9.png)
![image](https://user-images.githubusercontent.com/5963543/189462326-53614951-957a-4618-824f-996e2a7db39f.png)

**Setup:**
 - Foundry Version: 9.280
 - System Version: Fallout 2d20 9.0.5
 - Item Piles Version: 2.0.2
 - Browser & version Foundry main engine

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - [insert more modules here]

**Additional context**
![image](https://user-images.githubusercontent.com/5963543/189462386-820dfb7c-0736-4bb6-9718-418f08abc0a4.png)

**Comment by Haxxer** [comment]
As per the template.json for the system:
https://github.com/superseva/fallout/blob/main/template.json#L332-L334
It's `data.physical.cost` for the price attribute.

**Comment by Soundwavesghost** [comment]
Curious I am moving things to link to that guy and it still comes up undefined with that error. What a confounding game set. Got item piles up and running quickly on a fresh test of Dnd.

**Comment by Haxxer** [comment]
In addition, the currency is here:
https://github.com/superseva/fallout/blob/main/template.json#L206

**Comment by Haxxer** [comment]
Please ensure your settings are 100% correct before creating bug tickets.

**Comment by Soundwavesghost** [comment]
I was using the ones defined on the Item-template instead. But yeah I'll stop bothering you and figure this out.

**Comment by Haxxer** [comment]
Items have prices. The price attribute is listed in the items.

Actors have currencies. The currency attribute is listed in the actor.

Good luck#

**Comment by Haxxer** [comment]
@Soundwavesghost I've added support for the system in Item Piles in the upcoming update, but you should know that currencies are a bit weird, but I created a pull request on the system's repository to fix it:

https://github.com/superseva/fallout/pull/32
