### ISSUE TITLE
[BUG] - Currency icons reset

### ISSUE THREAD

**Issue by RavenknightDM** [fantasycalendar/FoundryVTT-ItemPiles#129]
Hiya, just a small bug that I've noticed with 2.0.4. The custom icons set for the various coins in setup will reset whenever I log out or refresh the window.

As always, thanks for this wonderful mod!
/Ravenknight

![Before F5](https://user-images.githubusercontent.com/53635985/189531547-e3d0e967-307c-40f6-b614-799a0266f110.png)

![After F5](https://user-images.githubusercontent.com/53635985/189531501-afa64b09-ac09-4305-8ebc-880664d0afb9.png)

**Comment by Haxxer** [comment]
The first image is just white?

**Comment by RavenknightDM** [comment]
Ack! My bad. Fixed.

**Comment by Haxxer** [comment]
Fixed in 2.0.5
