### ISSUE TITLE
[Bug] Item piles stopped workin in v9 after recent update

### ISSUE THREAD

**Issue by NdranC** [fantasycalendar/FoundryVTT-ItemPiles#132]
![image](https://user-images.githubusercontent.com/27837113/190036701-f496a8f4-ee41-4675-9efd-9a35fd1d4853.png)
Every time I try to open one of my already setup item piles I get this error and nothing happens.

I am able to open the item piles settings on the pile itself and in the general mod settings.

If I try to make a sheet into an item pile or one already made into a normal npc sheet the settings are not saved and nothing happens.

Draggin an item from the character sheet to the ground deletes the item from the sheet but doesn't create the item as a pile on the ground.

**Comment by Haxxer** [comment]
Please include what system you're playing, and the versions of all your modules

**Comment by NdranC** [comment]
Sorry I forgot, dnd 5e, foundry v9

The issue happens with this reduced list of modules
![image](https://user-images.githubusercontent.com/27837113/190091664-3c438514-bc2b-4e39-a661-9d709151f384.png)

If I make a new test world and only activate the item piles with prerequisites then I don't have the issue.

**Comment by Haxxer** [comment]
Try running this from a macro:

```js
Hooks.call(game.itempiles.hooks.RESET_SETTINGS)
```

**Comment by NdranC** [comment]
Ok, I ran it and it seems to be working again. I'm not sure how foundry works but would this be a permanent fix somehow? Restarting the world seems to not break the module again.

**Comment by Haxxer** [comment]
It is a permanent fix, your module settings was just not set up correctly for 5e, and this fixes it :)

**Comment by NdranC** [comment]
Thank you very much. I guess I should've reset the setting when the module told me to. I assumed it was optional.
