### ISSUE TITLE
[REQUEST] - direct sales/application functions.

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-ItemPiles#134]
two things that are basically close since there is now a merchant tool.
Being able to sell an item without sending the item to the player's file, such as offering services. You decrease the quantity of the item from the merchant, deduct the player's money, but do not add the item to the player. How to pay for a service.

in the same vein, being able to pay for the "use" of the item, the player pays the item and the item's effects are applied to the player who paid (or even executes a macro)

**Comment by Haxxer** [comment]
Perhaps I can add a tickbox on items' flags that set that item to be a service, and does the first thing you mentioned.

As for the second request, every single system implements "using" items differently, and not all items have "effects" (not even core D&D5e as far as I know). What would be the best way to implement that given Item Piles now support 14 systems?

**Comment by rinnocenti** [comment]
the idea of effects would be to use the item on whoever buys the item, regardless of the system.
example: a temple that sells "cure light wounds" or any other spell/effect/attack item normally.
And the purchase of the item is used on the purchaser (not necessarily an effect, but as if you had used the item on the character who purchased it)

**Comment by Haxxer** [comment]
@rinnocenti 
An item being "used" is system specific. In 5e it's a `roll` method on the item (that also creates a dialog), in others it might be `use`, etc. Do you have any suggestions how to use items in the systems that item piles support?

**Comment by 9ryex5** [comment]
Being able to buy services is really helpful. I usually sell stays in INNs through my merchants but the players always need to remove the item from the inventory afterwards.

**Comment by Haxxer** [comment]
As a compromise, would this suit your needs? 

* Add a checkbox on the item's config to not give the buyer any item for purchasing it
* Add input where you can put the name of a macro that's ran when the item is bought

**Comment by rinnocenti** [comment]
both options would be great for me.

**Comment by Haxxer** [comment]
Added in 2.2.4 - if you like it, you can support us here:
https://ko-fi.com/fantasycomputerworks
