### ISSUE TITLE
[REQUEST] - Allow interaction with no GM

### ISSUE THREAD

**Issue by zdaar** [fantasycalendar/FoundryVTT-ItemPiles#136]
**Is your feature request related to a problem? Please describe.**
This is not a problem with the module, more a restriction  of the Foundry permission system

**Describe the solution you'd like**
Allow transactions to be made in Piles and Merchants without a GM online

**Describe alternatives you've considered**
For Merchant : Merchant Sheet NPC and LootSheetNPC, both pretty buggy and with less features
For Piles : There are none that I know of

**Additional context**

Merchant Sheet NPC allows for interacting with the sheet when no GM is online.
LootSheetNPC also had this feature in one of its releases iirc.
There certainly is a usecase for it.

Mine is that the world is online 24/7 and all players of my west marches campaign can log in and do their shopping between sessions, which is a huge timesaver.

I also made them all a personal room with an item pile for storage of their own belongings so they can prepare the right tools for the job. 
The problem is Item Piles require a GM to be present for both its Merchant and Pile mode.

It would be incredible if you could add a "Allows interacting with merchant/pile with no GM present" feature like this
![image](https://user-images.githubusercontent.com/4218386/191714636-a9ee65ed-a93f-4de3-8b67-bb3f619030b2.png)

Here is a link to the function moveItem in Merchant Sheet NPC that allows to move the items
https://github.com/whelan/fvtt-merchant-sheet-npc/blob/a9323d24cbedcb684836bc29f461d92462c3f52a/Source/merchant/MerchantSheetNPCHelper.ts#L428

Thanks for considering it

**Comment by zdaar** [comment]
Hello, 
Apologies, refactored the OP
No, players do not need to be owner.
However both Merchant Sheet NPC and Lootsheet have an allowList for each players to be able to interact with the sheet
![image](https://user-images.githubusercontent.com/4218386/191719084-ef54e12a-5c67-4da1-b86d-99f03db4874b.png)
I believe it just gives them observer permissions
![image](https://user-images.githubusercontent.com/4218386/191719421-9def3067-406b-46c1-970d-b2b07bd909f4.png)

**Comment by Haxxer** [comment]
Looking at the code, it seems to me like it's... not doing any updates when players buy items from merchants with Merchant Sheet NPC (comments are mine):

```js
// If the source actor (the merchant) is owned by you
if (source.isOwner) {
	// Update actor as normal
	if (deletes.length > 0) {
		await source.deleteEmbeddedDocuments("Item", deletes);
	}
	if (updates.length > 0) {
		await source.updateEmbeddedDocuments("Item", updates);
	}

// If the setting is TURNED OFF
} else if (!allowNoTargetGM) {

	// Create an update to be sent to the GM
	packet = new MoveItemsPacket();
	if (source.id) {
		packet.actorId = source.id;
	}
	packet.deletes = deletes;
	packet.updates = updates;

	// @ts-ignore
	let actorLink: boolean = source.data.actorLink
	if (!actorLink) {
		if (source.parent) {
			// @ts-ignore
			let sceneId = canvas.scene.id;
			// @ts-ignore
			Logger.Log("Scene", canvas.scene.id)
			if (sceneId) {
				packet.sceneId = sceneId;
			}
			packet.tokenId = source.parent.id;
			packet.actorLink = false;
		}
	}
}

// So the merchant never gets updated??
```

**Comment by Haxxer** [comment]
So it just seems like if the GM is not connected, the merchant is never updated; i.e. the quantity of items on the merchant is not subtracted. If I add a setting like this, all merchants will have infinite quantity of all items and infinite quantity of currencies. Is that something you're willing to accept?

**Comment by zdaar** [comment]
Honnestly it would be pretty amazing already.
The general store can feature infinite amounts as they don't have infinite gold.

This is a know problem since the v9 update.
Here is a quote from a conversation I had with Whelan, dev of Merchant Sheet NPC : 

"Hi zdaar, Unfortunately this only works in 0.8.x, in 0.9 they have made the NPC character more strict so it is not possible anymore for a player to change the inventory on an NPC character. So at the moment I have no idea how to solve that problem, but I was thinking maybe I could use a compendium to store the results in. But it will make it more complicated."

I take it this limitation would also prevent players from storing and retrieving items from their item pile without a GM online ?

Thanks a LOT for looking into it, my players really love item pile it does wonders for everybody's immersion at our table

**Comment by mouse0270** [comment]
Wouldn't giving players ownership of their `item pile` resolve the GM issue? I am not sure, but I figured I'd ask cause I am curious about giving my players a `item pile` for their bag of holding and thought giving them ownership would let them access and use it while I was offline.

I haven't tested it, as I didn't think of this idea until reading this request.

**Comment by p4535992** [comment]
i solved by giving owner permissions to the merchant and hide the references on the UI interface with https://github.com/p4535992/foundryvtt-hidden-entity-links . This (at least for me) works because I assume that the merchant of itempiles should always be on the canvas . If I don't want merchants on the canvas you can use the Ironmonk module in that case https://github.com/ironmonk88/monks-enhanced-journal

**Comment by Haxxer** [comment]
In the current state of Foundry, this will not be done. Item Piles always requires a GM to be online.
