### ISSUE TITLE
[BUG] - as player, dropping item shows Locked cannot be opened

### ISSUE THREAD

**Issue by Terrox** [fantasycalendar/FoundryVTT-ItemPiles#138]
**Describe the bug**
Dropping item into open window from sheet shows "Locked cannot be opened" message.
Does work as GM.

**To Reproduce**
1. Make new unlinked token, attached json of actor I used
2. Set as conatiner or not, not locked, is open
3. as player, Drop item from player sheet

**Expected behavior**
Should work?

**Screenshots**
![image](https://user-images.githubusercontent.com/16533005/192119699-7d30f00f-59ea-4405-ae0b-7601b54873fc.png)
[fvtt-Actor-temp_to_itempile.json.txt](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/9639642/fvtt-Actor-temp_to_itempile.json.txt)

**Setup:**
 - Foundry Version: [e.g. 9.238]
 - System Version: [e.g. DND5e 1.5.7]
 - Item Piles Version: [e.g. 1.0.0]
 - Browser & version [e.g. Google Chrome 98.0.4758.82]

**Active modules:**
 - Item Piles 2.1.0
 - libwrapper 1.12.10
 - socketlib 1.0.10
 - lots and lots

**Other things**
When Midi-QOL drag/drop targetting is enabled. Dropping item into token on scene does not work as GM or player with an error message "Uncaught (in promise) TypeError: input.item.system is undefined
[Detected 4 packages: autoanimations, lib-wrapper, df-chat-enhance, midi-qol]"

**Comment by Haxxer** [comment]
Fixed in 2.1.1
