### ISSUE TITLE
[BUG] - Trade bug

### ISSUE THREAD

**Issue by caprichozow** [fantasycalendar/FoundryVTT-ItemPiles#141]
**Describe the bug**
Well I'm not sure if I'm messing up somewhere, and if I am, I'm very sorry, however that didn't use to be an issue in v9 so I do assume it's a bug, anyways it's pretty straightforward when dragging and dropping an item in the trade menu it just greets you with a error
![image](https://user-images.githubusercontent.com/109267376/193031528-e514729d-5c41-47d5-89f5-5d4e4eac03f7.png)
As if you were trying to drag the item to the map instead, if you are the GM the error does not happen at all, and it drags to the trade menu as normal, however if you're a player it doesn't

**To Reproduce**
1 - Be a non GM player
2 - Send a trade request
3 - Start a trade
4 - Try to drop an item in the trade menu

**Expected behavior**
The item to go in the item menu enabling the players to trade.

**Screenshots**
![image](https://user-images.githubusercontent.com/109267376/193032333-18d90c34-d17e-4eac-8ae7-031e9a90cc38.png)
![image](https://user-images.githubusercontent.com/109267376/193032384-00c04025-fecf-499c-9b16-e7e6701a604a.png)

**Setup:**
 - Foundry Version: 10.286
 - System Version: 2.0.3
 - Item Piles Version: 2.1.!3
 - Browser & version: Chrome 105.0.5195.128

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - TIdy UI - Game Settings

**Comment by Haxxer** [comment]
This is known and will be patched.

**Comment by caprichozow** [comment]
I'm very sorry about this then, I didn't mean to spam you with this, just didn't really see that as a known issue anywhere tbh, but I'm very glad then! :)
