### ISSUE TITLE
[BUG] - Can't update merchant descriptions

### ISSUE THREAD

**Issue by benbarbour** [fantasycalendar/FoundryVTT-ItemPiles#142]
**Describe the bug**
Cannot edit merchant description

**To Reproduce**
1. Create a merchant
2. Edit the description field
3. Observe the "Item Pile Updated Successfully" toast notification

**Expected behavior**
The description to persist

**Screenshots**

**Setup:**
 - Foundry Version: 9.269
 - System Version: DND5e 1.6.3
 - Item Piles Version: 2.1.1
 - Browser & version Google Chrome 106.0.5249.61

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment]
This is fixed in 2.2.0 for Foundry v10, but will sadly not be fixed in the Foundry v9 version.
