### ISSUE TITLE
[REQUEST] - Render links in merchant description.

### ISSUE THREAD

**Issue by benbarbour** [fantasycalendar/FoundryVTT-ItemPiles#144]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to add links to the Merchant descriptions. They render in the edit dialog.

**Additional context**
![image](https://user-images.githubusercontent.com/487715/193431234-0f89b44f-e507-4d9a-b5e8-d7ddac9b6e1a.png)

**Comment by Haxxer** [comment]
Fixed in 2.2.2
