### ISSUE TITLE
[REQUEST] Sort Items/merchant stock Alphabetically

### ISSUE THREAD

**Issue by Badacems** [fantasycalendar/FoundryVTT-ItemPiles#146]
Currently any items brought into a merchant or loot pile seem to be sorted by time brought in, making it a bit difficult to keep merchants organized as their inventory grows large.

Would love an option to have all inventories/item piles autosort their list by alphabetical order instead of by time added

**Comment by Haxxer** [comment]
Fixed in 2.2.2
