### ISSUE TITLE
[REQUEST] - Get the merchant item pile to BUY from players (PF2e)

### ISSUE THREAD

**Issue by Strangley-Browne** [fantasycalendar/FoundryVTT-ItemPiles#148]
(PF2e) Get item piles to BUY from players. I am not aware that any other module has yet done this. The system's own Loot Merchant can't do it. It seems such a "bread and butter" thing for the system not to be able to do, and no other "merchant/Loot" module to cope with. 
I can only assume the PF2e system just must do its currencies weird or something??

**Comment by Haxxer** [comment]
The way the system handles item prices makes it hard for me to make it work.

**Comment by Strangley-Browne** [comment]
Yeah, Thats the impression I get as no one else has been able to make it work either

**Comment by Strangley-Browne** [comment]
Well Done Sir!

**Comment by Haxxer** [comment]
Thanks! Closing as done.
