### ISSUE TITLE
[BUG] - Systems that has currency as integer causes fatal errors

### ISSUE THREAD

**Issue by RaaviArda** [fantasycalendar/FoundryVTT-ItemPiles#149]
**Describe the bug**
Using a system that has it's base currency defined as integer (no decimal point) when trying to open the merchant sheet there is an error in console and prices are calculated as "undefined". This is caused by line 492 in pile-utilities.js which reads:
const decimals = smallestExchangeRate.toString().split(".")[1].length;
When splitting ie. "500" with "." delimeter there is only one element in the resulting array and this line produces error:
TypeError: Cannot read properties of undefined (reading 'length')

**To Reproduce**
1. Use a system that has integer-only currency, ie. Stars Without Numbers
2. Define currency in the settings (for SWN that's data.credits.balance) with exchange rate 1 and item cost attribute (for SWN: data.cost)
3. Create a merchant, give it some items with non-zero cost
4. Try to open the merchant sheet

**Expected behavior**
Prices should be calculated based on lowest exchange rate which is decimal

**Screenshots**
![image](https://user-images.githubusercontent.com/33468788/194075785-89abc2a9-86c3-4b18-8ee8-5582a9911c55.png)

**Setup:**
 - Foundry Version: 9.280
 - System Version: SWN 0.5.3
 - Item Piles Version: 2.1.1 (cannot upgrade due to Forge not allowing v10)
 - Browser & version: Google Chrome 105.0.5195.127

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**

**Comment by Haxxer** [comment]
I don't know what you mean with Forge not allowing v10?

![image](https://user-images.githubusercontent.com/12858387/194080244-c965b6b6-bef1-455b-8e09-1de1132535c5.png)

Forge supports v10 just fine, and this bug has been fixed in the v10 version of Item Piles, and I do not intend to maintain two versions.
