### ISSUE TITLE
[REQUEST] - Assets Pack

### ISSUE THREAD

**Issue by brunocalado** [fantasycalendar/FoundryVTT-ItemPiles#15]
There is a free chests pack. Would be cool have at list some set as defaut.
![image](https://user-images.githubusercontent.com/4999783/148441435-53a0e03d-6489-4945-9bfd-f64ea3ef778d.png)

I already converted them to webp and reduced the size for foundry vtt use. But, this could make smaller.
[out.zip](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/7824305/out.zip)

# SOURCE AND LICENSE
https://foozlecc.itch.io/free-chest-and-key-pack

You are granted a non-exclusive perpetual license to:
1.1 Use any resources found in this download in any number of commercial or personal projects for yourself or clients perpetually except where forbidden as detailed below.
1.2 Create derivatives / modify any resources in this download and include them into your projects commercially or non-commercially such as games, websites, illustrations etc. except where forbidden as detailed below.
1.3 Sell and distribute games with these assets. No attribution or link back is required, however any reference will be highly appreciated.

FORBIDDEN

2.1 You can NOT resell the art source files (PNG, JPG, EPS, Adobe Illustrator, etc) or slightly modified versions of the art.
2.2 You can NOT use these assets or derivatives for Print On Demand / Merchandise (T-Shirts, Stickers, etc.).
You can not redistribute the art or modified version where it enables access to other end users.
Showing the art / asset in the game is acceptable, but an application which allows the end user to export or access the artwork is not acceptable.

**Comment by Haxxer** [comment]
Thank you for the request, but I will decline as I would like to avoid bloating the module.
