### ISSUE TITLE
[BUG] - Infinite Items

### ISSUE THREAD

**Issue by 9ryex5** [fantasycalendar/FoundryVTT-ItemPiles#151]
**Describe the bug**
Infinite items doesn't appear to be working properly.

1. When you create a merchant and toggle this option (screenshot 1), no item is automatically set to infinite.
2. You need to set an infinite item individually (screenshot 2) and they appear to be infinite, however if you buy one the item is gone from the merchant.

**To Reproduce**
1. Create a merchant
3. Set an infinite item
4. Buy it with a player

**Expected behavior**
The item wasn't supposed to be gone when it is bought.

**Screenshots**
![image](https://user-images.githubusercontent.com/43207603/194294515-b7298fde-2a03-4673-adf5-8a2682b54495.png)
![image](https://user-images.githubusercontent.com/43207603/194294880-8e3152ef-776b-45a5-a4ee-11be7ae87e69.png)

**Setup:**
 - Foundry Version: 10 (Build 286)
 - System Version: DnD5e 2.0.3
 - Item Piles Version: 2.2.3
 - Browser & version: Edge

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment]
Fixed in 2.2.4
