### ISSUE TITLE
[BUG] - Trading with yourself deletes the items you are trading

### ISSUE THREAD

**Issue by Janonas** [fantasycalendar/FoundryVTT-ItemPiles#152]
**Describe the bug**
Trading with yourself deletes the items you are trading

**To Reproduce**
1. Initiate a trade in which both sides are the same actor
2. Make the trade happen with some items
3. Check your inventory for the missing items

**Expected behavior**
Trading with yourself should not delete or add any items.

**Setup:**
 - Foundry Version: [10.287]
 - System Version: [Pathfinder 2e 4.2.3]
 - Item Piles Version: [2.2.3]
 - Browser & version [Tested on latest firefox and chrome, browser is irrelevant here]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment]
You should not be able to trade with yourself, so the bug is that you can trade with yourself, not that items are deleted

**Comment by Janonas** [comment]
Oh i did that by intiating a trade with a player as the GM, and then selecting his token as the one who is trading.

**Comment by Haxxer** [comment]
That is who _you_ are trading _as_. It is who is representing you. The player will then pick their own character.

**Comment by Haxxer** [comment]
Fixed in 2.2.4, you can no longer trade to and from the same actor, that would be bonkers.
