### ISSUE TITLE
[BUG] - Updating from and old version keeps old settings, breaking the module

### ISSUE THREAD

**Issue by Janonas** [fantasycalendar/FoundryVTT-ItemPiles#153]
**Describe the bug**
Updating from and old version keeps old settings, breaking the module. Such as picking up items which you dont have in inventory giving you -1 of the item in question

**To Reproduce**
1. Install the module on an older than 10 version world
2. update to foundry version 10 and the module to the newest version
3. Try to pick up an item which isnt in your inventory
4. Reset the modules setting to the default, see it change some settings, and then see that this issue no longer persists

**Expected behavior**
Updating to new version with default settings should change the default settings accordingly so the module isnt broken.

**Setup:**
 - Foundry Version: [10.287]
 - System Version: [Pathfinder 2e 4.2.3]
 - Item Piles Version: [e.g. 2.2.3]
 - Browser & version [Tested both on newest firefox and chrome, browser not an issue here]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment]
Did you not get a popup as a part of launching the world again to update the settings of Item Piles?
