### ISSUE TITLE
[REQUEST] - Randomize Quantities 

### ISSUE THREAD

**Issue by mouse0270** [fantasycalendar/FoundryVTT-ItemPiles#156]
**Is your feature request related to a problem? Please describe.**
I wouldn't say this is a problem. I'd like to make predefined merchants, like a general store, blacksmith, herbalist, etc. 
I've tried setting up a roll table, but I really don't want a random list of items, I want a specific list of items with a random quantity.

**Describe the solution you'd like**
I would like to be able to define a list of items with the quantity set to a roll, for example, `1d4 * 10`, and have a button that will roll for quantities when I hit it.

**Describe alternatives you've considered**
I really was unable to find anything in v10 that did anything like this

**Comment by Haxxer** [comment]
Added in 2.3.3
