### ISSUE TITLE
[SYSTEM] - KNAVE

### ISSUE THREAD

**Issue by PestoPosta** [fantasycalendar/FoundryVTT-ItemPiles#158]
# **https://foundryvtt.com/packages/knave/**

### **Item Price Attribute**: "coppers"

Given that it is such a bear bones system, I am fairly sure the info requested from here down does is not present the system or not relevant, if I am mistaken, please forgive me, and the info should be easily found [here](https://github.com/jrommann/knave/blob/master/template.json) Its a really quick scroll through, 150 lines.

Thanks for your time.
Cheers :)

### **Item Filters**: "[WRITE ITEM FILTERS HERE]"
Pretty sure there is only one item type.

### **Item Similarities**: [WRITE ITEM SIMILARITIES HERE]
There is only one item type.

### **Currencies**:
As far as I can tell money does note exist in this form, but I could be mistaken.

- **Name**: [coppers] _or localized name_ [coppers]
- **Path**: [WRITE ATTRIBUTE PATH HERE]
- **Image**: [WRITE IMAGE PATH HERE (or blank)]
- **Exchange Rate**: [WRITE CURRENCY EXCHANGE RATE]
- **Shorthand Name**: [WRITE CURRENCY SHORT HAND NAME]
- **Primary Currency**: Yes

**Comment by Haxxer** [comment]
If the system keep track of item values, how come characters don't keep track of currencies? Very odd.

**Comment by PestoPosta** [comment]
Because its as I said, it pretty bear bones.
Also 1 one could simply make an item called "money"
or 2 keep track of it in any given text field.

**Comment by Haxxer** [comment]
Added in 2.3.0
