### ISSUE TITLE
[BUG] - Individual Infinite Items not working

### ISSUE THREAD

**Issue by 9ryex5** [fantasycalendar/FoundryVTT-ItemPiles#160]
**Describe the bug**
If I create a merchant and set it with infinite items (screenshot 1), every item is infinite as expected.
However, if I create a merchant and don't set it with infinite items but set a specific item to be infinite (screenshot 2), the item appears to be infinite (screenshot 3) but it's not. When a player buys the item, it goes away.

**Screenshots**
![image](https://user-images.githubusercontent.com/43207603/194886532-696c418b-f208-4a58-bb5b-4079e4cb91fc.png)
![image](https://user-images.githubusercontent.com/43207603/194886626-c33bf9b5-0d76-4c59-b428-42f2397c60ae.png)
![image](https://user-images.githubusercontent.com/43207603/194886986-32949ffd-2833-46cb-ace6-74d123e5861b.png)

**Setup:**
 - Foundry Version: 10 build 287
 - System Version: DND5e 2.0.3
 - Item Piles Version: 2.2.4

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment]
Fixed in 2.2.5
