### ISSUE TITLE
[BUG] - the times that start at night are not counted correctly in the merchants

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-ItemPiles#161]
**Describe the bug**
When the time crosses the "dawn" or when the Opening value is greater than the closing value of the market, the store is always closed.
Making it impossible to have stores open only at night, for example from 22PM to 04AM.

![image](https://user-images.githubusercontent.com/3178127/194965868-020c5551-dbdf-4c09-85da-2a293abe4ec6.png)

**Setup:**
 - Foundry Version: 9.280
 - System Version: DND5 1.6.3
 - Item Piles Version: 2.1.2
 - Browser & version App

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment]
Fixed in 2.2.5
