### ISSUE TITLE
Search function does not work and throws error

### ISSUE THREAD

**Issue by GamerFlix** [fantasycalendar/FoundryVTT-ItemPiles#162]
**Describe the bug**
The search field that appears on item piles with 3 or more items does not function and throws a console error. This is reproducable in a new world.

**To Reproduce**
1. Optional: Create a new world (For the purpose of this test a dnd5e world was used)
2. Optional: Create a new scene (For the purpose of this test a scene with default settings was used)
3. Load into the scene
4. Create a new item pile by dragging at least three different items onto the same space on the canvas. This results in an item pile with three entries making the search box appear on the item piles sheet if opened.
6. Type anything into the search box and note that nothing happens while the console shows the error in the sceenshot below.

**Expected behavior**
The console should not throw an error when something is typed into the search box and the items on the pile should be filtered or otherwise highlighted depending on the search term.

**Screenshots**
Console error:
![grafik](https://user-images.githubusercontent.com/62909799/195854644-f595b540-4e9e-405a-b162-fd8b97fe62d1.png)

**Setup:**
 - Foundry Version: 10.288
 - System Version: DND5e 2.0.3
 - Item Piles Version: 1.12.10.0
 - Browser & version Google Chrome: 106.0.5249.119 64-BIt

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**
For the purpose of this test the item piles settings have not been altered at all. As such the default values have been used. This error also occurs in worlds migrated from v9 with existing piles and as such it is unlikely that the pile creation itself is at fault. The search function likely just does not work correctly.

**Comment by Haxxer** [comment]
Fixed in 2.2.5
