### ISSUE TITLE
[SYSTEM] - Twilight 2000

### ISSUE THREAD

**Issue by Stefouch** [fantasycalendar/FoundryVTT-ItemPiles#164]
At the request of a user in #154 , here are the information for the Twilight 2000 game system;

*PS: You should change the `data` by `system` in your D&D5e examples provided in this template.*

# **[Twilight 2000](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt)**

### **Actor Class Type**: "character"

*The actor class type is the type of actor that will be used for the default item pile actor that is created on first
item drop*

D&D5e system example: `character`

### **Item Quantity Attribute**: "system.qty"

*The item quantity attribute is the path to the attribute on items that denote how many of that item that exists*

D&D5e system example: `data.quantity`

### **Item Price Attribute**: "system.price"

*The item price attribute is the path to the attribute on each item that determine how much it costs*

D&D5e system example: `data.price`

### **Item Filters**: "specialty, injury"

*Item filters actively remove items from the item pile inventory UI that users cannot loot, such as spells, feats, and
classes*

D&D5e system example: `spell, feat, class`

### **Item Similarities**: "name, type, system.itemType"

*Item similarities determines how item piles detect similarities and differences in the system*

D&D5e system example: `name, type`

### **Currencies**:

*Currencies in item piles are a list of names, attribute paths, and images - the attribute path is relative to the
actor.data*

The system does not use any currency.

**Comment by Haxxer** [comment]
@Stefouch If items have prices, how do you track currencies in this system?

**Comment by Stefouch** [comment]
It's a post-apo game. The currency is mainly in form of weapons' bullets and munitions, which are their own Items in the game system.

**Comment by Haxxer** [comment]
Okay then, so every price of every item will have to be manually configured if you want to use the merchants, got it

**Comment by Stefouch** [comment]
Unfortunately, yes

**Comment by Haxxer** [comment]
Added in 2.3.0
