### ISSUE TITLE
[REQUEST] - Common Macros in new Wiki (had in old)

### ISSUE THREAD

**Issue by ngPescado** [fantasycalendar/FoundryVTT-ItemPiles#165]
New wiki is beautiful except on one point: Macros. I wish the commonly used macros from the old guide were listed (most likely at the bottom near hooks). Granted you could use the extremely well documented API section to build them but there are plenty of non-coders out there that a simple macro helps. Previously I believe you had macros for tasks such as converted an actor into an item pile and then an item pile back to an actor. Thoughts?

**Comment by Haxxer** [comment]
Added in 2.2.7:
http://fantasycomputer.works/FoundryVTT-ItemPiles/#/sample-macros
