### ISSUE TITLE
[REQUEST] - Display subcategories of items

### ISSUE THREAD

**Issue by Ikabodo** [fantasycalendar/FoundryVTT-ItemPiles#166]
As always, thanks for what I consider one of (if not the) most well made module on foundry for 5e.

**Is your feature request related to a problem? Please describe.**
If you have item piles with lots of items it can become a large list to scroll through for players. 

**Describe the solution you'd like**
It would be nice to have the option to display subcategories of items to the Item Piles list. (Consumables, Equipment, and so on). Bonus if it includes compatability with mods like Custom Character Section.

**Describe alternatives you've considered**
It's always possible to open the actual item sheet to get the sections, but that sort of defeats the purpose of the pile.

**Comment by Haxxer** [comment]
Something like this?

![127 0 0 1_29999_game (7)](https://user-images.githubusercontent.com/12858387/196233048-f81f55b1-7ad1-4c86-ac0e-6b77084842d6.png)

**Comment by Ikabodo** [comment]
Heh. Yeah, pretty much exactly like that. :)
