### ISSUE TITLE
[REQUEST] - Sort Merchant Items

### ISSUE THREAD

**Issue by 9ryex5** [fantasycalendar/FoundryVTT-ItemPiles#170]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a quality of life improvement.

**Describe the solution you'd like**
The ability to sort merchant items alphabetically, by price or rarity.
Not sure if possible, but it would be even better if each player could sort the items independently.

**Comment by Haxxer** [comment]
Added in 2.6.0
