### ISSUE TITLE
[BUG] - Cost amount of <1 is considered "free" on Merchant sheet

### ISSUE THREAD

**Issue by loofou** [fantasycalendar/FoundryVTT-ItemPiles#173]
**Describe the bug**
I play in a near-future setting where money works similar to nowadays, including decimal places. Some items (like ammo) have prices in the 0.x decimal range. Unfortunately the system simply treats everything under $1 as "free", even if you buy in bulk, which should multiply the prices into the 1+ range.

**To Reproduce**
1. Create item with cost of 0.25
2. Set up merchant actor and give item
3. Try to buy item from merchant
4. Try to buy 5 units of item from merchant

**Expected behavior**
Decimal prices should be taken into consideration and shown appropriately.

**Screenshots**
![image](https://user-images.githubusercontent.com/2287749/197395915-e961998f-d74a-44fb-8d8e-ba7ba497e1a9.png)

**Setup:**
 - Foundry Version: [e.g. 10.288]
 - System Version: [e.g. SWADE 2.0.6]
 - Item Piles Version: [e.g. 2.2.9]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**
I'm not sure if this is specific to the SWADE system or not.

**Comment by Haxxer** [comment]
Fixed in 2.2.10

**Comment by loofou** [comment]
That was extremely fast and I can confirm it working :) Thank you a lot! 

Unfortunately this introduced one other issue: due to various reasons (one of them the price modifer %) it can now happen that currencies end up with 3 or more decimal digits. It makes absolute technical sense, but it would be great if we could have a way to have custom rounding for prices. A small option to select to how many digits after the decimal point we want to round in the setting. This way "cent-less" currencies, like Gold Coins can set this to 0, modern currencies can have it set to 2, etc. I can imagine a sci fi setting wanted to turn this off as well and just deal with arbitrary decimal numbers as currency (like Crypto).

Would this be something you can add like this or should I request this specifically in another issue? If you have no time, I can also attempt a PR to introduce this change myself.

**Comment by Haxxer** [comment]
Please do attempt a PR, more eyes on my code would be good. Here's how it determines the max number of digits. It's arbitrary, but it is what it is.

https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/master/src/helpers/pile-utilities.js#L437

**Comment by loofou** [comment]
Alright, my idea is to introduce a new setting field to set the default "smallest exchange rate". Default of that would be "0.0001" like right now, but you could also set it to "0.01" for modern style currency systems or "1" to enforce the removing of any decimal points on the smallest currency unit.

I have only one question: I see that the module is compiled into a single src file. How do I go about testing my changes? Can I simply remove this file and work with the full folder structure or do I need to compile the file down into a single file like you do (and if so, what do you use for this?)

Sorry if the question is obvious, I'm just relatively new to javascript and foundry module development.

**Comment by Haxxer** [comment]
Thank you, this is a good PR. I will probably make this field only visible when there's just one currency in the system, defaulting to the base behavior if not.

**Comment by loofou** [comment]
You are right, I didn't think of that.
