### ISSUE TITLE
[REQUEST] - Access to sharing settings via API

### ISSUE THREAD

**Issue by CircuitMusicLabs** [fantasycalendar/FoundryVTT-ItemPiles#174]
**Is your feature request related to a problem? Please describe.**
When turning tokens into item piles with [turnTokensIntoItemPiles], sharing for currencies and items is always enabled.

**Describe the solution you'd like**
New API item pile methods to enable/disable item and currency sharing.

**Describe alternatives you've considered**
Configuration menu settings to enable/disable default item/currency sharing behaviour.

**Additional context**
Nope - should all be clear.

**Comment by Haxxer** [comment]
If you read the API documentation, you can see that you can override this behaviour.

**Comment by CircuitMusicLabs** [comment]
OK, thanks a bunch. As we say in German: "Those who can read have a clear advantage". I now saw the options.pileSettings, which can be passed to the method.

In that case let me turn this into a desperate cry for help, because I am not a developer. How would I pass these options (item and currency sharing disabled)?

Given the following:
```
let tok = canvas.tokens.controlled[0];
game.itempiles.API.turnTokensIntoItemPiles(tok);
```
How would I modify the code to achieve this? I can't find any help via reddit and such.

Thanks in advance!

**Comment by CircuitMusicLabs** [comment]
You, Sir, are my hero! Thanks so much! I just bought you a cup of coffee.

**Comment by Haxxer** [comment]
Happy to help, and thank you!
