### ISSUE TITLE
[BUG] - All Actor Tokens "Flatten" into the Canvas and Cannot be selected

### ISSUE THREAD

**Issue by rtschaefer** [fantasycalendar/FoundryVTT-ItemPiles#175]
**Describe the bug**
When the Item Piles module is activated, all of the actor tokens on a scene flatten into the canvas and can no longer be selected. 
 
**To Reproduce**
Activate the Item Piles module. 

To fix the problem, deactivate the module, restart the world, and all actor tokens work again without any problems. 

**Setup:**
 - Foundry Version:10. build 288]
 - System Version: DND5e 2.0.3
 - Item Piles Version: 2.2.10
 - Browser & version: Google Chrome Version 106.0.5249.119 (Official Build) (64-bit)

**Additional context**

**Comment by Haxxer** [comment]
Do you have any other modules active when this happens? No one else has reported this issue, so I'm very confused

**Comment by Haxxer** [comment]
And I'm not sure what you mean with flatten? Do they lose their elevation? Is it a visual thing?

**Comment by rtschaefer** [comment]
Good news, this issue is no longer happening, and it makes me wonder if it was the result of connection issues from the Forge Server (it was driving me batty). 

It was consistently happening to me every time I turned the module on, then the issue stopped when the module was turned off. What I mean by all tokens flattening to the canvas: the tokens would act as artwork embedded into the scene art itself. They could not be selected at all using the token select tool.  

I am borrowing the language of the DF Architect module, which has a tile flattener feature (takes all tiles in a scene and flattens them into the background scene art).

**Comment by rtschaefer** [comment]
I would close this issue out while taking some note of it occurring. Thank you very much for your time.
