### ISSUE TITLE
[REQUEST] Supporting "free-text" fields from item values

### ISSUE THREAD

**Issue by gsterling** [fantasycalendar/FoundryVTT-ItemPiles#176]
The system I am playing unfortunately doesn't have multiple fields for the different currencies. It just uses a single free-text field. But I really want to use the merchant :(

So it looks like `1S 50L` for example.

Would it be possible to add an option to allow free-text values, which then
1) Parses the value of the field
1) Splits the value by spaces (spaces are important, so it still looks nice on the item sheet)
1) Add them to a hash splitting the values into 'currency' and 'number'
1) Tries to match the currencies to the configured currencies.

So as per my example above, we'd have `hash = { 'S': 1, 'L': 50 }` which then could be correctly displayed.

Note that this is only a problem for item values in my system. Characters do in fact have multiple fields for S(olare), L(unare) and T(elare).

Additonal request: Could this also automatically map not configured currencies to items in the players inventory? So for example if the value of an item is `4 rock` it would automatically assume it's items the player has to have in their inventory? Ideally with possible quoation marks to reference item names with spaces, e.g. `3 "Sea shells"` But this would only be the cherry on top I would be more than happy if merchants work at all :)

**Comment by Haxxer** [comment]
Tough problem, but I will see what I can do. If you wish, you can always make pull requests to create this functionality in Item Piles :) It is an open source module after all.

Your additional request is exactly what the custom prices are, which can be configured per item. Duplicating functionality will only lead to confusion.

**Comment by gsterling** [comment]
Yeah, I can look into it. It doesn't sound too hard to me. But can you tell me, where exactly do you get the price from an item? I tried to figure it out myself, but I am pretty new to JS and FoundryVTT module development in general.

**Comment by gsterling** [comment]
Found it: `getItemCost()` in `src/helpers/utilities.js`

**Comment by Haxxer** [comment]
D&D5e is setup like this:

![image](https://user-images.githubusercontent.com/12858387/203629971-be053004-261f-4fae-befb-ad4146bce733.png)

Because people mostly handle gold coins, which then a fractional value of a price in results in silver and copper being used. Perhaps you need to set Telare to 0.01, Lunare to 1, and Solare to 100?

**Comment by gsterling** [comment]
Then it is still using the basePrice as Lunare, so the item suddenly costs 1200L instead of 12L.
I'd have to change the basePrice to be based on Lunare, but then I can't use an integer.

And I suspect I'd still have it show as 0.01L instead of 1T, no?

I'd like it to use the same (or similar) function to display the "You pay" currencies in the trading window:
![image](https://user-images.githubusercontent.com/58980630/203632391-ce157089-2fd5-4a05-96f6-850ae0e8c78f.png)

I can create a different issue with a feature request and we can close this one, if you want.

**Comment by Haxxer** [comment]
Perhaps we can discuss this on a thread in the foundry discord instead, yeah

**Comment by gsterling** [comment]
I have never use discord before and the link on the official foundry website doesn't work anymore: https://discord.com/invite/foundryvtt

![image](https://user-images.githubusercontent.com/58980630/203636731-37a24b0b-ad8d-4b0c-9ffd-d01798842830.png)


Should I contact you on LinkedIn or do you have another working invite link?

**Comment by Haxxer** [comment]
Works just fine for me? Have you tried in a different browser? Otherwise we can discuss it on the Fantasy Computerworks discord:

https://discord.gg/eTbVYnqg

**Comment by gsterling** [comment]
Can you write me? I really not familar with discord: Eupaawee#8985

I joined the Fantasy Computerworks and FoundryVTT discord now.
