### ISSUE TITLE
[BUG] - When opening a pile actor it open the character sheet instead

### ISSUE THREAD

**Issue by Lifthraser** [fantasycalendar/FoundryVTT-ItemPiles#180]
**Describe the bug**
When opening a pile actor by double clicking on its actor, it open the character sheet instead.

**To Reproduce**
Can't reproduce, occurs randomly.

**Expected behavior**
Should open the item pile sheet, open the character regular sheet.

**Setup:**
 - Foundry Version: 10 build 288
 - System SWADE and Dungeon World latest versions
 - Item Piles Version: 2.2.10
 - Browser & version: firefox 106.0.2 64bits

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

To correct the bug I either reload the web page OR copy (dont need to paste) the actor, the bug goes away.

**Comment by Haxxer** [comment]
Do you get any errors in the console?

**Comment by Lifthraser** [comment]
It was always in a session and as a GM i didnt get time to see that...
I'll try to see next time!

Also the bug is not new, had this for a long time (at least 6 month) and me and my players get it.
It occurs quite note often.... and is easy to correct localy so....

**Comment by Lifthraser** [comment]
Here is the console messages when i got the bug, then copied the actor (reflex...)
Error: You are accessing TokenDocument#img which has been migrated to TokenDocument#texture.src
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    logCompatibilityWarning http://152.228.143.63:30000/scripts/commons.js:1692
    _logDataFieldMigration http://152.228.143.63:30000/scripts/commons.js:6606
    get http://152.228.143.63:30000/scripts/commons.js:6570
    getTokenImages http://152.228.143.63:30000/modules/token-hud-art-button/artbutton.js:240
    prepTokenHUD http://152.228.143.63:30000/modules/token-hud-art-button/artbutton.js:283
    <anonymous> http://152.228.143.63:30000/modules/token-hud-art-button/artbutton.js:390
    #call http://152.228.143.63:30000/scripts/foundry.js:724
    callAll http://152.228.143.63:30000/scripts/foundry.js:681
    _render http://152.228.143.63:30000/scripts/foundry.js:5112
[commons.js:1703:34](http://152.228.143.63:30000/scripts/commons.js)
Valeur 0 0 undefined undefined inattendue lors de l’analyse de l’attribut viewBox. [jquery.min.js:2:39203](http://152.228.143.63:30000/scripts/jquery.min.js)
Valeur undefined inattendue lors de l’analyse de l’attribut width. [jquery.min.js:2:39203](http://152.228.143.63:30000/scripts/jquery.min.js)
Valeur undefined inattendue lors de l’analyse de l’attribut height. [jquery.min.js:2:39203](http://152.228.143.63:30000/scripts/jquery.min.js)
Valeur undefined inattendue lors de l’analyse de l’attribut cx. [jquery.min.js:2:39203](http://152.228.143.63:30000/scripts/jquery.min.js)
Valeur undefined inattendue lors de l’analyse de l’attribut cy. [jquery.min.js:2:39203](http://152.228.143.63:30000/scripts/jquery.min.js)
Copied data for 1 Token objects [foundry.js:58721:78](http://152.228.143.63:30000/scripts/foundry.js)
Foundry VTT | Created Token with id [mQp4eqrLw6R86NiN] in parent Scene [kS1VCGqPrXMCmRYP] [commons.js:6921:20](http://152.228.143.63:30000/scripts/commons.js)
WebGL warning: drawElementsInstanced: Using format enabled by implicitly enabled extension: EXT_float_blend. For maximal portability enable it explicitly.
![image](https://user-images.githubusercontent.com/79018988/198849783-78af8994-0403-4f45-aa58-72a68b8f69f2.png)

**Comment by Haxxer** [comment]
That's a warning. Errors are red :)
