### ISSUE TITLE
[BUG] - OSE: Dragging items onto item piles doesn't remove item and merges it with contents.

### ISSUE THREAD

**Issue by Naroek56** [fantasycalendar/FoundryVTT-ItemPiles#182]
**Describe the bug**
Items are not removed and merge on piles in OSE.

**To Reproduce**
1. Go to player inventory.
2. Create item pile with sword.
3. Drag and drop 5 gold onto item pile.
4. Item pile contains now 5 swords and character still has 5 gold.

**Expected behavior**
Item pile contains one sword and 5 gold. Character has 5 gold less.

**Screenshots**
![image](https://user-images.githubusercontent.com/49316726/200071893-4cfb0b02-9781-41a5-9ff6-60bcbcb29403.png)

**Setup:**
 - Foundry Version: 10.288
 - System Version: Old School Essentials 1.6.8
 - Item Piles Version: 2.2.10
 - Browser & version: Firefox 106.0.4

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - The Forge

**Comment by Haxxer** [comment]
As far as I know, OSE is not officially supported by Item Piles, so this is more of a system request, is it?

**Comment by Naroek56** [comment]
Doesn't the guidance say that the module still works if you put in those variables? I thought the system request is just for native support.

**Comment by Haxxer** [comment]
The `data` in `data.quantity.value` leads me to believe you have an old configuration from v9, which is obviously not correct. I would recommend setting the module up correctly as per the system's properties.

**Comment by Naroek56** [comment]
I tried other variables, data.quantity.value is the only one that still prompts the quantity request when draggin say 50 coins. Other variables give errors.

**Comment by Haxxer** [comment]
I do not know the system, so I would recommend consulting the creators or other module creators in that system.
