### ISSUE TITLE
[BUG] - [PF1e] Unidentified Name Not Respected In Piles

### ISSUE THREAD

**Issue by Tarbarian** [fantasycalendar/FoundryVTT-ItemPiles#183]
**Describe the bug**
The identified name of unidentified items appear in item piles. The item shown below has the identified name of "Silver Raven (Figuring of Wondrous Power)" and the unidentified name of "Silver Raven." This is possibly related to the PF1e core bug [#1787](https://gitlab.com/foundryvtt_pathfinder1e/foundryvtt-pathfinder1/-/issues/1787).

**To Reproduce**
1. Create an item with an identified and unidentified name
2. Uncheck the "identified" checkbox under item details
3. Put item in an item pile

**Expected behavior**
Show the unidentified name

**Screenshots**
![image](https://user-images.githubusercontent.com/76751079/200137484-02ae7fbc-8d65-4487-9e37-b6c98af0f9bf.png)

**Setup:**
 - Foundry Version: 10.288
 - System Version: PF1e 0.82.2
 - Item Piles Version: 2.2.10
 - Browser & version: Google Chrome 107.0.5304.88

**Active modules:**
 - Reproduceable with only Item Piles and dependencies

**Comment by Haxxer** [comment]
This ultimately stems from PF1e handling unidentified items differently than other systems - I simply get the name of the item, and if the system gives me the identified name, I assume it knows what it is doing. I'm in contact with the PF1e devs about this, but no promises given the amount of systems Item Piles support.

**Comment by Haxxer** [comment]
Given it is a system specific issue, this will not get fixed in Item Piles. I can see the ticket you linked has been merged and will be fixed in PF1e's next update.
