### ISSUE TITLE
[BUG] - PF2e Gifting Stopped by System

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-ItemPiles#185]
**Describe the bug**
When dropping an item to another token to gift them the item, PF2e tells you do not have permissions to give the actor the item.

**To Reproduce**
See above

**Expected behavior**
Gifting working.

**Screenshots**
![image](https://user-images.githubusercontent.com/32039708/201439979-30246b55-6220-42ea-b539-2914db28dc3a.png)

**Setup:**
 - Foundry Version: 10.288
 - System Version: PF2e 4.3.4
 - Item Piles Version: 2.2.10

**Comment by Haxxer** [comment]
Official stance is "no touchy":

https://discord.com/channels/880968862240239708/880969174661353484/1041135025590128650

**Comment by MrVauxs** [comment]
Can mark it as a "not planned" or leave it open and tag it as `wontfix`, this certainly ain't fixed.

**Comment by Haxxer** [comment]
I appreciate the sentiment, but there are friendlier ways to say the same thing 😉
