### ISSUE TITLE
[REQUEST] - transfer item

### ISSUE THREAD

**Issue by eunaumtenhoid** [fantasycalendar/FoundryVTT-ItemPiles#186]
it is possible to add the option to drop (Transfer) item from one token to another, preferably only for GM

like this mod:
https://github.com/David-Zvekic/DragTransfer

**Comment by Haxxer** [comment]
Have you tried doing this? It is a feature already...

**Comment by eunaumtenhoid** [comment]
yes, but it didn't work
just created an item on the character sheet, but not transferred from one sheet to another, only if you trade

**Comment by Haxxer** [comment]
I cannot interrupt sheet-to-sheet logic as that is **very system specific**, and I cannot make that work for the 10+ systems that I currently support. You will need another module for that, sorry.
