### ISSUE TITLE
[BUG] - Search Merchants

### ISSUE THREAD

**Issue by 9ryex5** [fantasycalendar/FoundryVTT-ItemPiles#187]
**Describe the bug**
The search box of merchants doesn't seem to be working.

**Screenshots**
![image](https://user-images.githubusercontent.com/43207603/201096029-8a23d69c-cb19-4269-b414-a7ed8049cf8f.png)

**Setup:**
 - Foundry Version: [e.g. 10.288]
 - System Version: [e.g. DND5e 2.0.3]
 - Item Piles Version: [e.g. 2.2.11]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment]
Fixed in 2.2.12
