### ISSUE TITLE
[REQUEST] - Randomise Items From a RollTable

### ISSUE THREAD

**Issue by pontusedberg** [fantasycalendar/FoundryVTT-ItemPiles#188]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I would like to have Randomised items a chest.
To do so I have a roll table with 100 items in it.
I would love so ItemPiles could fill a sheet with these random items. 

**Describe alternatives you've considered**
In the past I used lootsheetnpc5e By ChalkOne to make this happen.
but it is no longer supported. 

**Additional context**
it would be great to have it roll from multiple Rolltables aswell from foundry :)

**Comment by Haxxer** [comment]
Already supported:

https://fantasycomputer.works/FoundryVTT-ItemPiles/#/sample-macros?id=populate-loot-via-table
