### ISSUE TITLE
[PF2] Dialog for Giver and Receiver to approve the transaction

### ISSUE THREAD

**Issue by apoapostolov** [fantasycalendar/FoundryVTT-ItemPiles#191]
I have been using the Give to Player mod for item trading between players, unfortunately, it has been finally broken and doesn't seem to be supported anymore. I like how easy it is to drag items to other players in PF2 but there are several problems that the old Give to... mod handled better.

- When two players think about whether they should really pass an item to each other when one just drags and gives the item, and then they change their mind, the receiver must manually return the item back. If there was a dialog shown to both sides that both sides must approve to then complete the item transaction, that would prevent a lot of hasty item transfers. Alternatively, inspired by Damage Log, the automatic transfer could generate a chat message that any of the two players (including the GM) could right-click to revert the transaction from the receiver back to the giver. 

- There's no easy way to send only X of Y items from an item with quantity. The such item needs to be cloned, quantity distributed between the two piles and one of the piles sent to the receiver. Having a dialog that allows setting the exact amount at any time until both sides approve the transaction, would prevent a lot of manual work.

**Comment by Haxxer** [comment]
Have you tried to use the trading functionality of Item Piles by pressing the trade button in the player list? It seems like that would cover all of your use cases...

**Comment by apoapostolov** [comment]
Hello @Haxxer I just discovered it by searching for it now that you mentioned it, but it wasn't easy to find. Is there a way to add this to the inventory page of a player, as a button that would open a dialog that they could pick an actor from a dropdown and then add items to it?

**Comment by Haxxer** [comment]
The player list is always visible? It's the best place for it, honestly.

**Comment by apoapostolov** [comment]
I will run it with my players and see if a problem comes up, from UX standpoint.

**Comment by Haxxer** [comment]
Let me know what they think!

**Comment by apoapostolov** [comment]
Reopening just to ask a question, wouldn't it make it more accessible if the hands icon was available as a button on the right side of each of the other Player's rows? 

![image](https://user-images.githubusercontent.com/4083812/201442462-efd30b29-ed63-4d8f-9a26-fb0d06a62e47.png)
