### ISSUE TITLE
[BUG] - Spectators does not see trades in progress

### ISSUE THREAD

**Issue by gubacelar** [fantasycalendar/FoundryVTT-ItemPiles#193]
**Describe the bug**
Spectate Trade by GM not working.
The box shows up, but it's not possible to see the itens beeing traded, and if GM closes the popup the trade is cancelled.

**To Reproduce**
1. Create a new world using dnd 5e as system
2. Add 2 players and give then characters
3. Make one of then request trade to the other player and accept
4. As GM click in Spectate Trade
5. Add itens to trade
6. Players can see whats beeing trade but the GM can't

**Expected behavior**
The GM should be able to see the items in the trade as the player do.

**Screenshots**
Player 2 view
![5f6b0b98-d4f5-40bd-bd9d-7cd64937602f](https://user-images.githubusercontent.com/1326202/201943416-a15d0279-598f-4db9-b6f7-b6463356d573.png)
Player 3 view
![6bc27c76-df7e-441b-9226-f29ce8b9202f](https://user-images.githubusercontent.com/1326202/201943426-a7136a75-73f2-43fb-986a-a8876b91afe0.png)
GM view
![Screenshot_20221115_112340](https://user-images.githubusercontent.com/1326202/201943657-67d1306a-cb75-4c2a-874d-8e846bc9e398.png)

**Setup:**
 - Foundry Version: [e.g. 10.290]
 - System Version: [e.g. DND5e 2.0.3]
 - Item Piles Version: [e.g. 2.2.13]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - Ownership Viewer

**Additional context**
It seems that the GM can see only the items that where added until the moment he click on the spectate trade, all items added or removed after that can't be see.

**Comment by Haxxer** [comment]
Fixed in 2.3.0
