### ISSUE TITLE
[BUG] - German language not working

### ISSUE THREAD

**Issue by IrishWolf** [fantasycalendar/FoundryVTT-ItemPiles#194]
**Describe the bug**
If german / Deutsch is the foundry language, everything is still in english.

**To Reproduce**
1. Go to Settings
2. Scroll down to Language
4. Choose "Deutsch (German)"

**Expected behavior**
The Module should use the de.json

**Screenshots**
I think you get it without screenshots.

**Setup:**
 - Foundry Version: 10.288
 - System Version: Coriolis 3.0.2
 - Item Piles Version: 2.2.12
 - Browser & version MS New Edge 107.0.1418.42

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**
If another language is choosen like french: everything works as it should

**Comment by Haxxer** [comment]
That is because the German translation is several versions old, and therefore is not used as it would be broken. If you wish to contribute to the effort of translating the project, you can join weblate here:

https://weblate.foundryvtt-hub.com/projects/item-piles/#languages
