### ISSUE TITLE
[REQUEST] - Support for items without quantity value (as Unique Items?)

### ISSUE THREAD

**Issue by mrkwnzl** [fantasycalendar/FoundryVTT-ItemPiles#195]
**Is your feature request related to a problem? Please describe.**
In the Cypher system, there are several items that don’t have a quantity value, as that wouldn’t really make sense for the system. There are, for example, single, one-use items each with their own values (such as a level), so that they can’t be stacked. So if a character has multiple items of that, those need to be separate items on the character sheet.

As I understand Item Piles, all items need to have a quantity value to be compatible with it, so these one-use items won’t work.

**Describe the solution you'd like**
It would be great to be able to also have items that don’t have a quantity value be compatible with Item Piles. Maybe there could be a setting to define Unique Items (as a new concept within Item Piles) that can be used with Item Piles even if they don’t have a quantity value. Unique Items could be defined via item types, so that other item types, which don’t have a quantity value could be added to the supported items. If such an item were to be part of the the pile, those could have a hard coded, unchangeable quantity of one, so that they are unique items in the pile as well, or omit the quantity value entirely.

I realize that this might be an edge case, so a way to define such unique items only via the API within the system might also work, although I’ve read that at least Cyberpunk Red has the same problem, so a GUI solution might be desirable to make the module more system agnostic.

**Describe alternatives you've considered**
I have considered adding a quantity value to all items but I think that would be confusing for the user if there were stackable items in the pile, which aren’t stackable on their sheet and which are, conceptually, unique tokens of the same item type.

Thanks for considering!

**Comment by Haxxer** [comment]
Given the entire module's architecture is designed around the idea that items must have quantity, this request is a bit of a doozy. I've been thinking how to best approach it, but I suppose if the item doesn't have the quantity attribute, I can add 1 of that item and avoid merging it with similar items to increase their (non-existent) quantity. Something for me to noodle on, nonetheless. No promises it'll get done anytime soon.

**Comment by Haxxer** [comment]
Added in 2.3.0

**Comment by mrkwnzl** [comment]
Awesome! Thank you!
