### ISSUE TITLE
[SYSTEM] - Coriolis

### ISSUE THREAD

**Issue by IrishWolf** [fantasycalendar/FoundryVTT-ItemPiles#196]
# **https://foundryvtt.com/packages/yzecoriolis**
# **https://github.com/winks-vtt/yze-coriolis**

### **Actor Class Type**:
"npc"

### **Item Quantity Attribute**:
"system.quantity"

### **Item Price Attribute**:
"system.cost"

### **Item Filters**:
"injury, shipProblem, shipCriticalDamage, shipLogbook"

### **Item Similarities**:
"type, name"

### **Currencies**:
- **Name**: "Birr" _or localized name_ "YZECORIOLIS.Birr"
- **Path**: "system.birr"
- **Image**: "icons/commodities/currency/coin-inset-insect-gold.webp"
- **Exchange Rate**: 1
- **Shorthand Name**: Birr
- **Primary Currency**: Yes

**Comment by Haxxer** [comment]
Added in 2.3.0
