### ISSUE TITLE
[SYSTEM] - Kamigakari

### ISSUE THREAD

**Issue by jamijami00** [fantasycalendar/FoundryVTT-ItemPiles#197]
# **https://github.com/ksx0330/FVTT-Kamigakari-System**

### **Actor Class Type**: "character"

*The actor class type is the type of actor that will be used for the default item pile actor that is created on first
item drop*

### **Item Quantity Attribute**: "data.quantity"

*The item quantity attribute is the path to the attribute on items that denote how many of that item that exists*

### **Item Price Attribute**: "data.price"

*The item price attribute is the path to the attribute on each item that determine how much it costs*

### **Item Filters**: "talent, attack option, ancestry, facet, facade, bond"

*Item filters actively remove items from the item pile inventory UI that users cannot loot, such as spells, feats, and
classes*

### **Item Similarities**: name, class, usage

*Item similarities determines how item piles detect similarities and differences in the system*

### **Currencies**:

*Currencies in item piles are a list of names, attribute paths, and images - the attribute path is relative to the
actor.data*

- **Name**: "Gold" _or localized name_ "KG.Money"
- **Path**: "data.attributes.money"
- **Image**: 
- **Exchange Rate**: 1
- **Shorthand Name**: G
- **Primary Currency**: Yes

---------------------------------------------

Equipment doesn't have a quantity attribute and their relevant attributes are: form, restrict and mode

**Comment by Haxxer** [comment]
I cannot add support for this system as it does not have a v10 compatible version.

**Comment by jamijami00** [comment]
The release version 1.4.10 is compatible with the v10, but is running with some deprecated parts, like using data instead of system. I'll try to help on the migration of the system to v10 and update the system manifest to help out.

**Comment by Haxxer** [comment]
Added in 2.3.0
