### ISSUE TITLE
Passing `options.tokenSettings` to `turnTokensIntoItemPiles()` touches at least one part of the token config that it shouldn't, when applied to multiple controlled tokens.

### ISSUE THREAD

**Issue by unsoluble** [fantasycalendar/FoundryVTT-ItemPiles#199]
**To Reproduce**
1. Make a `turnTokensIntoItemPiles()` call on more than one token, passing some stuff in `options.tokenSettings`:
```
await game.itempiles.API.turnTokensIntoItemPiles(canvas.tokens.controlled,
{ tokenSettings: {
    "light.bright": 0
}});
```
Note that all controlled tokens' `texture.src` is replaced with the image of the oldest-placed token in the group.

**Expected behavior**
Only the `tokenSettings` that are actually configured in the call should be modified.

**Setup:**
 - Foundry Version: 10.290
 - System Version: dnd5e 2.0.3
 - Item Piles Version: 2.2.13

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment]
Turns out changing the object that every token update uses makes every token change to that token! Thanks!
