### ISSUE TITLE
[BUG] - [Conflict w/ Monk's Active Tile Triggers]

### ISSUE THREAD

**Issue by JasonSlingsCode** [fantasycalendar/FoundryVTT-ItemPiles#20]
**Describe the bug**

In a new world with only Item Piles and Monk's Active Tile Triggers enabled, I drop a single item from the items sidebar onto the canvas. A tile is created using the item's icon, then I am given the option of creating a single-item "item pile". There is no console error or warning given.

With Monk's disabled, the above workflow creates a single-item item pile using the expected art asset (with no extra tile remaining).

<img width="253" alt="Screen Shot 2022-01-07 at 01 15 57" src="https://user-images.githubusercontent.com/5216225/148500651-ba455269-e985-43fd-8134-9425e08b11d7.png">

<img width="815" alt="Screen Shot 2022-01-07 at 01 16 54" src="https://user-images.githubusercontent.com/5216225/148500733-1cd4aded-ffff-4090-8fc4-10e6cdf195ed.png">

**Expected behavior**

When the Monk's mod is on, I expect a single-item item pile to be created when dragging a single item onto the canvas.

**Actual behavior**

I get a single-item item pile, and a tile using the item's icon.

**Setup:**
 - Foundry Version: [.9241]
 - Item Piles Version: [e.g. 1.0.5]
 - OS: [iOS]
 - Browser [chrome]
 - Version [e.g. 96]

**Active modules:**
 - Item Piles
 - Monk's Active Tile Triggers
 - Dependencies listed on activation

**Comment by JasonSlingsCode** [comment]
Monk's Active Tile Triggers has a setting - "Drop Items As Tiles". Disabling this setting elicits the expected behavior (only an item pile is created, as expected).

**Comment by Haxxer** [comment]
I will add a warning to Item Piles in 1.0.6

**Comment by Haxxer** [comment]
Scratch that, Ironmonk will add a check on his side.
