### ISSUE TITLE
[BUG] Buying items can result in negative currency

### ISSUE THREAD

**Issue by gsterling** [fantasycalendar/FoundryVTT-ItemPiles#200]
**Describe the bug**
The calculation which determines what currency to substract from the token is broken. It can result in having negative amount of some currency. When you have currencies T, L and the amount x of T is equal to 1L, then you always have to pay it fully in T currency when you have between (price - x/2) and (price) of this currency in your pocket and this results in haven something between -x/2 and 0 of T left. See the following example to better understand it. Just keep in mind, the tipping point is half of the factor between the two currencies.

I suspect somewhere is something divided by 2 by accident.

It does correctly calculate, if you have enough money though. It's just substracting it wrong.

**To Reproduce**
1. Create multiple currencies. For example:
    ![image](https://user-images.githubusercontent.com/58980630/203632626-9ef68142-b522-468a-bdfd-ec1f8a790f28.png)
1. Create an Item with a base price of 1200
1. Give it to a merchant
1. Create a new token and give it 1L and 1149T
1. Buy the item
1. It's correctly calculated:
    ![image](https://user-images.githubusercontent.com/58980630/203632931-50da5502-de2b-4156-8236-51e677968302.png)
1. Set the token to 1L and 1150T
1. Buy the item again.
1. It's broken:
    ![image](https://user-images.githubusercontent.com/58980630/203633049-12d74c04-74f2-4071-b8e5-5363c5d370b5.png)
1. See the now negative currency:
    ![image](https://user-images.githubusercontent.com/58980630/203633102-fd5489d6-b16d-4fc3-945a-19820d096e7f.png)

**Expected behavior**
I'd expect to use the higher currency if the smaller currency isn't enough to pay for the item.

**Setup:**
 - Foundry Version: 10.290
 - System Version: Splittermond latest (With custom patch to enable merchants with ItemPiles)
 - Item Piles Version: 2.3.0
 - Browser & version Firefox & Chromium, both latest

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - Find the Culprit

**Comment by Haxxer** [comment]
Fixed in 2.3.1
