### ISSUE TITLE
[BUG] - Token Scaling and Adjusting Issues

### ISSUE THREAD

**Issue by Morrinn** [fantasycalendar/FoundryVTT-ItemPiles#201]
**Describe the bug**
Editing the appearance of an Item Pile token returns constant glitches. Either the token scales incorrectly, or refuses to flip horizontally or vertically. If I rotate the token, then attempt to edit the scale or flip it, the token snaps back into it's original position and scales down.

**To Reproduce**
1. Create an item pile.
2. Rotate it any angle.
3. Scale or flip the token.
5. Apply for fuckery!

**Expected behavior**

**Setup:**
 - Foundry Version: [e.g. 10.290]
 - System Version: [e.g. DND5e 2.0.3]
 - Item Piles Version: [e.g. 2.3.1]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment]
This appears to be coming from a Foundry bug - whenever a token is updated through its token configuration UI, the actor is also updated, which Item Piles picks up on, and then updates the token again, which causes this strangeness. I'll update this bug with the link to the ticket of the Foundry bug when it is created.

**Comment by Haxxer** [comment]
https://github.com/foundryvtt/foundryvtt/issues/8564

**Comment by Haxxer** [comment]
No longer happens in Foundry 10.291
