### ISSUE TITLE
[BUG] - Old-School Essentials drop items does not work anymore

### ISSUE THREAD

**Issue by JordanRR** [fantasycalendar/FoundryVTT-ItemPiles#202]
**Describe the bug**
Players do not have permission anymore to drop item on the canvas to create an item pile. Before last update, they could.

**To Reproduce**
1. Have players permission.
2. Drop item on canvas from inventory.
3. See error

**Expected behavior**
Item pile should be created on canvas.

**Screenshots**

**Setup:**
 - Foundry Version: [e.g. 10 build 290]
 - System Version: Old-School Essentials 1.6.8
 - Item Piles Version: 2.3.1
 - Browser & version Brave 1.45.131

**Active modules:**
Button Feel v;
Cautious Gamemaster's Pack v;
Compendium Folders v;
DF Architect v;
DF Chat Enhancements v;
DF Quality of Life v;
DF Scene Enhancement v;
Dice So Nice! v;
Dice Tray v;
Dig Down - Advanced Search v;
Drag Ruler v;
Dungeon Draw v;
Find the culprit v;
Forien's Quest Log v;
GM Notes v;
Illandril's Chat Enhancements v;
Illandril's Token HUD scaler v;
Inline Table Rolls v;
Item Piles v;
Less Fog v;
lib - Color Settings v;
libWrapper v.0;
LightsHUD v;
Module Compatibility Checker v;
Monk's Little Details v;
Monk's Scene Navigation v;
Monk's Wall Enhancement v;
Multilevel Tokens v;
Multiple Document Selection v;
Ownership Viewer v;
Perfect Vision v;
PnP - Pointer and Pings! v;
PopOut! v;
Quick Insert - Search Widget v;
Simple Calendar v;
SmallTime v;
Smart Target v;
socketlib v;
The Forge v;
The Forge: More Awesomeness v;
Tidy UI - Game Settings v;
Token Auras v;
Token Ease v;
Tokenizer v;
Token Z v;
User Latency v;
Window Controls v;
WTF: What the Flag? v;

**Additional context**
Thank you!

**Comment by Haxxer** [comment]
What is the error? You have not included it in the bug.

**Comment by Haxxer** [comment]
Besides, OSE is not one of the supported systems in Item Piles:
https://fantasycomputer.works/FoundryVTT-ItemPiles/#/README?id=natively-supported-systems

**Comment by JordanRR** [comment]
Not an error per se, but simply the fact that only GM can create an item pile.é

![image](https://user-images.githubusercontent.com/18445516/203772631-6fc09db4-93b4-4260-b110-330625baf756.png)

**Comment by Haxxer** [comment]
Well, unless you have configured the module correctly, I cannot ensure that the module will work.

**Comment by Haxxer** [comment]
This can't be fixed until the system integrates this pull request:

https://github.com/vttred/ose/pull/267

**Comment by JordanRR** [comment]
Thanks for taking the time!

**Comment by Haxxer** [comment]
Should work as of OSE's latest version
