### ISSUE TITLE
[BUG] - "Split Currency x ways" not working when "Sharing Enabled: Currencies" is disabled

### ISSUE THREAD

**Issue by stschmitt87** [fantasycalendar/FoundryVTT-ItemPiles#203]
**Describe the bug**
I disabled the option "Sharing Enabled: Currencies" in the configuration of an item pile. That item pile hat 9 Copper in it (dnd5e) and I have 3 players. 
Whe one of them clicked the button "Split currency 3 ways", they got a message "An item pile's content was split among 3 players, and each one has received:". The message was missing the amount that should have been splitted, and no player received any currency. The item pile still contained the 9 Copper.
My understanding is, that the opton "Sharing Enabled: Currencies" only restricts the maximum amount a player can take, but still allows them to split it if they want. If my understanding is not correct, the button to split the currency should not be displayed if the option is off.

**To Reproduce**
1. Create an Item Pile.
2. Add currency.
3. Configure the Item Pile,  remove the check on "Sharing Enabled: Currencies".
4. Open the Item Pile as a Player.
5. Click on "Split currency x ways".
6. A message appears, but no currency is given  to any player and the same amount is still in the item pile.

**Expected behavior**
The currency is still split among the specified players if the button is hit.

**Screenshots**
![image](https://user-images.githubusercontent.com/52425547/203873205-83e5ea9c-46c6-464e-b11a-4ddf85dfdc6c.png)
![image](https://user-images.githubusercontent.com/52425547/203873328-31c98c62-fd2b-4622-907f-85d4edbd6f44.png)
![image](https://user-images.githubusercontent.com/52425547/203873146-f59cf38b-bc56-415e-998b-55e55a337006.png)

**Setup:**
 - Foundry Version: 10 Build 290
 - System Version: DND5e 2.0.3
 - Item Piles Version: 2.3.2
 - Browser & version: Chrome Version 107.0.5304.107 and Firefox 107.0

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - Find the culprit
 - Multilevel Tokens

**Comment by Haxxer** [comment]
Fixed in 2.3.3

**Comment by Just2good** [comment]
I seem to get this issue with the latest version 2.4.15. I want the player to be able to take all the currency, or split if the button is pressed. Pressing the split button with "Sharing Enabled: Currencies" disabled causes all the currency to disappear into nether and nothing is split.
