### ISSUE TITLE
[BUG] Converting tokens to ItemPiles doesn't respect the 'Split Only With Active Players' setting of the Default Item Pile 

### ISSUE THREAD

**Issue by gsterling** [fantasycalendar/FoundryVTT-ItemPiles#205]
**Describe the bug**
When converting an existing token to an ItemPile to make it lootable as described in the [wiki](https://fantasycomputer.works/FoundryVTT-ItemPiles/#/sample-macros?id=make-tokens-lootable), it will always default to split the currency between all players, not only the active ones.

This means I'd have to set it up for every NPC I create seperately. Since I am using an importer, because of splittermonds complex rules it's not viable to create a default NPC everytime I need a new one and it bothers me, if I forget to change it for one of the NPCs.

**To Reproduce**
1. Create a 'Default Item Pile'
2. Enable 'Enable Split With Players Button'
3. Enable 'Split Only With Active Players'
4. Create a new actor
5. Place it on the canvas
6. Use the [macro](https://fantasycomputer.works/FoundryVTT-ItemPiles/#/sample-macros?id=make-tokens-lootable) to convert it
7. See the button saying it's split X ways (number of players, not number of players currently online)
8. Go the the new piles settings and see 'Split Only With Active Players' is disabled

**Expected behavior**
It should either respect the setting in the Default Item Pile or let me select a default for all converted tokens.

**Screenshots**

**Setup:**
 - Foundry Version: 10.290 (latest)
 - System Version: Splittermond 0.9.7 (latest)
 - Item Piles Version: 2.3.4 (latest)
 - Browser & version Chrome (latest)

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
- Find the culprit

**Additional context**

**Comment by Haxxer** [comment]
You could just ask for help with the macro too :) Here's a macro that'll turn on that setting:
```js
if (!canvas.tokens.controlled.length) return;
game.itempiles.API.turnTokensIntoItemPiles(canvas.tokens.controlled, {
    pileSettings: { activePlayers: true,  }
})
```

**Comment by gsterling** [comment]
> You could just ask for help with the macro too :) Here's a macro that'll turn on that setting:
> 
> ```js
> if (!canvas.tokens.controlled.length) return;
> game.itempiles.API.turnTokensIntoItemPiles(canvas.tokens.controlled, {
>     pileSettings: { activePlayers: true }
> })
> ```

That is even better :) Thank you. I haven't found that in the wiki.
