### ISSUE TITLE
[REQUEST] - Option to display cost of item in chat output when purchasing from shop

### ISSUE THREAD

**Issue by ZBell** [fantasycalendar/FoundryVTT-ItemPiles#207]
**Is your feature request related to a problem? Please describe.**
It is sometimes confusing or difficult to remember the exact cost of items, without opening up the item sheet.

**Describe the solution you'd like**
It would be nice if there were an option to display the amount spent on the item in the chat output.  Perhaps a total at the bottom when the character finishes shopping?

**Comment by Haxxer** [comment]
Added in version 2.6.9
