### ISSUE TITLE
[BUG] - Item types not named correctly

### ISSUE THREAD

**Issue by IrishWolf** [fantasycalendar/FoundryVTT-ItemPiles#210]
**Describe the bug**
If a Pile has "Split items by item types" activatet it listend the types like "Item.TypeArmor" or "Item.TypeTalent" instead of "Armor" oder "Talent".

**To Reproduce**
1. Go to an Item Pile
2. Click on Configure Pile --> Main Settings
3. Activate "Split items by item types"

**Expected behavior**
It should listen them with their name.

**Screenshots**
![image](https://user-images.githubusercontent.com/36819852/205690580-3ce87c80-8987-49c5-9415-10ebfdfbd193.png)

**Setup:**
 - Foundry Version: 10.290
 - System Version: Coriolis 3.0.2
 - Item Piles Version: 2.3.6

**Active modules:**
Reproduceable with only Item Piles and dependencies

**Comment by Haxxer** [comment]
This works in every other system, so it must be Coriolis that does something different. I'm relying on `CONFIG.Item.typeLabels` containing the unlocalized string for each item type. Since Coriolis breaks from this pattern, I can't do much about this. Closing as won't fix.
