### ISSUE TITLE
[BUG] Module Breaks When Used In WWN 

### ISSUE THREAD

**Issue by Cup-of-Coffee** [fantasycalendar/FoundryVTT-ItemPiles#211]
**Describe the bug**
In the Worlds Without Number game system, when a character drops a item from their inventory onto the ground to create a new pile, they instead drop a skill. The skills that are dropped do so in a pattern: Lead, Survive, Sneak, Exert, Know, Magic, Trade, Ride, Pray, Shoot, Work, Heal, Notice, Craft, Sail, Stab, Perform, Convince, Punch, Connect, Administer. 

After all skills have been removed/dropped out of the character, it will then begin to drop items in the order they were added to the sheet.

The settings of the Item Piles module has:
- Actor class type set to "character"
- Item quantity attribute set to "system.quantity".
- Item price attribute set to "system.price".

**To Reproduce**
1. Setup the module settings has noted above.
2. Create a new character.
3. Add a item, such as a new weapon or new item.
4. Drop a item on a scene to create a item pile with the item, instead getting a item pile with the skill instead.

**Expected behavior**
When a character drops a item from their inventory, it should drop that exact item instead of their skills or other items.

**Screenshots**
Items that were dropped in order.
![Screenshot 2022-12-12 150452](https://user-images.githubusercontent.com/39238717/207145223-d89672a4-33c2-4e7f-99f0-ab101f6269f1.png)

**Setup:**
 - Foundry Version: [291]
 - System Version: [Worlds Without Number Beta5]
 - Item Piles Version: [2.3.7]
 - Browser & version [Firefox 107.0.1]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**
The order of skills that drop follows the order of the skill items as established in the skill.db file for the game system's pack.

**Comment by Haxxer** [comment]
Please see:
https://fantasycomputer.works/FoundryVTT-ItemPiles/#/README?id=requesting-support-for-system
