### ISSUE TITLE
[SYSTEM] - Worlds Without Number

### ISSUE THREAD

**Issue by Cup-of-Coffee** [fantasycalendar/FoundryVTT-ItemPiles#212]
# **https://github.com/SobranDM/foundryvtt-wwn**

Note: The v10 compatible version that's worked on to remove bugs: https://github.com/SobranDM/foundryvtt-wwn/releases/tag/v1.0.1-beta5

### **Actor Class Type**: "character"

*The actor class type is the type of actor that will be used for the default item pile actor that is created on first
item drop*

### **Item Quantity Attribute**: "system.quantity"

*The item quantity attribute is the path to the attribute on items that denote how many of that item that exists*

### **Item Price Attribute**: "system.price"

*The item price attribute is the path to the attribute on each item that determine how much it costs*

### **Item Filters**: "ability, art, asset, focus, skill, spell"

*Item filters actively remove items from the item pile inventory UI that users cannot loot, such as spells, feats, and
classes*

### **Item Similarities**: "name, type"

*Item similarities determines how item piles detect similarities and differences in the system*

### **Currencies**:

*Currencies in item piles are a list of names, attribute paths, and images - the attribute path is relative to the
actor.data*

- **Name**: "Copper Pieces" _or localized name_ "WWN.items.CP.long"
- **Path**: system.currency.cp
- **Image**: Blank.
- **Exchange Rate**: 0.1
- **Shorthand Name**: Copper
- **Primary Currency**: No

---

- **Name**: "Silver Pieces" _or localized name_ "WWN.items.SP.long"
- **Path**: system.currency.sp
- **Image**: Blank.
- **Exchange Rate**: 1
- **Shorthand Name**: Silver
- **Primary Currency**: Yes

---

- **Name**: "Gold Pieces" _or localized name_ "WWN.items.GP.long"
- **Path**: system.currency.gp
- **Image**: Blank.
- **Exchange Rate**: 10
- **Shorthand Name**: Gold
- **Primary Currency**: No

**Comment by Cup-of-Coffee** [comment]
The system also supports B/X currencies, which is enabled by clicking a button in the settings.

- **Name**: "Electrum Pieces" _or localized name_ "WWN.items.EP.long"
- **Path**: system.currency.ep
- **Image**: Blank
- **Exchange Rate**: 5
- **Shorthand Name**: Electrum
- **Primary Currency**: No

- **Name**: "Platinum Pieces" _or localized name_ "WWN.items.PP.long"
- **Path**: system.currency.pp
- **Image**: Blank
- **Exchange Rate**: 50
- **Shorthand Name**: Platinum
- **Primary Currency**: No

**Comment by Haxxer** [comment]
Added in 2.3.8

**Comment by Cup-of-Coffee** [comment]
Copper Pieces exchange rate seems to be inputted incorrectly. It should be `0.1` and not `0.01`. Otherwise everything looks to working perfectly.

Thanks for the help!

**Comment by Cup-of-Coffee** [comment]
> Added in 2.3.8

Copper Pieces exchange rate seems to be inputted incorrectly. It should be 0.1 and not 0.01. Otherwise everything looks to working perfectly.

Thanks for the help!
