### ISSUE TITLE
[BUG] - WWN Weapons/Armor Causing Trade Window To Not Close

### ISSUE THREAD

**Issue by Cup-of-Coffee** [fantasycalendar/FoundryVTT-ItemPiles#214]
**Describe the bug**
When a trade between two players is done that involves a armor type item, the window will not close, showing the trade window with a continuously loading bar. In the console a error is given.

The items are transferred properly, but the window will need to be manually closed out in order to remove it.

**To Reproduce**
1. Start a trade with another player.
2. Have the trade involved a armor or weapon type item, such as "Mail Shirt"
3. Have both participants accept the deal.

**Expected behavior**
The window should close.

**Screenshots**
The error that's created after both participants accept the trade and the deal should end.
![armor](https://user-images.githubusercontent.com/39238717/207746692-836b9947-4c79-4561-a82f-c59d278ef032.png)

A example of a trade that doesn't close.
![Screenshot 2022-12-14 194023](https://user-images.githubusercontent.com/39238717/207747047-5261c638-cb01-477a-bec1-b07ed42586d6.png)

**Setup:**
 - Foundry Version: 10.291
 - System Version: WWM Beta5 Release
 - Item Piles Version: 238
 - Browser & version: Firefox 108.0

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**
This was tested on a fresh new world, with both items from the compendium and newly created items.

**Comment by Haxxer** [comment]
This is a bug with Worlds Without Number - `actor.createEmbeddedDocuments` returns an array of promises; which is unalike _every single system_ I have added support for thus far. Please report this to the devs.
