### ISSUE TITLE
[REQUEST] - Have `turnTokensIntoItemPiles()` pull IP flags from the Default Item Pile

### ISSUE THREAD

**Issue by unsoluble** [fantasycalendar/FoundryVTT-ItemPiles#218]
Currently, using `turnTokensIntoItemPiles()` nets you tokens with pile config that's pulled from the global defaults. I think it would be fairly universally preferable to instead pull from the Default Item Pile config, so that scripted loot piles can have their starting config easily match the rest of one's world defaults.

**Describe the solution you'd like**
I _think_ just straight-up having this method auto-pull Default Item Pile config should be fine in all cases; there's still room for overrides by passing `options.pileSettings`.

**Describe alternatives you've considered**
Could be implemented as an additional boolean argument in the method, I suppose.

Thanks for considering! :)

**Comment by Haxxer** [comment]
Added in 2.4.0
