### ISSUE TITLE
Trade/Give items message

### ISSUE THREAD

**Issue by 123mind123** [fantasycalendar/FoundryVTT-ItemPiles#219]
Just to have the option to have messages post in chat when items are given/traded and for that message to list of the items given/traded from who to who.

**Comment by Haxxer** [comment]
Trades should create messages, giving items does not yet. I will fix the former, and add the latter in the next update.

**Comment by 123mind123** [comment]
Hey hey. Sorry maybe I didn't describe it well. The problem wasn't trades not posting a message. It was that messages didn't contain a list of the items that were traded. Such as:
Player 1 traded:
1 rock
2 bread
Player 2 traded:
1 hat
5 gold

**Comment by Haxxer** [comment]
That is what I said.

There SHOULD be a message, but a bug prevents it.

Giving doesn't make a message, because I didn't make a feature for it.

**Comment by Haxxer** [comment]
Fixed in 2.4.0
