### ISSUE TITLE
Filtered Item Types still show up

### ISSUE THREAD

**Issue by Hyrkanus** [fantasycalendar/FoundryVTT-ItemPiles#22]
**Describe the bug**
The items filtered out by the "Item type filters" setting are still visible in the item pile. They can't be transferred though. So it seems tey are correctly identified by the filters but still shown. (This goes for both players and GM)

**To Reproduce**
1. Set up filters according to game system 
2. Turn itemPile on for a npc
3. insepct the created itemPile

**Expected behavior**
I expect the filtered items not to show up when insepecting an item pile.

**Setup:**
 - Foundry Version: 9.241
 - Item Piles Version: 1.0.5
 - OS: Windows 10 64bit
 - Browser: FoundryVTT Application, Opera
 - Version: 82.0.4227.43

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**
I tried it both in my DnD 3.5 World and in a freshly created 5e world which has no other modules than the required enabled,

**Comment by Haxxer** [comment]
This is known and will be fixed in 1.0.6

**Comment by Haxxer** [comment]
Fixed in 1.0.6
