### ISSUE TITLE
[REQUEST] - Possibility to filter items with boolean value attributes

### ISSUE THREAD

**Issue by diwako** [fantasycalendar/FoundryVTT-ItemPiles#220]
**Is your feature request related to a problem? Please describe.**
I have been trying to sharpen the built in item filter in the Cyberpunk Red Core system.
At the moment it filters out any cyberware that is of types cyberwareInternal, cyberwareExternal, and fashionware. This means it filters items even if they are not installed in that person, making it not possible to drop such items into an item pile such as any container or shop.

Originally the filters are made due to the nature of foundational cyberware, which are of those 3 types mentioned above, but as it turns out cyberware that can be installed into those 3 foundations are of the same type, just marked as not a foundation with another boolean flag.

My idea of sharpening the filters was to check if such items are "installed" in the corresponding token/inventory. The system itself has that as a flag set under `system.isInstalled` of type boolean. I have tried adding such a filter just to notice that it does not work. Turns out in a short conversation with Wasp in the Foundry VTT discord server that such a thing is not yet a feature.

**Describe the solution you'd like**
Possible to filter items using attributes of type boolean.
As example:
![image](https://user-images.githubusercontent.com/8259498/210069304-57d08f87-7d59-4874-b953-d51b43b75c12.png)

**Describe alternatives you've considered**
Tried as the image above, tried to create multiple filters trying to achieve the same goal, then asking in the Foundry VTT discord server for advice.

**Additional context**
Original question from the foundry vtt discord server
https://discord.com/channels/170995199584108546/722566083499786352/1057739876562383008

**Comment by Haxxer** [comment]
Added in 2.4.0
