### ISSUE TITLE
[BUG] - Giving item to self duplicates item

### ISSUE THREAD

**Issue by lizzard77** [fantasycalendar/FoundryVTT-ItemPiles#222]
**Describe the bug**
When an actor gives an item to themselves. it will duplicate

**To Reproduce**
1. Open actor sheet
2. Go to inventory
3. Drag an item from the inventory onto the actor token on the canvas
4. Check the inventory to see that the item quantity increased

**Expected behavior**
Giving an item to oneself should be impossible, or the quantity should not change

**Setup:**
 - Foundry Version: 10 / 291
 - System Version: DND5e 2.0.3
 - Item Piles Version: 2.3.11
 - Browser & version: Edge Dev Windows 110

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment]
Very odd, this should be impossible:

https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/master/src/API/private-api.js#L1369

This piece of code checks whether the source and target are the same thing, and thus should fail.

**Comment by lizzard77** [comment]
It seems to be inconsistent at least. I created a new, emtpy scene, dropped an actor onto it, and had the actor give himself an item. This time, the item disappeared. See attached video. I couldn't repro the original behaviour I saw before.

https://user-images.githubusercontent.com/15921685/210176845-d9e667f5-c644-4707-a0fe-4ba7b09c5f80.mp4

**Comment by lizzard77** [comment]
Update: it seems to duplicate the item when quantity > 0, see second video

https://user-images.githubusercontent.com/15921685/210176913-dbd5aea1-2017-4b0d-aa38-2fc9f860d971.mp4

**Comment by Haxxer** [comment]
I figured it out, this will be fixed in the next update

**Comment by Haxxer** [comment]
Fixed in 2.4.0
