### ISSUE TITLE
[BUG] - Quantity Invisible

### ISSUE THREAD

**Issue by RavenknightDM** [fantasycalendar/FoundryVTT-ItemPiles#223]
Hiya!
I'm having a problem with release 2.3.11.
For some reason the Item Quantity will not show up in the shops.
![No amount](https://user-images.githubusercontent.com/53635985/210282037-5ee5f7be-6847-49c1-b9d2-27b42d95ce2f.png)

**Comment by Haxxer** [comment]
Could you please fill out the bug template so that I know what system you are using?

**Comment by RavenknightDM** [comment]
Sure thing!

**Setup:**
 - Foundry Version: 10.291
 - System Version: DND5e 2.0.3
 - Item Piles Version: 2.3.11
 - Chrome (Unsure of what version)

The problem persists with only Item Piles, Lib Wrapper (1.12.11.0) and Socketlib (1.0.12) running and all other mods disabled.

And thanks for the excellent mod!

**Comment by Haxxer** [comment]
Thanks, can you try to reset the system specific settings in item piles' settings?

**Comment by RavenknightDM** [comment]
Ha! That did the trick! Thank you so very much.
