### ISSUE TITLE
[REQUEST] - Closed days for merchants

### ISSUE THREAD

**Issue by Vlfberth** [fantasycalendar/FoundryVTT-ItemPiles#224]
Currently there's an option in Merchant's settings for closed hours based on the simple calendar module, I'd like to suggest to add closed days.

Basically with everything else when DMing, it's hard to remember the stores should be closed on weekends, so if I can select a day of the week that automatically closes the merchant, that would be great.

Also, it would be perfect if we could select days of the month for the same purpose as well, that way merchants could automatically close on holidays too.

Thanks for your time!

**Comment by Haxxer** [comment]
Would this work for you?

![image](https://user-images.githubusercontent.com/12858387/212479394-17278bd2-df19-4370-a728-6b0c76307ea9.png)

**Comment by Vlfberth** [comment]
Totally!! Thank you very much

**Comment by Haxxer** [comment]
I have added this feature in the latest beta build, do you think you could test it out?

Installation link:
https://raw.githubusercontent.com/fantasycalendar/FoundryVTT-ItemPiles/next/module.json

Please do back up your data if you do

**Comment by Haxxer** [comment]
Added in 2.4.10

**Comment by Vlfberth** [comment]
Hi! Sorry for the late reply, I just tested it, seems to be working great! Thanks a lot!
