### ISSUE TITLE
[BUG] - Do not get Permissions on my merchants

### ISSUE THREAD

**Issue by Charbizard** [fantasycalendar/FoundryVTT-ItemPiles#226]
**Describe the bug**
When using item piles, I do not get to set permission settings, thus my players cannot interact with the merchant.

**To Reproduce**
1. Download PTU "https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/raw/development/system.json"
2. Set System Specific Settings to "item", "data.quantity", and "data.cost".
3. Add a new currency based off of "system.money"
4. Create an Actor (character).
5. Enable them as an item pile and merchant
6. Add any inventory
7. Have no ability to edit any permissions whatsoever.

**Expected behavior**
Expect to see a permissions button to be able to allow players to interact.

**Screenshots**
![image](https://user-images.githubusercontent.com/98428555/210926010-95ff4aac-8d00-4acc-b743-42fc588ac3ab.png)

![image](https://user-images.githubusercontent.com/98428555/210926056-c920a265-4f95-4005-bbe4-ce8d73264788.png)

**Setup:**
 - Foundry Version: [10.291]
 - System Version: [PTU 3.0.0.6]
 - Item Piles Version: [2.3.11]
 - Browser & version [Google Chrome 108.0.5259.125]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - CodeMirror
 - Color Picker
 - Confetti
 - Custom CSS
 - Day Night Cycle
 - Dfeds Droppables
 - Drag Ruler
 - FXMASter
 - Initiative Double Clock
 - JB2a Patreon Collection
 - Less Fog
 - Lib - Color Settings
 - Library: ACtive Effect Manager
 - Math.js
 - Party Resources
 - Pings
 - Random Target
 - Sequencer
 - Settings Extender
 - Simple Calender
 - Socketlib
 - Split Journal
 - Timed Event
 - Token Magic FX
 - Token Says
 - Token Tooltip Alt
 - Video Game Music
 - Weather Control

**Additional context**
I spent about 2 hours with a player trying everything on your wiki we could think of (shes a CSNA, so shes got a bit more experience than myself)

**Comment by Charbizard** [comment]
https://cdn.discordapp.com/attachments/1060749097428058172/1060763476844347422/image.png

This is what i expected to see

**Comment by Haxxer** [comment]
You can just right click on the actor in the actor directory and set the permissions there...?

**Comment by Haxxer** [comment]
> https://cdn.discordapp.com/attachments/1060749097428058172/1060763476844347422/image.png
> 
> This is what i expected to see

This is a different module than Item Piles?

**Comment by Charbizard** [comment]
> > https://cdn.discordapp.com/attachments/1060749097428058172/1060763476844347422/image.png
> > This is what i expected to see
> 
> This is a different module than Item Piles?

oh if thats different my bad, on that, i pulled it from reddit that said it was using itempiles.

**Comment by Charbizard** [comment]
> You can just right click on the actor in the actor directory and set the permissions there...?

changing permissions for players in the Actor itself only allows them access to the Character sheet not to be able to interact with the Merchant itself. It configures ownership, not "permissions". I was assuming (and I may be wrong) that the reason I can't get my players to be able to open up the merchant interaction screen that I lacked some sort of permissions.

**Comment by Haxxer** [comment]
Do they have their character assigned to their used in the bottom left? The merchant won't know which of their characters to use otherwise.

**Comment by Charbizard** [comment]
I should?

I followed all the instructions, on the Wiki and Github, settings all the settings correctly with the help of the developer from PTU.

I just this morning got it to work for a player when I am logged in as the Player and the GM on the same Computer, but I don't know what that means.
![image](https://user-images.githubusercontent.com/98428555/211034423-79f2dfd3-3203-4118-8b52-063d546328b8.png)

**Comment by Charbizard** [comment]
> Do they have their character assigned to their user in the bottom left? The merchant won't know which of their characters to use otherwise.

Yes, got that

**Comment by Haxxer** [comment]
Then everything should work. It seems that none of your items have any cost though?

**Comment by Haxxer** [comment]
This is what I see in 5e:

![image](https://user-images.githubusercontent.com/12858387/211035022-67908643-e6b6-4d0e-8662-a71652f1ac83.png)

**Comment by Charbizard** [comment]
> Then everything should work. It seems that none of your items have any cost though?

Yeah i dont understand that either. I am trying to get them to function with her because it works in the window 

![image](https://user-images.githubusercontent.com/98428555/211035191-2c63c2bc-051e-4b37-9816-567fda179baf.png)


So if i can at least get it that far, i can use it

**Comment by Charbizard** [comment]
Thanks for trying to help me, I will poke around and see if maybe im just missing something. I assumed it was permissions.
