### ISSUE TITLE
[BUG] - [D&D 5e] Backgrounds are not in item filters

### ISSUE THREAD

**Issue by Amd321** [fantasycalendar/FoundryVTT-ItemPiles#227]
When using the merchant feature of the module with the dnd 5e sheet, players have the option to sell their background feature.

**To Reproduce**
Have player character sheet with a background feature, attempt to sell to a merchant item pile.

**Expected behavior**
Players not being able to sell their background features.

**Screenshots**
![Background Selling](https://user-images.githubusercontent.com/77754673/211664503-06a4bcd6-f98b-4ba5-b4aa-cd4f5fd6cf61.png)

Foundry Version: 10.288
System Version: DND5e 2.0.3
Item Piles Version: 2.3.1.1

Active modules:
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**

**Comment by Haxxer** [comment]
Can you please try to reset the item pile system settings?

**Comment by Amd321** [comment]
> Can you please try to reset the item pile system settings?

I tried this already a couple of times, and the behaviour still persists.

**Comment by Haxxer** [comment]
Can you drag the background to the item sidebar to the right, then right click and export it, and upload it here?

**Comment by Amd321** [comment]
> Can you drag the background to the item sidebar to the right, then right click and export it, and upload it here?

It's happening for the backgrounds of all my players, but I'll just pick one to upload I guess.

**Comment by Amd321** [comment]
> > Can you drag the background to the item sidebar to the right, then right click and export it, and upload it here?
> 
> It's happening for the backgrounds of all my players, but I'll just pick one to upload I guess.

It's happening for the backgrounds of all my players, but I'll just pick one to upload I guess.

**Comment by Amd321** [comment]
Github isn't allowing me to upload as it says it's an unsupported file type (json)

**Comment by Haxxer** [comment]
Zip it up and add it :)

**Comment by Amd321** [comment]
[fvtt-Item-far-traveler.zip](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/10387034/fvtt-Item-far-traveler.zip)

**Comment by Haxxer** [comment]
Ok, easy fix. I don't know why things have worked thus far, but simply add this in the settings, then save it:

![image](https://user-images.githubusercontent.com/12858387/211667366-dc8a00de-2457-428c-b998-744d559fcd09.png)

**Comment by Amd321** [comment]
Looks like background wasn't added as a default filter. It would be great if it was. Thanks!

**Comment by Haxxer** [comment]
Yep, I wasn't aware of that type, I'll add it in the next release

**Comment by Haxxer** [comment]
Fixed in 2.4.0
