### ISSUE TITLE
[BUG] - [DND5e] Item cost set to {Object Object}

### ISSUE THREAD

**Issue by Saharacaine** [fantasycalendar/FoundryVTT-ItemPiles#228]
**Describe the bug**
When setting up merchant NPC loot Piles everything works fine until i reach the actual buy page. all items have their prices converted to {object object} which displays and undefined price in the buy window. What this means is if i have an item in the Items list then add it to the merchant. the item in the list as well as the item in the merchant inventory loses its original value and converts to the above mentioned object object that is unchangeable.

**To Reproduce**
screenshots better explain the issue 

**Expected behavior**
I expect that when an item is added to the merchant loot pile it keeps all stats and reflects them inside the designated windows. 

[**Screenshots**]
![Screenshot 2023-01-10 231610](https://user-images.githubusercontent.com/122423253/211716600-06d9546d-8850-4e61-bb43-21d52a932173.png)
![Screenshot 2023-01-10 231648](https://user-images.githubusercontent.com/122423253/211716601-1e920a5a-bf6f-481d-87a8-39e61d48739a.png)
The following screenshot shows a merchant listing as undefined even tho the item is clearly listed for 2cp
![Screenshot 2023-01-10 at 23-39-01 Lost Mines of Phandelver • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/122423253/211719006-a7cc10a5-aa82-42c5-a5f9-aa7e6a2489c3.png)

**Setup:**
 - Foundry Version: 10.291
 - System Version: DND5e 2.1.1
 - Item Piles Version: 2.3.11
 - Browser & version: Firefox 108.0.2

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - aboutface
 - about time
 - ace library
 - beyond20 companion module
 - character actions list dnd5e
 - combat ready
 - combat utility belt
 - compendium folder
 - crash's tracking and training
 - dnd beyond gamelog
 - dnd beyond importer
 - dangerzone
 - day night cycle
 - dice tray
 - foundry community tables
 - game audio bundle 1-4
 - item containers
 - journals like a script
 - lets trade 5e
 - midi QOL
 - not enough NPCs
 - perfect vision
 - ping
 - polyglot
 - quick encounters
 - sequencer
 - settings extender
 - simple calender
 - simple loot list
 - token action HUD
 - token info icons
 - token mold
 - torch

**Comment by Haxxer** [comment]
DND 2.1.1 have changed things drastically, it may not be compatible with item piles until I update it.

**Comment by Haxxer** [comment]
Fixed in 2.4.0
