### ISSUE TITLE
[BUG] - [LootPile Empty State Doesn't Happen After "Take All" Event, Doesn't Auto-Delete]

### ISSUE THREAD

**Issue by JasonSlingsCode** [fantasycalendar/FoundryVTT-ItemPiles#23]
**Describe the bug**

When I "take all" loot out of a LootPile, the Pile remains in the "Open" state and never changes to the "Empty" state. It never auto-deletes.

**To Reproduce**
1. I add a single item to my LootPile on the canvas.
2. As a `player`, I click on the LootPile. The chest moves from the `closed` to the `open` state. I select `Take All` to remove the book.
3. The chest remains in the `open` state, never the `empty` state. It never auto-deletes.
4. I see no console errors.

This is in a world with only LootPiles module active.

**Expected behavior**

When I take all loot out of an open chest, I expect the chest to either be in the `empty` state or be auto-deleted.

**Screenshots**
<img width="581" alt="Screen Shot 2022-01-07 at 11 23 53" src="https://user-images.githubusercontent.com/5216225/148575541-504b2b6d-7d32-40e3-877b-1c6c0d04bbbd.png">

<img width="573" alt="Screen Shot 2022-01-07 at 11 22 52" src="https://user-images.githubusercontent.com/5216225/148575547-2a146022-4d5e-48da-a2d1-14799a1cc00d.png">

<img width="556" alt="Screen Shot 2022-01-07 at 11 22 37" src="https://user-images.githubusercontent.com/5216225/148575568-c017fd84-9559-4a21-a759-cec3c947bfb1.png">

**Setup:**
 - Foundry Version: [e.g. .9241]
 - Item Piles Version: [e.g. 1.0.5]
 - OS: [iOS]
 - Browser [e.g. chrome]
 - Version [Version 96.0.4664.110]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**

**Comment by Haxxer** [comment]
This may have been fixed in 1.0.6, could you check?

**Comment by JasonSlingsCode** [comment]
It's completely non-interactable now in 1.0.6, and I don't see the module settings in the settings section anymore.

**Comment by Haxxer** [comment]
Welp, my bad. 1.0.6 was broken, try 1.0.7 which was just released

**Comment by JasonSlingsCode** [comment]
in 1.0.7 I was unable to remove the item using `Take All`. I was able to remove it from the item's individual `Take` button, which left the chest empty, but it still didn't auto-delete, or move to an `empty` state.

**Comment by Haxxer** [comment]
Could you add the item to the actor again, export it (right click on the actor in the actor tab), and send it to me (Wasp#2005) on Discord?

**Comment by Haxxer** [comment]
Fixed all of these issues in 1.0.8
