### ISSUE TITLE
[BUG] - [DND5e] - Canvas drawing failed: Actor5e

### ISSUE THREAD

**Issue by Geektasticdad** [fantasycalendar/FoundryVTT-ItemPiles#230]
**Describe the bug**
After upgrading to the DnD5e - Fifth Edition System 2.1.1 I started receiving a couple of errors on some of my scenes (see screen shots)

I narrowed down the actor ID to an Item Pile actor. I restored my Foundry VTT server to it's pre-upgrade state, removed all the actors and tokens related to Item Pile, and then disabled the module, and then upgraded to 2.1.1 and all was fine.

**To Reproduce**
You really have to have Item Piles installed and actors/tokens set up with loot. From there I just upgraded to DnD5e - Fifth Edition System 2.1.1. 

**Expected behavior**
I expect the scenes to load without error messages..

**Screenshots**
Error messages

![chrome_fEeMd7zl6O](https://user-images.githubusercontent.com/73676044/211946843-633792d1-4b15-4958-b38b-c1e9ea156d3b.png)

![chrome_LOHHbNboEb](https://user-images.githubusercontent.com/73676044/211946853-99d0cb99-a30d-49b9-92ff-1523cbce5722.png)

**Setup:**

- Foundry Version: 10.291
- System Version: DND5e 2.1.1
- Item Piles Version: 2.4.0
- Browser & version Google Chrome 108.0.5359.125 (64-bit)

**Active modules:**

- Active-Auras
- Character Actions List dnd5e
- Compact DnDBeyond 5e Character Sheet
- Compendium Folders
- D&D Beyond Importer
- Dice So Nice!
- Dice Tray
- Drag Ruler
- Dynamic effects using Active Effects
- Easy Target
- Encounter Statistics
- Foundry Community Tables
- FXMaster
- Give item to another player
- Iconizer
- Introduce Me
- Item Piles
- libWrapper
- Lordu's Custom Dice for Dice So Nice
- Magic Items
- Math.js
- Midi QOL
- Module Compatibility Checker
- Monk's Active Tile Triggers
- Monk's Enhanced Journal
- Monk's Little Details
- Monk's Scene Navigation
- Monk's TokenBar
- Monk's Wall Enhancement
- Multilevel Tokens
- Player Status
- Playerlist Status - Lib for View status on Playerlist
- PnP - Pointer and Pings!
- Roll Tracker
- socketlib
- Tabletop RPG Music
- Token Action HUD
- Tokenizer
- Torch
- Universal Battlemap Importer
- User Latency
- Whisper As

**Comment by Haxxer** [comment]
Can you please confirm it is not another module conflict, given you have a lot of modules active?

**Comment by Geektasticdad** [comment]
> Can you please confirm it is not another module conflict, given you have a lot of modules active?

I did, in fact I disabled ALL modules (including Item Pile) and still had the errors pop up.

**Comment by Haxxer** [comment]
Could you try to replicate the issue in your world with only item piles (and required modules) and post any errors you get in the console? The notifications do not really help in narrowing down the problem.

**Comment by Geektasticdad** [comment]
> Could you try to replicate the issue in your world with only item piles (and required modules) and post any errors you get in the console? The notifications do not really help in narrowing down the problem.

I'm not really sure what you're asking me to do ... I've done several iterations of testing and the only thing that works is completely removing the Item Pile module and all item pile actors before I upgrade to DND5e 2.1.1. Unfortunately, I really can't afford to lose any more time fighting with this problem.

**Comment by Haxxer** [comment]
Okay, then I cannot fix this bug because I do not know how to recreate your situation.

**Comment by Wolfyra** [comment]
Fixing this issue for me was simply deleting the actor 'default item pile'!
