### ISSUE TITLE
[BUG] - [5e] - Cannot roll form Rollable Table to Populate

### ISSUE THREAD

**Issue by MrYome** [fantasycalendar/FoundryVTT-ItemPiles#231]
**Describe the bug**
Clicking on either "Roll" or "Roll All Tables" does nothing.

**To Reproduce**

1. Go to 'Merchant Sheet'
2. Click on 'Populate Items'
3. Import a table
4. Roll on table

**Expected behavior**
Items populating

**Setup:**

- Foundry Version: [Lates]
- System Version: [Latest]
- Item Piles Version: [Latest]
- Browser & version [Latest]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- 3d Canvas
- Ambient Doors
- Better Roll 5e
- Better Roofs
- Character Action list dnd5e
- Compendium Folders
- DFreds Convenient Effects
- DFreds Droppables
- Dice So Nice!
- Dice Tray
- Dynamic Effects Using Active Effects
- Arms Reach
- FXMaster
- Group Roll Checks and Saves
- Ivan Duch's Music Pack
- Level
- Midi QOL
- Module Compatibility Checker
- Monks Active Tile Trigger
- Monks Little Details
- Monks Scene Navigation
- Multilevel Tokens
- Perfect Vision
- PnP - Pointers and Pings!
- Quick Insert
- Times Up
- Token Attacher
- Token Magic FX
- Tokenizer
- Wall Height

**Comment by Haxxer** [comment]
Do you get any errors in the console?

**Comment by Haxxer** [comment]
This should be fixed in 2.4.3
