### ISSUE TITLE
[BUG] - [PF2e] - Shops wont open for players

### ISSUE THREAD

**Issue by Dargboota** [fantasycalendar/FoundryVTT-ItemPiles#233]
**Describe the bug**
Shops wont open after update and all prices are marked as undefined.

**To Reproduce**

Boot Module / game
Open shop, as player
Doesn't open.

**Expected behavior**
Shop opens for players.

**Screenshots**
<img width="562" alt="image" src="https://user-images.githubusercontent.com/116990169/212229219-0d1878ec-31d6-4408-a6e9-aec9734ab001.png">

<img width="596" alt="image" src="https://user-images.githubusercontent.com/116990169/212229551-799d3448-56c8-4e09-b787-24942933aee3.png">

**Setup:**

- Foundry Version: [10.291]
- System Version: [pf2e 4.6.5]
- Item Piles Version: [2.4.0]
- Browser & version [Foundry Client]

**Active modules:**
- Advanced Macros
- Ambient Doors
- Automated Animations
- Better Roofs
- Combat Carousel
- Damage Log
- DF Active Lights
- DF Curvy Walls
- Dice So Nice!
- Door Colors
- Drag Ruler
- Enhanced Terrain Layer
- Entice with Dice so Nice
- Footsteps of Otari
- Foundry Achievements
- Foundry Community Macros
- Handyfon's Dice Addiction
- Item Piles
- Jack Kerouac's Animated Spell Effect: Cartoon
- JB2A - Patreon Complete Collection
- Kris's Compendium of Trade Goods
- lib - color settings
- Library: Df Module Buttons
- libwrapper
- Lordu's Custom Dice for Dice So Nice
- Monk's Active Tile Triggers
- Monk's Enhanced Journal
- Multi Token Status
- MyTab
- Narrator Tools
- Nice more Dice
- Pathfinder 2e: Abomination Vaults
- Pathfinder Token Pack: Bestiaries
- Pathfinder Ui v3
- Perfect Vision
- PF2E a shopping experience
- PF2e Animations
- PF2e Drag Ruler Integration
- PF2e Exploration Activities
- PF2e Exploration Effects
- PF2e Extemopre Effects
- PF2e Giveth
- PF2e Keybind Menagerie
- PF2e Modifiers Matter
- PF2e Persistent Damage
- PF2e Ranged Combat
- PF2e Rule Element Generator
- PF2e Rule Based MPC Vision
- PF2e See Simple Scale Statistics
- PF2e Spells Summary
- PF2e Staves
- PF2e Target Damage
- PF2e Token Magic Integration
- PF2e Tweaks by Ustin
- PF2e Unided
- PF2e Workbench
- PopOut!
- Sequencer
- Sidebar Macros
- Simple Calendar
- Simple Portraits
- Smart Doors
- socketlib
- SoundFx Library
- Splatter
- Stairways(Teleporter)
- Terrain Rulers
- Token Magic Fx
- Tokenizer
- Torch
- Visual Active Effects
- Walls Have Ears
- Warp Gate
- Your Turn!

**Comment by Haxxer** [comment]
I can't replicate your issue, could you please export your merchant and upload it here?

**Comment by Dargboota** [comment]
[fvtt-Actor-odd-stories.txt](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/10414068/fvtt-Actor-odd-stories.txt)

There is one of the shops that were acting up, more testing this morning after the game was played showed that their current PCs couldn't access the shops, but I made a fresh PC and tested it on their permission level and it worked fine.

When I opened the server, I did catch a warning of a migration error going to 2.4.0 and it popped up with this in the console
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/116990169/212385327-ffe60640-5e58-4873-b786-3babb966784f.png">

I can simple fix everything by making new PCs for everyone for the time being.

**Comment by Dargboota** [comment]
[fvtt-Actor-sunce.txt](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/10414104/fvtt-Actor-sunce.txt)

This is also one of the PCs that can't open the shops, just incase.

**Comment by Haxxer** [comment]
I made some changes in 2.4.1 and could not replicate it with your actors, could you test it out?

**Comment by RavenknightDM** [comment]
Hiya, I've tried 2.4.1 and players can open shops just fine, but the prices are still undefined.

**Comment by Haxxer** [comment]
Can you try to reset your item piles system settings?

**Comment by RavenknightDM** [comment]
Yes, still undefined.

**Comment by Haxxer** [comment]
Please contact Wasp#2005 on discord, I'd like to take a look in your world, I have no idea what is happening and I need to see it for myself 😅

**Comment by RavenknightDM** [comment]
Sure thing!

**Comment by Haxxer** [comment]
Fixed in 2.4.2/3
