### ISSUE TITLE
[BUG] - [SYSTEM NAME] - "Something went wrong when migrating ..."

### ISSUE THREAD

**Issue by jackkerouac** [fantasycalendar/FoundryVTT-ItemPiles#235]
**Describe the bug**
Throws an error on startup: "Something went wrong when migrating to 2.4.0! Check the log for details on the error."

**To Reproduce**

1. Start a Foundry World instance.

**Expected behavior**
Expected the migration to finish without an error.

**Screenshots**
migrations.js:25 TypeError: Cannot read properties of undefined (reading 'type')
    at migrateFlagData (pile-utilities.js:22:13)
    at migrations.js:77:63
    at Array.map (<anonymous>)
    at 2.4.0 (migrations.js:75:30)
    at async runMigrations (migrations.js:23:7)
    at async module.js:88:7

**Setup:**

- Foundry Version: 10.291
- System Version: 2.1.2
- Item Piles Version: 2.4.0
- Browser & version: Firefox 108.0.2 (64-bit)

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
Item Piles still SEEMS to work, but the error occurs every time Foundry is started.

**Comment by Haxxer** [comment]
This should be fixed in 2.4.1, or at least let you know which token was broken
