### ISSUE TITLE
[BUG] - [DnD5e] - Item Piles Does Not Show the Expected Dialog Following 2.4.1 Update

### ISSUE THREAD

**Issue by KelSolaar** [fantasycalendar/FoundryVTT-ItemPiles#236]
**Describe the bug**
Hello,

Thanks for the 2.4.1 release! While I don't see the error mentioned in #234, I do not get the expected dialog when double clicking an Item Piles's Actor on the canvas.

**To Reproduce**

Drop a Weapon Item on the Canvas.

**Expected behavior**
The Item Piles dialog should be shown after double-clicking the converted actor

**Screenshots**

![image](https://user-images.githubusercontent.com/99779/212423640-bccca2a7-5472-4d02-8b31-2cc9b9bcf7a4.png)

**Setup:**

- Foundry Version: 10.291
- System Version: DnD5e 2.1.2
- Item Piles Version: 2.4.1
- Browser & version: N/A

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
N/A

**Comment by Haxxer** [comment]
Can you delete your default item pile and try again?

**Comment by Haxxer** [comment]
Or at least confirm that the default item pile is enabled in its item piles settings

**Comment by KelSolaar** [comment]
Yes I tried to delete and re-create it but not dice, however coming back to it tonight, I restarted Foundry and it just worked!

Let's pretend nothing happened and move on... :)

Thanks and closing this one.
