### ISSUE TITLE
[BUG] - [PF2E] - Merchants cannot complete trades

### ISSUE THREAD

**Issue by noltari13** [fantasycalendar/FoundryVTT-ItemPiles#237]
**Describe the bug**
Shops wont open after update and all prices are marked as undefined.

**To Reproduce**
Boot Module / game
Open shop, as player
Attempt to buy or sell an item
Buy or Sell Dialog opens
Click on Buy or Sell Item button
Error thrown, trade is not completed

**Expected behavior**
Trade completed without error

**Screenshot of error**
![merchant](https://user-images.githubusercontent.com/48960289/212474695-e09a1450-7104-4fb5-bb97-0f919495b145.png)

**Setup:**
Foundry Version: [10.291]
System Version: [pf2e 4.6.5]
Item Piles Version: [2.4.3]
Browser & version [Foundry Client]

**Comment by Haxxer** [comment]
That is odd - it's failing to find the item's cost, which hasn't changed. Is this for every merchant?

**Comment by noltari13** [comment]
Yes, for every merchant. It displays the item's cost fine in the Merchant window.

**Comment by Haxxer** [comment]
Ah yeah I found the issue, I'll release a small patch

**Comment by Haxxer** [comment]
Fixed in 2.4.4
