### ISSUE TITLE
[REQUEST] System Compatibility (LevelUp A5E)

### ISSUE THREAD

**Issue by PsykotikDragon** [fantasycalendar/FoundryVTT-ItemPiles#238]
I'd like to request compatibility with the A5E system. It's similar to DnD5e in play, but a completely different system with different UID/coding for abilities/items/etc in practice on foundry. Thanks in advance for your time, effort, & consideration.

**Comment by Haxxer** [comment]
Could you please fill in the system request ticket form instead

**Comment by PsykotikDragon** [comment]
> Could you please fill in the system request ticket form instead

How/Where do I do that? I'm not that familiar w/ github, I thought this was where I did that.

**Comment by Haxxer** [comment]
![image](https://user-images.githubusercontent.com/12858387/215509815-69e2d859-f0be-46b6-8377-177affb46921.png)
![image](https://user-images.githubusercontent.com/12858387/215509852-a3df9d42-f580-4d79-8ae6-f4c64b21dc8f.png)
![image](https://user-images.githubusercontent.com/12858387/215509885-040d27b0-bef8-49a6-8a41-4abf303ca3b2.png)
