### ISSUE TITLE
[REQUEST] [Starfinder] - Inter-module compatibility with modules that impose dark themes

### ISSUE THREAD

**Issue by jbronner1972** [fantasycalendar/FoundryVTT-ItemPiles#239]
Item Piles is the best thing ever. Except when using some themes where the text and background don't play well and items in the pile aren't readable. 

An option to disable the tinted every other line, or to tint every line, or even set the background color on the piles to something visible would be extremely nice.

**Additional context**
![Untitled](https://user-images.githubusercontent.com/10430565/212627119-ade2b7e0-415d-4ebf-941b-d4fe1770e7cd.png)

**Comment by Haxxer** [comment]
What system is this? Item piles allows for system specific styling, which is my focus for the next update.

**Comment by jbronner1972** [comment]
Starfinder.

**Comment by Haxxer** [comment]
So it is not the default styling?

**Comment by jbronner1972** [comment]
No, the default styling on starfinder is fine, but any modules making changes to the theme (e.g. any dark themer addons) make the items unreadable when the text color flips to white. A color picker or some kind of style sheet for the items list to account for dark themes would be outstanding.

**Comment by Haxxer** [comment]
I cannot account for every module interaction, that would be a game of wack-a-mole that would not benefit anyone and take an extreme amount of time given that Item Piles supports 23+ systems to date.

However, I can take a look and see about allowing users to change the configuration of colors themselves.

**Comment by jbronner1972** [comment]
thx.

**Comment by Haxxer** [comment]
I have added a styling feature for this request in the latest beta build, do you think you could test it out?

Installation link:
https://raw.githubusercontent.com/fantasycalendar/FoundryVTT-ItemPiles/next/module.json

Please do back up your data if you do

**Comment by jbronner1972** [comment]
Outstanding. The only other thing I could think of would be putting an actual color picker dialog in the CSS Styles window and maybe doing the display in hex like the entire rest of the Foundry system, but the functionality is exactly right.  
![Untitled](https://user-images.githubusercontent.com/10430565/214353909-675fa1eb-ac7f-4442-bcf9-e90fb1e043f6.png)

**Comment by Haxxer** [comment]
Color pickers are hard.

Redesigning my entire module to support dynamic styles is harder.

**Comment by jbronner1972** [comment]
From what i've been able to set with it, the functionality is great. It's going to solve many problems for Dark UIs and themes users on nearly all systems not being able to read a Pile. A picker could be a down the road thing.
