### ISSUE TITLE
[SYSTEM] - DnD 3.5 SRD

### ISSUE THREAD

**Issue by Hyrkanus** [fantasycalendar/FoundryVTT-ItemPiles#24]
**https://foundryvtt.com/packages/D35E**

### **Dynamic Attributes**:

- **Name**: "Platinum Coins",
    - **Path**: "data.currency.pp",
    - **Image**: "icons/commodities/currency/coin-inset-snail-silver.webp"
- **Name**: "Gold Coins",
    - **Path**: "data.currency.gp",
    - **Image**: "icons/commodities/currency/coin-embossed-crown-gold.webp"
- **Name**: "Silver Coins",
    - **Path**: "data.currency.sp",
    - **Image**: "icons/commodities/currency/coin-engraved-moon-silver.webp"
- **Name**: "Copper Coins",
    - **Path**: "data.currency.cp",
    - **Image**: "icons/commodities/currency/coin-engraved-waves-copper.webp"

**Comment by Haxxer** [comment]
Dynamic attributes now support localized strings, but it seems that D&D 3.5e's currency localization of `D35E.CurrencyCP` is just `CP`, which is not very descriptive. How many localizations exist for 3.5e?

**Comment by Hyrkanus** [comment]
It looks like there are 5: English, Spanish, French, German and "br" is probably Brazilian/Portuguese.
https://github.com/Rughalt/D35E/tree/0.98.9/lang

**Comment by Haxxer** [comment]
Then it may be best to stick to the short-form version of the translations to support these languages. It may be worth to request the devs to add long-form translations of `Copper Coins` to the system.

**Comment by Hyrkanus** [comment]
Yeah, that's probably best. I don't think the System uses long-form names for the currencies to begin with. They normaly appear only on the character sheets where the short-form is used.

**Comment by Haxxer** [comment]
Cool, I'll implement that then. Closing and implementing in 1.1.0.
