### ISSUE TITLE
Latest Item Piles causes endless refreshes

### ISSUE THREAD

**Issue by apoapostolov** [fantasycalendar/FoundryVTT-ItemPiles#243]
Item Piles causes endless refreshing of my environment because of an issue mentioned shortly in a blue warning notification. 

Had to rush quickly and turn off the mod before the refreshing loop causes it to be no longer useful

**Comment by Haxxer** [comment]
That means you've got a really broken token somewhere, would you mind if I join your world with item piles enabled to check what's going on?

**Comment by Haxxer** [comment]
Please do fill out _all_ of the details of a bug report. It is very hard to help you if I don't have the information contained within.

**Comment by apoapostolov** [comment]
The problem is no longer happening with the latest verson.
