### ISSUE TITLE
[REQUEST] - Create Merchant Item Pile that and allows splitting of sold total and only allows selling

### ISSUE THREAD

**Issue by TheGreatRedDuke** [fantasycalendar/FoundryVTT-ItemPiles#246]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to create a Merchant style Item Pile that allows for selling of items only and also has an option to split the total value of items sold between party members in the same way you can split currency for a normal Item Pile.

**Describe the solution you'd like**
As party members acquire loot over time, they inevitably want to sell extra/old gear and often will want to split the proceeds between the party. Creating a sell only Merchant Item Pile actor that allows the total sold to be split would be a wonderful addition to this already amazing module.

There is an option for "Purchase Only", but it would be helpful to also have an option for "Sell Only" as well.

**Describe alternatives you've considered**
Forgive me if this is already possible, but I tried for some time to get this working and was unable to find a way to do it currently.

You can currently create style Merchant actor and allow for selling, but it still shows the Buy Items tab by default, and it will only give the total to the selling player.

**Additional context**
Though I'm using the Starfinder game system, I think this would be super useful for a number of game systems!

**Comment by Haxxer** [comment]
I've fixed the `Buy Items` tab being visible if the merchant has no visible items to sell to the players, but I haven't added any split proceeds setting or anything like that. If you simply set the setting to hide items that are sold to the merchant, the buy items tab will never show up (to the players):

https://raw.githubusercontent.com/fantasycalendar/FoundryVTT-ItemPiles/next/module.json

**Comment by TheGreatRedDuke** [comment]
That's great about the buy items tab not showing. Thank you!

Do you think that adding the ability to split proceeds is something that could eventually be added as a feature?

**Comment by Haxxer** [comment]
Added tab feature in 2.4.10, please open a new feature request for the splitting proceeds, easier to keep track of that! Thanks!
