### ISSUE TITLE
[REQUEST] PF2 - Mystified Items that are dropped become Identified

### ISSUE THREAD

**Issue by Craftzero** [fantasycalendar/FoundryVTT-ItemPiles#247]
In Pathfinder 2e, a player can have an item that is "Mystified" - as in, not identified as yet.  Players can not normally un-mystify an item without DM intervention on the item.  However, when using Item Piles, players can drop the item and it will un-mystify itself immediately.

**Comment by Haxxer** [comment]
Please use the bug template.

**Comment by Haxxer** [comment]
Is this not a bug?

**Comment by Craftzero** [comment]
I believe it may!  I shall do as you ask.  :)
