### ISSUE TITLE
[BUG] - [PF2E] - When Mystified Item Dropped, it Identifies itself

### ISSUE THREAD

**Issue by Craftzero** [fantasycalendar/FoundryVTT-ItemPiles#248]
**Describe the bug**
In Pathfinder 2e, a player can have an item that is "Mystified" - as in, not identified as yet. Players can not normally un-mystify an item without DM intervention on the item. However, when using Item Piles, players can drop the item and it will un-mystify itself immediately.

**To Reproduce**

1. Mystify an item by clicking on the ?.
2. Drop item.
3. Item becomes identified.

**Expected behavior**
The item should remain mystified.

**Screenshots**
![image](https://user-images.githubusercontent.com/92058223/213785512-cc59b8e8-1de4-4f23-bd33-713901e90129.png)
then when hovering:
![image](https://user-images.githubusercontent.com/92058223/213785683-b9372fe7-6d83-465c-918b-29d270b9de33.png)

**Setup:**

- Foundry Version: 10.291
- System Version: Pathfinder 4.6.8
- Item Piles Version: 2.3.11
- Browser & version Not using browser

**Active modules:**

- Item Piles
- libwrapper
- socketlib
![image](https://user-images.githubusercontent.com/92058223/213785958-3e9f0834-4aee-4db3-adaa-2e2bb7520bee.png)
![image](https://user-images.githubusercontent.com/92058223/213786030-2d5ff1fa-245f-4377-b75c-0249fbf1ad6d.png)
![image](https://user-images.githubusercontent.com/92058223/213786079-de6722de-fbeb-498c-a740-f1d488fa7bf3.png)
![image](https://user-images.githubusercontent.com/92058223/213786132-26559d3a-9593-485f-ae0e-644bbe52c3c3.png)

**Additional context**

**Comment by Haxxer** [comment]
Found out why, thanks for the report.

**Comment by Craftzero** [comment]
Awesome - thanks!

**Comment by Haxxer** [comment]
I have fixed this bug in the latest beta build, do you think you could test it out?

Installation link:
https://raw.githubusercontent.com/fantasycalendar/FoundryVTT-ItemPiles/next/module.json

Please do back up your data if you do

**Comment by Craftzero** [comment]
I installed this, and it fixed both the mystification bug as well as the log bug.  I tried multiple items, works great.
Thanks!

**Comment by Haxxer** [comment]
Fixed in 2.4.10
