### ISSUE TITLE
[SYSTEM] - SWADE

### ISSUE THREAD

**Issue by EternalRider** [fantasycalendar/FoundryVTT-ItemPiles#25]
**https://gitlab.com/peginc/swade**

### **Actor Class Type**: "character"

*The actor class type is the type of actor that will be used for the default item pile actor that is created on first item drop.*

### **Item Quantity Attribute**: "data.quantity"

*The item quantity attribute is the path to the attribute on items that denote how many of that item that exists.*

### **Item Type Filters**: "edge,hindrance,skill,power,ability"

*Item types and the filters actively remove items from the item pile inventory UI that users cannot loot, such as spells, feats, and classes.*

### **Dynamic Attributes**:

*Dynamic attributes are things like currencies or transferable powers that exist as editable number fields on character sheets.*

- **Name**: "Currency"
    - **Path**: "data.details.currency"
    - **Image**: "icons/svg/coins.svg"

**Comment by EternalRider** [comment]
Here is a problem, the data.details.currency is a string , add will be connect them but not increase right number, and then, the system will set the value is "500" default, when every charactor actor been created.
It means the item pile will always be 500 currency when create, and if a pc have 100 currency to take them, it will be 100500.

**Comment by Haxxer** [comment]
That should be an easy fix, thanks for reporting that

**Comment by Haxxer** [comment]
Added support for SWADE, and fixed the attribute bug
