### ISSUE TITLE
[BUG] - [PF2E] - Money Not Defined in Vault Mode Log

### ISSUE THREAD

**Issue by Craftzero** [fantasycalendar/FoundryVTT-ItemPiles#250]
**Describe the bug**
In Pathfinder2e, when selecting vault mode, you can deposit and withdraw all types of money without issue.  When doing so, however - the log records something "undefined" was withdrawn rather than the type of coin and number.

**To Reproduce**

1. Deposit coin or withdraw coin.
2. Check log.

**Expected behavior**
The log should show the type and amount of coin withdrawn.

**Screenshots**
![image](https://user-images.githubusercontent.com/92058223/213922375-e1787ecd-1c3a-4b2f-b72f-d021f393ae46.png)

**Setup:**

-     Foundry Version: 10.291
-     System Version: Pathfinder 4.6.8
-     Item Piles Version: 2.3.11
-     Browser & version Not using browser

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- [insert more modules here]
![image](https://user-images.githubusercontent.com/92058223/213922403-9bb3de5b-507d-421f-88f4-a5be57a590e2.png)
![image](https://user-images.githubusercontent.com/92058223/213922413-9e598315-5c63-420a-b0d0-7f66ca7dd295.png)
![image](https://user-images.githubusercontent.com/92058223/213922419-3d9c3f0e-3023-4956-bc48-b1a31275790e.png)
![image](https://user-images.githubusercontent.com/92058223/213922425-bb24f1d0-f26c-4d95-8e08-8787d3d36f1b.png)

**Additional context**

**Comment by Haxxer** [comment]
I have fixed this bug in the latest beta build, do you think you could test it out?

Installation link:
https://raw.githubusercontent.com/fantasycalendar/FoundryVTT-ItemPiles/next/module.json

Please do back up your data if you do

**Comment by Haxxer** [comment]
Fixed in 2.4.10
