### ISSUE TITLE
[BUG] - [D&D5e] - Populate itens not respect preconfigure itens for sevice

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-ItemPiles#251]
**Describe the bug**
When an item is configured other than the default item piles (such as a service type item) and it is inserted into the merchant with a roll table it loses all existing configurations and reverts to its default status.

**To Reproduce**

1 - create an item and configure the item as a service (or any other change)
2 - Create a table and place this modified item on it.
3 - populate a market using this table.
4 - the drawn item loses all settings and becomes a normal sellable item.

the bug appears both in items drawn in the world and in the compendium

**Expected behavior**
that drawn keeps the pre-defined item piles settings

**Setup:**

- Foundry Version: 10.291
- System Version: DND5e 2.1.2
- Item Piles Version: 2.4.9

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
I have fixed this bug in the latest beta build, do you think you could test it out?

Installation link:
https://raw.githubusercontent.com/fantasycalendar/FoundryVTT-ItemPiles/next/module.json

Please do back up your data if you do

**Comment by Haxxer** [comment]
Fixed in 2.4.10
