### ISSUE TITLE
[SYSTEM] - Cypher System

### ISSUE THREAD

**Issue by mrkwnzl** [fantasycalendar/FoundryVTT-ItemPiles#254]
# **https://foundryvtt.com/packages/cyphersystem**

### **Actor Class Type**: "marker"

*The actor class type is the type of actor that will be used for the default item pile actor that is created on first
item drop*

### **Item Quantity Attribute**: "system.basic.quantity"

*The item quantity attribute is the path to the attribute on items that denote how many of that item that exists*

### **Item Price Attribute**: none

*The item price attribute is the path to the attribute on each item that determine how much it costs*

### **Item Filters**: "ability, lasting-damage, power-shift, recursion, skill, tag"

*Item filters actively remove items from the item pile inventory UI that users cannot loot, such as spells, feats, and
classes*

### **Item Similarities**: "type"

*Item similarities determines how item piles detect similarities and differences in the system*

### **Currencies**: None

No default. GM’s need to set that up for each game, as each setting has their own currency.

*Currencies in item piles are a list of names, attribute paths, and images*

**Comment by Haxxer** [comment]
added in 2.4.12
