### ISSUE TITLE
[BUG] - [5e] - Lost item images after reload-Image shifting when dropped to canvas

### ISSUE THREAD

**Issue by MrPotatoZed** [fantasycalendar/FoundryVTT-ItemPiles#257]
I've been experiencing lost images for items dropped in item piles. FTC points to Items with Spells dnd5e and disabling Items with Spells dnd5e makes the behavior less common (probably because it means items with spells don't show the behavior). However, there are some items that seem to show the behavior even with Items with Spells disabled (probably all spells with active effects). My current theory is that items with added spells and items with added effects seem to be causing the behavior. My guess is the effect icon image for the effects and/or spells are what's replacing the container image/leading to weirdness. 

**To Reproduce**
Drop an item that contains added effects or spells from the item bar onto a scene to create an item pile. View item to note it has an image. 
Reload the browser window. View item pile again to note item image has been changed to the item-bag.svg.  

It's noteworthy that for effected items when dropping them to create a pile it is initially using the container image that is the norm for my settings, it then quickly shifts to using the item image as is seen here:  
![itempiles125](https://user-images.githubusercontent.com/85974617/214736759-94397690-4da1-4a39-8076-9b12fc8e70d9.gif)
With Items with Spells disabled this is what happens for most items when dropping an item onto a scene. This is also what happens for items without spells/effects even with Items with Spells dnd5e active:
![itempiles125b](https://user-images.githubusercontent.com/85974617/214736845-0d6c56cc-2b87-4195-a41d-92d3b9fed7f2.gif)

With items with spells active the first time I drop an item to create an item pile it looks like this when viewed:
![image](https://user-images.githubusercontent.com/85974617/214737070-96b7a208-60c2-456e-9f7c-87d69fa5a0db.png)

After reloading the browser it looks like this:
![image](https://user-images.githubusercontent.com/85974617/214737221-c76d2ff4-28d3-4983-b757-471ce3e120c9.png)

Noteworthy that not all items demonstrate this behavior. Some items keep the container image when dropped. After reload these items keep their original image instead of having the image changed to the bag.svg.  
Also noteworthy that dragging the same items from the item bar onto an actor and reloading does not lead to any lost/shifted images.   

No errors in console.  

Foundry 10.291, 5e 2.1.4 (same behavior in previous 5e versions)
Item Piles 2.4.10, Items with Spells Dnd5e 1.3.1
Tested with only Item Piles, libwrapper, socketlib, and Items with Spells dnd5e active
Hosted on the forge
Tested in firefox and chrome

Here are two items that demonstrate this behavior only with Items with spells active:
[message(6).txt](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/10505681/message.6.txt)
[message(7).txt](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/10505688/message.7.txt)
Here's an item that doesn't seem to demonstrate this behavior even with Items with Spells active:
[message(8).txt](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/10505705/message.8.txt)
Here's an item that demonstrates the behavior even with Items with Spells disabled:
[message(9).txt](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/10505801/message.9.txt)
Another weird item. This one shifts from container to a bag.svg image when dropped on the scene instead of using the item image:
[message(10).txt](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/10505802/message.10.txt)

Thanks for taking a look at it!

**Comment by Haxxer** [comment]
Can you reproduce this locally on your own machine?

**Comment by MrPotatoZed** [comment]
Just tried for a bit and I can't get it to replicate in my home machine either; or at least haven't so far. I can get the items with spells part to replicate in a clean world on the forge but when in a clean world I haven't seen missing images with just effects yet. Also noteworthy that I'm not seeing the container to item image change at all in the clean world. 
Bottom line it sounds like I need to do a bit more testing. Thanks again for taking a look.
