### ISSUE TITLE
[BUG] - [WWM] & [T2K4e] - Dropping Items Into Loot Sheet From Sheet Dupes Item

### ISSUE THREAD

**Issue by Cup-of-Coffee** [fantasycalendar/FoundryVTT-ItemPiles#258]
**Describe the bug**
When the GM or Player drags and drop a item from a sheet into a item pile sheet, the item gets copied over but it doesn't delete the original item. This doesn't appear to be a intended function, as dragging and dropping a item from a sheet onto a item pile token will properly delete the original item.

**To Reproduce**
Steps to reproduce the behavior: I tested this on Worlds Without Number and Twilight 2000 4e.

1. Create a character sheet.
2. Add a some items to the sheet
3. Go to a scene and have the actor drop a item on the scene to make a item pile.
4. Open the item pile sheet from the token and drag and drop a item into it.
5. Look and see that the original dragged item still exists on the sheet, and has copy on the item pile sheet.

**Expected behavior**
When dragging and dropping items from a character sheet into a item pile sheet, it's expected to delete the original item to limit confusion on how many items exists.

**Setup:**

- Foundry Version: [e.g. 9.238]
- System Version: [Twilight: 2000 (4th Edition) 10.1.0] and [Worlds Without Number (1.1.1)]
- Item Piles Version: [2.4.10]
- Browser & version: Firefox (64-bit) [109.0]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
This is potentially effecting all systems, as there aren't any errors produced when this occurred.

**Comment by Haxxer** [comment]
Please always check your console for errors

**Comment by Cup-of-Coffee** [comment]
There weren't any errors logged on the console (at least when testing Twilight 2000).

**Comment by Haxxer** [comment]
Cool, thanks for confirming. Did you also try to reset the item pile system settings?

**Comment by Cup-of-Coffee** [comment]
I did. 

I also just tested it again as a Player to make it's not a GM permission issue.

**Comment by Haxxer** [comment]
Fixed in 2.4.11
