### ISSUE TITLE
[BUG] - [PF2e] - Merchant shops broken

### ISSUE THREAD

**Issue by Fyrexian** [fantasycalendar/FoundryVTT-ItemPiles#259]
**Describe the bug**
I'm not sure how to explain this, since I don't have the exact idea where the problem starts. Seemingly Merchant shops are broken to where they only are able to sell (unless you set it to buy only). When you set it to buy only and someone buys it item, it breaks and can't be opened again,

**To Reproduce**

1. Make merchant shop
2. Set to buy only
3. buy an item
4. close
5. try to reopen

**Expected behavior**
It was working before this recent update, so if it can be as functional as the previous ones.

**Screenshots**
This is what comes up when you try the above reproduce.
![image](https://user-images.githubusercontent.com/47077661/215237811-fb1c0d49-addf-4a85-a093-7f157aeb930f.png)

**Setup:**

- Foundry Version: [10.291]
- System Version: [PF2e 4.6.8]
- Item Piles Version: [2.4.10]
- Browser & version [Foundry]

[localhost-1674873607676.log](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/10524387/localhost-1674873607676.log)

**Comment by Haxxer** [comment]
Have you tried to reset the item pile system settings?

**Comment by Haxxer** [comment]
Fixed in 2.4.11
