### ISSUE TITLE
[BUG] - Saving settings for an item pile (icons for closed/open etc) doesn't transfer to a new pile?

### ISSUE THREAD

**Issue by nirurin** [fantasycalendar/FoundryVTT-ItemPiles#26]
**Describe the bug**
I have an item pile in the sidebar called "chest item", where I set the closed-item, open-item, empty-item etc images for it, with the intention that I could then drop that onto the map, and it would show as a chest, and I can then fill the chest with loot. 

Except it doesn't seem to work like that. Even though the sidebar item has all the settings in place, when I drag it onto the map it turns into a totally default pile. 

Is there no way to pre-set everything? Cos having to manually set up multiple images for each loot pile is a bit of a pain. 

This feels like a bug, because I can set the settings in the sidebar, and normally these things will copy over to the actor you place on the map. 

**To Reproduce**
Above

**Expected behavior**
Above

**Setup:**
Current versions of everything. 

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - +84 other ones

**Comment by Haxxer** [comment]
Any errors in the console?

**Comment by nirurin** [comment]
Nothing I can see. 

The only solution I just found, was to place the pile onto the map, set up the settings for it, and then ctrl-C / ctrl-v to copy it. This gives me multiple chests which all have the proper image setups. 

I haven't experimented with changing the 'default item pile' settings, cos the wiki specifically says not to change those, and to instead create duplicates. So I wonder if the issue is something to do with me making and renaming a duplicate? The duplicate pile drops as an item pile, but uses the default settings instead of the settings on the duplicate.

**Comment by Haxxer** [comment]
It should work, I'll attempt on my end and get back to you

**Comment by nirurin** [comment]
As another thing (which again, not sure if it's a bug or just me), but the chest icons are a bit small at 0.8 scale (which seems to be the default for a container, even though its only a setting in the 'single item' menu), so I manually change them to 1.2 scale... except that every time I edit the contents (eg. add another  item) the chest reverts back to 0.8 scale (this is in the 'token' settings, not in the item pile settings). 

Hate to sound like I'm complaining, cos I love this module already, just a couple of niggles. Still planning to use it!

**Comment by Haxxer** [comment]
Have you turned off "display one"? It forces a scale when the pile only has one item.

**Comment by Haxxer** [comment]
A pile may still be a container (locked, opened), if it chooses to display one image and a scale

**Comment by Haxxer** [comment]
If you have any queries about the usage of the module, please write on the foundry discord server, rather than in a bug ticket

**Comment by nirurin** [comment]
Haha just edited to say that the scale in 'single item' seemed to be the problem (disabling it stops the rescaling), though the item pile is set to be a container and isn't showing a single item image, so it still seems a little off. The image being displayed is the chest icons, but yeh its scaling the chest using the single-item rules. 

Though actually it did have 'two items' , in that there were caltrops and some gold. So I guess Gold doesn't count as an item. 

At the time it seemed like a bug, but as Gold isn't being treated as an 'item' I guess it makes sense. Easy enough to work around.

**Comment by Haxxer** [comment]
Okay, initial investigations:

- You are correct, the prototype token is never updated, which means that dragging out new tokens will behave as fresh ones
- I can see where the logic breaks down where having it as a container always overwrites the image but only sometimes the scale. I will make it so that `Is Container` always wins out in these instances
- I will include gold and such things in the `Display one` mode

Thank you for your feedback!

**Comment by nirurin** [comment]
"You are correct, the prototype token is never updated, which means that dragging out new tokens will behave as fresh ones"

Sorry just to clarify - Is this how it's -meant- to be working? Or are you planning to tweak it so that the prototype settings will actually carry over to placed tokens? 

I'm only asking so that I know whether to carry on using my workaround, or just hang on for an update, I'm happy either way!

**Comment by Haxxer** [comment]
It is meant to be working, yes.

**Comment by Haxxer** [comment]
Fixed in 1.1.3
