### ISSUE TITLE
[REQUEST] - Randomise single item amount

### ISSUE THREAD

**Issue by SalieriC** [fantasycalendar/FoundryVTT-ItemPiles#260]
**Is your feature request related to a problem? Please describe.**
"I'm always frustrated when" I have to roll to generate a random amount of coins as loot. 🤣 - Sorry, it isn't really a problem but I couldn't resist.

**Describe the solution you'd like**
When configuring a preset single item _pile_, I'd appreciate the ability to randomise the amount when the item is dropped to the canvas from the sidebar.

**Describe alternatives you've considered**
The only way to have a random amount of an item right now is to manually roll some dice during preparation of a session.

**Additional context**
This feature would cut prep time a bit as the user could configure a default coin purse or whatever that acts as a single item which adds a random amount of the provided currency or item to the single items token as soon as it is dropped to the canvas. The way this could work is by providing a dice formula (something like `1d100+20*2` or something like that). Alternatively it could be implemented by letting the user choose a range in which a random amount is generated. This would probably be easier to use but might be harder to implement.

**Comment by Haxxer** [comment]
Here's a macro that will randomly generate loot on the selected token, would that do?

```js
if (!canvas.tokens.controlled.length) return;
for(const tokenD of canvas.tokens.controlled){
    game.itempiles.API.addCurrencies(tokenD, "1d6gp 2d6sp")
}
```

**Comment by SalieriC** [comment]
I'm sorry, I completely missed your reply @Haxxer.
This will randomise currencies only I think, right? And it's using the abbreviation for currencies set in the item piles settings? Just asking because I'll need to adapt it in to my system order to use it.
Also it's not exactly what I meant. I was more looking for something to randomise the amount of certain items rather than currencies.

**Comment by Haxxer** [comment]
Check the sample macros on the wiki.
