### ISSUE TITLE
[BUG] - [Pathinder 1e / maybe universal] - Players are able to add currency

### ISSUE THREAD

**Issue by ShadowK13** [fantasycalendar/FoundryVTT-ItemPiles#262]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When players interact with an item pile, they get the option to add currency. Once selecting add currency, they have a message saying "As a GM, you can update the currencies this on Item Pile". All players are listed as Players in Foundry.

**To Reproduce**

1. Log in as a player account
2. Click on an item pile
3. Choose add currency

**Expected behavior**
Players should not be able to freely change the currency in Item Piles

**Screenshots**
![image](https://user-images.githubusercontent.com/68548089/215364486-d0c49e35-d79a-4c88-8a58-44cd222475fc.png)

**Setup:**

- Foundry Version: [10.290]
- System Version: [PF1e 0.82.5]
- Item Piles Version: [2.4.11]
- Browser & version [Different between all players]

**Comment by Haxxer** [comment]
Fixed in 2.4.12
