### ISSUE TITLE
[BUG] - [DND5E] - Unable to drag actors into "Actor Price modifiers"

### ISSUE THREAD

**Issue by Cryanide** [fantasycalendar/FoundryVTT-ItemPiles#264]
**Have you tried to reset Item Piles' system settings?**
No (Using default settings)

**Describe the bug**
Unable to drag actors into "Actor Price modifiers"

**To Reproduce**

1. Go to 'Configure Actor Price Modifiers'
2. Drag an actor
3. See error

**Expected behavior**
Actors added to the price modifiers list

**Screenshots**

**Setup:**

- Foundry Version: 10.291
- System Version: DND5e 2.1.4
- Item Piles Version: 2.4.12
- Browser & version: FoundryVTT Desktop Application

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
I have tested with a fresh game world and the problem is still present. Weirdly there is no error, I'd assume nothing is being called/updated. I have checked the wiki but don't see anything that would point to that I have some setting preventing me from doing this, especially considering Item price modifiers work.

**Comment by Haxxer** [comment]
Fixed in version 2.4.14
