### ISSUE TITLE
[REQUEST] - Make the Custom Item Category textbox an editable dropdown.

### ISSUE THREAD

**Issue by MorganVergara** [fantasycalendar/FoundryVTT-ItemPiles#267]
**Is your feature request related to a problem? Please describe.**
It's a bit annoying to type the name of a custom category over and over for many items.

**Describe the solution you'd like**
Make the current text box into a dropdown that shows the categories that have already been entered, along with a spot to add a new category. Upon adding it, it should show up in the dropdown.

**Describe alternatives you've considered**
Cutting and pasting works, but you can only have one item in the clipboard at a time.

**Additional context**
This is the one to which I'm referring.
![image](https://user-images.githubusercontent.com/30846057/215903255-c8c720dd-f1de-4604-b055-b954f3b8b500.png)

**Comment by Haxxer** [comment]
Not sure how I would track this across all temporary item piles, merchants, vaults, etc - what about an editable list in the settings to populate suggestions?

**Comment by Haxxer** [comment]
Added in 2.4.15

**Comment by MorganVergara** [comment]
I was thinking per item pile, not globally. Would that work?

**Comment by MorganVergara** [comment]
In particular for merchants. That's where I spend most time categorizing.

**Comment by Haxxer** [comment]
If you check my last comment, it is already in the latest release.
