### ISSUE TITLE
[BUG] - [PF2E] - Purchasing from merchants gives negative coins.

### ISSUE THREAD

**Issue by LKLani** [fantasycalendar/FoundryVTT-ItemPiles#268]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When buying items from a merchant, gold is not being correctly deducted from the players inventory. Instead, a copy of the gold coin item with negative value is being added. Screenshots below.

This affects all denominations of coins. Transaction otherwise functions properly in all respects.

**Screenshots**
![piles1](https://user-images.githubusercontent.com/75685325/216407114-4bfc8b03-77b7-4ecb-9b60-5db702a10667.jpg)
![piles2](https://user-images.githubusercontent.com/75685325/216407132-9ed5cc24-c60a-4809-855d-ce76cf1268c9.jpg)
![piles3](https://user-images.githubusercontent.com/75685325/216407158-d401f053-f81f-49bf-8a64-4a00207214ab.jpg)

**Setup:**

- Foundry Version: 10.291
- System Version: PF2E 4.6.8
- Item Piles Version: 2.4.14
- Browser & version Edge 109.0.1518.70. Also tested on Chrome 110.0.5481.77.

**Active modules:**

- Item Piles
- libwrapper
- socketlib
Tested with all modules disabled.

**Comment by Haxxer** [comment]
Thanks for the report, I have identified the issue and will patch it it in the next update.

**Comment by Haxxer** [comment]
Fixed in 2.4.15
