### ISSUE TITLE
[REQUEST] - Item "name" filter

### ISSUE THREAD

**Issue by gsterling** [fantasycalendar/FoundryVTT-ItemPiles#27]
**Is your feature request related to a problem? Please describe.**
When looting monsters or animals, they often won't have weapons, but "claws", "bite" and other natural weapons.

**Describe the solution you'd like**
Have a filter similar to the item type, but for names, to prevent players from looting natural weapons.

**Describe alternatives you've considered**
Asking the system author to add a new type of item types. This seems a bit overkill and would be needed to done by every system out there. It's unlikely the maintainers want to add another item type just for this ItemPiles.

**Comment by Haxxer** [comment]
I like this - would this be something global or something per item pile?

**Comment by Haxxer** [comment]
Otherwise, individual item piles do have custom item type filters, so you can choose to filter out `weapon` type items from animals

**Comment by gsterling** [comment]
> I like this - would this be something global or something per item pile?

I'd say global, but with per item pile option to overwrite it, if you'd find a legendary knuckle weapon called "Claws" for example.

> Otherwise, individual item piles do have custom item type filters, so you can choose to filter out weapon type items from animals

It's a good enough workaround for now.
But some playable races do have natural weapons and in my system even humans have "body" as a natural weapon.

**Comment by IcyLemonZ** [comment]
In DnD 5e I think most of the natural weapons like claws, bites and tentacles have data.data.weaponType set to "natural" in the item block. The current item type filter list would need to either check this value as well or a different filter list would be needed?

![image](https://user-images.githubusercontent.com/73080231/149167349-ddb17b5e-3491-4be6-be59-1f435dc14255.png)

**Comment by gsterling** [comment]
> In DnD 5e I think most of the natural weapons like claws, bites and tentacles have data.data.weaponType set to "natural" in the item block. The current item type filter list would need to either check this value as well or a different filter list would be needed?

That wouldn't be system agnostic anymore. A simpler filter for a name would be easier. My setting doesn't have a different value for natural weapons. It would certainly be nicer that way, but unfortunately it wouldn't help me.

**Comment by colinbate** [comment]
An even more generic approach would be allowing filtering based not just on name, but on an arbitrary property. So in 5e, it could be configured to filter out `Natural` from `data.data.weaponType` and if that isn't available, you could have `name` filter out `Claws`, `Tentacles`, `Pseudopod`, etc.

**Comment by Haxxer** [comment]
@colinbate This is exactly the feature I'm working on for 1.3.0 :)

**Comment by Haxxer** [comment]
I believe this has been resolved in 1.2.7 - it is the new item filters configuration in the module settings
