### ISSUE TITLE
[BUG] - [PF2E] - Can't Close Vault Window

### ISSUE THREAD

**Issue by Craftzero** [fantasycalendar/FoundryVTT-ItemPiles#270]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When opening a vault, there is no visible way to close the vault other than hitting Escape, there is no "X" to close.

**To Reproduce**

1. Open Vault
2. Try to close without hitting Escape.

**Expected behavior**
Clicking X to close a window.

**Screenshots**
![image](https://user-images.githubusercontent.com/92058223/216773062-904cb184-fbe5-4b13-bccd-386f82e425a0.png)

**Setup:**

- Foundry Version: 10.291
- System Version: PF2E 4.6.8
- Item Piles Version: 2.4.15
- Browser & version: N/A - using Foundry, but same on Chrome/Firefox.

**Active modules:**

- Item Piles
![image](https://user-images.githubusercontent.com/92058223/216773124-4c909b16-b21e-48e2-af61-67adef85c549.png)
![image](https://user-images.githubusercontent.com/92058223/216773130-90324d6b-0a12-41e4-9835-9222578af859.png)
![image](https://user-images.githubusercontent.com/92058223/216773138-1108f97d-c594-41f9-8253-d8c1478470c5.png)
![image](https://user-images.githubusercontent.com/92058223/216773143-2ea6a1b9-786a-4c92-b891-94baa30c158d.png)

**Additional context**

**Comment by Haxxer** [comment]
It has been pushed to the side, try enabling the setting to remove the header text from item piles.

**Comment by Craftzero** [comment]
Yup, that seemed to work!  Shall I close this or do you normally do that?
