### ISSUE TITLE
[REQUEST] - Better handling of infinite items in merchants

### ISSUE THREAD

**Issue by jazzman831** [fantasycalendar/FoundryVTT-ItemPiles#272]
**Is your feature request related to a problem? Please describe.**
There is no easy way to set up a shop that is mostly infinite items. For instance, perhaps you don't want to control player's purchases of basic items, but want to include a few unique items. Using the "Infinite Quantity" option on the shop settings causes every item to be infinite, with no way to override the few items. The only option is to uncheck this box, then individually check each infinite item.

**Describe the solution you'd like**
Minimally, if the "Infinite Quantity" setting is enabled at the shop level, it should be able to be overridden on the item level. It would be nice if there were an icon, similar to the hidden/not for sale icons that currently exist, so you could check or uncheck items at will.

**Comment by Haxxer** [comment]
Added in 2.4.17
