### ISSUE TITLE
[BUG] - SW5e - Spectate trade button not working

### ISSUE THREAD

**Issue by capn-cat** [fantasycalendar/FoundryVTT-ItemPiles#273]
**Have you tried to reset Item Piles' system settings?**
yes

**Describe the bug**
Spectate trade button produces no effect as GM.

**To Reproduce**

1. Log in as two PCs
2. Request a trade between the PCs
3. As GM, click Spectate Trade

**Expected behavior**
A view of the trade underway to appear

**Screenshots**

![image](https://user-images.githubusercontent.com/29226389/216944835-3421d617-8385-4550-980f-37a4f329340d.png)

**Setup:**

- Foundry Version: 10.291
- System Version: SW5e 2.0.3.2.3.7
- Item Piles Version: 2.4.13
- Browser & version Google Chrome 109.0.5414.120

**Active modules:**

- Item Piles
- libwrapper
- socketlib

Bug appears with no other active modules

**Additional context**

**Comment by Haxxer** [comment]
Please fix the title.

**Comment by capn-cat** [comment]
done.

**Comment by Haxxer** [comment]
Fixed in 2.4.16

**Comment by capn-cat** [comment]
legend!
