### ISSUE TITLE
[BUG] - [PF2] - Whenever I load my world a Default Item Pile Actor appears in the Actor tab

### ISSUE THREAD

**Issue by DocMysterio** [fantasycalendar/FoundryVTT-ItemPiles#277]
**Have you tried to reset Item Piles' system settings?**
Yes /

**Describe the bug**
Whenever I load my world a Default Item Pile Actor appears in the Actor tab which I have to delete. I cannot find a way to turn this off.

**To Reproduce**
Tried looking in Item Pile settings.

**Expected behavior**
I don't want the Default Item Pile Actor to appear.

**Screenshots**

**Setup:**

- Foundry Version: [e.g. 10.291]
- System Version: [e.g. PF2 4.7.4]
- Item Piles Version: [e.g. 2.4.16]
- Browser & version [Google Chrome 109.0.5414.119 (Official Build) (x86_64)]

**Active modules:**
- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Fixed in 2.4.17
