### ISSUE TITLE
[BUG] - [e5] - On Interact Macro doesn't populate items array into Macro execution context

### ISSUE THREAD

**Issue by FeistyMango** [fantasycalendar/FoundryVTT-ItemPiles#279]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
If I setup an On Interact macro to be executed from a particular Merchant, it is executed appropriately. However, the items that were either bought or sold do not appear in the context payload correctly. When buying, the item is just missing from the `items` array, when selling to a merchant, the items array is populated with  an `undefined`.

**To Reproduce**

1. Setup an NPC Merchant
2. Open the mechant's Item Pile Configuration 
3. Under Main Settings Tab, attach a On Interact Macro using this code `console.log(arguments);`
4. Have a player character complete a Buy/Sell transaction with the merchant item pile
5. Review GM dev tools console and you'll see that the context object passed into the macro is missing the `items` information involved in the transaction

**Expected behavior**
I should be able to receive a list of items that were involved in the transaction so I can use them in my macro script.

**Screenshots**
When Selling
![image](https://user-images.githubusercontent.com/3461388/219227612-72e56318-62c5-47e6-83d0-2f6dd1f5dc7c.png)

When buying:
![image](https://user-images.githubusercontent.com/3461388/219227733-c1d24db5-0674-4ffb-a65f-bbe323a0894c.png)

**Setup:**

- Foundry Version: 10.291
- System Version: Dnd5e 2.1.4
- Item Piles Versio: 2.4.16
- Browser & version 110.0.5481.97 (Official Build) (64-bit)

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by FeistyMango** [comment]
Confirmed the location of the bug, it appears either the bug is that the object was double wrapped unintentionally, or it was just improperly referenced in a mapping function right before it is emitted to the macro function

In the image: When selling to a merchant, this code path attempts to map the items using the line:
```
if (macroData.items) {
        macroData.items = macroData.items.map(item => targetActor.items.get(item._id));
      }
```

However, the object structure is `item.item._id` whereas it attempts to access `item._id` which results in the mapped array containing undefined values.

![image](https://user-images.githubusercontent.com/3461388/219295784-5c3b080f-721a-4f88-bbf1-1ae26d59986d.png)

**Comment by FeistyMango** [comment]
The issue is slightly different when purchasing from a merchant. In that situation, the seller's item delta is empty, and that is the only actor that passes the `_executeItemPileMacro()`'s `if (!PileUtilities.isValidItemPile(target)) return false;` function. However, the PC item delta has the actual item in the list, but it does not pass this check, so the NPC's data is what is executed and sent to the Macro hook.

In this case, it seems like the bug is that the Merchant's item delta is not being populated.

![image](https://user-images.githubusercontent.com/3461388/219297032-8a3c5467-4b5d-49ac-b51e-92fe24a520c2.png)

![image](https://user-images.githubusercontent.com/3461388/219296654-63f7286c-daff-4115-a379-1b52bd76a21d.png)

**Comment by FeistyMango** [comment]
More info on the Buying from a Merchant scenario. I discovered it is because the logic doesn't take into account if the Merchant has been configured to have an infinite amount of an item. When the config is on, this bug manifests on the Purchasing scenario, when I disable the infinite quantity, then I start seeing the delta populated properly.
![image](https://user-images.githubusercontent.com/3461388/219298531-1b15779a-7ae7-45bb-b8ec-9f3d0c24ff07.png)

**Comment by Haxxer** [comment]
Thank you for the detailed write-ups. I will take a look and see what I can do about this.

**Comment by FeistyMango** [comment]
np, I was able to quickly make a fix quick for the section where the items are merged which was pretty simply. However, it seems like the idea here is that if you are not a ItemPiles actor, the intent was not to run the On Interact macro. So that means addressing the other issue upstream in the logic that runs the `Transaction` and then finds the deltas of what was aded/removed. However, when you are an NPC with infinite inventory, there is going to be no database call where anything is actually removed, so it seems that the logic of calculating the delta upstream in the `Transaction.prepare()` is the appropriate place to fix the issue of the items not appearing as a delta? I haven't read through all the code after that which might be affected by the sudden appearance of the item so perhaps a metadata property indicating that it was sold, but not actually deleted whereever that may be necessary to take into account?

**Comment by Haxxer** [comment]
@FeistyMango 

Contrary to what I just said, that was the easiest way to go about it without having to keep track of items before and after updates, deletions, and creations.

Would you mind trying out your implementation in the 2.4.17 alpha? Do back up your world, in case the alpha has any bugs:
https://raw.githubusercontent.com/fantasycalendar/FoundryVTT-ItemPiles/next/module.json

**Comment by FeistyMango** [comment]
I do, I'll load it up locally and give it a go!

**Comment by FeistyMango** [comment]
I haven't examined the code change you made but just testing it, it appears to fire off the macro twice. I presume once for each character.
![image](https://user-images.githubusercontent.com/3461388/219514993-105b7203-5ba1-46a1-ae98-09af4a4b4780.png)

**Comment by Haxxer** [comment]
Ah yeah, that makes sense; I'll make the adjustment.

**Comment by Haxxer** [comment]
If I make a single macro call, we will have to decide how to handle which deltas to pass; we could potentially abandon that entire idea by simply using the `prices` property on this macro callback. Thoughts?

**Comment by FeistyMango** [comment]
For my particular purposes, I really want to have all that useful info about the items themselves as well as the prices. Couldn't we also emit based on the item deltas of the item pile npc? Yes, it will mean that an integration has to calculate whether it is a sale to or buy from transaction, but even just the prices themselves would be enough to determine that since Purchases from players would have negative numbers whereas sales to players would be positive numbers.

**Comment by Haxxer** [comment]
Did you check out the `prices` properties? It has all of the information you are looking for, I assume.

**Comment by FeistyMango** [comment]
👁️ Ahhh I didn't even notice how that had been changed. Ya, that would work just fine for my use-case!

**Comment by Haxxer** [comment]
Here's what I'm thinking of changing:
```js
const itemPileActorUuid = sellerIsMerchant ? sellerUuid : buyerUuid;

await this._executeItemPileMacro(itemPileActorUuid, {
  action: "tradeItems",
  source: sellerUuid,
  target: buyerUuid,
  sourceItems: sellerTransactionData.itemDeltas,
  sourceAttributes: sellerTransactionData.attributeDeltas,
  targetItems: buyerTransactionData.itemDeltas,
  targetAttributes: buyerTransactionData.attributeDeltas,
  prices: itemPrices,
  userId: userId,
  interactionId: interactionId
});
```
and 

```js
if (macroData.items) {
  macroData.items = macroData.items.map(item => targetActor.items.get(item?.item?._id ?? item._id));
}

if (macroData.sourceItems) {
  macroData.sourceItems = macroData.sourceItems.map(item => sourceActor.items.get(item?.item?._id ?? item._id));
}

if (macroData.targetItems) {
  macroData.targetItems = macroData.targetItems.map(item => targetActor.items.get(item?.item?._id ?? item._id));
}
```

**Comment by FeistyMango** [comment]
Sorry for the delay. So essentially, all deltas on a single event. I like that approach. It feels cleaner that the structure of the prices object approach. Also unified it into a single contract. Perhaps one other modification, knowing which side of the transaction the npc is on, would give this a very clean interface to work with. Perhaps convert the source and target to objects that include a piece of conditional metadata such as `isNPC` or `isItemPileActor`. That would allow the macro script writer to easily decide what type of behavior they want to execute depending on whether or not it was a sell to vs buy from scenario. In my use-case I’ve got a discord web hook that I tied into a macro whenever a transaction with the merchant occurs. And formatting the way that is output into discord is dependent on if it was a sell to or buy from situation.

**Comment by FeistyMango** [comment]
Whenever you have a chance to complete that change, I can run it through some testing again. Thanks for your responsiveness with this request!

**Comment by Haxxer** [comment]
Just updated the alpha, the macro data now includes everything, as well as a bool for `sourceIsMerchant`

**Comment by FeistyMango** [comment]
Awesome! I’ll be home and can test it in about 3-4 hours.

**Comment by FeistyMango** [comment]
Performed some testing, see code review comments.

**Comment by FeistyMango** [comment]
Branched off your branch and added the missing loan. Put up a PR for it along with test script + screenshots

https://github.com/fantasycalendar/FoundryVTT-ItemPiles/pull/281

**Comment by Haxxer** [comment]
Thank you! I have merged this now, and shall push a release :)
