### ISSUE TITLE
[BUG] - [!! Midi-QOL Drag and Drop Targeting bug !!]

### ISSUE THREAD

**Issue by ravingdragoon** [fantasycalendar/FoundryVTT-ItemPiles#28]
**Describe the bug**
When using Item Piles and Drag and Drop Targeting I get a request to make an item pile whenever I drag the attack onto the creature. It's not game breaking, but it is annoying to have to dismiss the pop up box every time.

**To Reproduce**
1. Enable Midi-QoL and the Drag and Drop Targeting option
1. Go to 'A sheet with a weapon'
2. Drag the weapon, or the weapon's attack action, and drop on another token
3. See the pop up to make an item pile

**Expected behavior**
No pop up to make an item pile from a sheet to a token

**Screenshots**
https://user-images.githubusercontent.com/72875320/148793382-62de3e48-883d-4ffe-bf04-e771b9e3af56.mp4

**Setup:**
 - Foundry Version: 9.242
 - Item Piles Version: 1.1.2
 - OS: Windows 10
 - Browser: Chrome
 - Version: 96.0.4664.110

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - Midi-QoL
 - Module Sets - Dual Track GMing, baby

**Comment by Haxxer** [comment]
This has been fixed in 1.3.0 - it will no longer drop any items on the canvas when drag & dropping an item onto another token
