### ISSUE TITLE
[BUG] - [DND5e] - Populate store items not displaying buttons

### ISSUE THREAD

**Issue by ArekExora** [fantasycalendar/FoundryVTT-ItemPiles#283]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Create a merchant, go to Populate items tab, the buttons to add and roll for the tables do not show (see image).
![image](https://user-images.githubusercontent.com/20903647/220212700-4f32b437-5fde-4083-8a00-a5461cf5c745.png)

**To Reproduce**

1. Create a merchant
2. Go to Populate items tab
3. See error

**Expected behavior**
The buttons should be shown (see screenshot with edited CSS)
![image](https://user-images.githubusercontent.com/20903647/220212872-85731092-69d5-4073-bca0-50b1909277a2.png)

**Screenshots**
Added above

**Setup:**

- Foundry Version: v10, build 291
- System Version: DND5e 2.1.4
- Item Piles Version: 2.4.17
- Browser & version: Unsure, using Foundry app.

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- [insert more modules here]

**Additional context**
Seems to be an issue with the width of the elements, its overflowing the container.

**Comment by Haxxer** [comment]
What CSS did you edit?

**Comment by Haxxer** [comment]
Fixed in 2.4.18, hopefully

**Comment by Haxxer** [comment]
Shouldn't the description be a part of the rolltable's... description? :D
