### ISSUE TITLE
[BUG] - [Cypher System] - Itens price returning to 0

### ISSUE THREAD

**Issue by AgostinhoMestre** [fantasycalendar/FoundryVTT-ItemPiles#286]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
I'm not able to configure the price of the items, both in the merchant and directly in the item, any value placed always returns to 0..

**To Reproduce**
Open in Cypher System ruleset, create a pc, turn then into a merchant, create an item.

**Expected behavior**
Price changing

**Screenshots**

**Setup:**

- Foundry Version: [10 - 291]
- System Version: [Cypher Sysstem 2.4.1]
- Item Piles Version: [2.4.17]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**

**Comment by Haxxer** [comment]
Fixed in 2.4.18
