### ISSUE TITLE
[REQUEST] - Add ability to evenly split item stacks in vault

### ISSUE THREAD

**Issue by cpcodes** [fantasycalendar/FoundryVTT-ItemPiles#287]
**Is your feature request related to a problem? Please describe.**
Mostly I'd like a more convenient way to distribute healing potions among the party from my PF2e Alchemist's daily stash.

**Describe the solution you'd like**
This may not be the best way, so I'm open to suggestions, but what I was thinking is if I could drag the stack of freshly made potions to the vault, select the pile and hit a key combination (or right click on the pile and select an option) it would bring up a dialog that allows me to enter the number of piles I want and it would split the selected stack evenly in to that many new smaller stacks. If it could work in any context, that would be great, but when I try manually splitting stacks, PF2e auto-merges them if I drag them to the same character - i.e. a character can't seem to have more than one stack of a given item, hence I was thinking that a vault would solve this problem since I have had no problem with multiple stacks of the same item in a vault in PF2e - it seems that you might have more control over the vault container across multiple game systems, making this more system agnostic.
Ther could even be options for handling excess items if they don't evenly split into the chosen number of stacks - to create an additional partial stack with the excess (e.g. a stack of 17 split 3 ways would create stacks of 5,5,5,2), or to distribute them among as many stacks as possible (for 6,6,5 using the previous example).
From there, each player could then retrieve their stack.

**Describe alternatives you've considered**
Mostly manually dragging them to each target character splitting the stack as I go, which is tedious.

**Additional context**
None, except to add that this module seems the best suited to doing it (as it already supports splitting money), but a custom macro might also do the trick, but again, because PF2e seems to auto-merge stacks, I'd either have to do it from the vault anyway or build the macro to select the target actors as part of the splitting process, which might be beyond my skills.
I mean, yeah, I'm kinda hoping you'd do my work for me, but by the same token, it could be a great feature for your module, so the hopefully that makes the motivation for the request moot.

**Comment by Haxxer** [comment]
Added in 2.5.5
