### ISSUE TITLE
sw5e system settings

### ISSUE THREAD

**Issue by Ikaguia** [fantasycalendar/FoundryVTT-ItemPiles#288]
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/2f0e6fafee8c44a52a10f7d5e47980db6a380f2c/src/systems/sw5e.js#L13
Filters is missing `background`, aditionally, it has `subclass` instead of `archetype`.
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/2f0e6fafee8c44a52a10f7d5e47980db6a380f2c/src/systems/sw5e.js#L47
The path for galactic credits in sw5e should be `system.currency.gc` instead of `system.currency`.
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/2f0e6fafee8c44a52a10f7d5e47980db6a380f2c/src/systems/sw5e.js#L44
The img path is missing the system path at the start `systems/sw5e/packs/...`
![image](https://user-images.githubusercontent.com/16377028/222525580-36686ef8-fb95-4d07-a483-119d006682f8.png)

**Comment by Haxxer** [comment]
Fixed in 2.4.18, thanks
