### ISSUE TITLE
[Request] Output to Chat

### ISSUE THREAD

**Issue by saneronsds** [fantasycalendar/FoundryVTT-ItemPiles#29]
**Is your feature request related to a problem? Please describe.**
When many players are looting multiple chests, it is hard to keep track of what has and hasn't been picked up yet as a DM.

**Describe the solution you'd like**
Have a small chat message generated whenever a player loots something from an item pile. 
Something like '[PC] has looked [item] from [itempile]'

**Describe alternatives you've considered**
Asking the players to declare on voice when they've looted an item from the pile.

**Comment by Haxxer** [comment]
Would something like this work?

Each time a player picks up an item, it posts a message - if they pick up another item from the same pile in the same UI, it updates the previous chat message (assuming it's not too old of a message). If they close and return to the pile later, it will create a new message and begin again:

![image](https://user-images.githubusercontent.com/12858387/149539161-1a143a10-b260-4138-8086-4a6c99fc9864.png)

**Comment by saneronsds** [comment]
That's really good! It will definitely work.

**Comment by Haxxer** [comment]
Added feature in 1.2.0
