### ISSUE TITLE
[REQUEST] - Support for Rarity Colors module

### ISSUE THREAD

**Issue by Ikabodo** [fantasycalendar/FoundryVTT-ItemPiles#292]
**Is your feature request related to a problem? Please describe.**
Whenever an Item Pile is opened it's not as obvious to a user if the item is rare or not.

**Describe the solution you'd like**
There is an older module originally by Kandashi (managed by the great p4535992 now a days) that sets colors on items text to show rarity. it would be nice if Item Piles showed the colors too. I'm not sure if this is a change that needs to happen on Item Piles Side or Color Rarity though.

**Comment by Haxxer** [comment]
Added in 2.4.19

**Comment by Ikabodo** [comment]
I think this might have stopped working at some point. :D
Note sure if it's on Item Piles side or Rarity Colors, but it's not showing any colors. 

Foundry Virtual Tabletop: v11.313
DnD5e - Fifth Edition System: v2.3.1
Item Piles: 2.7.16
Rarity Colors: 0.3.4

**Comment by Haxxer** [comment]
Rarity coliors

**Comment by Haxxer** [comment]
Fixed once again
