### ISSUE TITLE
[BUG] - [PF2e] - Items sold in groups (that use Price-Per) lower the price of effected items dramatically

### ISSUE THREAD

**Issue by GorgoPrimus** [fantasycalendar/FoundryVTT-ItemPiles#294]
**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
Things like Sling Bullets, Chalk, Arrows, etc that are sold in groups (usually in 10s) cost dramatically less in Merchant Item Piles. If it costs 10cp for 10 it'll cost 'Free', if it costs 10sp for 10 it'll cost 10cp, etc.

**To Reproduce**

1. Make a Item Pile Merchant and fill it with consumables like Arrows and Chalk.
2. Look at prices in store and compare them to the actual prices in item description/data.

**Expected behavior**
They should follow the rules and cost the correct amounts, sold in proper size batches each time.

**Setup:**
Core Version: 10.291

System: 
- Foundry Version: 10.291
- System Version: pf2e 4.9.2
- Item Piles Version: item-piles 2.4.19 (Wasp)

**Active modules:**

Modules: 
advanced-macros v1.19.4 (mclemente, p4535992)
ambientdoors 2.3.3 (EndlesNights)
autoanimations 4.2.32 (Otigon (Otigon#2010))
award-xp 1.5.0 (Manuel Vögele)
betterroofs 1.7.6 (theripper93)
CautiousGamemastersPack 1.1.1 (Alan Davies, Shoyu Vanilla)
damage-log 1.11.0 (Alan Davies)
df-chat-enhance 4.1.0 (flamewave000)
dice-calculator 1.5.3 (Asacolips)
dice-so-nice 4.6.5 (Simone, JDW)
drag-ruler 1.13.4 (Manuel Vögele)
dragupload 2.2.2 (Cody Swendrowski <cody@swendrowski.us>)
footsteps-of-otari 2.0.1 (Mark Pearce)
force-client-settings 2.3.2 (kimitsu)
forien-copy-environment v2.1.6 (Blair McMillan, Forien)
foundryvtt-simple-calendar 2.1.80 (Dean Vigoren (Vigorator))
fxmaster 3.5.2 (Johannes Loher (ghost), Emmanuel Ruaud (U~man))
healthEstimate 29.8 (MClemente, Shylight)
illandril-token-tooltips 3.2.1 (Joe Spandrusyszyn (illandril))
initiative-double-click 1.6.1 (Matheus Clemente, KaKaRoTo)
item-piles 2.4.19 (Wasp)
ivan-duch-music-packs 1.6 (Ivan Duch)
JB2A_DnD5e 0.5.5.01 (Jules, Ben)
lib-wrapper 1.12.12.0 (Rui Pinheiro)
maestro 0.9.0 (Evan Clarke)
monks-hotbar-expansion 10.1 (IronMonk)
moonlight-maps-free 1.1.0 (Moonlight Maps)
multilevel-tokens 1.6.0 (grandseiken)
perfect-vision 4.1.19 (dev7355608)
pf2-flat-check 1.6.1 (enso#0361)
pf2e-abomination-vaults 2.0.0 (Andrew Clayton, Shane Martland, Viviane Charlier)
pf2e-animal-companions 5.6 (Tikael)
pf2e-dorako-ui 2.0.4 (Dorako)
pf2e-dragruler 2.1.8 ()
pf2e-f-is-for-flatfooted 4.20.1 (DrentalBot)
pf2e-jb2a-macros 2.10.9 (MrVauxs)
pf2e-modifiers-matter 1.5.4 (shemetz)
pf2e-ranged-combat 3.7.0 (JDCalvert)
pf2e-target-damage 2.4.5 (MrVauxs)
pfsconsumables 1.10.3 (Zach Armstrong (SLATE))
pings 1.4.0 (Azzurite#2004)
popout 2.10 (KaKaRoTo, Posnet)
popout-resizer 1.4.5 (cardagon)
quick-insert 2.8.0 (Sunspots)
sequencer 2.414 (Wasp)
settings-extender 1.2.1 (Azzurite#2004)
shopping-experience 2.1.0 (DrentalBot)
smalltime 1.16.3 (unsoluble)
smarttarget 0.9.8 (theripper93)
socketlib 1.0.12 (Manuel Vögele)
SoundBoard 1.7.1 (Blitzkraig)
SoundBoard-BlitzCommunityPack 1.0.1 (Blitzkraig)
tabletop-rpg-music 1.9.1 (Tabletop RPG Music)
tidy-ui_game-settings 0.1.51 (sdenec)
tile-scroll 1.9 (theripper93)
token-action-hud 3.0.19 (Larkinabout, Drental, ^ and stick)
token-attacher 4.5.11 (KayelGee)
token-mold 2.15.4 (Moerill, Geekswordsman)
tokenmagic 0.6.1.2 (SecretFire, sPOiDar, Zimm, Lozalojo, Moerill, KLO, dev7355608, Mestre Digital, BrotherSharper-Touge, OsiJr)
vtta-tokenizer 3.10.1 (MrPrimate, Sebastian Will)
wall-height 4.9.3 (theripper93, Ian Murphy, Cole Schultz)
warpgate 1.16.2 (honeybadger)
xdy-pf2e-workbench 4.52.1 (Jonas Karlsson (xdy))
_chatcommands 1.4.0 (Cody Swendrowski, The League of Extraordinary FVTT Developers)

**Comment by Haxxer** [comment]
Buying one should buy one, even if it's 10cp for 10. If you buy one, do you get 10? Is that the bug?

**Comment by GorgoPrimus** [comment]
The bug is that it sells Sling Bullets for '10 for 1cp' in the rules, the module will then divide the price down to Free because 1cp is the lowest you can get without using decimals and it doesn't handle selling items in bundles like that. So you can not only buy Bullets for 100% off, but if you go to buy 100 at once that'll also be Free since 0 x 100 is 0.

**Comment by Haxxer** [comment]
Added/fixed in 2.5.0
