### ISSUE TITLE
WFRP4e currency

### ISSUE THREAD

**Issue by Scrungusprime** [fantasycalendar/FoundryVTT-ItemPiles#296]
**Is your feature request related to a problem? Please describe.**
Populating a merchant with items only generates a price if the item has a GC value, if it uses one of the other 2 currencies for it's value a price can't be generated. I can't find a way to get it to recognise all 3 currencies in the module settings, and searching online doesn't get me anywhere

**Describe the solution you'd like**
Ability to have the  Item Price Attribute recognise more than 1 value, in this instance system.price.gc, system.price.ss, and system.price.bp

**Describe alternatives you've considered**
Searched online for similar problems, attempted to change the data path but nothing works for all 3 at once

**Additional context**

**Comment by Haxxer** [comment]
If you change the price system path to `system.price`, what happens?

**Comment by Scrungusprime** [comment]
Everything gets set to "undefined"

**Comment by Haxxer** [comment]
Fixed in upcoming version:
![image](https://user-images.githubusercontent.com/12858387/225433626-26f0310e-603c-44d7-89df-0cf04182197d.png)

**Comment by Haxxer** [comment]
Added/fixed in 2.5.0

**Comment by Scrungusprime** [comment]
amazing, thank you so much!
