### ISSUE TITLE
[BUG] - [Fallout 2d20] - Merchants will not deposit purchased items into character sheets

### ISSUE THREAD

**Issue by theMagius0** [fantasycalendar/FoundryVTT-ItemPiles#299]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Purchased items do not show up on Character Sheet.

**To Reproduce**
1) Drag actor to Scene.  Configure actor to Merchant.  Toss a few Items into the Pile.

2) Login on separate computer with "test" player instance.  Click on Merchant.  Click "Buy" button. 

3) Quantity (Max NaN) shows up (see attached picture).  Unable to change quantity from "1". 

4) Close and re-open merchant, as field is blank if it is ever changed from "1".

5) Leave quantity as "1" and click "Buy Item".  Chat dialog shows the purchase (see attached picture).

6) Open character sheet.  Money is deducted.  Item is nowhere to be found on any tab.

**Expected behavior**
- Purchase quantities should be user-selectable.
- Purchased items should appear on player Character Sheets.
- Item quantities (in shop) should decrement after purchase.

**Screenshots**
![ItemPiles_Merchant](https://user-images.githubusercontent.com/85370867/225732728-1c8ca2db-adda-471c-bac9-12de0fbacf26.png)
![ItemPiles_NaN](https://user-images.githubusercontent.com/85370867/225732348-ec428222-01d3-4945-bb09-89dc8ebded23.png)
![ItemPiles_Chat](https://user-images.githubusercontent.com/85370867/225732940-b6449536-531e-40ba-8b70-e3ab4fceec8e.png)
![ItemPiles_Character](https://user-images.githubusercontent.com/85370867/225733222-b20dfd9b-18b8-4689-b97d-9bce5231c3f1.png)

**Setup:**

- Foundry Version: [10 v291]
- System Version: [Fallout 2d20 v10.1.3]
- Item Piles Version: [v2.5.0]
- Browser & version [Google Chrome 111.0.5563.65]

**Active modules:**

Active Modules:
----------
Ace Library v;
Better Roofs v;
Combat Enhancements v;
Compendium Folders v;
Dice So Nice! v;
Drag Ruler v;
Fallout Core Data (Shared Compendiums) v;
FOCT: The Fire Down Below (Shared Compendiums) v;
Forien's Copy Environment v;
Foundry Community Macros v;
FXMaster v;
Health Estimate v;
Hover Distance v;
Item Piles v;
Levels v;
libWrapper v.0;
Macro Editor v;
Macro Grid v;
Mastercrafted - Crafting Manager v;
Moar Folders v;
Monk's Active Tile Triggers v;
Monk's Combat Details v;
Monk's Combat Marker v;
Monk's Enhanced Journal v;
Monk's Little Details v;
Monk's Player Settings v;
Monk's Scene Navigation v;
Monk's TokenBar v;
Multilevel Tokens v;
Patrol v;
Ping Logger v;
✋ Raise My Hand v;
socketlib v;
The Forge v;
Tidy UI - Game Settings v;
Token Attacher v;
Token Magic FX v;
Token Mold v;
Wall Height v;

**Additional context**
I could have _sworn_ that Item Piles was working when I installed it last week.

**Comment by Haxxer** [comment]
Fixed in 2.5.1, thanks for the report
