### ISSUE TITLE
[REQUEST] - Selectable Actor Type

### ISSUE THREAD

**Issue by loofou** [fantasycalendar/FoundryVTT-ItemPiles#30]
I really like the idea behind the Item Pile module, but in the SWADE at least, it's quite cumbersome to use, as every item pile is a Player Character actor and uses the PC sheet. The items are then hidden behind the "Gear" tab and it's not really clear to players that they can drag the items out. If the actor type could be definable, I could select "NPC" and use a much more readable sheet (either the default NPC sheet of SWADE or the Merchant sheet from the module of the same name for example).

I haven't found another way to make an item pile use the NPC actor, unless I create the item pile as an actor to begin with. But then I lose the drag & drop functionality of the module, as it will always create the Default Item Pile player character actor and uses that one instead.

**Comment by gsterling** [comment]
There is already a discussion in the SWADE repo to add a container actor: https://gitlab.com/peginc/swade/-/issues/186

**Comment by Haxxer** [comment]
Have you tried changing this setting in the module's settings?

![image](https://user-images.githubusercontent.com/12858387/149229072-e09493dd-6588-47a8-8df9-8dfe54b1e457.png)

**Comment by loofou** [comment]
... I'm sorry, I must have missed this setting. I was sure I checked the settings multiple times, but still missed it somehow. Thank you very much for pointing it out. It works as expected :)

**Comment by Haxxer** [comment]
If you think NPC would be a better setup, do you reckon that I should change SWADE's Item Pile defaults?

**Comment by loofou** [comment]
I would say so, yes. Here's an example:

Default Character Sheet:
Starts in Traits Tab, you have to manually switch to Gear tab to see the items -> not obvious at all.
![Screenshot 2022-01-13 141857](https://user-images.githubusercontent.com/2287749/149337712-b2bd4b62-97b5-49a2-b419-4da127dc57e1.png)

Default NPC Sheet:
Better, the items are directly visible. Stats can be ignored, but still lots of wasted space. Still great default!
![Screenshot 2022-01-13 141641](https://user-images.githubusercontent.com/2287749/149337780-086450bd-0399-4c83-9d63-e1ea9f8c1f1b.png)

NPC Merchant Sheet (from module):
Best option, IMO, no superfluous information (buttons at the top are also not available for players). Works still with NPC actor type.
![Screenshot 2022-01-13 141745](https://user-images.githubusercontent.com/2287749/149337902-01b8c795-760c-4666-b2fa-5f83648b1e62.png)

IMO using "npc" actor type as default makes the most sense, as it's the best way to get to the actual information the item pile provides.
