### ISSUE TITLE
How to set default container images/sounds?

### ISSUE THREAD

**Issue by arcanjl** [fantasycalendar/FoundryVTT-ItemPiles#300]
I set it all up of a container, but every new one I make does not have the images. Is there a way to set up a default? I looked in the settings, and could not find it :)

**Comment by arcanjl** [comment]
Thank you. I think that helps :) Is there supposed to be a default item pile actor in my actors list?

**Comment by Haxxer** [comment]
Drag and drop any item to the canvas to create it.

The first sentence on that page:

```When you first drag out an item onto the scene, the module will create the Default Item Pile actor in your sidebar.```

**Comment by arcanjl** [comment]
Thank you for pointing me to those instructions. I had no idea how powerful this module was. I haven’t figured it out plus lots more.

 Thank you for taking the time.
