### ISSUE TITLE
[BUG] - [5e] - "localize is not defined" when updating an item pile

### ISSUE THREAD

**Issue by stschmitt87** [fantasycalendar/FoundryVTT-ItemPiles#303]
When updating an item pile, I get the following error in console:

Uncaught (in promise) ReferenceError: undefined. localize is not defined
[Detected 1 package: item-piles]
    at ItemPileStore.update (item-pile-store.js:339:5)

After that, dropping an item onto a scene doesn't open the Item Pile popup anymore until I reload the page.

1. Create an item pile
2. Click on Update Item Pile

![image](https://user-images.githubusercontent.com/52425547/226064108-b4f5b671-3cca-499a-a7b2-49b89dcbd633.png)

**Setup:**

- Foundry Version: 10.291
- System Version: DnD 5e 2.1.5
- Item Piles Version: 2.5.1
- Browser & version Chrome Version 111.0.5563.65 (Official Build) (64-bit)

Active Modules:
----------
Ace Library v;
Action Pack v;
Active-Auras v;
Active Token Effects v;
Actually Private Rolls v;
Advanced Macros v;
Ambient Doors v;
Automated Animations v;
Auto-Rotate v;
Better Roofs v;
Cautious Gamemaster's Pack v;
Character Actions List dnd5e v;
Combat Focus v;
Combat Utility Belt v;
Compendium Browser v;
Compendium Folders v;
Compendium Scene Viewer v;
Crash's Automatic Blind Rolls (5e) v;
DF Architect v;
DF Curvy Walls v;
DFreds Convenient Effects v;
DF Scene Enhancement v;
Dice So Nice! v;
Dice Tray v;
DnD5e Drag Ruler Integration v;
Drag Ruler v;
Drag Upload (Get Over Here!) v;
Dynamic effects using Active Effects v;
Encounter Statistics v;
Find the culprit v;
Forien's Quest Log v;
Foundry Community Macros v;
Foundry Community Tables v;
FXMaster v;
Ghosts of Saltmarsh v;
GM Notes v;
Hidden Soundtracks v;
Item Macro v;
Item Piles v;
JB2A - Patreon Complete Collection v;
Levels v;
lib - Color Settings v;
Library: Active effect manager v;
Library: DF Module Buttons v;
Library: Scene Packer v;
lib Themer v;
libWrapper v.0;
Macro Editor v;
Magic Items v;
Mass Edit v;
Midi QOL v;
Midi SRD v;
Module Profiles v;
Monk's Active Tile Triggers v;
Monk's Combat Details v;
Monk's Combat Marker v;
Monk's Hotbar Expansion v;
Monk's Player Settings v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
Moulinette Core v;
Moulinette Game Icons (module) v;
Moulinette Image Search (module) v;
Moulinette Scenes (module) v;
Moulinette Sounds & SoundPad (module) v;
Moulinette Tiles (module) v;
Multilevel Tokens v;
Ownership Viewer v;
Perfect Vision v;
PnP - Pointer and Pings! v;
Polyglot v;
PopOut! v;
Popout Resizer v;
Quick Insert - Search Widget v;
Rest Recovery for 5E v;
Select tool everywhere v;
Sequencer v;
Show Notes v;
Simbul's Athenaeum v;
Simbul's Creature Aide v;
Simple Calendar v;
Simply Portraits v;
SmallTime v;
socketlib v;
Tabletop RPG Music v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Tile Scroll v;
Tile Sort v;
Times Up v;
Token Attacher v;
Token Ease v;
Token HUD Wildcard (fix) v;
Tokenizer v;
Token Magic FX v;
Token Z v;
Universal Battlemap Importer v;
Wall Height v;
Warp Gate v;
World Scripter v;

**Comment by Haxxer** [comment]
Should be all good in 2.5.2
