### ISSUE TITLE
[BUG] - [13th Age] Item Piles Revert to Standard Sheets

### ISSUE THREAD

**Issue by Maleketh** [fantasycalendar/FoundryVTT-ItemPiles#304]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When an actor is set to be an item pile, the normal item pile window comes up.  However, if the window is closed and reopened, it reopens as a standard sheet (PC or NPC, depending on what was used as the basis).  On NPC sheets, the items in the pile appears undear a "Misc." tab.

**To Reproduce**

1. Create an actor.
2. Designate it as an item pile.
3. Close the item pile window and reopen.

**Screenshots**
![ItemPile](https://user-images.githubusercontent.com/22279809/226108903-33e7e7a1-2a5b-43f1-8119-f22bc4ea84f8.png)

**Setup:**

- Foundry Version: 10
- System Version: 13th Age 1.25
- Item Piles Version: 2.5.2

**Active modules:**

- Item Piles
- libwrapper
- socketlib

My main game has other modules installed, but I tested it using only these three and the problem persisted.

**Additional context**
The module was working fine as of a couple of weeks ago.

**Comment by Haxxer** [comment]
This system is not supported by Item Piles, so unless I can have the configuration for the system, I cannot test it, and thus cannot confirm your bug.

**Comment by TheLaslo** [comment]
I have this same problem with SWADE.
When you go back to the sheet and choose "configure" the Item Piles "enabled" checkbox is no longer set.  When you re-enable it and try to save you get this javascript error.
"Uncaught (in promise) TypeError: currency.data is undefined
[Detected 3 packages: item-piles, socketlib, lib-wrapper]
    currencies pile-utilities.js:170
    getActorCurrencies pile-utilities.js:160"
plus some more lines.

**Comment by Haxxer** [comment]
And have you tried to reset the item piles module system settings?

**Comment by TheLaslo** [comment]
I have just tried to reset the system settings and no difference.
I don't know why it is trying to go to currency.data when SWADEs default currency would be found in system.details.currency.
I have attached a copy of the mule's json, note that this is an old actor and I seem to recall that Item Piles had a refactor at some point?
[mule.txt](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/11090512/mule.txt)

**Comment by Haxxer** [comment]
@TheLaslo The mule has override currencies enabled. I would fix that by turning that off on the token.

**Comment by Haxxer** [comment]
@Maleketh Could you perhaps provide the necessary information to run with Item Piles in 13th Age?

**Comment by Maleketh** [comment]
Probably not since I'm not very technically proficient, but if you tell me what you need I can try.

**Comment by Maleketh** [comment]
Actually, it looks like the 13th Age system has updated, and now the item piles work correctly again.  I can still try to send you information if you want to get your mod working with it though.

**Comment by Haxxer** [comment]
What did you put in the system specific settings inside of item piles? Without those configured, the module won't work properly. It did warn you the first time you launched it.

**Comment by Haxxer** [comment]
Unless the module is configured correctly, I unfortunately can't help with this bug.
