### ISSUE TITLE
[REQUEST] - Apply services and consume items immediately instead of adding them to the inventory

### ISSUE THREAD

**Issue by Shayulghul** [fantasycalendar/FoundryVTT-ItemPiles#305]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like services, like healing spells, to be cast or consumed automatically on the actor instead of adding an item to their inventory.

**Describe alternatives you've considered**
I thought about adding an item macro to automatically trigger/roll the item when it's added to the actor, but I don't know enough JS to pull that off.

**Additional context**
I have some merchants set up with clerical spells that are set as services. When an actor buys a service, it's added to the character sheet as an item. The problem I have with this is that they could stock up on the items or save them for later (like scrolls and potions). I also have food and lodging items that apply benefits and healing when used, but I don't want the players to store them. I would like the effects to be applied immediately when they purchase them.

**Comment by Haxxer** [comment]
It should not add the item when it is a service. Can you take a screenshot of your merchant? I want to make sure it looks like this:

![image](https://user-images.githubusercontent.com/12858387/226144339-5f403d71-2d0a-446c-b988-1b774d2ea1d2.png)

**Comment by Haxxer** [comment]
People have often confused other merchant modules for Item Piles merchants, when they are not the same.

**Comment by mfozz** [comment]
<img width="1101" alt="Screenshot 2023-03-18 at 6 18 49 PM" src="https://user-images.githubusercontent.com/89781047/226145054-71201a1a-e772-477d-9633-1c4a75c7584e.png">


Yeah, I think I was mistaken. It's not adding the service, but I would like it to cast the spell or force the buying actor to auto-consume the item. The effects work fine if they are normal items, but I would prefer them not to be added to the inventory, which is why I want to make them services. Automatically rolling the item when you purchase it would be really cool.

**Comment by Haxxer** [comment]
Check the macro compendium for item piles - it has a cure wounds service macro. Closing as fixed.

**Comment by mfozz** [comment]
This isn't exactly what I was looking for, but thanks. I already tried it. If it's something you don't want to explore, that's cool.

**Comment by Haxxer** [comment]
You can always modify the macro to roll the item when bought though - rolling items is a system specific thing, which item piles cannot support, since item piles support over 20 systems now, and some system have no concept of a "roll".

**Comment by Haxxer** [comment]
@mfozz I've added this information here:

https://fantasycomputer.works/FoundryVTT-ItemPiles/#/merchant?id=services-and-custom-behavior
