### ISSUE TITLE
[BUG] - Dark Heresy 2 - Missing Translation for "No currency"

### ISSUE THREAD

**Issue by diwako** [fantasycalendar/FoundryVTT-ItemPiles#306]
**Have you tried to reset Item Piles' system settings?**
No, no need as the system is not supported

**Describe the bug**
While adding support for the Dark Heresy 2 system, which has no currency, I noticed this when accidentally hitting the add currency button.
![image](https://user-images.githubusercontent.com/8259498/226304952-b9a76e01-33a5-4ab6-8eb9-3d5a3c6942aa.png)

**To Reproduce**

1. Create world with any unsupported system
2. Place down any token
3. make token a pile
4. Try to add currency to the pile

**Expected behavior**
Text is shown that the system does not support currency or has none

**Screenshots**
uuh, see above

**Setup:**

- Foundry Version: 10.291
- System Version: Any unsupported system
- Item Piles Version: 2.5.3
- Browser & version: Standalone foundry client

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Token mold
- Sequencer
- JB2A patron
- Quick Insert
- Dark Heresy 2nd Edition Resource Pack

**Additional context**
None

**Comment by Haxxer** [comment]
You shouldn't be able to add currencies to the piles if the system doesn't have any, so less of a localization bug and more of a bug-bug.

**Comment by diwako** [comment]
Well, glad to find bugs. I just thought it was simply a missing translation.

**Comment by Haxxer** [comment]
Fixed in 2.5.4
