### ISSUE TITLE
[REQUEST] - Hide Text from Item Pile icon

### ISSUE THREAD

**Issue by SalieriC** [fantasycalendar/FoundryVTT-ItemPiles#31]
**Is your feature request related to a problem? Please describe.**
The top bar of actor sheets can get pretty cluttered with icons and text.

**Describe the solution you'd like**
An optional setting to hide the text from the top bar of actor sheets and instead adding a text on mouse over.

**Describe alternatives you've considered**
The only alternative I can think of would getting rid of the button completely and hiding the item pile options somewhere else, like the context menu when right clicking on an actor in the sidebar.

**Additional context**
![image](https://user-images.githubusercontent.com/1230041/149154131-e695707a-0b0c-48a6-ae29-65a402c36645.png)
This is Savage Worlds with only CUB, PopOut! and Item Piles adding buttons there and it's still covering the actors name due to core and system buttons.

**Comment by gsterling** [comment]
In german it's even longer with "Gegenstandsstapel" instead of "Item Pile". I second this.

**Comment by Haxxer** [comment]
Added in 1.2.0
