### ISSUE TITLE
[SYSTEM] - Naheulbeuk 

### ISSUE THREAD

**Issue by Gebafdc** [fantasycalendar/FoundryVTT-ItemPiles#310]
https://foundryvtt.com/packages/naheulbeuk

https://github.com/Dipess/naheulbeuk

Hi, I have issues with this module which seems super useful for my campaign based on the Naheulbeuk system (french TTRPG system)

I'm sorry, I have no idea how to find any of the useful requested data points, I am new to this

I can provide a screenshot of the error messages that appear when I try to drag an item to the scene board:
![image](https://user-images.githubusercontent.com/128757862/227388869-a12dfcc9-becd-43d4-bd3a-0b1bc1c328da.png)

Feel free to ask for further data or to point me in a direction where I can learn where to find the requested infos to help support this system

**Comment by Haxxer** [comment]
Without the proper info I cannot implement this system. You can always ask in the appropriate discord channel for help with this.

**Comment by Gebafdc** [comment]
Hello, I am back with the missing info from the system devs :)

![image](https://user-images.githubusercontent.com/128757862/227782726-485467d8-b2bb-473f-a6a7-16425aa5a565.png)
![image](https://user-images.githubusercontent.com/128757862/227782760-31e8718c-81e2-4199-9a4c-aa62691aa362.png)
(from the "Equipements : materiel" compendium)

![image](https://user-images.githubusercontent.com/128757862/227782774-aa842ee4-25c0-4ec4-9543-0719938bfc15.png)

I hope this helps with implementation

**Comment by Haxxer** [comment]
The text makes it pretty hard to read; it would be helpful if you could include this as text on this ticket :) If not, no worries

**Comment by Gebafdc** [comment]
Actor Class Type : character


Item Quantity Attribute : system.quantity

Item Price Attribute : system.prix

Item Filters : ape, attaque, competence, coup, etat, metier, origine, region, sort, trait

Item Similarities : I have got no info regarding this, I can get back to asking the system devs if needed

Currencies : default should be "Pièce d'or" (PO), I'll configure the other currencies as needed, but the exchange rate is :
1 "Pièce d'argent" = 0,1 PO
1 "Lingot de Thrytil3 = 100 PO
1 "Lingot de Berylium = 500 PO

Hope this helps :)

**Comment by Haxxer** [comment]
@Gebafdc Is there any way you would shorten the `Pièce d'or` for the abbreviation? For example `Gold Pieces` in D&D5e is abbreviated as `GP`, can you do that with these words in French?

**Comment by Haxxer** [comment]
Added in 2.5.8, let me know when you see the above.

**Comment by Gebafdc** [comment]
Huge thanks, I'm gonna check it out :)

Of course, I used the "po" abbreviation above, it is widely used in french and is already used in the system as "po" on the price of objects

**Comment by Haxxer** [comment]
So `Pièce d'argent` would be `PA`? That is what I wanted to know :)

**Comment by Gebafdc** [comment]
Yes, absolutely :) thank you again, the module seems to be working great, I just need to test it out more with people to see if everything works as intended but so far so good !
