### ISSUE TITLE
[BUG] - [WFRP4] - Issue with "french translation currencies"

### ISSUE THREAD

**Issue by chegodaev** [fantasycalendar/FoundryVTT-ItemPiles#311]
**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
Hi, when i update items pile in last version (2.5.4) there is an issue with wfrp4 system. I use foundry in french and i can't anymore "switch" currencies ( "Gold piece" to "Couronne d'or".. ). item piles considers all item are free. This problem doesn't exist in version 2.4.18 of item piles

**To Reproduce**

1. Go to items pile last version 
2. Click on option, system configuration 
3. Scroll down to currencies configuration

**Expected behavior**
I don't know if you can resolve that :)
**Screenshots**
Item Piles in 2.5.4 (all other module are in last version)
![image](https://user-images.githubusercontent.com/123258058/227529425-092599ab-acd7-4ac3-a696-d8cbcf885c4f.png)
![image](https://user-images.githubusercontent.com/123258058/227529801-b7cc0bee-43bf-4cc6-a562-3b370677aeed.png)
![image](https://user-images.githubusercontent.com/123258058/227530178-74b10e24-8652-4ce1-bce8-4c8e0d563f46.png)

Item Piles in 2.4.18 (all other module are in last version)
![image](https://user-images.githubusercontent.com/123258058/227531461-58807fe5-f5ad-4cf6-ab16-ae25b86ed341.png)
![image](https://user-images.githubusercontent.com/123258058/227531647-97faf91d-74ab-413b-a25a-0fb6210421bb.png)
![image](https://user-images.githubusercontent.com/123258058/227531719-100a52ae-66a0-4fe0-b429-159f7dbbc0d6.png)

**Setup:**

- Foundry Version: 10.291
- System Version: WFRP4 6.4.0 
- Item Piles Version: 2.5.4

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Fixed in 2.5.5
