### ISSUE TITLE
[BUG] - Clicking on a placed token on the canva opens the actor sheet with "Prototype token" instead of "Token" when actor has linked data

### ISSUE THREAD

**Issue by JordanRR** [fantasycalendar/FoundryVTT-ItemPiles#313]
![image](https://user-images.githubusercontent.com/18445516/227735370-8f53495f-78a2-433b-a4cc-3fcc251f8590.png)
Item Pile 2.5.6

When I click on a placed token for an actor that has linked data, it opens the sheet that lets me modify the prototype token. It was not like that before.
Here is what I mean : I clicked the "Bel" token on the table (tis one has linked data). Look at the header on the PC sheet : it says "prototype token"
![image](https://user-images.githubusercontent.com/18445516/227735406-ea0afa37-1a6e-4c3c-94a6-f9f10b929e9b.png)

Compare, here, with the Albino Ape, which does not have linked data. It says "token".
![image](https://user-images.githubusercontent.com/18445516/227735423-774e0484-a2d1-4109-adcb-e38e555f227b.png)

Normal behavior would open a sheet with Token, not Prototype token : https://foundryvtt.com/article/tokens/

Thank you!

**Comment by Haxxer** [comment]
This doesn't happen to me with the latest version, weird. What system is this?

**Comment by JordanRR** [comment]
Item Pile 2.5.6 Here are the infos. Everything up to date. 
![image](https://user-images.githubusercontent.com/18445516/227735611-65650d55-0ade-486e-b2ad-9eedb0a359c1.png)

**Comment by JordanRR** [comment]
Maybe a weird interaction between Item Pile and another module? I disabled Item Pile and everything is back to normal.

**Comment by Haxxer** [comment]
This happens for me in OSE:

https://user-images.githubusercontent.com/12858387/227735678-42fd63ed-eb37-480d-8060-84bfa06d07a7.mp4

Could you try to use Find The Culprit to find which module causes it?

**Comment by JordanRR** [comment]
What you show is the problem I am refering to (0:02 : the button in the "header" is "Prototype token" and should be "Token", just like the monster sheet you open at 0:05). I did use Find the Culprit and it identified Item Piles.

**Comment by Haxxer** [comment]
I see, yeah, that's probably something I'm messing up :)

**Comment by Haxxer** [comment]
Fixed in 2.5.6
