### ISSUE TITLE
[BUG] - [DND5E] - Show item pile to players doesn't show all players

### ISSUE THREAD

**Issue by MemeProof** [fantasycalendar/FoundryVTT-ItemPiles#314]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
I have 4 players in my campaign on foundry. When i choose the "Show to Players" it only shows two of the 4 players. I've reviewed all the character sheets and can't find what could be wrong.

**To Reproduce**

1. Go to 'Item pile'
2. Click on 'Show To Players'
4. only shows 2 of 4 players

**Screenshots**
![image](https://user-images.githubusercontent.com/43192081/227748311-8d9b3ccb-eb6e-4659-8ccc-a779eeccd227.png)

**Setup:**

- Foundry Version: Current
- System Version: Current
- Item Piles Version: Current
- Browser & version: Current

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- [I have disabled all other modules i have set up but the issue still persists]

**Comment by Haxxer** [comment]
Do they have the characters assigned to their user profiles in the bottom left?

**Comment by MemeProof** [comment]
Oh that worked! I didn't know that was even a thing. Thank you and sorry!

**Comment by Haxxer** [comment]
I'll still probably improve this feature to assume that the most recently updated owned token by a player is the one they want to use, or some other implementation. I'll keep this ticket open to close later :)

**Comment by Haxxer** [comment]
Fixed in 2.5.8
