### ISSUE TITLE
[REQUEST] Item Piles vault in character sheets

### ISSUE THREAD

**Issue by SugarSheikh** [fantasycalendar/FoundryVTT-ItemPiles#315]
Hello! Loving the module and especially the vault feature.

Is there any possibility of enabling the vaults as an inventory style in 5e. Currently I use tidy5e sheet, so is there any possibility of an integration?

Thanks!

**Comment by Haxxer** [comment]
The main problem with this is that each system that item piles support implements their character sheets differently, not to mention the plethora of sheet modules out there for each system, bringing the number of potential implementations up by several factors. Perhaps someone in the future can take inspiration from item piles and implement their own grid-based sheet, but this is most likely not something item piles can support.
