### ISSUE TITLE
Updates to the Twodsix system configuration.

### ISSUE THREAD

**Issue by marvin9257** [fantasycalendar/FoundryVTT-ItemPiles#316]
Hi,
I'm one of the maintainers of the Twodsix system.  I'd like to suggest an update to the item filters for it.  Right now, I've put a hook in the system that looks like this to override the current configuration.
```
Hooks.once("item-piles-ready", () => {
  /// Called once Item Piles is ready to be used
  //Set Item Piles filtered items
  game.itempiles.API.setItemFilters([
    {path: 'type', filters: 'skills'},
    {path: 'type', filters: 'trait'},
    {path: 'type', filters: 'spell'},
    {path: 'name', filters: game.i18n.localize("TWODSIX.Items.Weapon.Unarmed")}
  ]);
});
```
Not certain whether the first three can be combined into one.  I think it would be better to have this update as part of the Item Piles system definition for Twodsix.  

Also, I noticed in some of the other system that formats for the css could be modified.  Something like this would make lists more readable with Twodsix's dark style.

```
.item-piles-odd-color:nth-child(odd), .item-piles-even-color:nth-child(even) {
  background-color: var(--s2d6-light-background-transparent);
}
```
I can put this override in Twodsix.  But I'm wondering whether it would be better as part of the system config in Item Piles.

Thanks for the great module!

**Comment by Haxxer** [comment]
Cheers for the great questions, and yes indeed, you can combine all three types into this:
```js
{ path: "type", filters: "skills,trait,spell" }
```
In addition, you can see the default configuration here, so if you want to suggest some changes, I would greatly appreciate a PR :)

https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/master/src/systems/twodsix.js

You can also see how some systems override certain CSS variables to solve your second question:

https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/master/src/systems/wfrp4e.js#L103-L106

**Comment by Haxxer** [comment]
Lastly, if you want the system to handle the system support, you can utilize something similar as OSE:

https://github.com/vttred/ose/blob/main/src/module/fvttModuleAPIs.js

**Comment by marvin9257** [comment]
Thanks...so I've tried to override the CSS variable with no luck.  Something like...
```
"CSS_VARIABLES": {
    "--item-piles-even-color": "#ffffff17"
  }
```

or 
```
"CSS_VARIABLES": {
    "even-color": "#ffffff17"
  }
```
Also, I can't call the localization function for the filters because it is "undefined".  I don't think it is loaded yet.
`{path: 'name', filters: game.i18n.localize("TWODSIX.Items.Weapon.Unarmed")}`

Maybe I should just leave these overrides as part of Twodsix? Open to your thoughts.

**Comment by Haxxer** [comment]
`#ffffff17` is not a valid color, as far as I know? try `#ffff17` - as for the unarmed attack, is there any properties that is unique to the unarmed attack item?

**Comment by marvin9257** [comment]
Unfortunately, unarmed does not have another unique property other than the img.  I think the best thing is to leave the filter updates for these in Twodsix.  Also the color desired is rgba(255, 255, 255, 0.09). But I still can't get your changes above to change the highlight color.  I'll leave these mods to the definition Twodsix. Let's not change your core definition for now.  Thanks and sorry to bother you!

**Comment by marvin9257** [comment]
On second thought...let me move the whole integration into Twodsix like you have for OSE.  I'll let you know when Twodsix is updated.

**Comment by marvin9257** [comment]
OK...I've updated the Twodsix system to include the full configuration per above.  You can probably delete the system file for it in this repro.  Thanks Again for all the help!
