### ISSUE TITLE
[BUG] - createItemPile creates an item pile in the DM's scene instead of the macro executor's

### ISSUE THREAD

**Issue by Eliasar** [fantasycalendar/FoundryVTT-ItemPiles#32]
**Describe the bug**
When using the `ItemPiles.API.createItemPile` as a player (and not the DM account)

**To Reproduce**
1. Have two accounts logged in: one of which is the DM account
2. Have the DM and non-DM accounts be on separate scenes
3. As the non-DM account, create a macro, setting the type to "script"
4. Paste the following code - `ItemPiles.API.createItemPile({ x: 0, y: 0 });`
5. As the non-DM account, execute the script
5. Item pile will be on the DM's scene and not the player's scene who ran the script

**Expected behavior**
An item pile to be created on the player's scene

**Setup:**
 - Foundry Version: [version 9, Build 242]
 - Item Piles Version: [1.1.2]
 - OS: [Windows 10]
 - Browser [Firefox, 96]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment]
Thank you for the report, this is most definitely unintended, thank you.

**Comment by Haxxer** [comment]
Fixed in 1.2.0
