### ISSUE TITLE
[BUG] - [PATHFINDER 1E] - Item-Piles Interface opens automatically after I move it's token on the map.

### ISSUE THREAD

**Issue by Icarus-Mods** [fantasycalendar/FoundryVTT-ItemPiles#321]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
After having updated Item-Piles for the first time in a few months, I started noticing that whenever i would drag the token of an item pile or merchant on my canvas, it would immediately open the item pile/merchant interface the moment i would let go of the token.
I've tested this without other modules installed as well (except for the ones required by item-piles) and the result appears to be the same. I've searched through the settings and options, but I've not found a feature or toggle that lets me turn off this behavior.

**To Reproduce**

1. Create a new NPC character sheet.
2. Turn it into an item-pile or merchant.
3. Drag it onto the canvas/map.
4. Move the token around, upon letting go of the token, the item-pile/merchant interface will open.

**Expected behavior**
The expected behavior would be that i can move the tokens of item-piles/merchants around without them automatically opening once i let go of them.

**Screenshots**
I didn't feel any would be applicable here.

**Setup:**

- Foundry Version: [10.291]
- System Version: [Pathfinder 1, 0.82.5]
- Item Piles Version: [2.5.7]
- Browser & version [I run FoundryVTT from a local instance, although when playing and not hosting myself I use Google Chrome Version 111.0.5563.111]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional Information**
*Edited to add the following information.*
Upon further troubleshooting and testing, I've found out the interface is also opened for everyone connected to the client, not just the person moving the item-pile/merchant. And it also happens when an item is bought or sold through the merchant interface.

**Comment by Icarus-Mods** [comment]
> Appears to be a PF1e issue:
> 
> https://discord.com/channels/170995199584108546/711278873047859201/1090179779157827665

Awesome, thanks for figuring out the issue. Good to see a fix has already been made for it. ^^

**Comment by Haxxer** [comment]
Adjusted in 2.5.8
