### ISSUE TITLE
When using Levels, Player Tokens can see Item Piles because the elevation constantly displays

### ISSUE THREAD

**Issue by rtschaefer** [fantasycalendar/FoundryVTT-ItemPiles#323]
Just really quick... When I set a token attributes to "Never show resources" There is no way players should be able to see the elevation marker in the resource hub around a token. But unfortunately, tokens that are designated as an Item Pile constantly illuminate the token's elevation across the entire scene to players, making it impossible to discretely position loot items unless I make it invisible. 

I have tried everything I can think of including shared vision settings, levels module settings, etc.   Anyway you can tweak the module so it does not telegraph elevation to all god's creation? :-)    

This is such a fantastic module! I am just whining. lol  

Here is an image of what I am talking about. The player can tell that I am hiding loot inside of a wall. 

![ITEM PILE ISSUE](https://user-images.githubusercontent.com/95512317/228404207-2658bf29-cfb1-4ddb-b1d6-913851bb2632.png)

**Comment by Haxxer** [comment]
@rtschaefer Without Item Piles enabled, if you place a token outside of the view of players and set the token's elevation, is it still visible?

**Comment by Haxxer** [comment]
And in the future, **please** use the bug template.

**Comment by Haxxer** [comment]
@rtschaefer Have you seen the above?
