### ISSUE TITLE
[CONFLICT] Item Piles and OBS Utils use the same CSS name for custom settings menus

### ISSUE THREAD

**Issue by 9ryex5** [fantasycalendar/FoundryVTT-ItemPiles#324]
The conflict is described [Here](https://github.com/FaeyUmbrea/obs-utils/issues/115)
![image](https://user-images.githubusercontent.com/43207603/228821532-ba002db2-485a-4aa2-8a6f-f17ff9a445e2.png)

**Comment by Haxxer** [comment]
What class is causing the conflict? None of the tickets mention it :D

**Comment by FaeyUmbrea** [comment]
the "settings" class, might have been a bit ambiguous in my reply in the other ticket

**Comment by Haxxer** [comment]
@FaeyUmbrea thanks - I'll scoped mine to the item piles in a future update, may be good to do so on your side as well

**Comment by FaeyUmbrea** [comment]
@Haxxer I'll do the same in the next update

**Comment by Haxxer** [comment]
Fixed in 2.6.0
