### ISSUE TITLE
[REQUEST] - Add Delete Button to "Buy Items" and/or Add Scroll to Populate Items

### ISSUE THREAD

**Issue by coolfox09** [fantasycalendar/FoundryVTT-ItemPiles#329]
**Is your feature request related to a problem? Please describe.**
I have a one-stop-shop sort of deal with one NPC selling all sorts of wares and I love the way this module works! Unfortunately the only way to remove items from the store from what I can see is by deleting off of the "Populate Items" menu which does not scroll and eventually gets cut-off with no way to select later items unless i delete earlier items and it's a hassle (screenshots below)

**Describe the solution you'd like**
I would love if we could have a delete button that's viewable to GMs only similar to the other buttons in the "Buy Items" section that way we can simply just delete them right there. If that's not possible, it'd be nice instead as well to have the "Populate Items" section scroll. If both were possible, that would be great. 

**Describe alternatives you've considered**
At the moment these are the solutions I think make the most sense. 

**Additional context**
Attached are some screenshots: 

![image](https://user-images.githubusercontent.com/3613208/230750966-b1f9ec87-1648-46f1-9a6d-d7c106d7e7a4.png)
![image](https://user-images.githubusercontent.com/3613208/230750994-909d5ed5-f77a-4059-8c3e-ba632edbb616.png)

**Comment by Haxxer** [comment]
Fixed in 2.6.1
