### ISSUE TITLE
[REQUEST] - Drop currency into pile

### ISSUE THREAD

**Issue by playest** [fantasycalendar/FoundryVTT-ItemPiles#33]
**Is your feature request related to a problem? Please describe.**
We can drop items into a pile but not currency.

**Describe the solution you'd like**
Next to the "take" button we could have a "put" button that would open a window to put more currency into the pile.

**Describe alternatives you've considered**
Or when we drop an item named "Currency" it could ask the player how much currency they want to drop instead of actually transferring the currency item.

**Comment by Haxxer** [comment]
Added in 1.3.0
