### ISSUE TITLE
[BUG] - [SYSTEM NAME] - Merchant per-type cost modifier override doesn't work with custom categories

### ISSUE THREAD

**Issue by ronin-seven** [fantasycalendar/FoundryVTT-ItemPiles#330]
I have an armorsmith merchant with armor sorted into weight categories using custom item category.  Prices are marked up by 150% globally and when I try to set a per-type cost modifier for the Light Armor category, the prices are not updated:
![image](https://user-images.githubusercontent.com/47235915/230754819-f8764a2b-7ba1-48e9-b813-0965fe8e5a5a.png)

If I remove the custom category and set the cost modifier for the default category, prices are updated for **all** armor:
![image](https://user-images.githubusercontent.com/47235915/230754893-52beb955-a208-4676-95fc-d4b53a54d327.png)

Tested with only Item Piles and dependencies enabled.

Edit: screenshots above are from 2.5.8 but I was also able to reproduce with 2.6.0

- Foundry Version: 10.291
- System Version: 2.1.5
- Item Piles Version: 2.6.0
- Browser & version: Google Chrome 111.0.5563.148

**Comment by ronin-seven** [comment]
Overriding the custom category price modifier using the Item Type Price Modifiers menu works as expected:
![image](https://user-images.githubusercontent.com/47235915/230756219-9c539658-1685-43f0-8491-44e1c6543fd0.png)

**Comment by Haxxer** [comment]
Did you save the item piles' configuration afterwards? Did editing the price modifier in the merchant work after that?

**Comment by Haxxer** [comment]
![image](https://user-images.githubusercontent.com/12858387/230776061-127be39e-e7c0-4623-91cf-b7a4ba3fafe2.png)

**Comment by ronin-seven** [comment]
Yeah, I have no idea what I'm missing here.  I've tried clicking "Update" after adjusting the global modifier (which updates the prices in real-time as I slide the notch), closing the UI, hitting F5 and then setting the override modifier (nothing changes in real-time).  Tried clicking "Update", closing and re-opening.  The override checkbox is still checked but the price reflects the global price.

No worries, I can use the alternate method but thanks for taking the time to check, appreciate it!

**Comment by Haxxer** [comment]
Try recreating the custom price modifier for the custom type. It might just be bugged.

**Comment by ronin-seven** [comment]
I was testing in an empty debug world with newly created merchant characters, so it's probably just me :P

**Comment by Haxxer** [comment]
Fixed in 2.6.1
