### ISSUE TITLE
[BUG] - [SYSTEM NAME] - Describe bug here

### ISSUE THREAD

**Issue by LonePaladin** [fantasycalendar/FoundryVTT-ItemPiles#334]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
PF2e allows you to "mystify" an item, replacing the name with "Unusual Item" or something similar. If you drag a mystified item to the map, the token it creates has the item's normal name. If you open it, the item listed has the mystified version, and it remains mystified when it's moved to someone's inventory.

**To Reproduce**

1. Open a token's inventory.
2. Select an item, and click on the (?) icon to "mystify" it. A magic amulet, for example, would change to "Unusual Object". Its icon changes to a gray shape with a question mark in it.
3. Drop the mystified item on the map; the item's original icon appears, with the original name.

**Expected behavior**
The token's name should honor the identified/unidentified status.

**Screenshots**
Original item:
![image](https://user-images.githubusercontent.com/37523352/231318654-4ce7a3ff-297b-4cf0-add1-a02564e18261.png)

Click on the (?) icon to "mystify" it:
![image](https://user-images.githubusercontent.com/37523352/231318719-0655b331-4857-48df-9daa-39f78b0ea0a4.png)

Drag it onto the map:
![image](https://user-images.githubusercontent.com/37523352/231318758-d325e081-9c5f-4cad-b721-d564bb249d34.png)

Open the pile:
![image](https://user-images.githubusercontent.com/37523352/231318847-d19f781d-1fa2-419d-a27e-27ca29da10b2.png)

**Setup:**

- Foundry Version: 10.291
- System Version: PF2e v4.10.4
- Item Piles Version: 2.6.4
- Browser & version: Foundry Client

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Tested with no other modules active

**Additional context**
It also appears that the item pile token is staying around even when empty, but that might be because I'm looking at it as a GM.

**Comment by Haxxer** [comment]
Fixed in 2.6.5
