### ISSUE TITLE
[BUG] - [PF2e] - Describe bug here

### ISSUE THREAD

**Issue by sorrythatuserbla** [fantasycalendar/FoundryVTT-ItemPiles#335]
**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
Configure Actor Price Modifiers not possible, throws bugs, will not save the data.

**To Reproduce**

Create new pf2e world.
Enable item-piles (which will enable socketlib and lib-wrapper also)
create 2 actors -> Type: Loot & Type: player character
open loot actor and click configure
Enable red exclamation mark enabled setting.
Switch to "other settings"
change item pile type to merchant
Click configure actor price modifier
drag and drop player char
click Save
click Update Item Pile
-> Error

**Expected behavior**
Configure Actor Price Modifiers possible / will not throw errors.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/78597675/231498561-1fd849c6-af08-4f5f-9aac-6ee9eec4f9fb.png)

**Setup:**

- Foundry Version: 10 / 291
- System Version: PF2e 4.10.4
- Item Piles Version: 2.6.4
- Browser & version Google Chrome 111.0.5563.147

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**

**Comment by Haxxer** [comment]
Fixed in 2.6.5
