### ISSUE TITLE
[REQUEST] Option to automatically add contents of rolled tables to custom category

### ISSUE THREAD

**Issue by Janner3D** [fantasycalendar/FoundryVTT-ItemPiles#336]
![image](https://user-images.githubusercontent.com/35965176/231564745-aded8f91-46fe-44cc-a3c9-b5550e70a0ca.png)
![image](https://user-images.githubusercontent.com/35965176/231564888-2859719b-416b-4f88-a75e-d1d748ed85ca.png)
It would be extremely handy if one were able to automatically assign items rolled from a specific roll table to a custom category.

Say, for example, I had a roll table called "Alchemy Components". If I rolled that table, all of the items added from that table were automatically given the appropriate custom category tag of "Alchemy Components".

**Comment by Haxxer** [comment]
Added in 2.6.8 as a separate input on each table added to a merchant
