### ISSUE TITLE
[BUG] - [PF2E] - Roll options not saved for rollable tables added to merchants

### ISSUE THREAD

**Issue by weepingminotaur** [fantasycalendar/FoundryVTT-ItemPiles#337]
No matter what I input in the roll option field for a rolltable -- a dice expression, like 1d20, or a flat number, like 5 or 10 -- the change is not saved when I close the merchant. There are no console errors; the roll option is simply not saved and always reverts back to the default (1d4).

I have tested this on a blank PF2E world running nothing but Item Piles, libWrapper, and Socketlib. Hosting: The Forge. Browser: Google Chrome for Mac Version 112.0.5615.49. PF2E 4.10.4, Item Piles 2.6.7.

**Comment by Haxxer** [comment]
Fixed in 2.6.8
