### ISSUE TITLE
[BUG] - [SFRPG] - Items dropped onto the canvas appear but don't contain the item

### ISSUE THREAD

**Issue by ian612** [fantasycalendar/FoundryVTT-ItemPiles#338]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Whenever an item is dragged from the equipment list, a compendium, or an actor sheet to the canvas, the item pile appears but does not contain the dropped item. It throws an error message in the console (below), and then any further items dropped to the canvas do not appear or throw any messages to the console at all until the browser is refreshed.

**To Reproduce**

1. Drag any item to the canvas.
2. Choose a quantity and create the pile
3. Double click to open the item pile, no items are present

**Expected behavior**
When items are dropped onto the canvas, an item pile is created with the specified quantity of that item inside it.

**Screenshots**
![image](https://user-images.githubusercontent.com/34078802/231928786-b090e335-f480-4762-af3d-b41e3e37993b.png)

**Setup:**

- Foundry Version: 10.291
- System Version: sfrpg 0.23.0
- Item Piles Version: 2.6.7
- Browser & version: Firefox 111.0.1 & Foundry Light Client 2.9

**Active modules:**

- Item Piles
- libwrapper
- socketlib
Issue appears on clean world with only these modules active

**Additional context**

**Comment by Haxxer** [comment]
Fixed in 2.6.8
