### ISSUE TITLE
[REQUEST] - Image/Sound Default

### ISSUE THREAD

**Issue by brunocalado** [fantasycalendar/FoundryVTT-ItemPiles#34]
Hi. Amazing job!

Can you add presets to chest image and sounds? So, you can just choose a preset defined in the module settings an apply it to the pile.
![image](https://user-images.githubusercontent.com/4999783/149596140-27d8d457-c2f5-40b0-968a-ccf52a473a43.png)

tks

**Comment by Haxxer** [comment]
Have you tried to modify the default pile?

**Comment by brunocalado** [comment]
> Have you tried to modify the default pile?

What do you mean? I did that to one. But, every new dropped item I have to set all over again.

**Comment by Haxxer** [comment]
Did you do it to the token, or to the actor in the actor list?

**Comment by brunocalado** [comment]
I found out. Thank you.
