### ISSUE TITLE
[BUG] - [PF1e] -Merchant pile services tab constrained rendering

### ISSUE THREAD

**Issue by GaistH** [fantasycalendar/FoundryVTT-ItemPiles#340]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
For some reason on the services tab it seems to be boxing the inventory in without using the full window such that when I do a pulldown with multiple currency options, it adds a scroll bar instead of just laying it out the full measure.  Item buying tab doesn't do this, just the services tab.

**To Reproduce**
Create a 'service' item for a merchant to sell with multiple currencies.

**Expected behavior**
Rendering using the full available window space.

**Screenshots**
https://i.imgur.com/qvlrJoH.png

**Setup:**

- Foundry Version: 10.291
- System Version: PF1e 0.82.5
- Item Piles Version: 2.6.4
- Browser & version N/A (using directly from Foundry client)

**Comment by Haxxer** [comment]
Fixed in 2.6.8
