### ISSUE TITLE
[BUG] - [DnD5e] - Split currency button disabled when currency sharing disabled and split currency enabled

### ISSUE THREAD

**Issue by ronin-seven** [fantasycalendar/FoundryVTT-ItemPiles#342]
**Have you tried to reset Item Piles' system settings?**
Reproduced in a fresh world with no existing IP data

**Describe the bug**
The split currency button is present but disabled when currency sharing option is disabled and split currency option is enabled.
![image](https://user-images.githubusercontent.com/47235915/232232324-cce99a49-148f-48c3-9790-a3ab50985864.png)

**To Reproduce**
Configure container item pile as above.

**Expected behavior**
Split currency button should be enabled.

**Setup:**

- Foundry Version: 10.291
- System Version: DnD5e 2.1.5
- Item Piles Version: 2.6.7
- Browser & version: Chrome 112.0.5615.121

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Fixed in 2.6.8
