### ISSUE TITLE
[REQUEST] - Add "Protected" toggle option to merchant items so they aren't deleted shop is refreshed 

### ISSUE THREAD

**Issue by weepingminotaur** [fantasycalendar/FoundryVTT-ItemPiles#343]
Would be great to be able to protect certain items from being deleted when the shop is refreshed (when the GM clicks Clear All Actor Items or when the shop auto-refreshes inventory, if/when the latter becomes possible). Leaving a github request here because you'd indicated in Discord chat that it was a decent idea. :)

**Comment by Haxxer** [comment]
This will become a feature in 2.6.9 together with https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/135

**Comment by Haxxer** [comment]
Done in latest update
