### ISSUE TITLE
[BUG] - [PF2E] - Item inspection doesn't respect PF2E's mystification system.

### ISSUE THREAD

**Issue by LKLani** [fantasycalendar/FoundryVTT-ItemPiles#346]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
PF2E contains an item 'mystification' system which is primarily used for unidentified items. Items can be toggled between mystified/unmystified.

When using the item inspection option in Item Piles, clicking on a mystified item will display info for the unmystified item details, revealing what it is. It should show the mystified version of the item.

**Setup:**
- Foundry Version: 10.291
- System Version: PF2E 4.11.0
- Item Piles Version: 2.6.8
- Browser & version: MS Edge 112.0.1722.58

**Active modules:**
- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
This is a limitation with PF2e, not item piles. PF2e does not normally render mystified item sheets, so it is best to turn off the feature.

**Comment by LKLani** [comment]
PF2E does allow for display of mystified items on its native loot sheets. I assume this is an implementation that item piles can't duplicate?
![image](https://user-images.githubusercontent.com/75685325/234900478-2ccb04bb-9c09-4d07-ad63-802259bffe20.png)

Thanks for your patience.

**Comment by Haxxer** [comment]
Could you please provide screenshot of the original bug?

What you are showing is expanding the entry of an item in an existing window. When clicking on the name of an item in item piles, it renders a full separate window. PF2e does not do that with regular items, thusly, they have not implemented support for mystified items rendered in a separate window while hiding its details.

Item Piles relies on the system handling edge cases like this, as we cannot support 30+ systems and still consider every edge case for every system.

**Comment by Haxxer** [comment]
Added support for this in 2.6.12
