### ISSUE TITLE
[BUG] - [PF2E] - Take All is broken for currency

### ISSUE THREAD

**Issue by gridstop** [fantasycalendar/FoundryVTT-ItemPiles#348]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Attempting to use Take All on a Item Pile containing currency in PF2E causes a TypeError: source.type is undefined.

**To Reproduce**
Create an Item Pile and place some amount of currency on it.
Disable the Sharing Enabled: Currencies (normally enabled by default) for the Item Pile
Enable the Take All button for the Item Pile

Open the Item Pile UI by double-clicking as a player or as GM with inspectingTarget set to a player.

Press the Take All button and note that nothing happens. See log for the error.

**Expected behavior**
The currencies and items should be moved to the player or to the inspectingTarget actor. Note that this works correctly for any number of stacks of items of any size, the error is only when adding currencies.

**Screenshots**
![item_pile_currency_error](https://user-images.githubusercontent.com/783880/235377659-0001280a-acc7-4e98-a5f9-9434ef867dc4.png)

**Setup:**
- Foundry Version: 10.291
- System Version: PF2E 4.11.1
- Item Piles Version: 2.6.8
- Browser & version - No difference on Firefox or Chromium

**Active modules:**
- Item Piles
- libwrapper
- socketlib
- PF2E Abomination Vaults
- Drag Ruler
- Illandril's Token Tooltips
- PF2E Workbench
- Quick Insert - Search Widget

**Comment by gridstop** [comment]
Note you get the same error when invoking transferEverything like so from macro:
`game.itempiles.API.transferEverything(token.actor, "Actor.3a18aOCP9mDPNLNQ")`

Also you can use the individual 'Take' button by each item of currency to transfer that individual currency one at a time. To take all the gold, then all the copper, etc... until all the currencies are gone, and then Take All works as expected.

**Comment by Haxxer** [comment]
Fixed in 2.6.12
