### ISSUE TITLE
[REQUEST] - allow players to swap between their owned tokens to interact with the pile

### ISSUE THREAD

**Issue by dmrickey** [fantasycalendar/FoundryVTT-ItemPiles#35]
**Is your feature request related to a problem? Please describe.**
For my players, I created an extra actor named "group loot" that they all have access to. Any loot that isn't claimed by an individual player goes into the "group loot" actor. When they're done with their current escapades they sell it all off. The interface for Item Piles is awesome. It's a much better interface for looting than the default experience in PF1. But what's tedious would be to have to claim everything into the player inventory, then manually transfer that into a different inventory.

**Describe the solution you'd like**
Once I've interacted with an Item Pile, I'd like to be able to swap actors that I'm inspecting as. So if I'm a player that owns multiple tokens, after I've already opened the container, I'd like to be able to swap the actor I'm inspecting it with
![image](https://user-images.githubusercontent.com/3664822/149616191-6c66a41c-9c18-4b8c-92e0-811b4c9f64b0.png)
(edited the html to show an example, probably should add a label to the select)
I know there's an interaction distance imposed on the loot--I propose that this dropdown bypass that. This could potentially allow the player to cheat if they have more than one real actor by letting them loot the pile with a different actor that's actively playing. My reasoning is that the player already moved a token over to the loot. At this point the player has access to it. If the player wanted to cheat, then they can simply transfer items after being looted into the first character (heck, the player could add whatever items they wanted to themselves without Item Pile if they wanted to cheat). So basically the player has already overcome "the obstacle" by getting to the Pile. At this point they should be able to put the loot wherever they want and not have to play "Inventory Management Simulator" by juggling loot between characters.

**Comment by Haxxer** [comment]
Added in 1.3.0
