### ISSUE TITLE
Merchant - pc selling not working?

### ISSUE THREAD

**Issue by arcanjl** [fantasycalendar/FoundryVTT-ItemPiles#353]
I must be doing something wrong. when I open a merchant as a PC, drag an item to the merchant: Inventory goes up by one on the merchant. The item does not disappear on the selling PC, and they don't receive gold. :)

**Comment by Haxxer** [comment]
You sell through the sell tab, not by drag and dropping.

**Comment by arcanjl** [comment]
/Facepalm
Thank you.
