### ISSUE TITLE
[BUG] - [DnD5e] - Can't see merchant currency when Infinite Currencies = OFF

### ISSUE THREAD

**Issue by hacky2007** [fantasycalendar/FoundryVTT-ItemPiles#356]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When infinite currencies is turned OFF, I am not able to see the merchant's current gold.

**To Reproduce**

1. I created a new NPC, and opened their sheet
2. I hit Configure Pile
3. I went to Other Settings and changed them to a merchant
4. While there I turned Infinite Currencies OFF
5. I went back to Main Settings, hit enabled
6. Then hit Update Item Pile
7. I opened the merchant screen and I could NOT see the merchant's current currency

**Expected behavior**
Since Infinite Currencies is OFF, I would expect to see the merchant's current currency amount and let me edit it as GM

**Screenshots**

**Setup:**

- Foundry Version: 10 - 291
- System Version: DND5e 2.1.5
- Item Piles Version: 2.6.11
- Browser & version Google Chrome 113.0.5672.93

**Active modules:**
Reproduced with just the 3 below
- Item Piles
- libwrapper
- socketlib

**Additional context**
It seems like a flag is just working in reverse. I tried doing some searching in the JS file but wasn't able to see where the flag might be set backwards.

**Comment by Haxxer** [comment]
Fixed in 2.6.12
