### ISSUE TITLE
[BUG] - [SYSTEM NAME] - Vault Sheet doesnt seem to check for stored currency

### ISSUE THREAD

**Issue by Wood-ruff** [fantasycalendar/FoundryVTT-ItemPiles#357]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
It seems like the Vault sheet doesnt check the currently stored gold, as long as its in the positives

**To Reproduce**
-Make a sheet be a vault
-Put some currency in the vault, amount doesnt matter, as long as its positive
-withdraw currency without using the slider, insert manually any amount that exceeds the currently stored amount,
-you cannot withdraw more money, but you just printed a custom amount of currency

**Expected behavior**
well, it probably should just check if the stored amount is lower than whats being tried to withdraw, probably an easy fix

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/47525871/a6e340ae-5c8b-4fc7-858e-c78f19795772)

**Setup:**

- Foundry Version: 10.291
- System Version: PF1e
- Item Piles Version: 2.6.11
- Browser & version: Chrome

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Fixed in 2.6.12
