### ISSUE TITLE
[BUG] - [Pathfinder 2e] - Quick Insert brakes item piles

### ISSUE THREAD

**Issue by ObliquityInfinity** [fantasycalendar/FoundryVTT-ItemPiles#358]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
The moment you search for items in quick search, all item pile windows break and don't function till you refresh

**To Reproduce**

1. Use keybind to open Quick search
2. Search any item
3. Open any item pile

**Expected behavior**
Item pile windows to open as normal

**Setup:**

- Foundry Version: 10.291
- System Version: 4.11.2
- Item Piles Version: 2.6.12
- Browser & version: Google Chrome

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Quick Insert - Search Widget

**Additional context**
Obviously they are 2 different modules, so I don't really expect this to be prioritized, but man does using quick insert to get items into an item pile make things so much easier.

**Comment by Haxxer** [comment]
Can you please include the error?

**Comment by ObliquityInfinity** [comment]
Apologies, but no error seems to pop up when it occurs. I have warnings and errors on in console.
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/133592645/b5ff49ac-09b3-4fd3-80fa-b2e89e191c53

**Comment by ObliquityInfinity** [comment]
> Apologies, but no error seems to pop up when it occurs. I have warnings and errors on in console. https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/133592645/b5ff49ac-09b3-4fd3-80fa-b2e89e191c53

And the yellow warning is for something else, I believe. I only have the modules above enabled for this clip.

**Comment by Haxxer** [comment]
Fixed in 2.6.13
