### ISSUE TITLE
[REQUEST] - Sharing Settings'

### ISSUE THREAD

**Issue by LtDerek** [fantasycalendar/FoundryVTT-ItemPiles#359]
Currently if you don't like the default sharing settings (currency is automatically split between players, but items are not). Then you have to manually configure every item pile you create.

It would be nice if you could change the defaults via the module settings.

**Comment by Haxxer** [comment]
You can change the default item pile actor settings, and every created item pile uses that.

**Comment by Haxxer** [comment]
Please do read the wiki, it goes over this concept:)

**Comment by LtDerek** [comment]
Ah, my bad. I did miss that.

But it doesn't fully solve the problem, which is that Actors you turn into item piles (Aka, enemies that the party want to loot) still need to manually set up.

**Comment by Haxxer** [comment]
Are you using some module for that or something?

**Comment by Haxxer** [comment]
You could always use a macro:

https://fantasycomputer.works/FoundryVTT-ItemPiles/#/sample-macros?id=make-tokens-lootable

**Comment by LtDerek** [comment]
Ah, thank you, previously I would just click 'configure' and then tick make an item pile. This is faster and solves the problem of default sharing. Thank you.
