### ISSUE TITLE
[Compatibility] Token Replacer and Item Piles don't work together

### ISSUE THREAD

**Issue by brunocalado** [fantasycalendar/FoundryVTT-ItemPiles#36]
Hi. Great module!

Item Piles don't work with Token Replacer. They generate an error together. 

I don't know which module should patch it. But, I'm reporting.

Thank you.
**Screenshots**
![image](https://user-images.githubusercontent.com/4999783/149622837-27a5104f-7e6d-4a7b-b351-c63e9df4e706.png)

**Setup:**
 - Foundry Version: 9.242
 - Item Piles Version: 1.1.3
 - OS: win10
 - Browser chrome

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 Token Replacer

issue on token replacer: https://github.com/vtt-lair/token-replacer/issues/86

**Comment by Haxxer** [comment]
Does TokenReplacer work on its own?

**Comment by Haxxer** [comment]
Fixed in latest token replacer version
