### ISSUE TITLE
[BUG] - [D&D] - items imported from a compendium table lose their individual settings.

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-ItemPiles#360]
**Have you tried to reset Item Piles' system settings?**
Yes / No

**Describe the bug**
Items imported from a compendium table lose their individual settings. ex: setting an item with a custom category back to its default category.
I didn't test all the settings, however the ones I use (custom category and keep in merchant) are reset to their default settings.

**To Reproduce**

1. create an item and modify its category.
2. import the item into a compendium
3. create a table with this compendium item.
4. import this table into a compendium to be used in the populate item.
5. roll the table and enter the item the merchant.

- The item will be added without the changes.

**Expected behavior**
the item must be added with its properties set on the item.

**Setup:**

- Foundry Version: [10.291]
- System Version: [DND5e 2.1.5]
- Item Piles Version: [2.6.12]

**Comment by Haxxer** [comment]
Fixed in 2.6.13
