### ISSUE TITLE
[BUG] - [5e] problems with merchants and changing the short name of currency

### ISSUE THREAD

**Issue by Orionox** [fantasycalendar/FoundryVTT-ItemPiles#361]
**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
If you change the "short" name of a currency, when placing an item with a denomination that has been changed, the value defaults to the primary currency at a 1-to-1 rate. So an item that is 1 cp, will cost 1 sp if copper had its short named changed and silver is the primary currency. 

**To Reproduce**
Make a test item, set value to 1 ep
Put item into a merchant., it should show the value as 1 ep.
Open Item pile configuration, open configure currency change the "short" name of "EP" to whatever you want. I chose CB.
Close and re-open merchant. Instead of the value now showing "1 CB," which you'd expect since all you did was change the "EP" to "CB." Instead it will show the value as 1 GP

**Expected behavior**
The "1 EP" cost of the item in the shop should have changed to 1 CB, when I changed the short name of EP to CB. 

**Setup:**
- Foundry Version: 10.291
- System Version: 5e 2.1.5

**Active modules:**
Compendium Folders
D&D5e - System Customizer
Find the culprit
Item Piles
libWrapper
socketlib
Module Management+
World Currency 5e

**Comment by Haxxer** [comment]
It is due to this code: https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/master/src/systems/dnd5e.js#L45-L57

In essence, if it cannot find the `EP` currency, it ignores it. I don't know what would be the best way around this, given it is the system's actual currency.

**Comment by Orionox** [comment]
> It is due to this code: https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/master/src/systems/dnd5e.js#L45-L57
> 
> In essence, if it cannot find the `EP` currency, it ignores it. I don't know what would be the best way around this, given it is the system's actual currency.

so, I just shouldn't rename any of the base currency? it does get pretty wonky when messing around with currency what it ends up doing.

**Comment by Haxxer** [comment]
Fixed in 2.6.13
