### ISSUE TITLE
[BUG] - Inspecting a merchant as a token issues

### ISSUE THREAD

**Issue by Txus5012** [fantasycalendar/FoundryVTT-ItemPiles#362]
**Have you tried to reset Item Piles' system settings?**
Yes. Also tried in a new fresh world.

**Describe the bug**
When dragging an actor to a merchant the game breaks. Can't interact with the merchant's window or even close it.
Refreshing (F5) is the only way to continue.

**To Reproduce**

1. Create a merchant.
2. Drag an actor to the merchant's window.
3. See that you can't change the merchant's tab or close the window. The message of "inspecting as" isn't shown.

**Expected behavior**
Inspecting a merchant as a token should work as it did.

**Screenshots**
Console error when dragging the actor:
![Merchant Error](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/87753744/f859e368-fa89-47e9-93c8-ff6b453ae293)

**Setup:**

- Foundry Version: 10.291
- System Version: WFRP4e 6.5.3, AGE System (unofficial) 1.2.4
- Item Piles Version: 2.6.12
- Browser & version: Foundry app.

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
Inspecting item piles, containers and vaults as a token works well.
Players can use the merchant normally.

**Comment by Haxxer** [comment]
Fixed in 2.6.13
