### ISSUE TITLE
[BUG] - [DND5e] - Item Piles causing tooltips to get stuck

### ISSUE THREAD

**Issue by M0nk3yy** [fantasycalendar/FoundryVTT-ItemPiles#367]
**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
When hovering over a "Save" button, a tooltip appears. Acfter clicking Save with Item Piles enabled, moving the mouse away from the button does not cause the tooltip to fade out. Instead it gets stuck on screen until a new tooltip is generated by hovering something else.

**To Reproduce**

1. Go to a character sheet.
2. Choose an inventory item to edit.
3. Edit its description.
4. Click "Save and Close Editor" button and do not move mouse.
5. The tooltip will not fade out, even if the item window is closed, until a new tooltip is created.

**Expected behavior**
With Item Piles disabled, the tooltip should fade in the normal amount of time.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/66137312/74a5d30e-4e46-4eb9-968b-de9d76d04033)

**Setup:**

- Foundry Version: v10.291]
- System Version: DND5e 2.1.5
- Item Piles Version: 2.6.12
- Browser & version: Foundry app

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
Whilst the screenshot above shows a world with mods, this is reproducable in a world with only Item Piles and depencies.

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/66137312/7c33b5eb-e73b-43f7-a5a8-bc49174f339c)

**Comment by Haxxer** [comment]
Does this happen without item piles installed? I've seen tooltips get stuck in vanilla dnd5e

**Comment by M0nk3yy** [comment]
I cannot recreate this in a world with no modules.

**Comment by Haxxer** [comment]
Fixed in 2.6.13
