### ISSUE TITLE
[SYSTEM] - Tormenta 20

### ISSUE THREAD

**Issue by brunocalado** [fantasycalendar/FoundryVTT-ItemPiles#37]
**[INSERT FOUNDRY PAGE LINK TO SYSTEM HERE]**
https://gitlab.com/vizael/Tormenta20

### **Dynamic Attributes**:

- **Name**: Ouro
    - **Path**: data.dinheiro.to
    - **Image**: icons/commodities/currency/coin-embossed-insect-gold.webp
- **Name**: Prata
    - **Path**: data.dinheiro.tp
    - **Image**: icons/commodities/currency/coin-embossed-unicorn-silver.webp
- **Name**:Cobre
    - **Path**: data.dinheiro.tc
    - **Image**: icons/commodities/currency/coin-engraved-waves-copper.webp

**Comment by Haxxer** [comment]
Added in 1.2.0, thank you

**Comment by brunocalado** [comment]
THank you!
