### ISSUE TITLE
Automatic default name on an item dropped from player

### ISSUE THREAD

**Issue by JoueurSansFromage** [fantasycalendar/FoundryVTT-ItemPiles#371]
**Is your feature request related to a problem? Please describe.**
When you drop a single item, the item pile name could automatically have the name of the single item in it.

**Describe the solution you'd like**
When a player drops "Bob's Backpack" on the game canvas, the item pile is automatically called "Bob's Backpack".

**Describe alternatives you've considered**
I change the token name on the canvas manually when a backpack is dropped

**Additional context**
I'm using Variant Encumberance, so players drop their backpack if they're encumbered in combat. When they go for their backpack, I want to reduce confusion as to which token is their's

**Comment by JoueurSansFromage** [comment]
I would also love for item piles to have by default a HP formula (Can simply be 1d1HP), because it creates an error message with other modules (Token Mold in this instance) since the HP is not defined.

**Comment by Haxxer** [comment]
Have you looked into the Default Item Pile character in the sidebar. All that you are describing is possible. I recommend you read the wiki.
