### ISSUE TITLE
Cannot access any Items, Journals, or Actors after update.

### ISSUE THREAD

**Issue by R0gu3P403n1x** [fantasycalendar/FoundryVTT-ItemPiles#372]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
After updating to ver 2.6.14 I no longer have access to any entries in the Actors, Items, or Journals tabs of Foundry.  The entries are there, but clicking on them does nothing.  Right clicking does still all the altering of ownership or anything else normally associated with the right click.  Left click does nothing however.

**To Reproduce**

1. Install and activate item piles 2.6.14
2. Click on 'any entry in Actors, Journals, or Items'
3. See error

**Expected behavior**
I expect to see the normal sheet associated with the entry clicked on.
**Screenshot**
![Screenshot (28)](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/38843279/5b81dde3-1ba4-4a19-8b40-d258cfad313e)
![Screenshot (29)](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/38843279/f3720f6a-04d3-488d-831a-257a139ddbca)

**Setup:**

- Foundry Version: 10.291
- System Version: PF1E ver 0.82.5
- Item Piles Version: 2.6.14
- Browser & version N/A

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
First screenshot is with usual modules installed, second is with ONLY Item Piles, libwrapper, and socketlib active.

**Comment by diwako** [comment]
Same issue, same version in foundry and item piles. Different system tho.

**Comment by rwanoux** [comment]
same issue :
happens when user isGM;
fresh new empty world

Setup:

Foundry Version: 10.291, node
System Version: dnd5e 2.1.5
Item Piles Ve
rsion: 2.6.14
Browser & version brave browser

Active modules:

Item Piles
libwrapper
socketlib

![Screenshot_7](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/18176317/3355853a-e5e5-453a-919f-363ab8fe5adb)

**Comment by Haxxer** [comment]
Thank you all for the information. The error is system agnostic, no need to post any more.
