### ISSUE TITLE
[BUG] - [D&D5e] - Services not showing up in populate items

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-ItemPiles#374]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
service items are not being listed in populate items, to remove them you need to enter the sheet

**To Reproduce**
populate a merchant with a rolling table of service items

**Expected behavior**
list the services to be able to manage them

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/3178127/807a9999-cea2-450a-88db-403b348ec818)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/3178127/bac72ff8-5fc6-47aa-8f54-c413b70360ed)

**Setup:**

- Foundry Version: [10.291]
- System Version: [DND5e 2.2.1]
- Item Piles Version: [2.6.16]
- Browser & version Vanilla and Chrome

**Comment by rinnocenti** [comment]
Testing a little more, what does not appear in the list are the items with the option "cannot be sold to merchant" activated

**Comment by Haxxer** [comment]
> Testing a little more, what does not appear in the list are the items with the option "cannot be sold to merchant" activated

This doesn't seem to be the case. I think this overall issue has been addressed in recent updates.
