### ISSUE TITLE
[BUG] - [PF2E] - Can’t properly edit item quantities in merchant pile

### ISSUE THREAD

**Issue by GorgoPrimus** [fantasycalendar/FoundryVTT-ItemPiles#375]
**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
I’ve run into an issue. After dragging a new item to a store the inventory is 3(?). If I click that number it has a box I can type in and I change it to 5. It’ll still show the original number. If I click the box to check on it it’ll have the 5 written there, but upon clicking elsewhere to close said box it won’t actually show the amount I’ve input and once the displayed quantity of that item is sold it’ll treat it as sold out. Only way to actually increase the number of that item is to drag new copies in from the compendium for me.

**To Reproduce**

1. Open merchant actor that’s been set up to use item piles
2. Open item compendium.
3. Drag item from compendium to store.
4. Try to edit quantity in store by clicking the quantity number and typing in box.
5. Hit enter and then cry.

**Expected behavior**
When I type a 10 into quantity box and hit enter or click away it’ll save it and that’ll be how many are available to buy.

**Setup:**

- Foundry Version: [Release 10.291]
- System Version: 4.12.9
- Item Piles Version: 2.6.16
- Browser & version: Firefox 113.0.2

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- workbench
- Dorako UI

**Additional context**

**Comment by Haxxer** [comment]
I can't replicate this.

https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/12858387/139de72e-b02d-4d5d-8559-5d686a658329

**Comment by GorgoPrimus** [comment]
I'm on V11 now and it's still happening wven with just Item Piles and Libwrapper on. Could it be something wrong with them upon creation in an older version that's causing issues now? If it helps, here's a copy of one of them.
[Sample Merchent with Bug.zip](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/11943408/Sample.Merchent.with.Bug.zip)

**Comment by GorgoPrimus** [comment]
Whatever this was, it was fixed a version or three ago. Thanks!
