### ISSUE TITLE
Fix/Add delete merchant if empty && auto rolling roll tables.

### ISSUE THREAD

**Issue by Axblade** [fantasycalendar/FoundryVTT-ItemPiles#376]
Currently there is a setting to delete a item if it is empty however seems this feature does not work if item pile is set as a merchant.
Why need it? I like puting items in world but dont want players just pick them up rather they purchase them if want make a slight of hand to steal it I can handle it myself but after they buy the item be nice for it to disappear from scene.

Auto roll tables.
I have made merchants like weapon racks that roll list of items that be on that rack however if drag and drop it on to scene it doesnt roll on its own have enter item and tell it to roll the roll tables. This be nice feature add for making shelves that contain items.

**Comment by Haxxer** [comment]
Please make two tickets for each issue. One ticket does not help track two issues :)
