### ISSUE TITLE
[BUG] - [Level Up: Advanced 5th Edition] - Can't turn actors into loot sheets

### ISSUE THREAD

**Issue by neovista** [fantasycalendar/FoundryVTT-ItemPiles#380]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Clicking the Item Piles confit button to turn an actor into a loot sheet doesn't work.

**To Reproduce**
1. Create actor
2. Open actor sheet (from either canvas or actor directory)
3. Click on "Configure"
4. Nothing happens

**Expected behavior**
The UI to open  up and let me create a merchant sheet (or convert a fallen enemy into a loot pile)

**Screenshots**
See attached screenshot for the error that shows up in the log when debugging is enabled
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/1858098/23794cd8-9eb9-492b-af5a-78a61e85c1e3)

**Setup:**
- Foundry Version: Version 11 Stable, Build 301
- System Version: 0.12.3
- Item Piles Version: 2.6.16
- Browser & version [whatever the version of the desktop client they package now for the most recent release]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

No other modules, I did a test before submitting the bug in a fresh world with only Item Piles and it's dependencies active.

**Comment by Haxxer** [comment]
Fixed in 2.7.0
