### ISSUE TITLE
[BUG] - [DND5E] - Item Price Presets setting window won't render

### ISSUE THREAD

**Issue by TimGonz** [fantasycalendar/FoundryVTT-ItemPiles#381]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
The "Configure Price Presets" button in "Module Settings" does not render a window.

**To Reproduce**

1. Open 'Configure Module' in Item Pile's entry in 'Configure Settings'
2. Click on the 'Module Settings' tab
3. Click on the 'Configure Price Presets' button
4. Verify nothing happened
5. Open console
6. Click on the 'Configure Price Presets' button
7. Verify error in console: "TypeError: An error occurred while rendering PricePresetEditor 121. item is undefined"

**Expected behavior**
A window would open to allow me to configure new price presets.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/4957245/43714f9a-2b71-4ae1-9172-d679e04ca996)

**Setup:**

- Foundry Version: 10.291
- System Version: DND5E 2.1.5
- Item Piles Version: 2.6.16
- Firefox 114.0.1 (64-bit)

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Fixed in 2.7.0
