### ISSUE TITLE
Item Token not Auto deleting

### ISSUE THREAD

**Issue by Iankid** [fantasycalendar/FoundryVTT-ItemPiles#384]
Item Pile isn't auto deleting the pile token as it should when the pile is empty

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/60759323/85c086ba-f1ab-4cec-9c06-ab69e01ecb8f)

- Foundry Version: v11
- System Version: Starfinder (dev branch)
- Item Piles Version: 2.6.16

**Comment by Haxxer** [comment]
Fixed in 2.7.0
