### ISSUE TITLE
Item vanishing with too much transfers

### ISSUE THREAD

**Issue by Iankid** [fantasycalendar/FoundryVTT-ItemPiles#385]
Receiving this error and item vanishing, if transferring item too much.

https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/60759323/0ac4cdbe-085a-4ad2-85d7-4cf8ccc90d2a

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/60759323/efe18cf1-7153-437e-8ca1-e999821eb865)

- Foundry Version: v11
- System Version: Starfinder (dev branch)
- Item Piles Version: 2.6.16

**Comment by Haxxer** [comment]
Could you add reproduction steps? The ticket doesn't explain how to best get this issue.

**Comment by Iankid** [comment]
Video added to report

**Comment by Haxxer** [comment]
Should be fixed in 2.7.0 - it is also a problem with Starfinder, which was identified in the discord channel. Closing this ticket for now.
