### ISSUE TITLE
[BUG] - [WFRP4E] - White outline and invisible text

### ISSUE THREAD

**Issue by FatGiwafe** [fantasycalendar/FoundryVTT-ItemPiles#387]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
A white outline around items for merchants, and barely readable categorization buttons

**To Reproduce**

1. Take an npc sheet
2. Enable as a merchant
3. Add items to the merchant

**Expected behavior**
No white outline

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/116798137/0f8a734b-bb85-4fc9-ad0f-de7cf1424afc)

**Setup:**

- Foundry Version: 10
- System Version: WFRP 4e 6.5.9
- Item Piles Version: 2.6.16
- Firebox 114.0.1

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- GM TOOLKIT
- Simple Calendar (Which has a similar problem)
- The Forge
- WFRP 4e : Winds of Magic , Up in Arms, Ubersreik Adventures 1 , Core Rulebook, starter setn rought nights and hard days, death on the reik, middenheim, archives of the empire 1 and 2 , power behind the throne, the horned rat, empire in ruins, 
- Fan made maps

**Additional context**
I used to run this module without problems , but now I do on this fairly new world (Deleted the oher)

**Comment by Haxxer** [comment]
This is because the system overrides every single style ever. I will not spend the time to fix this for a single system, sorry.

**Comment by FatGiwafe** [comment]
Aaaah ok, thanks for looking into it ^^
