### ISSUE TITLE
Token icon is changed - PF1e

### ISSUE THREAD

**Issue by ckdragons** [fantasycalendar/FoundryVTT-ItemPiles#389]
I'm finding that when a character has only 1 item on the character sheet, the token's icon is changed from it's normal pic to the pic of the item on the sheet. This doesn't happen when a character has 2+ items.

Example: Did a group conversion of these tokens. The top row has 1 item each while the bottom row has multiple items.
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/84493092/b37b8e64-233e-4f4c-9242-90f6265f618e)

Another Example: These tokens were also converted, both have only 1 item each.
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/84493092/66644def-9d80-4023-87c5-52d648ddac42)

This is showing the details of their items. Cultists are top row. Hellknights are bottom row.
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/84493092/b3513916-4349-4d49-89f5-076c9a7b2511)

I'm using a macro to change tokens from normal to an Item Pile.
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/84493092/ac55372b-7c24-48ec-8e0f-ede2ec1a36c4)

I remember reading this was fixed recently, but I'm not seeing this with the latest version. Did I miss an option that I should have enabled?

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/84493092/efede56b-140e-4a72-9003-a3c400cfa75b)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/84493092/3acb51e0-d4f8-4f4e-8f7b-1b49d6fa013f)

Thank you.

**Comment by Haxxer** [comment]
Not a bug. Check the item pile settings of your default item pile.

**Comment by ckdragons** [comment]
I was thinking I may have been overlooking an option. Not sure why I didn't see that before.
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/84493092/eddecf48-5722-453f-8fdc-9b796d5bd8fb)

Thank you for showing me the easy fix!
