### ISSUE TITLE
[BUG] - [SYSTEM NAME] - Describe bug here

### ISSUE THREAD

**Issue by ArgensVentus** [fantasycalendar/FoundryVTT-ItemPiles#390]
**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
When trading pathfinder2e's unidentified item (under the mystified tab), pop-ups explaining the traded item reveal the items' identity.

**To Reproduce**

1. Install the Pathfinder2e system with item piles module installed
2. Take any item, go to "Mystification" tab, and set Mystification status from "Identified" to "unidentified"
3. Perform a trade, using the unidentified item
4. Result: the message describing the confirmed trade will show the item's identified name and description

**Expected behavior**

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/84055930/2f2e9f73-ff51-4955-8484-b58f47ce0335)
![Screenshot 2023-06-25 233207](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/84055930/74723bc3-8bef-43b3-b584-ab8aa5d98f75)

**Setup:**

- Foundry Version: [V 11.302]
- System Version: [e.g. Pathfinder 2e 5.02]
- Item Piles Version: [e.g. 2.6.16]
- Browser & version [e.g. Google Chrome 114.0.5735.134]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- advanced drawing tool
- color picker
- df template enhancements
- dice so nice!
- health estimate
- monk's bloodsplats
- monk's combat marker
- monk's enhanced journal
- monk's little
- pathmuncher: pathbuilder character importer for PF2e
- PF2e companion compendia
- PF2e dailies
- pf2E extempore effects
- PF2e giveths
- Pf2E modifiers matter
- pf2e reaction checker
- pf2e staves
- pf2e target damage
- pf2e workbench
- polyglot
- stairways (teleporter)
- token action HUD core
- token action HUD pathfinder 2e
- Universal battlemap importer

**Comment by Haxxer** [comment]
Fixed in 2.7.0

**Comment by Haxxer** [comment]
Fixed in 2.7.0
