### ISSUE TITLE
[REQUEST] - Restrict players from looking inside vaults

### ISSUE THREAD

**Issue by Velheka** [fantasycalendar/FoundryVTT-ItemPiles#392]
**Describe the solution you'd like**
The ability to completely restrict a player from a vault. Currently, anyone is able to open a vault and look at the descriptions of any item inside. The only restrictions that can be applied to vaults are on withdrawing, depositing, and organizing, not specifically visual access to investigating the items inside.

My use case for this is a system of literal 'lockers', where PC's, between missions, are able to drop off items they don't think they need or pick up items they think will come in handy. It's possible that PC's will keep secrets from one another in this campaign, and evidence of this is likely going to be in the form of letters (which are items with the description text and the content) and suspicious magic items with unexplained origins. With the current system, hiding this is impossible as any player can just walk up to someone's locker/vault and investigate every last detail of the items inside. My in-game justification for not being able to do this is that they're simply locked, and only the owner of the locker has the correct key, but there is no way of simulating this currently with vaults as-is.
 
**Describe alternatives you've considered**
Using Containers and manually locking and unlocking them only when the PC is at their locker would work, but is cumbersome and doesn't actually stop another player from quickly going over to it and peeking unless the game is constantly paused and unpaused.

**Comment by Haxxer** [comment]
Added in 2.7.0

**Comment by Velheka** [comment]
Sick, thanks!
