### ISSUE TITLE
[BUG] - [dnd5e] - Cannot populate merchants from new rollable tables in v11

### ISSUE THREAD

**Issue by LukasPrism** [fantasycalendar/FoundryVTT-ItemPiles#395]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
The Add Table dropdown to select tables to populate merchant items with doesn't seem to be finding any new rollable tables I've created in v11.

**To Reproduce**

1. Create a rollable table, eg. by right-clicking on a folder in the Items sidebar
2. Open a merchant and go to Populate Items
3. The Add table dropdown won't display the new table (even if you reload or restart FVTT)

**Setup:**

- Foundry Version: 11.302
- System Version: DND5e 2.2.1
- Item Piles Version: 2.6.16
- Browser & version Edge 114.0.1823.58

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by LukasPrism** [comment]
PS. Not worth a full report but just a lil reminder while you're in merchants that dnd5e is using `veryRare` for their rarity mapping now instead of `veryrare`
https://discord.com/channels/772596237605011466/881983179920142356/1122830973239824384

**Comment by Haxxer** [comment]
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/12858387/67309c38-6a65-4250-a778-9ae658372767) ![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/12858387/54c6cd2f-8acc-4188-a3f9-eecc3d1c8ef4)

Works for me. Make sure your roll tables setting is configured correctly:

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/12858387/c4fe614f-20ff-4ca9-9877-386997efca49)

**Comment by LukasPrism** [comment]
Well..... that solves that then doesn't it? Makes sense that All Tables isn't the default. Thanks for your help!

**Comment by Haxxer** [comment]
It is, but you might have changed if 😅

**Comment by LukasPrism** [comment]
But I did reset settings like this issue form prompted me to 🤔 Maybe this falls outside that. Anyway all’s well that ends well. Thanks again!

**Comment by Haxxer** [comment]
Resetting only resets system specific settings, as it is located in that tab :) Thanks for confirming though!
