### ISSUE TITLE
[BUG] - [DnD5E] - Empty piles do not autodelete on v11

### ISSUE THREAD

**Issue by maxobremer** [fantasycalendar/FoundryVTT-ItemPiles#401]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When a item pile gets emptied, it does not delete itself, as in the token on the scene stays there.

**To Reproduce**

1. Make a new world and only activate item piles, libwrapper and socketlib
2. make sure the settings are set to delete when empty (for both the default pile and just in the settings menu
3. drop an item from on the map (i tested by dropping a acid vial from the dnd5e srd item compendium)
4. open the pile and set the amount to 0.
5. close the pile
6. see the pile still being there on the scene

**Expected behavior**
I expect the item pile token to get deleted when empty

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/86924581/81f0d540-f7a5-412c-8e4a-f66c84434aeb)

**Setup:**

- Foundry Version: [v11.302]
- System Version: [e.g. DND5e 2.2.2]
- Item Piles Version: [e.2.7.1]
- Browser & version [not applicable]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**

**Comment by Haxxer** [comment]
I'm guessing you have MidiQOL?

**Comment by Haxxer** [comment]
https://discord.com/channels/915186263609454632/1125061930894229544

**Comment by maxobremer** [comment]
I do not, else I would have mentioned that in the bug report.

**Comment by Haxxer** [comment]
Fixed in 2.7.2
