### ISSUE TITLE
[REQUEST] - Add "equipped" column to merchant sell interface

### ISSUE THREAD

**Issue by dkniffin** [fantasycalendar/FoundryVTT-ItemPiles#402]
**Is your feature request related to a problem? Please describe.**
My players have a hard time determining what they can and cannot sell, because equipped items show in the sell interface.

**Describe the solution you'd like**
I would like an "equipped" column in the sell interface. 

Alternatively/additionally, it would be nice if the players could hide/show equipped items, since they usually don't want to sell those.

**Describe alternatives you've considered**
I tried adding it to the "Merchant Columns" settings, but it only showed up for the "Buy Items" tab.

**Additional context**
N/A

**Comment by Haxxer** [comment]
Not every system has an equipped status of items, what system are you using?

**Comment by GaistH** [comment]
This would be handy for PF1E at least

**Comment by dkniffin** [comment]
dnd 5e
