### ISSUE TITLE
[BUG] - [WFRP4e] - Vaults not working

### ISSUE THREAD

**Issue by Forien** [fantasycalendar/FoundryVTT-ItemPiles#403]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
GM cannot set money to vault.
Players can't take items from Vault.
GM doesn't see items that players add to Vault.

**To Reproduce**

1. Create a vault
2. Add some items either as GM or as a Player
3. Try taking them as a Player (dragging not working)
4. Try adding money as GM (simply won't save)

**Expected behavior**
I expected players to be able to take items (they can't even drag them around in the Vault) and GM to spawn some money.

**Screenshots**
n/a

**Setup:**
- Foundry Version: [e.g. 11.305]
- System Version: [e.g. WFRP4e 6.5.9]
- Item Piles Version: [e.g. 2.7.1]
- Browser & version [e.g. Google Chrome 114.0.5735.199]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Forien's Armoury
- Times Up
- some WFRP4e official content modules (Up in Arms, Winds of Magic, Archives of the Empire I and II, Imperial Zoo)

**Additional context**
Not only Vault, but entire module is hard to navigate in WFRP4e due to CSS incompatibility :(

**Comment by Haxxer** [comment]
Fixed in 2.7.2
