### ISSUE TITLE
[BUG] - [WFRP4e] - Weird price calculation when selling arrows in bulk

### ISSUE THREAD

**Issue by Forien** [fantasycalendar/FoundryVTT-ItemPiles#404]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
WFRP4e sets _some_ ammunition prices in bulk. For example, normal Arrows come in quantity of 12 for a price of 5 SS (silver shillings). 
That would mean that a single arrow costs 5 BP (brass pennies).

When I set up that my test player can sell 12 arrows for half price, it displays **almost** correctly that my player would get 2 SS and 6 BP (actually shows 2SS 5BP, I guess rounding error).

But when I try to sell as my test player, I see that I can only get 6 BP for entire stack. On one hand I expect price of 2 SS and 6 BP, on the other, if it was a price of a single arrow then it should show 2-3 BP (2.5 actually, but BP is not divisible). Not 6. If it shows what it thinks is a full price (why not 50%?), then why 6 BP, not 5 BP?

Maybe it correctly wants to give my 2 SS and 6 BP and 2 SS is somehow disappearing, leaving the 6 BP?

**To Reproduce**

1. Create a Merchant
2. Add `Arrows` ammunition item to a player character
3. Set `Arrows` to be sold in bulk of `12`
4. Attempt to sell the `Arrows` to the merchant

**Expected behavior**
Player should get 2 SS 6 BP when selling 12 Arrows 

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/11304207/3b3b83fe-fcd3-478f-b0ff-c7f482d33889)

**Setup:**

- Foundry Version: [e.g. 11.305]
- System Version: [e.g. WFRP4e 6.5.9]
- Item Piles Version: [e.g. 2.7.1]
- Browser & version [e.g. Google Chrome 114.0.5735.199]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Forien's Armoury
- Times Up
- some WFRP4e official content modules (Up in Arms, Winds of Magic, Archives of the Empire I and II, Imperial Zoo)

**Comment by Forien** [comment]
I think it omits the bigger currencies altogether. I did another test and this is the result:

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/11304207/5c30bc55-9450-422a-9be7-b904933fdafb)

**Comment by Haxxer** [comment]
Fixed in 2.7.2
