### ISSUE TITLE
[REQUEST] - [WFRP4e] Allow Brass Penny as Primary Currency

### ISSUE THREAD

**Issue by Forien** [fantasycalendar/FoundryVTT-ItemPiles#405]
## Is your feature request related to a problem? Please describe.
In WFRP4e, basic primary currency is BP, a Brass Penny. It's the smallest and non-divisible. All other currencies are derived from it.  

Silver Shilling is 12 Brass Pennies and Gold Crown is 240 Brass Pennies. 

Currently Item Piles treats Gold Crown as Primary currency of value "1" and other as fractions. Which can lead to rounding errors.

### Describe the solution you'd like
Not sure how feasible it is, but if you could allow primary currency to be the smallest and secondary currencies to be bigger variants, it would probably help.

### Describe alternatives you've considered
I tried setting up Brass Penny as a value of 1, Silver Shilling as a value of 12 and Gold Crown as a value of 240, but Merchant broke and displayed everything for free...

## Additional context
**Setup:**

- Foundry Version: [e.g. 11.305]
- System Version: [e.g. WFRP4e 6.5.9]
- Item Piles Version: [e.g. 2.7.1]
- Browser & version [e.g. Google Chrome 114.0.5735.199]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Forien's Armoury
- Times Up
- some WFRP4e official content modules (Up in Arms, Winds of Magic, Archives of the Empire I and II, Imperial Zoo)

**Comment by Forien** [comment]
Sooo I tested some more and I think issue boils down to `ITEM_COST_TRANSFORMER` which isn't set up to be modifiable by config.

I tried using API to set this myself, but to no avail. It said that transformer must return an object, but in all examples it clearly returns number...

So I tried to set up my own System Integration by changing `ITEM_COST_TRANSFORMER` to:
```js
"ITEM_COST_TRANSFORMER": (item) => {
        let overallCost = 0;
        const prices = getProperty(item, "system.price");
        overallCost += (Number(prices?.["gc"]) ?? 0) * 240;
        overallCost += (Number(prices?.["ss"]) ?? 0) * 12;
        overallCost += (Number(prices?.["bp"]) ?? 0) * 1;
        return overallCost;
      },
```
and I also currencies exchange to reflect those values. 

I then copied the entire integration into my module and tried to use Hook, but module simply refuses to register the new settings. I guess the issue is in your `Systems.addSystem()` function which fails to update object? Not sure, haven't done enough testing.

But with my entire file looking like this:

<details><summary>ItemPilesIntegration.mjs</summary>
<p>  


```js
export default class ItemPilesIntegration {
  bindHooks() {
    Hooks.once("item-piles-ready", this.addForienSystemIntegration);
  }

  addForienSystemIntegration(api) {
    console.log("Forien: running item piles (item-piles) system integration");
    /// Called once Item Piles is ready to be used
    game.itempiles.API.addSystemIntegration({
      VERSION: "2.0.0",

      // The actor class type is the type of actor that will be used for the default item pile actor that is created on first item drop.
      "ACTOR_CLASS_TYPE": "character",

      // The item quantity attribute is the path to the attribute on items that denote how many of that item that exists
      "ITEM_QUANTITY_ATTRIBUTE": "system.quantity.value",

      // The item price attribute is the path to the attribute on each item that determine how much it costs
      "ITEM_PRICE_ATTRIBUTE": "system.price",

      // Item types and the filters actively remove items from the item pile inventory UI that users cannot loot, such as spells, feats, and classes
      "ITEM_FILTERS": [
        {
          "path": "type",
          "filters": "career,container,critical,disease,injury,mutation,prayer,psychology,talent,skill,spell,trait,extendedTest,vehicleMod,cargo"
        }
      ],

      // Item similarities determines how item piles detect similarities and differences in the system
      "ITEM_SIMILARITIES": ["name", "type"],

      // This function is an optional system handler that specifically transforms an item's price into a more unified numeric format
      "ITEM_COST_TRANSFORMER": (item) => {
        let overallCost = 0;
        const prices = getProperty(item, "system.price");
        overallCost += (Number(prices?.["gc"]) ?? 0) * 240;
        overallCost += (Number(prices?.["ss"]) ?? 0) * 12;
        overallCost += (Number(prices?.["bp"]) ?? 0) * 1;
        return overallCost;
      },

      "PILE_TYPE_DEFAULTS": {
        "merchant": {
          merchantColumns: [{
            label: "Availability",
            path: "system.availability.value"
          }],
        }
      },

      // Currencies in item piles is a versatile system that can accept actor attributes (a number field on the actor's sheet) or items (actual items in their inventory)
      // In the case of attributes, the path is relative to the "actor.system"
      // In the case of items, it is recommended you export the item with `.toObject()` and strip out any module data
      "CURRENCIES": [
        {
          type: "item",
          name: "Gold Crown",
          img: "icons/commodities/currency/coin-embossed-crown-gold.webp",
          abbreviation: "{#}GC",
          data: {
            item: {
              "name": "Gold Crown",
              "type": "money",
              "img": "icons/commodities/currency/coin-embossed-crown-gold.webp",
              "system": {
                "quantity": {"type": "Number", "label": "Quantity", "value": 1},
                "encumbrance": {"type": "Number", "label": "Encumbrance", "value": 0.005},
                "coinValue": {"label": "Value (in d)", "type": "Number", "value": 240},
                "source": {"type": "String", "label": "Source"}
              }
            }
          },
          primary: true,
          exchangeRate: 240
        },
        {
          type: "item",
          name: "Silver Shilling",
          img: "icons/commodities/currency/coin-engraved-moon-silver.webp",
          abbreviation: "{#}SS",
          data: {
            item: {
              "name": "Silver Shilling",
              "type": "money",
              "img": "icons/commodities/currency/coin-engraved-moon-silver.webp",
              "system": {
                "quantity": {"type": "Number", "label": "Quantity", "value": 1},
                "encumbrance": {"type": "Number", "label": "Encumbrance", "value": 0.005},
                "coinValue": {"label": "Value (in d)", "type": "Number", "value": 12},
                "source": {"type": "String", "label": "Source"}
              }
            }
          },
          primary: false,
          exchangeRate: 12
        },
        {
          type: "item",
          name: "Brass Penny",
          img: "icons/commodities/currency/coin-engraved-waves-copper.webp",
          abbreviation: "{#}BP",
          data: {
            item: {
              "name": "Brass Penny",
              "type": "money",
              "img": "icons/commodities/currency/coin-engraved-waves-copper.webp",
              "system": {
                "quantity": {"type": "Number", "label": "Quantity", "value": 1},
                "encumbrance": {"type": "Number", "label": "Encumbrance", "value": 0.005},
                "coinValue": {"label": "Value (in d)", "type": "Number", "value": 1},
                "source": {"type": "String", "label": "Source"}
              }
            }
          },
          primary: false,
          exchangeRate: 1
        }
      ]
    });
  }
}
```  

</p></details> 

I get these debug messages: 
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/11304207/1154dfed-4845-4c2f-ba9e-31b84eca9bea)


Worth noting is that if I edit the integration in your `item-piles/module.js` itself, it all registers. And works fine, fixing all issues about rounding and missing coins when selling items (Resolves #404).

So it's now up to you, whether you allow modules to update system data (it also could be nice if we could append/push to arrays of currencies and change parts of integration, not everything), or if you will change the WFRP integration to avoid fractions and decimals. (the latter being literally quick change to 6 numbers in one file, I could even PR this if you want :) )

**Comment by Haxxer** [comment]
Thanks for the investigation and details! Please do create a PR, the module is under an MIT license after all - I'm in maintenance mode for this module for the time being as I don't have the same drive to keep it in line across all of the systems it supports.

**Comment by Forien** [comment]
> Thanks for the investigation and details! Please do create a PR, the module is under an MIT license after all - I'm in maintenance mode for this module for the time being as I don't have the same drive to keep it in line across all of the systems it supports.

Oh, okay. I will do a PR then. If the module weren't so big and complex (and TypeScript), I would even consider trying to fix other V11 issues I'm encountering, but oh well :)

Still enjoying the module a lot, and with the change to how currencies are handled for the wfrp4e I should be able to abuse the module even more, so thanks for your work!

**Comment by Haxxer** [comment]
It's not typescript, it's just svelte. To build and run, you just need to run `npm run build` and then `npm run dev` :)

**Comment by Forien** [comment]
> It's not typescript, it's just svelte. To build and run, you just need to run `npm run build` and then `npm run dev` :)

Oh, my bad :D must-have confused with other module I was checking out and/or maybe because of some `tjs` class in some of the css stuff from your module (I made wfrp4e css compatibility fixes as well for your module (moo-man/WFRP4e-FoundryVTT#1689)
nevermind, I was reading too much code today :D

**Comment by Forien** [comment]
Hmm, when I made changes I proposde, Selling works perfectly. No rounding errors, no missing coins. Nice.

But buying gets screwed. Not entirely, because values are right, but buying stuff worth 5 shillings when I have 1 gold crown and 0 silver shillings,  should ask me for 1 GC and give me 15 SS back, but after my changes it doesn't care about by 1 gold crown (uses it to calculate if I can afford item), and just asks me to pay 5 SS which results in character having 1 GC and -5 SS. 

So if fractionals work for Buying, but result in coins missing when Selling, and integers work for Selling, but result in "missing" coins on Buying, I guess something else is amiss.

Will probably investigate further when I have energy.

**Comment by Haxxer** [comment]
Added support for this setup in 2.7.2
