### ISSUE TITLE
[BUG] - [WFRP4e] - Player can buy/sell partial stacks for full price

### ISSUE THREAD

**Issue by Forien** [fantasycalendar/FoundryVTT-ItemPiles#407]
### **Have you tried to reset Item Piles' system settings?**
Yes

### **Describe the bug**
Players can buy/sell bulk items even if there is not enough items to buy/sell. And the price is full!

### **To Reproduce**

1. Create a merchant
2. Give both Merchant and Players a stack of 3 Arrows
3. Set both `Arrows` items to be "Quantity for price = 12"
4. Buy or Sell Arrows
5. If you Buy, 3 Arrows will be removed from Merchant, Player will pay full price and get 12 arrows
6. If you Sell, 3 Arrows will be removed from Player, Merchant will pay full price (bugged atm, see #404) and receive 12 Arrows

### **Expected behavior**
Trade should be either completely impossible both ways, or price should be adjusted for partial stack. If the latter will be the solution, then buyer should not receiver entire stack, but partial one. 

### **Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/11304207/94debeb1-042b-409e-96b3-2e78e2abb1cf)
As seen on Screenshot above, Merchant only has 2 Arrows that should be traded in Quantity of 12. Player can buy 1 stack of those (even though popup says "0"), and the button is not disabled. What's more, Player has to pay full price for 2 Arrows. However, if Player does click to buy, Player receives full 12 arrows

### Setup:

- Foundry Version: [e.g. 11.305]
- System Version: [e.g. WFRP4e 6.5.9]
- Item Piles Version: [e.g. 2.7.1]
- Browser & version [e.g. Google Chrome 114.0.5735.199]

### Active modules:

- Item Piles
- libwrapper
- socketlib
- Forien's Armoury
- Times Up
- some WFRP4e official content modules (Up in Arms, Winds of Magic, Archives of the Empire I and II, Imperial Zoo)

**Comment by Haxxer** [comment]
Fixed in 2.7.2
