### ISSUE TITLE
[BUG] - [WFRP4e] - Currency Bug in Item Piles Trade Requests

### ISSUE THREAD

**Issue by jtsmirror** [fantasycalendar/FoundryVTT-ItemPiles#408]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When adding currencies either as a GM or as a player during a trade request between two players or a player and a GM, there seems to be an issue with the display and unwanted currencies are being added. Moreover, once these currencies are added, they cannot be changed or modified.

**To Reproduce**

1. Initiate a 'Trade Request' between two players, or between a player and a GM.
2. Look at Currency.
3. Try to add desired currency by moving the slider.
4. See that undesired currencies are also added.
5. Attempt to change or modify the added currencies.
6. Notice that the currencies cannot be changed or modified.

**Expected behavior**
Only the currencies selected by the user should be added, and any added currency should be able to be changed or modified at any time.

**Screenshots**
<img width="526" alt="Zrzut ekranu 2023-07-12 o 07 17 25" src="https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/136428641/c1147a3a-dc2e-4b92-a4ed-9f218bc4f3af">
<img width="492" alt="Zrzut ekranu 2023-07-12 o 07 18 57" src="https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/136428641/92f5209c-dc45-4585-b3d9-534c0330c722">

**Setup:**

- Foundry Version: [11]
- System: [Warhammer Fantasy 4ed]
- System Version: [6.5.9]
- Item Piles Version: [2.7.1]
- Browser & version [Google Chrome 114.0.5735.199]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Simple Calendar
- Warhammer Core Module

**Additional context**
-

**Comment by Haxxer** [comment]
Fixed in 2.7.2
