### ISSUE TITLE
[BUG] - [WFRP4e] - Overriding "Item Filters" in item pile overrides global setting

### ISSUE THREAD

**Issue by Forien** [fantasycalendar/FoundryVTT-ItemPiles#409]
### **Have you tried to reset Item Piles' system settings?**
Yes

### **Describe the bug**
If I change the "Item Filters" using "override" option on the item pile, the global setting changes as well.

### **To Reproduce**

1. Make an Item Pile
2. Enable "Override Item Filters"
3. Click on "Configure Override Item Filters"
4. Delete either "containers" from the right side, or delete entire entry, doesn't matter much
5. Save and exit
6. Go to Foundry's "Configure Settings" -> "Item Piles" -> "Configure Module"
7. Navigate to "System Specific Settings"
8. Open "Configure Item Filters"
9. Witness changes you made to specific item pile.

### **Expected behavior**
Override on one Pile should not affect global setting and other Piles

### **Screenshots**
n/a

### Setup:

- Foundry Version: [e.g. 11.305]
- System Version: [e.g. WFRP4e 6.5.9]
- Item Piles Version: [e.g. 2.7.1]
- Browser & version [e.g. Google Chrome 114.0.5735.199]

### Active modules:

- Item Piles
- libwrapper
- socketlib
- Forien's Armoury
- Times Up
- some WFRP4e official content modules (Up in Arms, Winds of Magic, Archives of the Empire I and II, Imperial Zoo)

### **Additional context**
Additionally, when you click `reset defaults`, you need to F5 to see the changes saved.

**Comment by Haxxer** [comment]
Fixed in 2.7.2
