### ISSUE TITLE
[BUG] - Item Pile Container Settings do not persist when dragging from actor list

### ISSUE THREAD

**Issue by dhorkin** [fantasycalendar/FoundryVTT-ItemPiles#41]
**Describe the bug**
I get the actor image rather than the expected image of a closed chest

**To Reproduce**
1. Right click on the Default Item Pile and duplicate it
2. Customize the new Item Pile (disable "Display Single Image" and put images/sounds on the Container Settings tab and click update)
3. Drag the new type of Item Pile onto a scene
4. Result: I see the Item Pile's image, not the closed chest imag
5. If I open the Item Pile from the scene, go to Container Settings, and click Update, then it behaves as expected

**Expected behavior**
4 should not happen and 5 should be automatic

**Setup:**
 - Foundry Version: 0.8.9
 - Item Piles Version: 1.2.5
 - OS: Windows
 - Browser chrome
 - Version [version of what?)

**Active modules:**
 - Item Piles
Active Modules:
----------
About Time v1.0.6;
Ace library v1.3.0;
Active-Auras v0.3.08;
Active Token Effects v0.3.04;
Actor Attribute Lists v0.0.5;
Advanced Macros v1.12;
Adventure Log v0.2.3;
Adventure Music v1.1.0;
Autocomplete Whisper v0.3.4;
Automated Animations v1.2.6;
Award XP v1.3.2;
Break Time v1.0.11;
Chat Images v2.5.6;
Combat Carousel v0.2.3;
Combat Enhancements v1.0.2;
Compendium Folders v2.3.64;
Control concealer v1.2.0;
Cycle Token Stack v0.5.4;
D&amp;D Beyond Importer v2.8.8;
DDB D&amp;D 5E (Shared Compendiums) v1.0;
Deprecated Modules v1.1.6;
DF Architect v3.1.1;
DF Chat Enhancements v3.5.1;
DF Curvy Walls v3.2.4;
DF Flags Editor v1.1.2;
DF Quality of Life v1.6.1;
DFreds Convenient Effects v2.0.1;
DFreds Droppables v1.4.0;
DFreds Pocket Change v3.2.1;
DF Settings Clarity v3.2.1;
Dice So Nice! v4.3.1;
Dice Tray v1.4.1;
DnD5e Helpers v3.0.4;
Drag Ruler v1.9.1;
Dungeon Draw v0.19.1;
Dynamic Active Effects SRD v6.0.01;
Dynamic effects using Active Effects v0.8.79;
Find the culprit v1.4.0;
FVTT Encounter Stats v0.20.3;
FXMaster v2.2.2;
Health Estimate v2.6.13;
Hey, Wait! v0.6.3;
Initiative Double Click v1.2;
Item Macro v1.5.6;
Item Piles v1.2.5;
JB2A - Jules and Ben's Animated Assets - Free Content v0.3.4;
Keybind Lib v0.3.4;
Let's Trade 5e v0.3.0;
lib - Color Settings v2.8.2;
Library: Chat Commands v1.4.0;
Library: DF Hotkeys v2.3.5;
libWrapper v1.11.4.0;
Loot Sheet NPC 5e v3.4.1;
Midi QOL v0.8.103;
Midi SRD v0.1.03;
Milby's Maps Free v1.1.9;
Minimal UI v1.1.10;
MiWwewa's Free Maps Bundle v1.3.0;
Not Enough NPCs: A 5e NPC Generator v1.1.0;
Perfect Vision v2.10.8;
Permission Viewer v0.8.14;
Pings v1.2.12+0.8.6;
Polyglot v1.7.28;
PopOut! v2.4;
Popout Resizer v1.4.2;
Quick Insert - Search Widget v2.5.3;
Quick Module Enable v1.3.4;
Radugen (Random dungeon generator) v0.0.5;
Sequencer v2.0.7;
Settings Extender v1.2.0;
Simple Calendar vv1.3.75;
SmallTime v1.13.10;
Smart Target v0.6.7;
socketlib v1.0.10;
Spells, Items, and Features Toolkit v0.4.3;
Tabletop RPG Music v1.5.1;
Tidy5e Sheet v0.5.21;
Tidy UI - Game Settings v0.1.30;
Times Up v0.8.31;
Token Action HUD v1.3.29;
Token Magic FX v0.5.2.1;
Token Mold v2.14.0;
True RNG v1.0.6;
Warp Gate v1.11.2;
Window Controls v1.7.4;

**Comment by Haxxer** [comment]
I believe this has been resolved in 1.2.7
