### ISSUE TITLE
[BUG] - [WFRP4e] - Can't add items when Trading

### ISSUE THREAD

**Issue by Forien** [fantasycalendar/FoundryVTT-ItemPiles#410]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Latest update seem to broke the Trading (tested on hosted server, connected as GM and Player). I can't add items by dragging. 

**To Reproduce**
1. Open trade windows with another player/gm
2. Try to drag items
3. Items are not added, but no error

**Expected behavior**
Items should be added

**Screenshots**
![](https://i.gyazo.com/5c60daf89644b5706a3b2d0c8f040939.mp4)

[Link to video, if doesn't appear above](https://i.gyazo.com/5c60daf89644b5706a3b2d0c8f040939.mp4)

**Setup:**

- Foundry Version: [e.g. 11.305]
- System Version: [e.g. WFRP4e 6.5.9]
- Item Piles Version: [e.g. 2.7.2]
- Browser & version [e.g. Google Chrome 114.0.5735.199]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Forien's Armoury
- Times Up
- some WFRP4e official content modules (Up in Arms, Winds of Magic, Archives of the Empire I and II, Imperial Zoo)

**Comment by Haxxer** [comment]
Fixed in 2.7.3
