### ISSUE TITLE
[BUG] - [PF1E] - Migrating fails due to max depth being exceeded on items

### ISSUE THREAD

**Issue by GaistH** [fantasycalendar/FoundryVTT-ItemPiles#412]
**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
Trying to launch in V11 Foundry and PF1E v9.1 and Item Piles fails to migrated existing items due to hitting max depth.  Sadness.

**To Reproduce**
Loading world in foundry.

**Expected behavior**
Ideally migrating the items and merrily gaming.

**Screenshots**
![HI4dYhx](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/42808283/bb5e6f6b-9ba1-4703-94de-6b130bbfbe0a)

**Setup:**

- Foundry Version: [v11.306]
- System Version: [PF1E v9.1]
- Item Piles Version: [2.7.3]
- Direct through PC client for hosting Foundry

**Active modules:**

- Item Piles
- libwrapper
- socketlib
Does this with only those three modules enabled

**Additional context**
Seemingly having a smorgasbord of problems due to the items not migrating, to my immense bummer.

**Comment by SirAron111** [comment]
same issue in DnD 5e migration of item piles fails.

**Comment by Haxxer** [comment]
> same issue in DnD 5e migration of item piles fails after the last update of it.

Even after 2.7.4 that was supposed to resolve it?

**Comment by mclearc** [comment]
I'm seeing this on the most recent version of v11, 5e,and item piles.

**Comment by SirAron111** [comment]
Interestingthing is, i am on 2.7.4 item piles and v11 306 build and i still get the error message for the migration error for 2.7.3 item piles

**Comment by MiniGrief** [comment]
Unsure if this is exactly related to PF1E's issue but for 5e a fix for me was to modify line 363 of migrations.js and change `actor` to `validToken[1][0].delta`. I no longer have any errors and everything _seems_ to have migrated correctly as far as I can tell.

(I do not recommend this unless you have a backup of your world as you are messing with data migration and can easily corrupt stuff)

**Comment by Runesmite** [comment]
@MiniGrief I am experiencing the same issue in 5e. I can see line 363 in the developer console, but I cannot find the file to change it on my server. I see many "migration.js" but no "migrations.js". Do you have the path to the file?

**Comment by MiniGrief** [comment]
> @MiniGrief I am experiencing the same issue in 5e. I can see line 363 in the developer console, but I cannot find the file to change it on my server. I see many "migration.js" but no "migrations.js". Do you have the path to the file?

That would be because of how this module is built, it's in module.js if you're modifying it directly like that. You will have to find it using something like function names as it's all the code in a single file.

**Comment by Haxxer** [comment]
This has been fixed in 2.7.5
