### ISSUE TITLE
[BUG] - [Cyberpunk RED Core] - Migrations fail "actor not defined"

### ISSUE THREAD

**Issue by diwako** [fantasycalendar/FoundryVTT-ItemPiles#413]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
After the update migrations fail when entering the world

```
ReferenceError: actor is not defined
    at 2.7.3 (migrations.js:363:40)
    at async runMigrations (migrations.js:13:7)
    at async module.js:97:7
```

**To Reproduce**

1. Update module
2. Load world
3. See error

**Expected behavior**
Migrations run through

**Setup:**

- Foundry Version: 10.303
- System Version: 0.87.3
- Item Piles Version: 2.7.4
- Browser & version: Google Chrome 115.0.5790.102

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
Tried with and without safe configuration of the world. Could be world related or not

**Comment by Haxxer** [comment]
This has been fixed in 2.7.5
