### ISSUE TITLE
[BUG] - [D&D 5e] - migration issue for 2.7.3

### ISSUE THREAD

**Issue by monkeyPoc** [fantasycalendar/FoundryVTT-ItemPiles#414]
**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
i am on item piles version 2.7.4 but still get the migration issue for version 2.7.3

**To Reproduce**

load foundry

**Expected behavior**

**Screenshots**

**Setup:**

- Foundry Version: [e.g. 9.238]
- System Version: [e.g. DND5e 1.5.7]
- Item Piles Version: [e.g. 1.0.0]
- Browser & version [e.g. Google Chrome 98.0.4758.82]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- [insert more modules here]

**Additional context**

**Comment by aldaron838** [comment]
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/33810839/2f9c6262-b4bf-4da3-aafc-85e72b6ca551)

This is the error I get when I try to update the DH 2e module on the new Foundry.

**Comment by Dyrnwyrm** [comment]
Same error here

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/129613553/1a5176d8-1076-49cd-af95-d92e7f12f126)

**Comment by Mesk62** [comment]
Having the same issue

**Comment by Haxxer** [comment]
This has been fixed in 2.7.5

**Comment by Haxxer** [comment]
One ticket is fine for the future.
