### ISSUE TITLE
[BUG] - [PF2e] - Holding Ctrl does not affect which sheet is opened

### ISSUE THREAD

**Issue by SantoII-github** [fantasycalendar/FoundryVTT-ItemPiles#415]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Using Ctrl+Double Click to open the actor sheet instead of the Item Pile does not work.
Using the "Invert Ctrl + Double Click Open" option in the setting inverts the behavior, but also does not function.

**To Reproduce**

1. Install the Module, alongside only the required dependencies socketlib and libwrapper
2. In a PF2e World, create an Item Pile, Vault, Merchant, or Container with the module
3. Ctrl+Double Clicking it with the default settings opens the configured Item Pile type

**Expected behavior**
Ctrl+Double Click should open the Actor Sheet as described.

**Screenshots**
Unfortunately none could show me Ctrl+Double Clicking

**Setup:**

- Foundry Version: v11 Stable Build 306
- System Version: Pathfinder 2nd Edition 5.2.1
- Item Piles Version: 2.7.5
- Browser & version Tried Google Chrome Version 115.0.5790.102 (64 bit) and Firefox 110.0 (64-bit)

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
I also tested this with the DnD 5e system and had the same results. It's entirely possible I might be doing something wrong.
Changing the hotkey in the Controls settings did not change the results either.

**Comment by Haxxer** [comment]
Fixed in 2.7.7
