### ISSUE TITLE
[REQUEST] - API method to add "per actor" price modifier

### ISSUE THREAD

**Issue by Forien** [fantasycalendar/FoundryVTT-ItemPiles#416]
I would like an API method that would allow me to programatically set price modifiers for actors depending on some action, for example a Haggle Test in wfrp4e.

From our conversation on Discord:

> So it would be a method that needs the merchant actor, the actor/user to update, and an object containing one or many of; a buy modifier, a sell modifier, whether it is overriding the base modifier

**Comment by Forien** [comment]
I forgot to mention, it would be beneficial to be able to do "relative" changes (for example if Actor already has entry in the merchant with "110%" buy price, to change it by "+10%" to get "120%".

Alternatively, similar, second API method to retrieve the current Actor's price modifier with that Merchant (basically a getter) so that relative changes like addition/substraction could be done on my end.

**Comment by Haxxer** [comment]
Added in 2.7.7 as `game.itempiles.API.getMerchantPriceModifiers` and `game.itempiles.API.updateMerchantPriceModifiers`
