### ISSUE TITLE
[BUG] - [WFRP4e] - If RollTable Folder is set, nested rolltables are not accessible

### ISSUE THREAD

**Issue by Forien** [fantasycalendar/FoundryVTT-ItemPiles#417]
**Describe the bug**
When choosing a folder for the `RollTables folder for "Populate Items"` setting, the Populate Items tab on Merchant will not show RollTables that are in subfolders of selected folder. 

Please add recursive search in nested folders.

**To Reproduce**

1. Create a nested tree of folders
2. Make a Rolltable deep within the tree
3. Set the parent folder in the settings as the folder for "Populate Items"
4. Try adding the Rolltable from point 2, it won't show up on the list.

**Expected behavior**
All RollTables within the selected folder and all subfolders should appear on the list, either sorted alphabetically or in tree-like structure

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/11304207/82156f7f-0897-46c5-bae5-977fac2d75be)

**Comment by Haxxer** [comment]
Fixed in 2.7.7
