### ISSUE TITLE
[BUG] - [WFRP4e] - Populate Items breaks when using "Add all items" with nested RollTables

### ISSUE THREAD

**Issue by Forien** [fantasycalendar/FoundryVTT-ItemPiles#418]
**Describe the bug**
When populating Merchant with a RollTable that has nested further RollTables while also having the `Add all items` checkbox checked, module throws an error (see screenshots).  

Works properly if the `Add all items` is **not** checked. 

**To Reproduce**

1. Create a Rolltable with some items
2. Create a second "Parent" Rolltable that only has Rolltable from point 1 as an entry
3. Add "Parent" Rolltable to the Merchant's Populate Items
4. Check the `Add all items` next to that table
5. Roll for that table

**Expected behavior**
I would expect script to follow through nested rolltables just like it does if `Add all items` is not checked.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/11304207/dcd61b2e-d5f2-4b42-9997-82cbf8b134a9)

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/11304207/f0848804-80c6-4c73-8d78-764607c1a8af)

**Comment by Haxxer** [comment]
Fixed in 2.7.7
