### ISSUE TITLE
[REQUEST] - When Populating Items in a Merchant via RollTables, respect the Item Quantity

### ISSUE THREAD

**Issue by Forien** [fantasycalendar/FoundryVTT-ItemPiles#419]
**Is your feature request related to a problem? Please describe.**
In some systems (I'm using WFRP4e as an example), some items can be defined as a bundle/bulk. For example an `Arrow` Item in wfrp4e. It costs 5 shillings for a bundle of 12. 

In Foundry wfrp4e system, those arrows have quantity of 12 and price of 5 shillings in core compendiums.

When `Populate Items` feature of a Merchant rolls an `Arrow`, it assumes that a single instance of an item is being added.

**Describe the solution you'd like**
I would expect `Populate Items` feature to respect the Quantity of _rolled_ items, so in case of rolling an `Arrow`, I would like it to add `12` Arrows to the Merchant, not `1`.

Incidentally, if `Arrow` is rolled twice, it should add `24` Arrows ( 2 * 12 )

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/11304207/536a550b-6493-443f-bb36-3d5e11dfe35a)

Additionally, if it could automatically set the `Quantity For Price` field as well (but only when item is added via rolled entry from `Populate Items` RollTable), it would be even better, but I understand that might be a stretch and it could break compatibility with other systems.

**Comment by Haxxer** [comment]
Added in 2.7.7
