### ISSUE TITLE
[Roll Table not populating] - [DnD 5e] - When adding rolltables to merchant and clicking "roll" nothing happens.

### ISSUE THREAD

**Issue by GodOfTheHanged** [fantasycalendar/FoundryVTT-ItemPiles#420]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
After adding a roll table to a merchant, nothing is happening when I click "Roll Table"

**To Reproduce**

1. Go to 'Merchant Pile'
2. Click on 'Add Roll table'
3. Click on 'Roll table'
4. Nothing happens

**Expected behavior**
Expecting the tables to roll.

**Screenshots**
Cant add screenshot as nothing happens.

**Setup:**

- Foundry Version: [Latest]
- System Version: [Latest]
- Item Piles Version: [Latest]
- Browser & version [Google Chrome Latest]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Always HP
- Backpack Manager
- Better Roofs
- Carousel Combat Tracker
- Cautious Gamemaster's Pack
- Config Presets
- D&D 5E System Customizer (Havent used it yet)
- DF Curvy Walls
- Dice So Nice!
- Dice Tray
- Dynamic Effects using Active Effects
- Dynamic Soundscapes
- Epic Rolls 5e
- File Picker+
- Gatherer
- Hover Distance
- Image Context
- Inactive Tokens
- Ivan Duch's Music Pack
- Levels
- library: DF Module Buttons
- Light Switch
- Lock & Key
- MasterCrafted
- Media Optimizer
- Monks Modules
- Moulinette Modules
- Multiface Tiles
- Multilevel Tokens
- Polyglot
- Quick Doors
- Quick Insert
- Ready Set Rolls
- RPG Damage Numbers
- Sequencer
- Simplefog
- Situational Shortcuts
- Socket Macros
- Schotastic, Fantastic!
- TheRipper93's Module Hub
- Tidy5e Sheet
- Times Up
- Token Attacher
- Tokenizer
- Wall Height

**Additional context**

**Comment by Forien** [comment]
Must be one of your modules. Seems to work just fine with dnd5e

![](https://i.gyazo.com/caf67228a1b056ba1826f1acf4742cb2.gif)

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/11304207/d90f7df0-434e-49e7-88a4-53992d436c74)

### My testing setup:

Core Version: 11.306

System: dnd5e 2.2.2 (Atropos) 

Modules: 
forien-ammo-swapper 0.2.0 (Forien)
forien-copy-environment v2.1.9 (Blair McMillan, Forien)
forien-quest-log 0.7.12 (Michael Leahy (TyphonJS) - MLeahy#4299, Forien)
item-piles 2.7.5 (Wasp)
lib-wrapper 1.12.13.0 (Rui Pinheiro)
socketlib 1.0.13 (Manuel Vögele)
token-action-hud-core 1.4.16 (Larkinabout, Drental, ^ and stick)
token-action-hud-dnd5e 1.4.9 (Larkinabout, Drental, ^ and stick)

List generated with Forien's Copy Environment: https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment

**Comment by Haxxer** [comment]
Cannot reproduce, please run Find The Culprit to eliminate any external factors.
