### ISSUE TITLE
[BUG] - [WFRP4e] - Macros are not fired when Item is purchased

### ISSUE THREAD

**Issue by Forien** [fantasycalendar/FoundryVTT-ItemPiles#421]
### **Have you tried to reset Item Piles' system settings?**
Yes

## **Describe the bug**
When Item has set a `Purchase Macro`, it doesn't fire. 

I wanted to fire a macro straight from Compendium when Player purchased a Service.   
Then I tried imported macro.   
Then I tried this but on normal item and not a `Service`.   
Neither works.  

I made sure Player has permission to both see the World Macro and the Compendium I tried to run macro from.   
I made sure Player has permission to run macros. 

## **To Reproduce**

1. Set up a merchant
2. Set up an Item (preferrably a Service)
3. Give the Item a `Purchase Macro`
4. Buy the item as a Player, notice no macro fires
5. No error in console can be seen

## **Expected behavior**
When set a macro from Compendium a Player can see, I expect macro to be imported as a Player and then run. 

When set a macro from World, I expect it to run (if Player has permission to see the macro). 

## **Screenshots**
n/a 

### Setup:

- Foundry Version: [e.g. 11.306]
- System Version: [e.g. WFRP4e 6.6.1]
- Item Piles Version: [e.g. 2.7.6]
- Browser & version [e.g. Google Chrome 114.0.5735.199] 

###Active modules:

- Item Piles
- libwrapper
- socketlib
- Forien's Ammo Swapper
- Forien's Armoury
- Times Up
- some WFRP4e official content modules (Up in Arms, Winds of Magic, Archives of the Empire I and II, Imperial Zoo)

**Comment by Haxxer** [comment]
As discussed, it is PEBCAK
