### ISSUE TITLE
[BUG] - [Fallout 2d20] - Populate Loot Via Table Throws Error

### ISSUE THREAD

**Issue by theMagius0** [fantasycalendar/FoundryVTT-ItemPiles#423]
**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
The Following script on the Wiki:

> if (!canvas.tokens.controlled.length) return;
> for (const selected_token of canvas.tokens.controlled) {
>  await game.itempiles.API.rollItemTable("MY_TABLE_NAME_HERE", {
>    timesToRoll: "1d4+1",
>    targetActor: selected_token.actor,
>    removeExistingActorItems: false
>  });
> }
> await game.itempiles.API.turnTokensIntoItemPiles(canvas.tokens.controlled);

Throws the following error after upgrading to most current version of ItemPiles:

> transaction.js:34 Uncaught (in promise) TypeError: items is not iterable
>     at Transaction.appendItemChanges (transaction.js:34:22)
>     at PrivateAPI._addItems (private-api.js:178:23)
>     at async PrivateAPI._rollItemTable (private-api.js:2255:15)

**To Reproduce**

1. Replace "MY_TABLE_NAME_HERE" with a valid table in the Foundry game world (or compendium)
2. Click on a loot item placed on the Foundry map
3. Execute the script
4. See error (above)
5. Note that loot is not modified in any way

**Expected behavior**
Script was working perfectly before I updated to most current ItemPiles version today.

**Screenshots**
n/a

**Setup:**

- Foundry Version: [v10.291]
- System Version: [Fallout 2d20 v10.1.4]
- Item Piles Version: [v2.7.8]
- Browser & version [Google Chrome 115.0.5790.171 (Official Build) (64-bit)]

**Active modules:**

- Ace Library v;
- Ambient Doors v;
- Better Roll Tables v;
- Better Roofs v;
- Combat Enhancements v;
- Compendium Folders v;
- Dice So Nice! v;
- Drag Ruler v;
- Fallout Core Data (Shared Compendiums) v;
- FOCT: The Fire Down Below (Shared Compendiums) v;
- Forien's Copy Environment v;
- Foundry Community Macros v;
- FXMaster v;
- Health Estimate v;
- Hover Distance v;
- Item Piles v;
- Levels v;
- libWrapper v.0;
- LiveKit AVClient v;
- Macro Editor v;
- Macro Grid v;
- Mastercrafted - Crafting Manager v;
- Moar Folders v;
- Monk's Active Tile Triggers v;
- Monk's Combat Details v;
- Monk's Combat Marker v;
- Monk's Enhanced Journal v;
- Monk's Little Details v;
- Monk's Player Settings v;
- Monk's Scene Navigation v;
- Monk's TokenBar v;
- Multilevel Tokens v;
- Patrol v;
- Ping Logger v;
- PopOut! v;
- Raise My Hand v;
- Smart Doors v;
- socketlib v;
- The Forge v;
- Tidy UI - Game Settings v;
- Token Attacher v;
- Token Magic FX v;
- Token Mold v;
- Wall Height v;
- Z Scatter v;

**Additional context**
Was working with N-1 verison.

**Comment by theMagius0** [comment]
Note: I retried this test with ONLY the following conditions:

Reset ItemPiles: 
Yes.

Active Modules: 
-ItemPiles
-libWrapper
-SocketLib
-The Forge 

And saw the exact same error message.

**Comment by Ikabodo** [comment]
Can confirm this bug with the same settings, except the forge.

**Comment by Haxxer** [comment]
Fixed in 2.7.9
