### ISSUE TITLE
[BUG] - [5E] - Api openitempiles Banker type

### ISSUE THREAD

**Issue by tirzah2** [fantasycalendar/FoundryVTT-ItemPiles#426]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
game.itempiles.API.renderItemPileInterface(await fromUuid('Actor UUID'))
if i try to open a Item Piles of type Banker (banker module) instead of opening the Banker dialogue, it opens its inventory

**To Reproduce**
create this macro and run it on targetting a banker type actor

**Expected behavior**
Open the main banker dialogue

**Comment by Haxxer** [comment]
Added in 2.7.9 and item piles bankers in 1.0.9
