### ISSUE TITLE
Register prices beyond 3 digits as "Free" - Level Up A5e - cost value of 4 digits or more shows up as "free" on merchant sheet

### ISSUE THREAD

**Issue by Genocide-Games** [fantasycalendar/FoundryVTT-ItemPiles#429]
**Have you tried to reset Item Piles' system settings?**
I did not touch the settings, and left them in their default state

**Describe the bug**
When using item sheets to make a merchant, and putting an item in there with a 4 digit value or higher, the text reads out as free instead of the actual value (see image below) After a bit of investigation, it's revealed (in te second image) that it somewho mistook the item's weight as it's actual price.

**Expected behavior**
To have the actual price lsited (after the buy price modifier of 120% is applied)

**Screenshots**
![Foundry Virtual Tabletop 8_13_2023 9_18_41 AM](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/31664722/b925e3b5-aaac-4ccb-8d67-89d8a2cb5a3e)
![Foundry Virtual Tabletop 8_13_2023 9_32_24 AM](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/31664722/153c70dc-79c9-4681-83ed-c58e78a7c229)

**Setup:**

- Foundry Version: 11.307
- System Version: Level Up: Advanced 5th Edition V0.14.7
- Item Piles Version: 2.8.7
- Browser & version: Seen in the Foundry VTT program itself, did not test it with a browser

**Active modules:**
- A5e Concentrator
- Archon (Masked Item)
- Better Roofs
- Carousel Combat Tracker
- Combat Booster
- Combat Music Master
- Compendium Folders
- DND5e SRD Content (A5e)
- D&D Item Icons
- Dice So Nice
- Does it Hit!? (A5e)
- Domille's Wonder Works Scene Phaser
- Ecology of Gravitas
- FX Master
- Weather FX
- Hurry Up Combat Timer
- Initiate Double Click
- Item Piles
- Kobold Press Ogl (A5e)
- Library: Scene Packer
- Libwrapper
- socketlib
- Angela Maps
- Module Compatibility Checker
- Module Management+
- Active Tile Triggers
- Combat Details
- Combat Marker
- Enhance Journal
- Enhance Journal Objective Styles
- Scene Navigation
- Scene Enhancements
- TokenBar
- Multilevel Tokens
- Pull Players to Scene
- Rideable
- Rollable Tokens
- Simple Calender
- Weather Reports
- Ripper's Module hub
- Tile Scroll
- Token Attacher
- Token Frames
- Tokem Elevator
- Tokenizer
- Wall Heights
- Levels
- Weather Color Settings

**Comment by Genocide-Games** [comment]
Slight correction, the above about mistaking weight for price does not applie to all the potions, as the potion of flying has its price correctly listed in the settings yet for some reason is registered as free.

**Comment by Haxxer** [comment]
Why are the price of the item in pounds?

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/12858387/6c310c08-4105-4bf8-806f-382a11d47f19)

**Comment by Haxxer** [comment]
As for the reason why items in the thousands are broken, it might be because the system stores the comma in the item's price. Eg, 400 GP vs 4**,**000 GP.

**Comment by Genocide-Games** [comment]
> Why is the price of the item in pounds?
> 
> ![image](https://user-images.githubusercontent.com/12858387/260311842-6c310c08-4105-4bf8-806f-382a11d47f19.png)

no fucking clue

**Comment by Haxxer** [comment]
No need for profanity :) Please reset your item piles system settings in this case. Your settings must be broken and wrong, if that is the case.

**Comment by Haxxer** [comment]
Fixed in 2.7.9
