### ISSUE TITLE
[SYSTEM] - Old-School Essentials

### ISSUE THREAD

**Issue by justinthejaguar** [fantasycalendar/FoundryVTT-ItemPiles#43]
**https://foundryvtt.com/packages/ose**

### **Dynamic Attributes**: N/A

    
Miscellaneous Item (Such as gold)

      "type": "item",
      "img": "systems/ose/assets/default/item.png",
  
Container Item (Such as a backpack holding items)

      "type": "container",
      "img": "systems/ose/assets/default/bag.png",

Armor Item

      "type": "armor",
      "img": "systems/ose/assets/default/armor.png",

Weapon Item

      "type": "weapon",
      "img": "systems/ose/assets/default/weapon.png",

**Comment by Haxxer** [comment]
The dynamic attributes that you have provided are invalid. They are inputs on the character sheet like HP and hero points. If things are items, they are not considered dynamic attributes.

Here are other system examples:
[Tormenta20](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/37)
[SWADE ](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/25)
[DnD 3.5 SRD](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/24)

Please update this ticket accordingly.

**Comment by chrisesharp** [comment]
I just submitted a request for my `WWII:OWB` system, which is derived from OSE. 

@Haxxer @justinthejaguar  I think the details you need are:

Actor Class Type:`character`
Item Quantity Attribute: `data.quantity.value`
Item Filters: `ability, spell`
Item Similarities: `name, type`

Re: Dynamic attributes, there aren't any on the character that are relevant, but money it represented as items, and items have a `data.cost` attribute, if that helps?

**Comment by Haxxer** [comment]
As of the latest version of OSE and with Item Piles 1.4.4, you will no longer get a system incompatibility warning
