### ISSUE TITLE
[BUG] - [SWADE] - Adding items to vault changes token and name of container to added item

### ISSUE THREAD

**Issue by apostate9** [fantasycalendar/FoundryVTT-ItemPiles#431]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Adding loot to a player vault makes the icon and name change to "cloak" or whatever.

**To Reproduce**

1. As a player, approach the vault, called "chest"
2. Click, and add a sword.
3. See that the "chest" now looks like, and is identified as "sword".

**Expected behavior**
Adding items to a vault container should not affect it's apparent identity or artwork,

**Setup:**

- Foundry Version: [10.303]
- System Version: [SWADE]
- Item Piles Version: 2.7.3
- Chrome

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Fixed in 2.7.9
