### ISSUE TITLE
[REQUEST] - Compendium RollTables to populate item piles

### ISSUE THREAD

**Issue by dxwarlock** [fantasycalendar/FoundryVTT-ItemPiles#432]
**Is your feature request related to a problem? Please describe.**
No current bug or issue

**Describe the solution you'd like**
Able to select/filter to tables in compendium roll tables

**Describe alternatives you've considered**
None that I know of, any tables I export to compendium are not selectable to populate loor or merchants

**Additional context**
If this feature is available I seem to not be able to find it.

**Comment by Haxxer** [comment]
This is possible though macros:

https://fantasycomputer.works/FoundryVTT-ItemPiles/#/sample-macros?id=populate-loot-via-table

**Comment by Haxxer** [comment]
You have to use the UUID of the table:

https://fantasycomputer.works/FoundryVTT-ItemPiles/#/api?id=rollitemtable

Right click the little book icon in the header of the compendium.
