### ISSUE TITLE
[BUG] - [Pf1e] - Macro to fill with loot throws error

### ISSUE THREAD

**Issue by dxwarlock** [fantasycalendar/FoundryVTT-ItemPiles#435]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When using the macro from the wiki, I get a console error attempting to use it to fill an actor with loot.

**To Reproduce**
Use the macro listed below, replace table name with a table you have.
Click a token on the play area, execute macro

**Expected behavior**
Actor being populated with items, and converting to lootable.

**Screenshots**
Screenshot of macro, and table being called:
https://i.imgur.com/kXnsUB9.jpg

**Setup:**

- Foundry Version: [11.307]
- System Version: [Pf1e 9.4.66]
- Item Piles Version: [2.7.8]
- Browser & version [Google Chrome 109.0.5414.75]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
Using this macro:
`if (!canvas.tokens.controlled.length) return;
for (const selected_token of canvas.tokens.controlled) {
  await game.itempiles.API.rollItemTable("LOOTWands0", {
    timesToRoll: "1d4+1",
    targetActor: selected_token.actor,
    removeExistingActorItems: false
  });
}
await game.itempiles.API.turnTokensIntoItemPiles(canvas.tokens.controlled);`

throws:
`Uncaught (in promise) TypeError: undefined. items is not iterable
[Detected 2 packages: item-piles, socketlib]
    at Transaction.appendItemChanges (transaction.js:34:22)
    at PrivateAPI._addItems (private-api.js:178:23)
    at PrivateAPI._rollItemTable (private-api.js:2255:26)
    at Object.rollItemTable (socket.js:121:62)
    at SocketlibSocket._executeLocal (socketlib.js:192:15)
    at SocketlibSocket.executeAsGM (socketlib.js:90:16)
    at ItemPileSocket.executeAsGM (socket.js:181:25)
    at API.rollItemTable (api.js:1861:40)
    at async Macro.eval (eval at #executeScript (foundry.js:22792:16), <anonymous>:5:3)`

**Comment by Haxxer** [comment]
You are not on the latest version.

In which this bug has been fixed.

Please update.

https://github.com/fantasycalendar/FoundryVTT-ItemPiles/releases/tag/2.7.9
