### ISSUE TITLE
[BUG] - SWADE - Trader doesn't count item quantites when set as currency

### ISSUE THREAD

**Issue by Alekboldlin** [fantasycalendar/FoundryVTT-ItemPiles#437]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When player character is interacting with merchant items set as currencies aren't counted properly. Player can still buy item if he have enough money, but then all of this coin type disaaper from character sheet.

**To Reproduce**

1. Set up items as currencies
2. Create merchant with random items
3. Create player character with items set as currencies
4. Interact with merchant as player character
5. Buy something from merchant
6. Sell item to merchant

**Expected behavior**
Correct amount of money should be showed in right down corner of merchant window.
After transaction correct quantity of money should be removed or added.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/143077587/fd8d2bcb-517b-4693-a548-cc47bd09907a)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/143077587/88a8c370-67fd-40de-ab08-9912eb8ce818)

**Setup:**

- Foundry Version: 11.307
- System Version: 3.1.2
- Item Piles Version: 2.7.9
- Browser & version Google Chrome 116.0.5845.97

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- SWADE Core Rules
- SWADE Fantasy Currencies
- Warp Gate
- Advanced Macros

**Additional context**
Checking quantity in small Trading item window is showing correct values.

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/143077587/07deb774-46da-459f-b1aa-4cd4908154d4)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/143077587/f01a96de-8816-4d38-bb15-5322a4808457)

**Comment by Alekboldlin** [comment]
I tried reproduce this on cyberpunk Red system and finał result is the same.

**Comment by Alekboldlin** [comment]
I gave a character chem item and set quantity in character inventory.

**Comment by Alekboldlin** [comment]
As alternative I tried to set Savage Fantasy Currencies flags as currencies. It works for buying but not for selling. In both cases there are errors about permissions. It's far from system agnostic way of doing things, but wanted to add this as alternative solution or maybe extra feature in the future.
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/143077587/96fa6ebc-f998-4a7a-a77b-3d529f704f8a)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/143077587/f13ee03b-e399-47b9-a581-0562f16b7c64)

**Comment by Haxxer** [comment]
Was a GM logged in while you bought and sold? Item Piles requires that to be the case.

**Comment by Alekboldlin** [comment]
Yes, I am hosting on my PC, so I was logged as GM on application, and loged in as player from browser.

**Comment by Haxxer** [comment]
Fixed in 2.7.11
