### ISSUE TITLE
[QUESTION] - [PF1e] - Module forces table reset/normalize

### ISSUE THREAD

**Issue by dxwarlock** [fantasycalendar/FoundryVTT-ItemPiles#438]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
More a question than a bug. Is there a reason Item piles forces a reset/normalize on the tables? This changes how I use my tables, and refactored any table I used causing me to redo them all.
I managed to find the lines that do this, and commented them out, and module still works as expected (at least in all the use cases I use it).

I set my tables up as such, this is an example table I setup for testing:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/520536/4d6359e9-2625-423b-8c76-bff8b694274d)
So 1d100, and either has one of each item (50% of the time) or just the second one (100% of the time).

I setup all my tables to roll, and each row is a percentage chance of it getting one of those item in that row. _(Before using item piles, I used better roll tables for how many of each IF it has it, but that feature request is already in another ticket another person requested)_

When I roll a table, item piles forces it to calculate the weights and ranges. Making it so only one item ever can return from the tables. Not sure if I am missing some critical part of the module that requires the reset/normalize of the table.

**_Perhaps a middle ground option:_** Adding an option in the module settings if table reset/normalize is done?

**To Reproduce**
Create table that can return multiple items on a roll.
Populate an actor with either macro, or merchant UI tab table setup
Recheck table, its been recalculated for weights and ranges

**Setup:**
Foundry Version: [11.307]
System Version: [Pf1e 9.4.66]
Item Piles Version: [2.7.8]
Browser & version [Google Chrome 109.0.5414.75]

**Active modules:**
- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Fixed in 2.7.10
