### ISSUE TITLE
[BUG] - [PF2E] - Players cant open merchant

### ISSUE THREAD

**Issue by Crosant** [fantasycalendar/FoundryVTT-ItemPiles#439]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When setting up an merchant using item piles. Players arent able to view the resulting actor. Only the GM account which created it can view it.

**To Reproduce**

Create merchant actor and enable "Itempile Configuration"

**Expected behavior**
The player sees the merchant window

**Screenshots**
TypeError: An error occurred while rendering MerchantApp 120. pileData.actorPriceModifiers.find is not a function
[Detected 2 packages: item-piles, lib-wrapper]
    updatePriceModifiers merchant-store.js:221
    setupSubscriptions merchant-store.js:155
    make item-pile-store.js:83
    instance$x merchant-app-shell.svelte:21
    init index.mjs:2098
    Merchant_app_shell module.js:54134
    loadSvelteConfig loadSvelteConfig.js:90
    _injectHTML SvelteApplication.js:484
    _render foundry.js:5757
    _render SvelteApplication.js:872
    render foundry.js:5691
    show merchant-app.js:56
    show merchant-app.js:54
    _renderItemPileInterface private-api.js:2056
    _itemPileClicked private-api.js:1921
    registerLibwrappers libwrapper.js:11
    call_wrapper libWrapper-wrapper.js:616
    _onClickLeft2#0 libWrapper-wrapper.js:189
    callback foundry.js:31624
    #handleClickLeft2 foundry.js:31828
    #handleMouseDown foundry.js:31795
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerDown earcut.js:128
    mapEvent earcut.js:128
    onPointerDown earcut.js:128
    addEvents earcut.js:128
    setTargetElement earcut.js:128
    init earcut.js:128
    emit index.mjs:5
    run index.js:89
    un index.js:126
    wa index.js:89
    xn earcut.js:128
    #createApplication foundry.js:26189
    initialize foundry.js:26085
    initializeCanvas foundry.js:8814
    setupGame foundry.js:8644
    _initializeGameView foundry.js:9908
    _initializeView foundry.js:9884
    initialize foundry.js:8570
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:91546
    async* foundry.js:91522
foundry.js:753:30
    onError foundry.js:753
    call_wrapped libWrapper-wrapper.js:507
    <anonymous> listeners.js:135
    onError#0 libWrapper-wrapper.js:187
    render foundry.js:5693
    (Async: promise callback)
    render foundry.js:5691
    show merchant-app.js:56
    show merchant-app.js:54
    _renderItemPileInterface private-api.js:2056
    _itemPileClicked private-api.js:1921
    registerLibwrappers libwrapper.js:11
    call_wrapper libWrapper-wrapper.js:616
    _onClickLeft2#0 libWrapper-wrapper.js:189
    callback foundry.js:31624
    #handleClickLeft2 foundry.js:31828
    #handleMouseDown foundry.js:31795
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerDown earcut.js:128
    mapEvent earcut.js:128
    onPointerDown earcut.js:128
    (Async: EventListener.handleEvent)
    addEvents earcut.js:128
    setTargetElement earcut.js:128
    init earcut.js:128
    emit index.mjs:5
    run index.js:89
    un index.js:126
    wa index.js:89
    xn earcut.js:128
    #createApplication foundry.js:26189
    initialize foundry.js:26085
    initializeCanvas foundry.js:8814
    setupGame foundry.js:8644
    _initializeGameView foundry.js:9908
    _initializeView foundry.js:9884
    initialize foundry.js:8570
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:91546
    <anonymous> foundry.js:91522

**Setup:**

- Foundry Version: [e.g. 11.307]
- System Version: [e.g. Pf2E 5.3.2]
- Item Piles Version: [e.g. 2.7.9]
- Browser & version [ANY]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/889109/08ca7d2f-38e8-4a1e-ad5f-00fb6e014757)

**Comment by Haxxer** [comment]
Fixed in 2.7.11
