### ISSUE TITLE
[BUG] - [WFRP4e] - Merchants won't populate items with "Add all items" unchecked

### ISSUE THREAD

**Issue by Forien** [fantasycalendar/FoundryVTT-ItemPiles#445]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When using a Merchant that has set up Populate Items tab with multiple rolltables, if for any rolltable the `Add all items` checkbox **is not checked**, that rolltable will throw an Error.

**To Reproduce**

1. Setup a Merchant with Populate Items using Roll Tables
2. Make sure the `Add all items` is not checked
3. Try to populate Merchant using `Roll All Tables` button

**Expected behavior**
All tables are properly rolled.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/11304207/4485b4fe-1e1c-4024-aa85-2bb7f38921bd)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/11304207/feaaf18f-3156-4c3f-be0d-71849e679450)

**Setup:**

- Foundry Version: 11.308
- wfrp4e 7.0.1 (Moo Man, CatoThe1stElder) 

Modules: 
ATL 0.6.2 (Kandashi, kaelad)
forien-ammo-swapper 0.2.2 (Forien)
forien-armoury <<autoreplaced>> (Forien)
forien-copy-environment v2.2.0 (Blair McMillan, Forien)
forien-custom-utility 1.0.0 (Forien)
forien-easy-polls 1.0.1 (Forien)
item-piles 2.7.10 (Wasp)
itemacro <<autoreplaced>> (Kekilla, Honeybadger, Forien)
lib-wrapper 1.12.13.0 (Rui Pinheiro)
socketlib 1.0.13 (Manuel Vögele)
times-up 11.0.3 (tposney)
token-action-hud-core 1.4.18 (Larkinabout, Drental, ^ and stick)
token-action-hud-wfrp4e <<autoreplaced>> (Forien)
wfrp4e-archives1 4.0.0 (Moo Man, Published by Cubicle 7)
wfrp4e-archives2 4.0.0 (Moo Man, Published by Cubicle 7)
wfrp4e-core 4.0.0 (Moo Man, Published by Cubicle 7)
wfrp4e-up-in-arms 4.0.0 (Moo Man, Published by Cubicle 7)
wfrp4e-wom 4.0.0 (Moo Man, Published by Cubicle 7)
wfrp4e-zoo 4.0.0 (Jagusti, Moo Man, Published by Cubicle 7)

**Comment by dxwarlock** [comment]
Came to report the same issue.
Mine will not populate a merchant regardless of the number of tables. This is with just one table that is a 'table of other tables':
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/520536/330d6313-6e6e-4c24-a8f1-a3c25a53469b)

**Comment by Haxxer** [comment]
Fixed in 2.7.11
