### ISSUE TITLE
[BUG] - [D&D 5e] - Merchants stop responding after 2.7.10 update

### ISSUE THREAD

**Issue by Shayulghul** [fantasycalendar/FoundryVTT-ItemPiles#446]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
I can't open merchants after the recent update. I rolled back to 2.7.9, and that version works.

**To Reproduce**

1. Click an NPC that is set up as a merchant (nothing happens).
2. Turn off module, stop server, start game, turn module back on.

**Expected behavior**
Should work fine after an update.

**Screenshots**
<img width="492" alt="Screenshot 2023-09-04 at 7 58 08 AM" src="https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/81927456/ca12a94b-2ac5-4b1c-a30a-4ced05437b35">

**Setup:**
- Foundry Version: 10.303
- System Version: DND5e 2.3.1
- Item Piles Version: 2.7.10
- Browser & version Google Chrome 116.0.5845.110

**Active modules:**

- Item Piles
- libWrapper
- socketlib
- The Forge
- Tidy UI - Game Settings

**Comment by Haxxer** [comment]
Fixed in 2.7.11
