### ISSUE TITLE
[BUG] - [D&D5e] - Rollable tables not applying custom category

### ISSUE THREAD

**Issue by missmelisande** [fantasycalendar/FoundryVTT-ItemPiles#449]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Populated items on merchants from the rollable tables do not go into a custom category.

**To Reproduce**

1. Create a new merchant.
2. Add a rollable table with a custom category filled in the "Add items to custom category:" box.
3. Roll the table with Roll All Tables or individually.
4. Add item(s) to inventory with either the single arrow button or the "Add All Items" button.
5. Click on the buy items tab to check the category - it will be the item's normal (not custom) category.

**Expected behavior**
If a custom category is filled in for the rollable table, I would expect the item to be added to that custom category.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/136761195/bd3b8575-0f70-47fb-981d-ea0f9e188e43)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/136761195/2fdfb5e4-dae1-4eeb-92af-59209eed636a)

**Setup:**

- Foundry Version: 11.308
- System Version: DnD5e 2.3.1
- Item Piles Version: 2.7.12
- Browser & version Google Chrome 116.0.5845.142

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**

**Comment by Haxxer** [comment]
Fixed in 2.7.13
