### ISSUE TITLE
[REQUEST] - Turn all selected tokens into item piles button

### ISSUE THREAD

**Issue by Deadlander** [fantasycalendar/FoundryVTT-ItemPiles#45]
**Is your feature request related to a problem? Please describe.**
You have to select each actor separately to enable the Item Pile features.

**Describe the solution you'd like**
The option to enable Item Piles on all actors with one click.  Note:  Not to turn them into containers, just enable the pile feature.

**Describe alternatives you've considered**
Possibly be able to select multiple actors to enable it on.

**Additional context**

**Comment by Haxxer** [comment]
How do you imagine this be done? Where would this button or action be located?

**Comment by Haxxer** [comment]
Closed as no response was given

**Comment by Ikabodo** [comment]
I also see the need for this. Mostly to convert tokens to piles after a battle.

Three ways to do this on the top of my head:
1. Add a button to the left (convert all marked tokens to Item Pile)
2. Add a shortcut to convert marked tokens to piles
3. Add a token button on the token gui
