### ISSUE TITLE
Configuring currencies without using Items

### ISSUE THREAD

**Issue by kristianserrano** [fantasycalendar/FoundryVTT-ItemPiles#452]
I'm working on a PR for SWADE Fantasy Coins (SFC) that allows SFC to save its coin data to Item Piles' currency configuration for the setting.

I'm seeing the `data` property as an object used to create a new Item rather than copying an existing Item's data. This causes an error when the View button is clicked because IP is trying to get and remove data such as `._id` and `.ownership`, but it's not there.

I'm not sure if it's my means of adding the Item data that's incorrect (not using an actual Item) or if IP is making an incorrect assumption about the data.

Any help is appreciated.

**Comment by Haxxer** [comment]
Could you please show me your changes to your fork?

**Comment by kristianserrano** [comment]
Here's a link to the changes in the PR for SFC.
https://github.com/ddbrown30/sfc/pull/29/files

**Comment by kristianserrano** [comment]
I think I see my issue. I'm storing the actual data at the `data` level instead of the `data.item` level. I'm going to see if altering that fixes things.

**Comment by kristianserrano** [comment]
Yup that worked! Sorry to bother you!
