### ISSUE TITLE
[BUG] - [OSE] - Purchase from merchant removes all coins instead of price

### ISSUE THREAD

**Issue by coldmug** [fantasycalendar/FoundryVTT-ItemPiles#456]
**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
When purchasing from a merchant, the entire stack of currency is removed from a character's sheet, instead of the price charged. This applies to "change" currency as well. Currency that is not part of the quoted price is unaffected. 

This used to work in 2.7.9 but does not work in 2.7.10

**To Reproduce**

1. Create a merchant, add item with a price. Create a character with currency in their inventory. (In OSE this is explicit objects called "gold pieces" and the like). Place merchant and character on canvas.
2. As character, double click Merchant on canvas.
3. Click on purchase button. Price is displayed. Click on purchase item.
4. Check character sheet, entire stack of currency has been removed.

**Expected behavior**
Only the amount corresponding to the quoted price should have been removed from character's inventory.

**Screenshots**
N/A

**Setup:**

- Foundry Version: 11 Build 308
- System Version: Old School Essentials v1.9.3
- Item Piles Version: 2.7.10
- Browser & version: Google Chrome Version 116.0.5845.188

**Active modules:**

- Button Feel
- Color Picker
- Compendium Folders
- Dice So Nice!
- Dice Tray
- Dramatic Rolls
- Dungeon Draw
- Entice with Dice so Nice
- Filepicker Improvements
- Foundry VTT Anniversary Dice Set by The Rollsmith
- Health Estimate
- Item Piles
- libWrapper
- Lordu's Custom Dice for Dice so Nice
- Monk's Bloodsplats
- Monk's Combat Details
- Monk's Enhanced Journal
- Monk's Scene Navigation
- Monk's TokenBar
- Old-Shool Essentials: Advanced Fantasy for Foundry VTT
- OSR Helper Module
- Ownership Viewer
- Pin Cushion
- PopOut!
- Quick Insert - Search Widget
- Simple Calendar
- SmallTime
- socketlib
- Tabletop RPG Music
- Token Frames
- Token Mold
- Tokenizer
- Universal Battlemap Importer

**Additional context**
N/A

**Comment by Haxxer** [comment]
Fixed in 2.7.13
