### ISSUE TITLE
[BUG] - [PF2E] - system.level.value causes Merchant Columns to disappear on sheet reload

### ISSUE THREAD

**Issue by HydrallUrakan** [fantasycalendar/FoundryVTT-ItemPiles#458]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**

**To Reproduce**

1. Create a merchant item pile
2. Set up a column using `system.level.value`
3. Close and reopen the sheet

**Expected behavior**
The column _does_ properly appear after adding the column, at least until the sheet is reopened.

**Screenshots**
Before:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/94702225/800fc953-695c-40aa-b51c-08083e54b610)

After Adding:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/94702225/253d70bd-25bc-426f-9ea8-1e5b5205b2d2)
(Ignore the prices being different, I accidentally scrollwheeled on the price slider)

After Closing and Reopening:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/94702225/386858f2-7ba2-4b1e-bfb5-4d728b42a2f8)

**Setup:**

- Foundry Version: 11.308
- System Version: PF2e 5.5.2
- Item Piles Version: 2.7.12

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
I also had it happen once even without `system.level.value` being added, but only on sheets with `system.bulk.value` included - I wonder if it's something to do with the value selector?

**Comment by Haxxer** [comment]
Fixed in 2.7.13
