### ISSUE TITLE
Populating items from roll tables that contain text doesn't work

### ISSUE THREAD

**Issue by Klala** [fantasycalendar/FoundryVTT-ItemPiles#460]
So I tried populating a token with items with my roll tables. My roll table contains more text based results than compendia results and even the compendia results contain text in them since I use Inline Table Rolls.

I don't know whether it's a bug or something I'm missing. Is there a way to populate a token's inventory with text results?

**Comment by Haxxer** [comment]
What are the examples of text results? How am I to know what text relates to which item?

**Comment by Klala** [comment]
> What are the examples of text results? How am I to know what text relates to which item?

Text results are text results, just as if you'll copy and paste this sentence into the game's chat.
I figured that was the issue so I had to make sure it's not just me not doing it well.

In any case, what I would request is that perhaps text results should be added as generic new item without anything special set but only the text that was resulted.

An example for such an item is "Scroll of Detect Magic" Since I'm using PF1E, I have detect magic in the compendium as a spell but I don't have a scroll for each spell in any compendia unless I create it.

**Comment by Haxxer** [comment]
Since every system's item types are different, I don't know how I would pick the "right" item type for this, to be honest. I don't think it fits item piles as a whole, but if someone wants to make an update and create a pull request to add this behaviour, I will integrate it.

**Comment by Klala** [comment]
> Since every system's item types are different, I don't know how I would pick the "right" item type for this, to be honest. I don't think it fits item piles as a whole, but if someone wants to make an update and create a pull request to add this behaviour, I will integrate it.

I think I have a lead for you if you'll take it.
Fair Strides, the developer of the SBC module for PF1E pretty much have such a feature in that module.
The module takes text statblocks and creates character sheets. The important part related to this subject is the way it creates the items the statblock has if any. It basically creates a generic item with a generic icon but with the name of what was in the text.
Maybe try asking or looking at it? I'll understand if you deem it too complicated either way :D
