### ISSUE TITLE
[BUG] - [Forbidden Lands] - Item Pile not being created on drag/drop to canvas

### ISSUE THREAD

**Issue by Orlanth-Rex** [fantasycalendar/FoundryVTT-ItemPiles#461]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Item piles not being created on canvas

drop-item-dialog.js:50 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'uuid')
    at DropItemDialog.show (drop-item-dialog.js:50:42)
    at PrivateAPI._dropItem (private-api.js:1775:43)

**To Reproduce**

1. Go to items tab
2. drag item to canvas

**Expected behavior**
Item pile created

**Screenshots**
Nothing relevant to show

**Setup:**

- Foundry Version: [e.g. 9.238]
- System Version: [e.g. DND5e 1.5.7]
- Item Piles Version: [e.g. 1.0.0]
- Browser & version [e.g. Google Chrome 98.0.4758.82]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**

**Comment by Haxxer** [comment]
Fyi, the invalid tag refers to an invalid ticket, which this is not.

**Comment by Haxxer** [comment]
It is a system issue;

https://discord.com/channels/170995199584108546/751202281172762675/1156703645400834130

Closing for now, since it's not something I can fix.
