### ISSUE TITLE
[BUG] - Cannot drop items on existing pile without Midi QoL

### ISSUE THREAD

**Issue by colinbate** [fantasycalendar/FoundryVTT-ItemPiles#47]
**Describe the bug**
When attempting to drop an item on an existing pile token, nothing happens. There is an exception raised in the console, specifically: `Error: This is not a registered game setting`.

It is initiated on line 1992 of the `api.js` file. When a check is made to see if the `DragDropTarget` is enabled in `midi-qol`, that check fails with an exception if the `midi-qol` module is not installed.

**To Reproduce**
1. Configure a World without Midi QoL enabled
2. Create an item pile
3. Attempt to drag an item from the items sidebar onto the pile.
4. See the error in the console. Nothing happens. Item is not added to the pile.

**Expected behavior**
Would expect the item to be in the inventory of that pile after step 3.

**Setup:**
 - Foundry Version: 9.245
 - Item Piles Version: 1.3.0
 - OS: macOS
 - Browser: Chrome
 - Version: 96

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - Not `midi-qol`

**Comment by Haxxer** [comment]
Fixed in 1.3.2
