### ISSUE TITLE
[REQUEST] - Manual Update merchants

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-ItemPiles#470]
Merchants can update their services and items using the calendar option to do it automatically, but in a world where I have many merchants, these checks take a lot of resources.

It would be interesting to have a way to do it manually, directly in the token (without having to open the store for this)

or even better, a macro that updates the items of the merchants that are on the scene. is it possible?

**Comment by Haxxer** [comment]
Added in 2.8.0 as `game.itempiles.API.refreshMerchantInventory(token)`
