### ISSUE TITLE
[REQUEST] - allow group members to get discount

### ISSUE THREAD

**Issue by dracolumina** [fantasycalendar/FoundryVTT-ItemPiles#472]
Allow members of a group to get actor adjustment on price.

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/7224999/8255a1c3-9843-4da3-8abc-e7413480dce1)

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/7224999/ae9249d1-3744-4596-835b-58c16b821604)

**Comment by Haxxer** [comment]
As group actors are a system specific thing, it does not exist in most other systems, meaning that this task would have to modify Item Piles at its core to allow this sort of thing.

**Comment by dracolumina** [comment]
ahh ok, was hoping it would be easier than that since the group is "still considered an actor"

**Comment by Haxxer** [comment]
Added in 2.8.0
