### ISSUE TITLE
[BUG] - [OSE] - Cannot populate merchant containe undefined 'exchangeRate'

### ISSUE THREAD

**Issue by coldmug** [fantasycalendar/FoundryVTT-ItemPiles#473]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When adding items to a merchant pile nothing is added, and an error is sen in console: "TypeError: An error occurred while rendering MerchantApp 155. Cannot read properties of undefined (reading 'exchangeRate')"

Once a merchant has been created and items attempted to be added, double clicking the actor will not open the merchant sheet, issuing the above error in console. 

**To Reproduce**

1. Create an actor, change to item pile. Modify to "merchant". 
2. Try to add an item in "Populate Items" tab.
3. Item is not added, and error is seen in console (as above).

**Expected behavior**
Last version that worked was 2.7.9.
1. Double clicking the merchant actor should open merchant sheet.
2. Adding items to merchant in "Populate Items" tab should add items.

**Screenshots**

**Setup:**

- Foundry Version: [11 Stable, build 311]
- System Version: [Old-School Essentials 1.9.2]
- Item Piles Version: [2.7.19]
- Browser & version [Google Chrome 117.0.5938.152]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
N/A

**Comment by Haxxer** [comment]
Should be fixed in the latest version.

**Comment by coldmug** [comment]
It works! Thank you for the quick fix!
