### ISSUE TITLE
Support for Token - On Click trigger for Containers / Piles for traps and additional behaviors

### ISSUE THREAD

**Issue by Spuznik** [fantasycalendar/FoundryVTT-ItemPiles#477]
When you have an Item Pile that you want to treat as if it is a trap you need to manually manage this.

Have the On Interact Macro fire before the Item Pile is opened with a double click or a choice of a before or after open macro

Tested using other modules to get around this issue only method I can see is to place a tile around the token and use MATT to trigger the dialog for disarm etc of a trap, but the doesn't force the players to do so.

**Comment by Haxxer** [comment]
This is possible with macros now - interaction macros now fire when an item pile UI is rendered, and can be interrupted by returning `false` in the macro
