### ISSUE TITLE
Ability to split a portion of the currency with players.

### ISSUE THREAD

**Issue by OregonPinkRose** [fantasycalendar/FoundryVTT-ItemPiles#48]
Would love to be able to split a certain amount with actors. If there is 765 gp, maybe they each get 50 and the rest stays for the group resources later. 
There is no way to only split a designated amount at this time. It's all or nothing. 

An input interface would work. The ability to type in how much you want to split with the actors. Or all.

**Comment by Haxxer** [comment]
Please follow the request ticket template.
