### ISSUE TITLE
[BUG] - [DnD5e / Agnostic] - item nonstacking issues

### ISSUE THREAD

**Issue by Zarhog** [fantasycalendar/FoundryVTT-ItemPiles#480]
sorry about not following your structure but im making this as a reminder based on what we talked about 

- When an item that dose not stack is dragged into an item pile other than a vault it seems to increase the count of the item instead of creating a sepereate instance of the item.
- Weather or not if an item stacks should A. Be determined by the Pile settings and if not then B. Be determined by the item settings.
- I imegen the merchant would check against there own setting then the item setting, if item is set to default then go by merchant setting. If item is set to anything but default go by item settings 

to quote you:

There are multiple layers to it:
If a GM adds an item to the merchant, or a player sells an item, or a table rolls an item and adds it to the merchant, I need to check if the item exists on the merchant, if it does, I need to check if the item can stack or not, and then compare that against the merchant's setting, and maybe create a new item, maybe add quantity to the existing item
If a player buys an item, I need to check if the item was previously stacking, and reset it back to what it was before the merchant changed it.
There are a lot of places that I would need to make sure works
It's not just "when this then do this", there are a lot of parts of the code that would need to correctly add items
It's a fundamental change deep in the code that has a huge impact across all parts of item piles

**Comment by Haxxer** [comment]
I think this has been added with the last few updates. Let me know if this issue still persists.

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/12858387/5cd42642-e196-4ab8-83a1-d6a200e521e5)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/12858387/15af72ee-15be-4e26-8dfe-608ec8981e77)
