### ISSUE TITLE
[BUG] - [Warhammer Fantasy Roleplay 4th Edition] - Item Piles duplicating coins on the trappings type

### ISSUE THREAD

**Issue by warhammering** [fantasycalendar/FoundryVTT-ItemPiles#486]
**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
In the Warhammer system is duplicating the coins in the trappings since it create a new version on the item piles backup
https://cdn.discordapp.com/attachments/928423439281324063/1175885994478805052/image.png?ex=656cdc2b&is=655a672b&hm=985315749b568b877816c3b20cf5047d2644c7d6593ca749803c62df2b186a50&
https://cdn.discordapp.com/attachments/928423439281324063/1175886417935745114/image.png?ex=656cdc90&is=655a6790&hm=d49bd5cab41ef1fe9d43421c56c8b15c45e10349cbebebd3cae870be13481981&
**To Reproduce**
Create a new character, character or npc
Go to the trappings tab and there should be a duplication of the coins
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/140810683/1473c3c4-f452-4255-b199-4372ccd90a77)

**Expected behavior**
There should not be any duplication of items there should only be 1 type of coin

**Setup:**

- Foundry Version: [11.315]
- System Version: [wfrp4 7.0.3]
- Item Piles Version: [2.8.1]
- Browser & version [Brave v1.60.118]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/140810683/4eca1bf1-9fe6-46c1-a97d-629fca8bb4a2)

**Additional context**
After a while it creates more coins in the trapping

**Comment by warhammering** [comment]
wfrp4e: 7.0.3
wfrp4e-altdorf: 4.0.1
wfrp4e-archives1: 4.0.2
wfrp4e-archives2: 4.0.2
wfrp4e-core: 4.0.2
wfrp4e-dotr: 4.0.2
wfrp4e-eis: 4.0.1
wfrp4e-empire-ruins: 4.0.2
wfrp4e-horned-rat: 4.0.2
wfrp4e-middenheim: 4.0.2
wfrp4e-owb1: 4.0.2
wfrp4e-pbtt: 4.0.2
wfrp4e-rnhd: 4.0.1
wfrp4e-salzenmund: 4.0.1
wfrp4e-starter-set: 4.0.0
wfrp4e-ua1: 4.0.1
wfrp4e-ua2: 4.0.2
wfrp4e-up-in-arms: 4.0.1
wfrp4e-wom: 4.0.1
wfrp4e-zoo: 4.0.1
Active Modules: Inline-Table-Rolls, LocknKey, SharedVision, about-face, about-time, autoanimations, background-volume, baileywiki-cabal-dungeon, baileywiki-city-district-01, baileywiki-landing-pages, baileywiki-maps-premium, baileywiki-maps-premium-towns, baileywiki-nuts-and-bolts, betterroofs, bhk-errt, calendar-weather, chat-images, color-picker, colorsettings, config-presets, cursor-hider, dd-import, dice-calculator, dice-so-nice, drag-ruler, dragupload, dynamic-soundscapes, easy-target, entice-with-dice-so-nice, fateroll, filepicker-plus, find-the-culprit, foundry-taskbar, foundryvtt-simple-calendar, fvtt-party-resources, fvtt-syrin-control, fxmaster, gatherer, give-item, go-to-player, healthEstimate, hover-distance, image-context, image-hover, inactive-tokens-lmao, item-piles, jb2a_patreon, journal-thumbnail, lessfog, levels, levels-layer-effects, levelsautocover, levelsvolumetrictemplates, lib-wrapper, light-switch, macro-folders, macro-manager, macro-wheel, mastercrafted, media-optimizer, module-credits, monks-active-tiles, monks-combat-details, monks-common-display, monks-hotbar-expansion, monks-little-details, monks-scene-navigation, monks-sound-enhancements, monks-tokenbar, monks-wall-enhancement, moulinette-core, moulinette-gameicons, moulinette-imagesearch, moulinette-scenes, moulinette-sounds, moulinette-tiles, multi-token-edit, multiface-tiles, multilevel-tokens, narrator-tools, omniscient-die, patrol, permission_viewer, playlist-down, playlist-drag-and-drop, popout, popout-resizer, progress-tracker, quick-doors, quick-insert, quickdraw, quickscale, ready-check, scene-packer, scenery, select-tool-everywhere, sequencer, settings-extender, sidebar-resizer, smalltime, smarttarget, socketlib, splatter, super-select, svt, tagger, theripper-premium-hub, tile-scroll, tile-sort, token-action-hud-core, token-action-hud-wfrp4e, token-attacher, token-hud-wildcard, token-mold, token-notes, token-z, tokenflip, tokenmagic, tokenmagic-automatic-wounds, tomcartos-ostenwold, trs-foundryvtt-dice-set, trs-hyperdrive-console-dice-set, user-latency, wall-height, warpgate, weather-control, weatherblock, wfrp4e-eis-maps, wfrp4e-gm-toolkit, what-the-flag, zoom-pan-options, forge-vtt, forge-vtt-optional

**Comment by Haxxer** [comment]
I believe this to be fixed.
