### ISSUE TITLE
[REQUEST] - Allow DM to disable currency division

### ISSUE THREAD

**Issue by kiloforce** [fantasycalendar/FoundryVTT-ItemPiles#488]
*Module Unable to Correctly Determine Players*
Module wants to split currency 7 ways, but I only have 4 players.

7 players, in a 4 player game?
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/433058/1053d4bf-506f-4cb9-b211-683262291755)

I have a "test" player, and an "observer" player, and the players have some summon friendly pets. How exactly is it calculating 7 players, and can I override which players it selects?

The easiest solution would be an option for the DM to disable this forced auto division.  Should still leave the "split currency X ways" button for those that want to auto split.  For auto division the module really needs option to override the players it divides among.  Thanks

(_Similar to Issue #50, but requesting option for DM to disable for campaign, not for players to make choice_)

**Comment by Haxxer** [comment]
This is located in the item piles' configuration. It can be found when editing the settings on individual item piles.
