### ISSUE TITLE
[BUG] - [v11] - Item piles are prefilled with invalid items

### ISSUE THREAD

**Issue by somedndaccount** [fantasycalendar/FoundryVTT-ItemPiles#489]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Newly created item piles in v11 have some historically created items in there. removing them or deleting them from the sheet is not possible and results in an error since the ID cannot be found
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/85035427/2263bd48-8198-45bc-85aa-58e1ec8c0f93)

**To Reproduce**

Use item piles in earlier version
Update to v11
delete itempiles module, restart game and enable
Create an item pile or interact with existing ones
Item Pile has the item in it and several invalid ones
they cannot be removed by setting to 0, moving them out, going to the sheet and trying to delete them - they are stuck.
Interacting with them gives and error
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/85035427/e8914e11-0646-4715-86a8-8bf211883da7)

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/85035427/9f713354-fc93-4776-a9f7-dd57b20eb8a8)

**Expected behavior**
Item pile has the one item in that you dragged on the map
and/or: faulty items can be deleted centrally to restore the expected behaviour

**Setup:**

- Foundry Version: 11.315
- System Version: PF1e
- Item Piles Version: 2.8.3
- Browser & version: in client

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- a lot - i think it's not module related

**Additional context**

**Comment by Haxxer** [comment]
Can you check if your default item pile has a linked token, and whether it has items stored in it? The default item pile is used anytime you create a new item pile, so its content gets duplicated. Could you also try with just item piles and its dependencies to see if it is truly an item piles module issue?

**Comment by somedndaccount** [comment]
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/85035427/d7c4d44d-d90c-41d6-ba97-5f996aef96cd)
after disabling all modules, it actually migrated something, and now the token appears to be functioning as expected.
thank you.

**Comment by somedndaccount** [comment]
small followup question if you check this out again - previously i could open a newly created pile, immediately save it and the token on the map would change to the name of the item inside it - is that removed functionality or did i miss a setting somewhere?

**Comment by StevenEvans1966** [comment]
I created a wfrp game with no other modules but item piles.  I place 2 item piles on a scene, reloaded the game. Found all the items on the scene had been coped to the default item and both piles contain their items plus the other pile's item.

there appears to be some migration happening not sure why as this is a clean world with the latest versions
 
I have included the log for completeness

[error.log](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/13504545/error.log)

**Comment by rinnocenti** [comment]
For me, markets without a link to the original actor do not update and issue errors. Even though the link has already been updated, it tries and keeps trying, causing slowdowns in the system.

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/3178127/00b93c6f-bb5e-4f77-bcbd-f76ff83a47f3)

**Comment by Haxxer** [comment]
@rinnocenti @StevenEvans1966 @somedndaccount Sorry for the issue, do you think you could test this beta release and see if the duplication bug still occurs?

https://github.com/fantasycalendar/FoundryVTT-ItemPiles/releases/download/2.8.!4/module.json

**Comment by StevenEvans1966** [comment]
I reopened the test world.  some errors where reported but both the scene piles and the default had there correct contents.  A second reopen produced no errors.

**Comment by Haxxer** [comment]
Excellent. You should be able to update item piles, and this bug should be no more.
