### ISSUE TITLE
[BUG] - [DND 5e] - SimpleCalendar

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-ItemPiles#490]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**

**To Reproduce**
When the time is running out it keeps sending this error to the console.

I don't know exactly why, but it appears that he is trying to access some actor, but I have so many (in side bar) that I don't know which one.
but I'm in a scene with only 1 item pile (container)

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/3178127/054aa48f-5f93-4545-909f-4f489b922889)

**Setup:**

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/3178127/8b178ead-ee79-4824-86c2-975fc7bc4233)

**Active modules:**

All necessary + Simple Calendar

**Comment by Haxxer** [comment]
You have enabled inventory refresh on simple calendar date change. Check your merchant's settings, but I will fix the bug.

**Comment by Haxxer** [comment]
I may have fixed it in 2.8.4
