### ISSUE TITLE
[BUG] - [PF2e] - Merchant money exchange not working

### ISSUE THREAD

**Issue by sphynx22** [fantasycalendar/FoundryVTT-ItemPiles#491]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When buying an item from a merchant if you don't have the exact type of coin it costs, it will still let you buy but won't reduce your money.

**To Reproduce**

1. Open a merchant while controlling a character
2. Try to buy an item without the right type of currency on the character

**Expected behavior**
When buying without the exact type of coin it should remove a bigger value coin and give you a change in the smaller value coin.

**Screenshots**
[vokoscreenNG-2023-12-04_02-57-27.webm](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/13906473/291ba2b1-1378-4d6c-b120-d392182b8451)

**Setup:**

- Foundry Version: 11.315
- System Version: PF2e 5.10.3
- Item Piles Version: 2.8.5
- Browser & version: Brave 1.60.118 (Chromium: 119.0.6045.163)

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
In my main campaign I'm using more modules but in the video it's a new world with only item piles and its requirements, using almost default settings. Enabled Infinite Quantity and Infinite Currencies.

**Comment by EternalRider** [comment]
also happens on swade.
and in swade, this problem cause negative number money.

**Comment by Haxxer** [comment]
Bug has been reproduced, fix coming sometime tonight

**Comment by Haxxer** [comment]
Fixed in 2.8.6
