### ISSUE TITLE
[REQUEST] - Conditions for item piles take action

### ISSUE THREAD

**Issue by Enthropx** [fantasycalendar/FoundryVTT-ItemPiles#502]
**Is your feature request related to a problem? Please describe.**
Sometimes, you want your players to be able to take someting from a pile only if they have a certain item (say for exemple they can take the monster fluid only if they have a vial).

**Describe the solution you'd like**
It would be nice to be able to put "conditions" for items when they are in an item pile: having a certain item, a certain AE, a certain ability score, maybe others?

**Comment by Haxxer** [comment]
Have you looked into Lock & Key? This module already has support for this feature, so I will not be adding it.

**Comment by Haxxer** [comment]
Oh, sorry, I misunderstood your request - in any case, this is a very system specific implementation. As you can see here:

https://fantasycomputer.works/FoundryVTT-ItemPiles/#/?id=natively-supported-systems

Item Piles supports 30+ systems, and adding game system specific behavior such as this would be very hard. Perhaps a different module can add support within the game system you play within to use the hooks that item piles provides.
