### ISSUE TITLE
[BUG] - [D&D 5e] - Compatibility with the Rarity Colors module

### ISSUE THREAD

**Issue by GabrielOsvair** [fantasycalendar/FoundryVTT-ItemPiles#504]
**Describe the bug**
Currently, colors do not appear in the Item Piles module sheets.

 https://github.com/p4535992/foundryvtt-rarity-colors/issues/11

**Screenshots**
Tidy5e Sheet:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/67530921/106332f6-bea9-4a77-8d6b-cb8d21d4d639)

Item Pile Type: Item Pile:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/67530921/134095fa-892a-4d31-b218-135c83887406)

Item Pile Type: Container:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/67530921/3a13215f-0b48-44a6-9665-0e6ae4697e06)

Item Pile Type: Merchant:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/67530921/046eb89f-2a0c-4b87-85a9-5daae6ababd7)

Item Pile Type: Valt: _The colors are from the Item Piles module_
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/67530921/d0928b53-32d3-4102-bd16-560b3569f987)

**Setup:**
- Foundry Version: v11 b315
- System Version: D&D 5e v2.4.1
- Item Piles Version: Latest
- Browser & version: FLC v4.3.1

**Comment by Haxxer** [comment]
Fixed in 2.9.0

**Comment by adunis** [comment]
Is this fixed? Iḿ on 2.9.1 ItemPiles and on 0.3.18 Rarity Colors but it doesn´t seem to work

**Comment by kftb** [comment]
+1. It doesn't seem to work for me either. @adunis Did it every start working for you?
