### ISSUE TITLE
[BUG] - [PF2E] - All pile types work but vaults

### ISSUE THREAD

**Issue by jayleew** [fantasycalendar/FoundryVTT-ItemPiles#509]
**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
Dragging items into a vault as GM doesn't work, either from compendium or other actors.

**To Reproduce**
1. Create a Vault
2. Drag Healing Potion from compendium as GM

**Expected behavior**
Nothing happens. 

**Screenshots**

**Setup:**

- Foundry Version: [11.15]
- System Version: [PF2E 5.6]
- Item Piles Version: [2.8.16]
- Browser & version [Chrome & Edge]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- ![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/13368496/3edff7e1-5816-400f-b2e8-c0ad1128e626)
- 
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/13368496/e5045b0f-052c-4682-91a1-75dd1585d5de)

**Additional context**

**Comment by jtsmirror** [comment]
5e also don't work

**Comment by Haxxer** [comment]
This should work in 2.8.17

**Comment by jayleew** [comment]
Works now on 2.8.17!
