### ISSUE TITLE
Loot fill quantity issue with API

### ISSUE THREAD

**Issue by dxwarlock** [fantasycalendar/FoundryVTT-ItemPiles#512]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Using the API to fill a actor with items does not act the same as using the Roll all tables option on the actors sheet

**To Reproduce**
Use the macro
`game.itempiles.API.rollItemTable(table, {timesToRoll: 1,targetActor: tokens[0].actor,removeExistingActorItems: true });`

And a betterrolltable table, it only populates 1 item, regardless of the better tables settings.
Table settings:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/520536/449bb16b-06fc-4dab-bec5-582bf633992a)
What it produces
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/520536/9d60bab5-c619-4905-b6a2-8dbb37acbbb7)

When using the button on the actor sheet itself, it complies with the quantity options:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/520536/7773ed8f-07e2-4fea-a593-d28104db70d9)

**Expected behavior**
Both should produce the same results.

**Screenshots**
Shown above.

**Setup:**
- Foundry Version:11.315
- System Version: pf1e 9.4
- Item Piles Version: 2.7.12 (2.8.16 does not work at all, produces no items with no error)

**Active modules:**
Reduced down the ones needed for itempiles and bettertables (v 1.9.3) for this scenario to test.

**Comment by Haxxer** [comment]
I do not personally use Better Tables, this user provided the implementation to fix it based on changes to better tables:
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/pull/496

**Comment by Haxxer** [comment]
Make sure you have fully updated BetterTables and Item Piles to their latest versions.

**Comment by dxwarlock** [comment]
Do I need to incorporate #$96 into them manually?
If I update both, I get no errors in console, but also no item generated at all on API call.

**Comment by Haxxer** [comment]
No - the PR is already in Item Piles - this means that either that user badly implemented their solution, or BetterTables has updated once again.

**Comment by dxwarlock** [comment]
Thanks, I will dig into it. It may be a BRtables issue. Thanks for the quick response time.

**Comment by Haxxer** [comment]
Fixed in 2.9.0
