### ISSUE TITLE
[BUG] - Not populating off of table rolls

### ISSUE THREAD

**Issue by dracolumina** [fantasycalendar/FoundryVTT-ItemPiles#513]
**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
When I try roll the table to populate the merchant (and when the day starts and it is suppose to repopulate) it throws the following error.
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/7224999/2e23e65a-3bf3-4601-a9b7-e29dbb021cd8)

**To Reproduce**

1. Go to 'Populate Items'
2. Click on 'Roll Table'
3. Nothing happens
4. error in console

**Expected behavior**
Table rolls fine if rolling from the table window

**Screenshots**

Multiple browsers
foundry current
all modules current

**Comment by Bradeck** [comment]
I also have this problem, tested with only Item Piles and his dependencies activ, in Chrome.

**Comment by felixleonhart** [comment]
same

**Comment by Haxxer** [comment]
Fixed in 2.8.19
