### ISSUE TITLE
Could you add a shortcut key that would toggle a token into a item pile? 

### ISSUE THREAD

**Issue by VisionsVortex** [fantasycalendar/FoundryVTT-ItemPiles#515]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Haxxer** [comment]
Please fill out the ticket.

In any case, have you taken a look at the wiki?
https://fantasycomputer.works/FoundryVTT-ItemPiles/#/sample-macros
