### ISSUE TITLE
[REQUEST] - Option to Use Token Image

### ISSUE THREAD

**Issue by Larkinabout** [fantasycalendar/FoundryVTT-ItemPiles#516]
**Is your feature request related to a problem? Please describe.**
I haven't found an option to do this, so forgive me if it already exists. I have set up multiple item piles in the Actors tab, so that they can be dragged and dropped onto the canvas, however, when I do this, the token image seems to use the item image rather than the actor's token image.

**Describe the solution you'd like**
I would like an option to use the token image when dropping the item pile actor to the canvas as my item pile images are round tokens with a frame, whereas my item images are square without a frame.

**Describe alternatives you've considered**
Replacing the token image once the item pile is added to the canvas, however this is cumbersome.

**Additional context**
Foundry: 11.315
System: dnd5e 2.4.1
Module: Item Piles 2.8.18

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/105953297/9014e2f0-d70c-4dff-a8dd-16129efcb6ce)

**Comment by Haxxer** [comment]
Have you checked the settings on the item piles in question? There is a setting in the Other Settings of each item pile that can be set to use the only item's image as the token image, which is enabled by default.

**Comment by Larkinabout** [comment]
This one?:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/105953297/6ffc8a77-d2b3-4757-aec7-600b3909bfd7)

I have disabled it, but when dragging the actor to the canvas, it still seems to use the item image. Or, at least it doesn't use the prototype token image. I'm not sure if the resulting square image is coming from the item or the avatar. NB, the prototype token image is set to the Tokenizer's token image file.
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/105953297/d2cf3cf4-bc4a-4370-8977-7d02b1db3ecc)

**Comment by Haxxer** [comment]
What if you disable most modules except item piles and its dependencies? Does it still happen?

**Comment by Larkinabout** [comment]
> What if you disable most modules except item piles and its dependencies? Does it still happen?

Yes, all other modules disabled except for Item Piles, libWrapper and socketlib.

Interestingly, if I add a second different item, the prototype token image is used. It seems to only be when the item pile has only one item. Also, quantity of the single item doesn't make a difference.

**Comment by Haxxer** [comment]
That's telling me the setting is still enabled. Make sure the token on the scene also has it disabled, as it might not be linked with the one you are asking the item to.

**Comment by Larkinabout** [comment]
Made a video as I tried a few options. Sorry it's a bit sped up and low quality, has to get it under GitHub's 10mb limit:
![item-piles-token-image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/105953297/60faaced-e691-490c-b5db-032840738cc8)

**Comment by Haxxer** [comment]
Can you contact me, Wasp, through Discord instead? This form of communication is not ideal.

**Comment by Haxxer** [comment]
Solved according to discord conversation, partial user mistake, partial strange bug.
