### ISSUE TITLE
Merchant pile error - PF2e

### ISSUE THREAD

**Issue by neilhatcher** [fantasycalendar/FoundryVTT-ItemPiles#517]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When attempting to add an item to a Merchant item pile, the item is free and when bought (which does not always work), it shows errors for bulk and the item cannot be edited on the character sheet.

**To Reproduce**

1. Create merchant item pile.
2. Add item (see console error below)
3. Have PC actor (attempt to) buy it

**Screenshots**
<img width="1915" alt="item_add" src="https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/26612249/60959e1d-d877-4693-bcfc-e7aa6a5a6806">

<img width="604" alt="merchant" src="https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/26612249/fc9767c4-c802-4d9a-904c-eddcfe9e7203">

<img width="1397" alt="purchase" src="https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/26612249/70f26ec3-1ac7-4a14-bc0a-dc2dfb29a1be">

**Setup:**
- Foundry Version: 11.315
- System Version: PF2e 5.12.7
- Item Piles Version: 2.8.19
- Browser & version FLC 4.3.1

**Active modules:**
- Item Piles
- libwrapper
- socketlib

**Additional context**
Error exists with both with current PF2e game (many mods) and a new world with only system and Item Piles mods. Also tested with new world running current 5e system, no error.

**Comment by Haxxer** [comment]
Should be fixed in 2.8.20

**Comment by neilhatcher** [comment]
I tried all the tests again and everything appears to be back to normal.
