### ISSUE TITLE
[BUG] - [SIMPLE WORLDBUILDING] - Vault open when log in

### ISSUE THREAD

**Issue by Manume96** [fantasycalendar/FoundryVTT-ItemPiles#519]
**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
Everytime I log in as a GM (it happens in app and browser as well) a token vault windows is opened. Is not a big headache but i prefer this to not happen.

**Setup:**

- Foundry Version: 11
- System Version: Simple World-Building 0.8.2
- Item Piles Version: 2.8.7

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
I would... recommend updating item piles.

**Comment by Haxxer** [comment]
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/12858387/ce311670-8150-4a4c-a686-a4fe4589bd44)

**Comment by Manume96** [comment]
Done it, same thing happens.

**Comment by Haxxer** [comment]
There's nothing in my code that opens any windows automatically. You can confirm that this happens with only the modules you specified as active? What about a fresh world? Do you have any world scripts that are run during the world's setup?

**Comment by Haxxer** [comment]
I thought it might have been this:
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/master/src/module.js#L104
But that's commented out.

If you disable Item Piles, does a sheet render by itself?

Do you get any errors in the console? Before and after disabling Item Piles?

**Comment by Manume96** [comment]
Sorry, I thought I had disabled the modules but it seems I have not. It seems that the conflict is caused by the module "GM Screen".

**Comment by Manume96** [comment]
Okay i've fix it, the token sheet was in the GM screen but it opened the vault sheet instead of the character sheet, i just use the configuration setting for invert the control+click and everything works now.
Thank you very much for your help.
