### ISSUE TITLE
[REQUEST] - Retain token names when turning tokens into piles.

### ISSUE THREAD

**Issue by RavenknightDM** [fantasycalendar/FoundryVTT-ItemPiles#52]
Hiya, a ton of thanks for the fantastic mod!
I wonder if it would be a hassle to have the module retain the names of tokens turned into piles? I have a lot of named enemies in my game and it's kinda boring that they revert to the original character name "Orc" instead of "Angry Orc" or even "Bargh the Red."
Thanks again
/Ravenknight

**Comment by Haxxer** [comment]
Will fix in the next update.

**Comment by Haxxer** [comment]
Fixed in 1.4.0
