### ISSUE TITLE
[BUG] - [DND5e] - Merchant Inventory Will Not Populate With Better Rolls

### ISSUE THREAD

**Issue by AndrewRP8023** [fantasycalendar/FoundryVTT-ItemPiles#521]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
With only Item Piles, Better Roll Tables, Libwrapper and Socketlib installed, nothing happens when the 'Roll Table' or 'Roll All Tables' button is pressed on the merchant's Populate Items page. Oddly enough, if I click on 'Configure Table' and select 'Add All Items,' then all the items are added.

I see similar issues have been brought up previously, but I didn't want to dig one out from the dead, and mine seemed to be a bit different as far as I could tell.

**To Reproduce**

1. Load Item Piles, Better Roll Tables, Libwrapper, and Socketlib.
2. Create Actor's menu from Foundry.
3. Click 'Create Actor' button.
4. Enter actor name, 'Shop'. Select Non-Player Character from dropdown. And click the 'Create New Actor' button.
5. Click the 'Configure' button along the top of the NPC sheet.
6. Select 'Enabled,' then click the 'Other Settings.'
7. Select 'Merchant' from the dropdown at the top, then click on 'Update Item Piles' at the bottom of the window.
8. Click on 'Populate Items.'
9. Under rollable tables, select any table and click the 'Add Table' button.
10. Click either the 'Roll Table' or 'Roll All Tables' buttons.
11. Nothing happens.
12. Disable Better Roll Tables and repeat these steps. Only this time, on step 11, the items show up in the merchant window.

**Expected behavior**
I expect the items from the roll table to populate the merchant inventory.

**Screenshots**
![ItemPiles01](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/131478664/562387f8-d825-43ad-a542-0d0b91e3114d)

![ItemPiles02](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/131478664/78555c46-2963-4a3e-8100-b72877c7fcb6)

**Setup:**

- Foundry Version: 11.315
- System Version: DND5e 2.4.1
- Item Piles Version: 2.8.20
- libWrapper: 1.12.13.0
- Socketlib: 1.0.13
- Better Roll Tables: 1.9.3
- Browser & version: Google Chrome 120.0.6099.227

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Better Roll Tables

**Additional context**
No additional context available.

**Comment by BrendanBetheldo** [comment]
I get the exact same issue in that I'm not able to get rollable items without Better Rollables.

**Comment by Haxxer** [comment]
What is everyone's better rolltables version?

**Comment by BrendanBetheldo** [comment]
> What is everyone's better rolltables version?

I am **not** using Better rolltables.

@AndrewRP8023 is using Better RollTables: 1.9.3

**Comment by AndrewRP8023** [comment]
> > What is everyone's better rolltables version?
> 
> I am **not** using Better rolltables.
> 
> @AndrewRP8023 is using Better RollTables: 1.9.3

Just pointing out that you listed Better Rolltables as being loaded. For me, I get nothing as long as it's loaded. When I unload it, the Merchant function works fine.

To add to the troubleshooting, I picked one table, opened it, and changed the type of table to the different types and it didn't work under any setting.

**Comment by BrendanBetheldo** [comment]
> > > What is everyone's better rolltables version?
> > 
> > 
> > I am **not** using Better rolltables.
> > @AndrewRP8023 is using Better RollTables: 1.9.3
> 
> Just pointing out that you listed Better Rolltables as being loaded. For me, I get nothing as long as it's loaded. When I unload it, the Merchant function works fine.
> 
> To add to the troubleshooting, I picked one table, opened it, and changed the type of table to the different types and it didn't work under any setting.

You're right, my mistake. I've updated my comment it better reflect my environment.

**Comment by Haxxer** [comment]
Fixed in 2.9.0
