### ISSUE TITLE
[BUG] - [TWILIGHT: 2000 4E] - Merchant not populating items, will not open interface

### ISSUE THREAD

**Issue by AnAverageTeapot** [fantasycalendar/FoundryVTT-ItemPiles#522]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When trying to make a Merchant, I can create the actor and pull up its interface. However, when I try to drag and drop items into the merchant, the items do not populate. And then when I close out the merchant, I can't open it again.

**To Reproduce**

1. Duplicate "Default Item Pile"
2. Click on "Default Item Pile (Copy)"
3. Click on 'Configure Pile"
4. Click on 'Other Settings"
5. Click on the "Item Pile Type" dropdown
6. Click on "Merchant"
7. Click on "Update Item Pile"
8. Click on "Close"
9. Click on "Default Item Pile (Copy)"
10. Drag an item into the merchant
11. See error 
12. Close the merchant
13. Attempt to reopen the merchant
14. See error

**Expected behavior**
What I expect to happen is that items populate as their dragged into the merchant and that I can open the merchant's interface to see the items.

**Setup:**

- Foundry Version: [Version 11 Stable, Build 315]
- System Version: [Twilight: 2000 (4th Edition) 11.0.1]
- Item Piles Version: [e.g. 2.8.20]
- Browser & version [Google Chrome 121.0.6167.87]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Argon - Combat HUD (CORE)
- Argon - Combat HUD (TWILIGHT: 2000)
- Dice So Nice!
- lib - Color Settings
- Reverse Initiative Order
- Twilight: 2000 (4th Edition) - Core Set
- Twilight: 2000 (4th Edition) - Urban Operations
- Year Zero Actions
- Year Zero Engine: ⚔️ Combat

**Additional context**
I also turned off all the excess modules, and the bug still persisted.

**Comment by Haxxer** [comment]
> 14. See error

What error? Please post any console log errors you are running into.

**Comment by AnAverageTeapot** [comment]
My bad, there's not a console log error. By error I just meant something breaks. The first "error" refers to no items populating when dragged into the merchant, and the second "error" refers to the merchant interface not opening again after it's been closed

**Comment by Haxxer** [comment]
Perhaps fixed in 2.9.1
