### ISSUE TITLE
[BUG] - [SWB] - Purchase Macro only works on GM

### ISSUE THREAD

**Issue by Manume96** [fantasycalendar/FoundryVTT-ItemPiles#523]
**Are you on the latest version of Item Piles?**
Yes 

**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
I have a item service that execute a macro (right now the macro only shows a ui notification) but when a player purchase the service the ui notification only appear for the DM

**To Reproduce**
Create a macro, select it on the item configuration to execute when buy it, as a player buy the item. The item does not execute for the player but the dm see the notification (the ui notification is because do other stuff but wasn't working.

**Expected behavior**
See the ui notification on the player screen

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/128139195/013f2a33-37dc-4722-ad5a-3826e5360ad1)
The left image is the DM running of the browser and the right one is the player, as you can see the player just did the purchase but doesn't see the notificacion while the DM can.

**Setup:**

- Foundry Version: [11.315]
- System Version: [SWB 0.8.2]
- Item Piles Version: [2.8.20]
- Browser & version [Microsoft Edge  120.0.2210.144]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Changing this now would risk breaking macros for everyone who is currently using them. The reason why I chose to run it on the GM side is to make it so that it could update anything that the GM wanted to, such as attributes on characters, or create new items, etc.

**Comment by Manume96** [comment]
So, for explample, in this case i want my merchant to have a service to refill the water, in case the player have the bottle full, i can't make a message pop up to notify it?

**Comment by Haxxer** [comment]
Correct - I reiterate, if you want to execute a macro on the player side, please make a feature request.
