### ISSUE TITLE
[BUG] - [DnD5e 2.4.1] - Empty/Filled Chest Icon not updating after taking adding/gold

### ISSUE THREAD

**Issue by ChobitsCrazy** [fantasycalendar/FoundryVTT-ItemPiles#525]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When all items are removed or when items are added to an empty chest the icon does not update. It seems to update after the lid has been closed but doesn't do it on the fly.

**To Reproduce**
1. Create a container pile with a closed, empty, and open image.
2. Add 100g to the chest.
3. Place token on the scene have a character interact with the token and take all the gold.
4. Image does not update until the chest is closed and then opened. (The same is true the opposite way.)

**Expected behavior**
After the item pile becomes empty or filled the icon I would expect to change.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/21301107/c1c3709a-e901-426e-9c86-2c88c5df4273)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/21301107/68eaa22b-784f-4ec3-9911-565184bbcc52)

**Setup:**

- Foundry Version: 11.315
- System Version: DnD5e 2.4.1
- Item Piles Version: 2.8.20
- Browser & version Foundry Application

**Active modules:**
- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Fixed in 2.9.0
