### ISSUE TITLE
[BUG] - [DnD5e 2.4.1] - Gold duplication glitch

### ISSUE THREAD

**Issue by ChobitsCrazy** [fantasycalendar/FoundryVTT-ItemPiles#526]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When taking gold from a chest, if you leave the default 1/100 and hit the Take button then it adds a single gold to the character's inventory but the chest still shows 1/100. At this point you can input 100/100 and then you end up with 101 gold.

**To Reproduce**
1. Create a new container item pile with these settings:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/21301107/090fd663-3c1b-4b6a-abb6-3b3d0737f8f9)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/21301107/9007efb2-2b4b-46d5-b792-9d10aec0d98e)
2. Set the item pile on the scene and have a PC interact with it.
3. Select take when the gold count shows 1/100 and see that you have 1 gold in your inventory and the pile shows 1/100 still. Then change the value to 100/100 and then select take. It empties the pile but you have 101 gold in inventory.

**Expected behavior**
Should not allow to take more gold then what is in the container.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/21301107/a87911ac-cc7a-4e7e-ac60-119559cd4227)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/21301107/4812478a-4bd6-4ab1-a9d4-1a9f2f4a8ecc)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/21301107/34b3e65b-efbc-4773-920b-4e6dba3d20dd)

**Setup:**

- Foundry Version: 11.315
- System Version: DnD5e 2.4.1
- Item Piles Version: 2.8.20
- Browser & version Foundry Application

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Fixed in 2.9.0
