### ISSUE TITLE
[BUG] - [DND 3.0.3] - Natural Weapon Filter does not work.

### ISSUE THREAD

**Issue by RavenknightDM** [fantasycalendar/FoundryVTT-ItemPiles#534]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Natural weapons are showing up in Item Piles even if set to be filtered out. I guess this is due to a change in DND 3.0.0+. It worked just fine until system update. ( I reset the system settings before making this post. ;) )

![ItemFilter](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/53635985/ee92901d-a4b3-4ed2-8705-199204a83aa8)

**Setup:**

- Foundry Version: [11.315]
- System Version: [e.g. DND5e 3.0.3]
- Item Piles Version: [e.g. 2.8.20]

**Comment by Haxxer** [comment]
Check if 3.0.0 changed this.

**Comment by RavenknightDM** [comment]
My bad. This is not a bug at all. I totally missed that the new path is:
system.type.value

I really, really wish that they didn't change the API this often and yes, sorry for the faulty report. <3
