### ISSUE TITLE
[BUG] - [D&D5e] - Attempting to edit 'Merchant Columns' of actor prevents token, including prototype from opening.

### ISSUE THREAD

**Issue by zbyers26** [fantasycalendar/FoundryVTT-ItemPiles#544]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
After clicking on 'Configure Merchant Columns' under 'Configure Pile --> Other Settings', nothing happens in the UI. Closing the Actor and attempting to reopen displays the error shown in the attached screenshot.

**To Reproduce**
Covered in the bug description.

**Expected behavior**
Expect to have a window open so that I can view settings. When closing the window, expect to be able to edit my canvas actor and certainly the prototype token.

**Screenshots**
![ItemPilesBug](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/115838937/8941c5dd-ba95-4b6b-9b1e-14400656c8c4)

**Setup:**

- Foundry Version: 11.315
- System Version: D&D5e 3.0.3
- Item Piles Version: 2.0.9
- Browser & version Google Chrome 122.0.6261.112 - 64-bit

**Active modules:**

Foundry Virtual Tabletop: Version 11 Stable, 11.315
Game System: dnd5e, 3.0.3
Active Modules: 127
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
GPU: ANGLE (AMD, AMD Radeon RX 6950 XT (0x000073A5) Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 9450 x 6900 | Grid Size: 150 | Padding Percentage: 0
Walls: 233 | Ambient Lights: 80 | Ambient Sounds: 0 | Tiles: 1 | Tokens: 17

Actors: 555 | Items: 1962 | Journal Entries: 1149 | Rollable Tables: 169 |
Playlists: 18 | Compendium Packs: 232 | Chat Messages: 2

**Additional context**
I've attached a snapshot of the console error when attempting to open the Item Pile. This also affects the prototype token.

Removing the Item Piles module seems to 'recover' the token, but re-enabling it puts the token back into an inaccessible state.

**Comment by Haxxer** [comment]
Fixed in 2.9.1
