### ISSUE TITLE
[BUG] - [DND5 3.0.4] - Features added to merchant are added to its character sheet instead

### ISSUE THREAD

**Issue by JoueurSansFromage** [fantasycalendar/FoundryVTT-ItemPiles#549]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Whenever I add a feature on the merchant, a popup asks if I'm sure If I want to do that, and when I say yes, it adds the feature to the character sheet instead of the merchant shop.

**To Reproduce**
Add a feat in the merchant shop.

**Expected behavior**
The feat should be up for purchase in the merchant shop

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/114048051/5c3e9a6f-39a4-41bc-8dd4-3b5838990d15)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/114048051/b92aabce-1576-49f2-965a-48c02f9c28ca)

**Comment by Haxxer** [comment]
Have you configured this merchant to not filter away the features? If so, it is not a bug.
