### ISSUE TITLE
[REQUEST] consider supporting the foundryvtt-world-currency-5e module

### ISSUE THREAD

**Issue by DarKDinDoN** [fantasycalendar/FoundryVTT-ItemPiles#55]
**Is your feature request related to a problem? Please describe.**
[foundryvtt-world-currency-5e](https://github.com/cstby/foundryvtt-world-currency-5e) is used to change the currency name and trade values for the 5e system. Very useful when you don't play with the classic Forgotten Realms setting and money has different names in the setting you are playing with.

**Describe the solution you'd like**
Make this module compatible with [foundryvtt-world-currency-5e](https://github.com/cstby/foundryvtt-world-currency-5e). This module doesn't actually override the currency i18n keys but rather modify the CONFIG.DND5E.currencies object: https://github.com/cstby/foundryvtt-world-currency-5e/blob/master/scripts/world-currency-5e.js#L26

**Comment by Haxxer** [comment]
No can do. That module is a system-specific module, Item Piles is not a system specific module.

**Comment by DarKDinDoN** [comment]
OK. Is it possible to initiate a trade request by API?
I think I can make this work with a simple macro.

**Comment by Haxxer** [comment]
Not yet, and that is a separate question. Please refrain from turning tickets into a discussion :)
