### ISSUE TITLE
[BUG] - [Dragonbane] - Can't buy stuff with lower denominations from merchant, when I run out, even though I have a higher one

### ISSUE THREAD

**Issue by Vass1979** [fantasycalendar/FoundryVTT-ItemPiles#555]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
I have setup item piles to work with Dragonbane like this:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/470640/1a58bf31-598c-4758-ad90-d5efd8b33902)
It works great for the most part. My players can buy from a merchant just fine. The problem comes when they try to buy something that they don't have the exact currency for, but they have a "higher" currency. So for instance, they don't have 2 copper, but they do have 1 silver. The module says they don't have the required currency.

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/470640/c076776e-ba80-42ec-8e08-123b2dff3e16)

As you can see, my player has 3 copper, 1 silver and 2 gold, but can't buy anything that costs 4 or more copper or 2 or more silver.

**To Reproduce**

See above

**Expected behavior**
The module should be able to convert a higher currency to a lower one so my player can pay for it.

**Screenshots**

**Setup:**

- Foundry Version: 11.324
- System Version: Dragonbane 1.8.2
- Item Piles Version: 2.9.0
- Browser & version Chrome Vrsion 123.0.6312.86 (Official Build) (64-bit)

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
N/A

**Comment by Haxxer** [comment]
It is the wrong way around. Try gold 1, silver 0.1, copper 0.01. The order should have tipped you off.

**Comment by Vass1979** [comment]
I did try with both orders, same problem

**Comment by Vass1979** [comment]
[image: Untitled.jpg]

**Comment by Vass1979** [comment]
![Untitled](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/470640/7780fede-3872-45ee-989e-5183c9c211d0)

Please see the attached image, it shows the setup and also my player trying to buy from merchant

**Comment by Haxxer** [comment]
Does the items for sale have a drop down for the price denomination in their sheets? If so, item piles may not be able to suss out the total price of the items and thus not know how to best get that from the item.

**Comment by Vass1979** [comment]
No dropdown, it is a text field that has the number and then copper,
silver, or gold next to it. When I drop it on the merchant, obviously it
does not read the price, I have to manually go into every item and add the
price myself.

[image: image.png]

So I will edit the item, go to the price settings tab and add a purchase
option, using the system currency.
[image: image.png]

Is this not the right way?

**Comment by Vass1979** [comment]
Please close this issue with my apologies. There is no bug, except in my
brain. Someone helped me fix my issue

**Comment by Haxxer** [comment]
It might help someone else if you explain what went wrong! 🙂

**Comment by Vass1979** [comment]
Certainly,

So I hadn't set my Item Price Attribute in System Specific Setting, and
that in turn meant I wasn't able to add price per item via Base Price in
the item price setting, and was adding a price bia Purchase Options :(

Once I sorted those 2, everything worked perfectly.

For Dragonbane btw the Item price attribute is system.cost
