### ISSUE TITLE
[REQUEST] Consider hiding the item piles button in the sheet header

### ISSUE THREAD

**Issue by DarKDinDoN** [fantasycalendar/FoundryVTT-ItemPiles#56]
**Is your feature request related to a problem? Please describe.**
The new sharing feature is very cool.
But that is the only feature I want to use, and my sheet headers are really bloated.

**Describe the solution you'd like**
 Is it possible to deactivate completely the item piles feature and not have the button displayed in the sheet headers?

**Comment by Haxxer** [comment]
This is already a setting in the module settings.

**Comment by DarKDinDoN** [comment]
@Haxxer Then it's not working cause the icon is still showing up:
![image](https://user-images.githubusercontent.com/1687854/153316043-73014bdf-8c7e-485a-92a0-2ac75d317f0b.png)

**Comment by Haxxer** [comment]
Oh, you want to hide the entirety of the icon? How would you configure item piles in the actors bar?

**Comment by DarKDinDoN** [comment]
Someone didn't read the initial ticket 😸 
I don't want to use the core features of the this module, only the very cool trading window (that could have been its own module imo)

**Comment by Haxxer** [comment]
My apologies - the trading system is heavily integrated into the item pile system, so splitting them would be hard to say the least. I'll see about adding togglable settings for each sub-system.

**Comment by DarKDinDoN** [comment]
Great! Should I open a new ticket about adding togglable settings for each sub-system or do you reopen this ticket?

**Comment by Haxxer** [comment]
The item piles module is completely open source, so feel free to submit a PR with how you'd like this to work :)

**Comment by Haxxer** [comment]
Added option in 2.3.3
