### ISSUE TITLE
[BUG] - [likely system agnostic]- Searchbar disapears when filter not giving enough results

### ISSUE THREAD

**Issue by DenDrummer** [fantasycalendar/FoundryVTT-ItemPiles#561]
**Are you on the latest version of Item Piles?**
Yes ~~/ No~~

**Have you tried to reset Item Piles' system settings?**
Yes ~~/ No~~

**Describe the bug**
When using the search bar to filter items, if the number of items after searching drops below 8, the search box disapears while the filter stays, resulting in having to close and reopen the pile if you want to search for something else.

**To Reproduce**

1. Open an item pile on the map with 8 or more items
2. Focus the Search box
3. Start typing until the list of filtered items drops below 8
4. The search bar disappears

**Expected behavior**
The search box stays visible while it is being used.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/17620245/a6d45705-801a-47ad-b60f-82a069721e92)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/17620245/ca7ef8a7-2f21-4813-8cd5-82dbf3d85060)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/17620245/4f9706b6-63e5-486d-8787-dab387b8a708)

**Setup:**

- Foundry Version: 11.315
- System Version: Custom System Builder 3.0.0
- Item Piles Version: 2.9.1
- tested both directly from within Foundry itself and from `Chrome 123.0.6312.107 (Official Build) (64-bit) (cohort: Control)`

**Active modules:**

- Item Piles 2.9.1
- libwrapper 1.12.13.0
- socketlib 1.0.13
- Active Token effects 0.7.2
- Alt Drag 0.5.1
- Always Centred 0011
- Ambient Doors 2.3.3
- Chat Commander 2.0.2
- Day Night Cycle 0007
- DunGen 1.0.1
- Dungeon Draw 2.3.0
- Dynamic effects using Active Effects (DAE) 11.3.17
- Elevated Vision 0.5.13
- Foundry Achievements 11.0
- Hey, Wait! 0.7.7
- Levels 4.3.9.1
- lib - Color Settings 3.0.2
- Monk's Active Tile Triggers 11.26
- Monk's Wall Enhancements 11.02
- Multilevel Tokens 1.6.0
- Patrol 1.4.3
- Player Status 3.0.1
- Playerlist Status - Lib for View status on Playerlist 3.0.1
- Polyglot 2.4.7
- Shared Vision 1.1.2
- Simple Calendar 2.4.13
- Smart Doors 1.4.1
- Speak As...... 1.5.1
- Splatter 3.4.5
- Stairways (Teleporter) 0.10.2
- Sync Token Names 1.0.5
- TheRipper93's Module Hub 2.3.3
- Torch 2.11.1
- Visual Active Effects 11.1.3
- Wall Height 5.1.5
- Walls Have Ears - Muffled sounds behind walls 1.11.1
- Whisper As 1.2.0

**Additional context**
I have also tested this in a world with DnD 5e version 3.1.2, with the exact same result, so as I suspected, this loooks like a system-agnostic bug.

Additionally, while verifying this bug, I noticed another bug that where if you press backspace after step 3 as GM before clicking or focussing something else, it deletes the pile. This happens regardless of it being set to delete on empty or not and regardless of whether it has any items still shown or not. I suspect that this will no longer happen if the main bug from this bug report is fixed however.

**Comment by p4535992** [comment]
Did you replicate this behaviour with onlty the "Item Piles" module active ? 
Otherwise, I would ask you to use the "Find hte culprit" module to help the developer reduce the number of modules to verify for conflicts.

**Comment by Haxxer** [comment]
Fixed in 3.0.0
