### ISSUE TITLE
[REQUEST] - Have a global default setting for 'Use Item Name'

### ISSUE THREAD

**Issue by adunis** [fantasycalendar/FoundryVTT-ItemPiles#563]
I would like to have this option 

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/47754845/e269c2f4-b130-486c-8dba-dae3f9690d42)

being able to set it up in the 'Configure Settings' to be able to set it off as default for all item piles created

**Comment by Haxxer** [comment]
You can simply change the default item pile, and any item pile created from drag and dropping will not have that setting enabled. Please read the wiki.
