### ISSUE TITLE
[REQUEST] - Selling Options as the inverse function of Purchase Options

### ISSUE THREAD

**Issue by Karuna053** [fantasycalendar/FoundryVTT-ItemPiles#564]
**Is your feature request related to a problem? Please describe.**
Hi, I would like for my players to be able to sell an item of their possession, and gain something other than primary currency, for example: their HP, and other secondary currencies.

**Describe the solution you'd like**
I would like a feature where we can set a Selling Option as an inverse of Purchase Option. This is so that merchants can be more flexible and can act as a barter-NPC. With this feature for example, when you "sell" a powerful artifact to a Blacksmith Disassembler, they can "disassemble" it for you and you get 2 Soul Points and 2 Mineral Materials (both secondary currencies).

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/17472074/4c75874a-9d36-499d-831c-00ba7be0d5d8)

And the inverse of "Disable Normal Cost" too, for Selling Options:

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/17472074/bfced301-98e9-4a25-a48c-21fb89975966)

Thank you!

**Comment by Haxxer** [comment]
Added in 3.1.0
