### ISSUE TITLE
[BUG] - [D&D 5E] - Split Currency not detecting all players

### ISSUE THREAD

**Issue by edoreld** [fantasycalendar/FoundryVTT-ItemPiles#565]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Split Currency only detecting 2 players out of 5

**To Reproduce**

1. Drag a "Default Item Pile' to the scene
2. Double left-click it
3. See "Split Currency 2 ways" button

**Expected behavior**
The button should say "Split Currency 5 ways", as there are 5 players in the world, each with their own account and player token.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/973854/93be1620-433a-461d-9037-30b24915c515)

**Setup:**

- Foundry Version: V11 Stable - Build 315
- System Version: DND5e 3.0.4
- Item Piles Version: 2.9.1
- Browser & version: Google Chrome 124.0.6367.79 (Official Build) (64-bit)

**Active modules:**

"knownModules": {
      "ActiveAuras": {
        "title": "Active Auras",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "0.9.8",
        "foundryVersion": "11"
      },
      "about-time": {
        "title": "About Time",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "11.0.1",
        "foundryVersion": "11.305"
      },
      "anonymous": {
        "title": "Not installed",
        "active": false,
        "installed": false,
        "moduleVersion": "",
        "foundryVersion": ""
      },
      "autoanimations": {
        "title": "Automated Animations",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "4.2.71",
        "foundryVersion": "11"
      },
      "babonus": {
        "title": "Build-a-Bonus",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "11.9.3",
        "foundryVersion": "11.315"
      },
      "chris-premades": {
        "title": "Chris's Premades",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "0.10.52",
        "foundryVersion": "11"
      },
      "concentrationnotifier": {
        "title": "Concentration Notifier",
        "active": false,
        "ibstalled": true,
        "moduleVersion": "11.3.0",
        "foundryVersion": "11"
      },
      "condition-lab-triggler": {
        "title": "Not installed",
        "active": false,
        "installed": false,
        "moduleVersion": "",
        "foundryVersion": ""
      },
      "dae": {
        "title": "Dynamic effects using Active Effects (DAE)",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "11.3.15",
        "foundryVersion": "11.315"
      },
      "ddb-game-log": {
        "title": "Not installed",
        "active": false,
        "installed": false,
        "moduleVersion": "",
        "foundryVersion": ""
      },
      "ddb-importer": {
        "title": "DDB-Importer: A D&D Beyond Integrator",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "5.0.1",
        "foundryVersion": "11"
      },
      "df-templates": {
        "title": "Not installed",
        "active": false,
        "installed": false,
        "moduleVersion": "",
        "foundryVersion": ""
      },
      "dfreds-convenient-effects": {
        "title": "DFreds Convenient Effects",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "6.0.3",
        "foundryVersion": "11.315"
      },
      "dice-so-nice": {
        "title": "Not installed",
        "active": false,
        "installed": false,
        "moduleVersion": "",
        "foundryVersion": ""
      },
      "effectmacro": {
        "title": "Effect Macro",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "11.2.2",
        "foundryVersion": "11"
      },
      "itemacro": {
        "title": "Item Macro",
        "active": false,
        "ibstalled": true,
        "moduleVersion": "1.11.1",
        "foundryVersion": "11.315"
      },
      "levels": {
        "title": "Levels",
        "active": false,
        "ibstalled": true,
        "moduleVersion": "4.3.6",
        "foundryVersion": "11"
      },
      "lib-wrapper": {
        "title": "libWrapper",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "1.12.13.0",
        "foundryVersion": "11"
      },
      "lmrtfy": {
        "title": "Not installed",
        "active": false,
        "installed": false,
        "moduleVersion": "",
        "foundryVersion": ""
      },
      "monks-active-tiles": {
        "title": "Monk's Active Tile Triggers",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "11.22",
        "foundryVersion": "11"
      },
      "monks-chat-timer": {
        "title": "Monk's Chat Timer",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "11.01",
        "foundryVersion": "11"
      },
      "monks-player-settings": {
        "title": "Monk's Player Settings",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "11.04",
        "foundryVersion": "11"
      },
      "monks-tokenbar": {
        "title": "Monk's TokenBar",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "11.15",
        "foundryVersion": "11"
      },
      "multilevel-tokens": {
        "title": "Multilevel Tokens",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "1.6.0",
        "foundryVersion": "10"
      },
      "retroactive-advantage-5e": {
        "title": "Retroactive Advantage DnD5e",
        "active": false,
        "ibstalled": true,
        "moduleVersion": "11.1.1",
        "foundryVersion": "11"
      },
      "sequencer": {
        "title": "Sequencer",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "3.1.4",
        "foundryVersion": "11"
      },
      "simbuls-cover-calculator": {
        "title": "Simbul's Cover Calculator",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "2.0.4",
        "foundryVersion": "11"
      },
      "socketlib": {
        "title": "socketlib",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "1.0.13",
        "foundryVersion": "11"
      },
      "templatemacro": {
        "title": "Template Macro",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "11.0.1",
        "foundryVersion": "11"
      },
      "times-up": {
        "title": "Times Up",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "11.3.8.1",
        "foundryVersion": "11.315"
      },
      "tokenmagic": {
        "title": "Token Magic FX",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "0.6.5.0",
        "foundryVersion": "11.313"
      },
      "walledtemplates": {
        "title": "Walled Templates",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "0.7.6",
        "foundryVersion": "11.315"
      },
      "warpgate": {
        "title": "Warp Gate",
        "active": true,
        "ibstalled": true,
        "moduleVersion": "1.19.2",
        "foundryVersion": "11"
      },
      "wjmaia": {
        "title": "Not installed",
        "active": false,
        "installed": false,
        "moduleVersion": "",
        "foundryVersion": ""
      }
    },

**Additional context**
N/A

**Comment by Haxxer** [comment]
Your players must assign a character to their user accounts in the bottom left of foundry. Right click on their names and click configure.

**Comment by edoreld** [comment]
Thank you, that works. May I suggest adding this info somewhere in the Wiki? I've come across the same issue before when I was a player in another campaign, and the DM there similarly didn't know how to fix it. If he and I couldn't work it out, maybe others can't as well.

**Comment by Haxxer** [comment]
Done: 

https://fantasycomputer.works/FoundryVTT-ItemPiles/#/common-issues
