### ISSUE TITLE
[BUG] - [PF2E] - Custom Category in Merchant Rollable Tables Not Applying

### ISSUE THREAD

**Issue by Ponnosaurus** [fantasycalendar/FoundryVTT-ItemPiles#567]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Using Rollable Tables with "Add all items" unchecked removes any specified custom category in Merchant Item Piles. If said option is checked, feature operates as expected. Appears to be a repeat of #543 

**To Reproduce**

1. Create Merchant Item Pile
2. Generate Rollable Table with Compendium Results
3. Go to "Populate" in Item Pile
4. Add generated Rollable Table with anything in the "Add items to custom category" entry box and "Add all items" unchecked.
5. "Roll All Tables" and "Add All Items"
6. See no custom category applied in "Buy Items"

**Expected behavior**
Items added through Rollable Tables with custom category listed should be applied and visible in buy menu..

**Screenshots**
The Rollable Tables setup in Item Piles
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/73410161/f1efd7a5-7713-423e-8f2b-6c1e74d8f3fb)

The Rollable Table itself
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/73410161/ad41f239-85f8-446c-aee0-f8673871dc27)

Output with "Add all items" unchecked
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/73410161/a1f12e30-581a-4d67-9356-e0b9cfeeae48)

Output with "Add all items" checked
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/73410161/eda5a803-d683-4bed-a87e-c5b2e3922240)

**Setup:**

- Foundry Version: 11.315
- System Version: PF2E 5.15.3
- Item Piles Version: 2.9.1
- Browser & version: Microsoft Edge 124.0.2478.67 (64-bit)

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- [insert more modules here]

**Comment by Drag0nF** [comment]
having the same issue on dnd5e

**Comment by Drag0nF** [comment]
This issue still persists in dnd5e 3.2.1 v11

**Comment by Haxxer** [comment]
This should be fixed in 3.0.11
