### ISSUE TITLE
[BUG] - [PF2E] - Unable to Edit Merchant Columns

### ISSUE THREAD

**Issue by Ponnosaurus** [fantasycalendar/FoundryVTT-ItemPiles#568]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Clicking "Save" and then "Update Item Pile" in the Merchant Columns in Merchant Item Piles causes all the descriptive columns (including those preset by the module) to be wiped, leaving only "Quantity" and "Price". 

**To Reproduce**

1. Create new Item Pile.
2. Set as Merchant.
3. Drag and drop actor onto canvas.
4. Drag and drop any item (I used a Rapier) onto the actor to add into its inventory.
5. Go to "Configure Pile" --> "Other Settings"
6. Go to "Configure Merchant Columns" and don't edit anything.
7. "Save" --> "Update Item Pile"
8. "Rarity" and "Bulk" columns should be absent immediately upon closing and reopening Item Pile.

**Expected behavior**
Saving changes to Merchant Columns should not be wiping the preset columns or any custom columns.

**Screenshots**
Before accessing Column settings.
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/73410161/95dfebb3-3beb-42bc-98a8-9820f0ff2fce)

After saving Column settings without any changes.
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/73410161/a02f04d2-aa27-4b3f-8805-340953415a94)

**Setup:**

- Foundry Version: 11.315
- System Version: PF2E 5.15.3
- Item Piles Version: 2.9.1
- Browser & version: Microsoft Edge 124.0.2478.67 (64-bit)

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**

**Comment by Zarhog** [comment]
this also happened to us. wasp said he is aware

**Comment by OlavStornes** [comment]
A workaround I've found that works is to change a line in the installed module.
On line 65437 in `{foundry_data_folder}/modules/item-piles/module.js`, change the line from:

`pileData.merchantColumns = Array.isArray(result.merchantColumns) ? result.merchantColumns : [],`

to:
`pileData.merchantColumns = Array.isArray(result) ? result : [],`

I have sent a suggestion to change this in the source as well.

**Comment by Drag0nF** [comment]
Having the same issue in dnd5e
