### ISSUE TITLE
[BUG] - You cannot drop items from the item bar unless you are a GM.

### ISSUE THREAD

**Issue by gsterling** [fantasycalendar/FoundryVTT-ItemPiles#57]
**Describe the bug**
When trying to drop items as a player or putting items in the trade dialog, it won't paste the item and just output "Item Piles | You cannot drop items from the item bar unless you are a GM."

**To Reproduce**
1. Initiate trade with player
2. Let player put an item in the trade window
3. See message

**Expected behavior**
I was under the impression non-GM should be able to drop items, too. Now with sharing it's obvious it's not working as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/58980630/153496710-927cf17b-0c45-4d63-8e6d-91f570f9e177.png)

**Setup:**
 - Foundry Version: 9.249
 - Item Piles Version: 1.4.0
 - OS: Arch Linux
 - Browser Firefox
 - Version 97

**Active modules:**
![image](https://user-images.githubusercontent.com/58980630/153498564-46e52768-26f6-4951-959f-85679ee43fc0.png)
![image](https://user-images.githubusercontent.com/58980630/153498606-dc81ba8d-c929-463c-8a4f-8c48dcc90e4e.png)
![image](https://user-images.githubusercontent.com/58980630/153498655-10e0bc8b-4294-400f-baca-b85c7706a7b8.png)

**Additional context**
I am using Splittermond as a game system.

**Comment by gsterling** [comment]
It's not form the sidebar. Maybe it's weirdly implemented in my setting:
![image](https://user-images.githubusercontent.com/58980630/153502129-95e2d9c2-aabf-4e9e-92bc-41c61e599726.png)

But to be fair, I am not really sure, what the sidebar is in this context.

**Comment by Haxxer** [comment]
Please include which system this is then :)

**Comment by Haxxer** [comment]
In any case, if the system does not include which actor a drag and dropped item came from, that's not something Item Piles can work with sadly

**Comment by gsterling** [comment]
> Please include which system this is then :)

 I am using Splittermond as a game system.
 
 > In any case, if the system does not include which actor a drag and dropped item came from, that's not something Item Piles can work with sadly
 
 Ah. Sad indeed. But it still works excellent for looting!

**Comment by Haxxer** [comment]
I would recommend contacting the creators of the system and perhaps log a bug with them. Including the `actorId` in drop data is common across many systems, so it would be useful for them to conform in this case.

**Comment by gsterling** [comment]
> I would recommend contacting the creators of the system and perhaps log a bug with them. Including the `actorId` in drop data is common across many systems, so it would be useful for them to conform in this case.

It was indeed the missing actorId. It's fixed now in Splittermond.
