### ISSUE TITLE
Request to adjust sale prices for specific items

### ISSUE THREAD

**Issue by Nevets1701** [fantasycalendar/FoundryVTT-ItemPiles#571]
Would it be possible to adjust the sale price for specific items for a merchant?

I have a merchant in the fallout rpg who pays full price for purified water. I don't want to put it into a custom category, I just want to be able to adjust the sale price of that specific item.

Thanks!

**Comment by Haxxer** [comment]
You can adjust the price on the item on the merchant, right?

**Comment by Nevets1701** [comment]
I see that I can place on item on the merchant and adjust its price. I thought this would just effect the price when players purchase the item, would it effect the price when players are selling that items as well?

**Comment by Haxxer** [comment]
It would affect the core price of that item. There's no way to adjust per item price modifiers at this moment.

**Comment by Nevets1701** [comment]
Ah ok. I just wanted it to sell at a higher price for a specific merchant. 

Thanks

**Comment by Haxxer** [comment]
Added in 3.0.0
