### ISSUE TITLE
[BUG] - [Mutant Year Zero 11.0.5] - players cant drag and drop items from their sheets, even when the are themselves identified as an item pile

### ISSUE THREAD

**Issue by KrultiNinja** [fantasycalendar/FoundryVTT-ItemPiles#579]
**Are you on the latest version of Item Piles?**
Yes 

**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
A a GM, everything's fine.
But my players can't drag and drop items form their sheets, even when i declare them as item piles.
As a result, they cant exchange items, or create new piles.

**Setup:**

- Foundry Version: [11.315]
- System Version: [11.05]
- Item Piles Version: [2.9.1]
- Browser & version [Firefox 126.0 / Chrome 125.0.6422.78]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- all others deactivated for testing purposes

**Additional context**

all necessary permissions granted to players both in the game settings and the item piles settings

**Comment by Haxxer** [comment]
Try having them drag the item to the other player's token, or use the trade interface in the bottom left of the screen. Item piles was never meant to be used in a way where everyone is a pile, nor to support dragging items between player's sheets.

**Comment by KrultiNinja** [comment]
Thank you for answering this fast.

Unfortunately, they can't drag and drop anything from their sheet. They can't drag and drop items from the item menu even though i activated all permissions in the settings

I can verify that by connecting as them to the server.

**Comment by Haxxer** [comment]
Can you record what you are trying to do? Is it perhaps that the game system's sheet simply does not allow for drag and dropping items, then?

**Comment by KrultiNinja** [comment]
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/141031889/1e67bfaa-460f-4069-b9f6-043ed41db617

Here i try to frag and drop items on another token (being logged a sa plyer myself) and on the floor.

Now that you mention it, as a GM i can only drag and drop from the items menu of foundry of from an item pile...

**Comment by Haxxer** [comment]
Item piles does not change the core sheets of game systems. I cannot make them draggable, that is the responsibility of the game system.

**Comment by KrultiNinja** [comment]
Damn. Thank you for your answer though.
