### ISSUE TITLE
[REQUEST] - Allow purchasing for a merchant to refill an item charges, rather than giving them a new item

### ISSUE THREAD

**Issue by edoreld** [fantasycalendar/FoundryVTT-ItemPiles#580]
**Is your feature request related to a problem? Please describe.**
I wish I could set up a merchant service that allows player to refill item charges instead of giving them a copy of that item

**Describe the solution you'd like**
My player have waterskin for which they would like to buy refills from item piles set up as merchants

**Describe alternatives you've considered**
I've considered destroying the water skin on use but that doesn't work when they are foraging and wanna refill them

**Comment by Haxxer** [comment]
What system is this for? Item Piles supports [many systems](https://fantasycomputer.works/FoundryVTT-ItemPiles/#/README?id=natively-supported-systems), so you have to be specific - this also means that system specific behavior is harder to support. Have you considered using the [services feature](https://fantasycomputer.works/FoundryVTT-ItemPiles/#/merchant?id=services-and-custom-behavior) in merchants to run a macro to refill their charges?
