### ISSUE TITLE
Foundry v12 support?

### ISSUE THREAD

**Issue by Stormthirst** [fantasycalendar/FoundryVTT-ItemPiles#581]
I love the module, and I was wondering if it was going to be updated for Foundry v12 support?

Thanks

**Comment by Haxxer** [comment]
Yes - V12 has only been out for a few days, and I work on this module for free, on my already limited free time. As you can see, this module gets regular updates, so it is not abandoned.

**Comment by Stormthirst** [comment]
I am so pleased and really appreciated your time and effort in creating a great module. Keep up the good work!

**Comment by Haxxer** [comment]
If you feel *especially* appreciative, there's a Kofi link on the GitHub page 😉

**Comment by Stormthirst** [comment]
Done!
