### ISSUE TITLE
[BUG] - [PF2e] - Players can speak as item piles

### ISSUE THREAD

**Issue by Peach774** [fantasycalendar/FoundryVTT-ItemPiles#584]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Players can speak as item piles when they have them selected, such as opening a treasure or shop.

**To Reproduce**

1. Create an item pile that players can access
2. As a player, click on the item pile
3. Type in character in chat
4. Chat comes out as the item piles

**Expected behavior**
When having an item pile selected, characters should still speak as their designated character token or as the user, but not as the item pile.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/5171184/351c6f8e-9a24-4f25-8526-77e514271719)
This was setup in a test world, i just make some item piles and created a player and logged in as the player and when selected, players can speak as shops.

**Setup:**

- Foundry Version: 11.315
- System Version: PF2e 5.6.1
- Item Piles Version: 2.9.1

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
I am unsure if this is system specific or tied to foundry

**Comment by Haxxer** [comment]
You don't need to give them ownership of the pile to have them be able to interact with it.
