### ISSUE TITLE
[Macro on 'vault' not being executed] - [DnD 5E] 

### ISSUE THREAD

**Issue by Aemeth21** [fantasycalendar/FoundryVTT-ItemPiles#585]
**Are you on the latest version of Item Piles?**
No - version 2.8.20

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
I have a 'vault' item pile and I'm trying to execute a macro whenever this vault is opened, it's just an audio file, I'm using sequencer for that. The audio just doesn't play.

**To Reproduce**

1. Go to 'item pile config.'
2. Click on 'On interact macro'
3. Scroll down to 'macro plays audio'
4. See error "Audio doesn't play"

**Expected behavior**
I want the audio to be played every time I open this vault.
 

**Setup:**

- Foundry Version: [11]
- System Version: [e.g. DND5e 2.4.1]
- Item Piles Version: [e.g. 2.8.20]
- Browser & version [e.g. Google Chrome 125.0.6422.142]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Sequencer

**Comment by Haxxer** [comment]
Can you please post the macro?

**Comment by Aemeth21** [comment]
new Sequence()
            .sound()
            .file("Fridge-sfx.mp3")
            .volume(1)
            .delay(150)
            .play()

**Comment by Haxxer** [comment]
Added in 3.0.0
