### ISSUE TITLE
[BUG] - D&D 5E - Players can't open NPC item pile

### ISSUE THREAD

**Issue by TheDying0fLight** [fantasycalendar/FoundryVTT-ItemPiles#592]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Players can't open item piles and the browser throws an error, while the Gamemaster can open item piles

**To Reproduce**

1. Make a new DnD 5E world
2. Make a Player and a NPC Actor
3. Make a new user for the player and give them ownership for the token
4. Pull NPC and Player on canvas, turn NPC into item pile and unpause the game
5. Change to player user and try to open item pile
6. Error

**Expected behavior**
The item pile view opening after step 5

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/95179191/3a9ed8f2-5028-426c-8ba6-dbaf27c93a68)

**Setup:**

- Foundry Version: [12.328]
- System Version: [DND5e 3.2.1]
- Item Piles Version: [3.0.0]
- Browser & version [Firefox 127, Foundry Client]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
-

**Comment by hyrapower** [comment]
I'm getting this too. Merchants suffer from the same issue.

**Comment by Haxxer** [comment]
Fixed in 3.0.1
