### ISSUE TITLE
[Translation] - RU Language

### ISSUE THREAD

**Issue by VirusNik21** [fantasycalendar/FoundryVTT-ItemPiles#593]
I made a Russian translation of your module. Please include it in the next version of your module. Thank you.
[ru.json](https://github.com/user-attachments/files/16039211/ru.json)

**Comment by Haxxer** [comment]
I will, but in the future, use weblate:
https://weblate.foundryvtt-hub.com/projects/item-piles/main/ru/

**Comment by Haxxer** [comment]
Also, a [pull request](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/pulls) may have been better

Added in 3.0.1
