### ISSUE TITLE
[BUG] - [D&D 5e (probably system independent)] - Item pile data resets upon token update

### ISSUE THREAD

**Issue by Saibot393** [fantasycalendar/FoundryVTT-ItemPiles#594]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
When changing the token settings of an item pile (e.g. the name, though any setting seems to work), the item pile data gets reset and the token is no longer an item pile. (`tokendocument.flags.item-piles.data` is set to `null`)

**To Reproduce**

1. Create a new item pile token via drag and drop
2. Go into the newly created tokens setting and change any setting (e.g. name) and save the change(s)
3. The item pile data will have reset to `null`

**Expected behavior**
For item pile settings not to reset when updating any token data field

**Setup:**
- Foundry Version: v12.328
- System Version: DND5e 3.2.1 (though the bug seems to be system independent)
- Item Piles Version: 3.0.1
- Browser & version: Foundry Host (v12.328)

**Active modules:**

- Item Piles (3.0.1)
- libwrapper (1.12.13.1)
- socketlib (1.0.13)

**Comment by Haxxer** [comment]
Fixed in 3.0.6
