### ISSUE TITLE
[BUG] - [Dragonbane] - Unable to edit Merchant columns, items do not stack and do not show quantities

### ISSUE THREAD

**Issue by tak5haka** [fantasycalendar/FoundryVTT-ItemPiles#596]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
While setting up a merchant for Dragonbane, the items will not stack when dragged onto it and the "Configure Merchant Columns" option does not open and throws an error in Console:

foundry.js:631 Error: An error occurred while rendering MerchantColumnsEditor 90. Cannot read properties of undefined (reading 'map')
    at Hooks.onError (foundry.js:630:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:5771:13

**To Reproduce**

1. Create new actor, set it up as a Merchant
2. Drag items onto actor, no stacking, no quantity
3. Click 'Configure Merchant Columns'

**Expected behavior**
I expect stackable items to stack, showing quantity in that column on the merchant sheet (worked before)
I also expect to be able to modify the merchant columns information.

**Setup:**

- Foundry Version: 12.327 & 11.315
- System Version: Dragonbane / Draka och Demoner 1.8.3
- Item Piles Version: 3.0.1
- Browser & version: Google Chrome

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Fixed in 3.0.2
