### ISSUE TITLE
[BUG] - PS2e - Appears that the game-system specific arrays are not getting localization values

### ISSUE THREAD

**Issue by Truncated** [fantasycalendar/FoundryVTT-ItemPiles#598]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
In the System Specific Settings, the following selection drop-downs now have just lists of numbers.
1. Actor class type
2. Item Loot class type
3. Item Weapon class type
4. Item Equipment class type

**To Reproduce**

Install the module.
Go to the settings.
Click dropdowns.

**Expected behavior**
The class types from PS2e, in my case. This was working correctly in the last version release.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/14208325/737531eb-ba50-49c7-953b-de95d2fda993)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/14208325/4f059dcb-e50b-4b5d-a1b4-81308aa62a7b)

**Setup:**

Foundry Virtual Tabletop: Version 11 Stable, 11.315
Game System: pf2e, 5.16.1

- Item Piles Version: 3.0.1
- Browser & version: Edge, Version 126.0.2592.81 (Official build) (64-bit)

**Active modules:**

### Active Modules
Baileywiki Mass Edit v1.70.0
Carousel Combat Tracker v2.7.7
Dice So Nice! v4.6.10
Dice Tray v2.1.11
Item Piles v3.0.1
Color Picker v1.3
libWrapper v1.12.13.1
socketlib v1.0.13
Token Action HUD Core v1.5.5
LiveKit AVClient v0.5.30
Module Management+ v2.2.3
Monk's PF2e Encounter Aftermath v11.05
Monk's Player Settings v11.04
Ownership Viewer v12.0
Pathfinder 2e: Abomination Vaults v3.1.2
PF2e Dorako UX v1.3.6 
Pf2E Modifiers Matter v1.9.5
PF2e Toolbelt v2.4.3
PF2e Workbench v5.65.8
Polyglot v2.4.7
PopOut! v2.18
Token Action HUD Pathfinder 2e v1.5.15
PF2e Dorako UI v3.4.11

**Additional context**

**Comment by Haxxer** [comment]
Fixed in 3.0.2
