### ISSUE TITLE
[BUG] - DND5e - Getting error when double-clicking an item pile

### ISSUE THREAD

**Issue by matthewbstroud** [fantasycalendar/FoundryVTT-ItemPiles#600]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
I have an actor setup as an item pile loot chest.  When I drag the token to map and try to double-click it, it bombs with the error below.

**To Reproduce**

1. Create a actor
2. Configure it as an item pile.
3. Set up the pile with all the images you want (open, closed, locked, etc)
4. Drag the actor to a scene.
5. Double-click the token.

**Expected behavior**
This used to work without issue

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/17620888/aa6056fd-5d3b-4adf-8f98-782397d432a9)

**Setup:**

- Foundry Version: 11.315
- System Version: DnD 5e 3.1.2
- Item Piles Version: 3.0.3
- Browser & version Edge 126.0.2592.81

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**

**Comment by matthewbstroud** [comment]
I was able to get past this by deleting the actor and recreating it...

**Comment by matthewbstroud** [comment]
Actually, nm, it is back...

**Comment by Haxxer** [comment]
I just released 3.0.4, update to it when it's available and test again please!

**Comment by matthewbstroud** [comment]
Seems to be fixed in 3.0.4

**Comment by matthewbstroud** [comment]
Btw, thanks for the quick fix!
