### ISSUE TITLE
[BUG] - [DnD 5e] - Give to Character only sends 1 item

### ISSUE THREAD

**Issue by pumpkin1972** [fantasycalendar/FoundryVTT-ItemPiles#601]
**Are you on the latest version of Item Piles?**
Yes  - 3.0.4

**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
give to character only gives 1 item at a time

**To Reproduce**
Right click on an item with more than quantity 1
select "give to character"
use slider to give more than 1 item
only 1 of the item is transferred

**Expected behavior**
Multiple of the items are transferred, as per the number selected using the slider

**Screenshots**

**Setup:**

- Foundry Version: [e.g. 11.315]
- System Version: [e.g. DND5e 3.2.1]
- Item Piles Version: [e.g. 3.0.4]
- Foundry server

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
slider is picking up the correct quantity for the item (max is set to item quantity) but is not incrementing/decrementing count correctly. It only increments/decrements by 1 regardless of the value selected

**Comment by Haxxer** [comment]
Fixed in 3.0.6
