### ISSUE TITLE
[REQUEST] - Global and Individual Permissions Switch for Same Vault Token,

### ISSUE THREAD

**Issue by ianglang** [fantasycalendar/FoundryVTT-ItemPiles#605]
REQUEST:
Global Vault Setting to only open an instance owned by the PC
PC1 - opens vault token and gets a vault instance for ONLY PC1 permissions.
PC2 - opens samee vault token and gets a vault instance for ONLY PC2 permissions.

if vault set private/single, permissions are clicking.pc = owner.view
else 
use group defined permissions as normal. (vault functions as a group vault)

I'm trying to set up a bank with individual vaults (and I only want to draw one) while the group vault is in another location.
The benefit is not having to set permissions on 5 or 6 different individual vaults or chests.

**Comment by Haxxer** [comment]
Have you taken a look at this?

https://github.com/fantasycalendar/FoundryVTT-ItemPiles-Bankers

**Comment by ianglang** [comment]
Hey Haxxer, thanks.  Tried to install it using the manifest link but the link is broken.

**Comment by Haxxer** [comment]
@ianglang Try again.
