### ISSUE TITLE
[BUG] - [SFRPG] - Placing items in a vault fails with error

### ISSUE THREAD

**Issue by TheGreatRedDuke** [fantasycalendar/FoundryVTT-ItemPiles#606]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Dragging a dropping an item into a vault fails and produces an error in console.

**To Reproduce**  
1. Create a Vault.
2. Try to drop any item into it.
3. Check console.

**Expected behavior**
Item appears in vault and is removed from source location.

**Screenshots**

![Screenshot 2024-07-08 095950](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/78890368/e0e52b2b-a005-42ca-a1f1-73e7fe862476)

**Setup:**

- Foundry Version: 11.315
- System Version: SFRPG 0.25.3 (and v0.26.0)
- Item Piles Version: 3.0.6
- Browser & version: Newest Chrome and Foundry Client 11.315

**Active modules:**
- Item Piles
- libwrapper
- socketlib

**Additional context**
This error appears sometime after version 3.0.0 of Item Piles I believe. Everything worked as expected before then.

**Console Error:**
```caught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'pack')
[Detected 2 packages: system:sfrpg(0.25.3), item-piles(3.0.6)]
    at new ItemSFRPG (item.js:18:21)
    at PrivateAPI._depositWithdrawItem (private-api.js:1685:16)
ItemSFRPG @ item.js:18
_depositWithdrawItem @ private-api.js:1685
```

**Comment by Haxxer** [comment]
This line seems to be relating to the system not handling temporary items very well:
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/master/src/API/private-api.js#L1685
I can't account for systems not handling temporary items well.

**Comment by Haxxer** [comment]
Not an item piles issue, see mentioned link above.
