### ISSUE TITLE
[BUG] - [SYSTEM NAME] - Unlocking as DM does not update lock status on client side

### ISSUE THREAD

**Issue by WolfLycanorcant** [fantasycalendar/FoundryVTT-ItemPiles#607]
Description:
When using the mod, I can lock and unlock as the DM, but when I unlock an item as the DM, the client still shows it as locked. This issue persists even though the only mods activated are LibWrapper and Item Piles.

Steps to Reproduce:

1. Lock an item on the DM side.
2. Attempt to open the item on the client side (it correctly shows as locked).
3. Unlock the item on the DM side.
4. Attempt to open the item on the client side (it still shows as locked).

Expected Behavior:
Unlocking an item as the DM should update the lock status on the client side, allowing the item to be opened.

Environment:

Mod Version: 3.0.6
Foundry VTT Version: 12.328
Operating System: Windows 11
Additional Information:
No other mods were active during testing besides LibWrapper and Item Piles.

**Comment by Haxxer** [comment]
Is not socketlib enabled?

**Comment by Markus-blip** [comment]
I guess it`s similar to my issue #604

**Comment by EireneWolfe** [comment]
I can also confirm that I cannot open or unlock containers. I am running PF2e and made a new world with just this mod and the 2 required mods running. Everything is up to date.

**Comment by danimrath** [comment]
Can confirm also seeing this issue in PF2e

**Comment by Haxxer** [comment]
Fixed in 3.0.7
