### ISSUE TITLE
[BUG] - [Cyberpunk Red Core] - Cannot drag item onto scene

### ISSUE THREAD

**Issue by diwako** [fantasycalendar/FoundryVTT-ItemPiles#609]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
Dragging an item out of a compendium or character sheet will produce no result, an error in the browsers console is thrown

Drag from compendium
```log
TypeError: Cannot read properties of undefined (reading 'prototypeToken')
    at PrivateAPI._createItemPile (private-api.js:1197:19)
    at PrivateAPI._dropItems (private-api.js:1032:29)
    at Object.dropItems (socket.js:105:52)
    at SocketlibSocket._executeLocal (socketlib.js:192:15)
    at SocketlibSocket.executeAsGM (socketlib.js:90:16)
    at ItemPileSocket.executeAsGM (socket.js:185:23)
    at PrivateAPI._dropItem (private-api.js:1786:25)
```

Drag from character sheet
```log
TypeError: Cannot read properties of undefined (reading 'prototypeToken')
    at PrivateAPI._createItemPile (private-api.js:1197:19)
    at PrivateAPI._dropItems (private-api.js:1018:29)
```

**To Reproduce**

1. Use Foundry v11
2. Have a default item pile actor already
1. Go to any compendium which houses items
3. Drag item onto scene
4. See nothing happening

**Expected behavior**
Item pile token created, item added in token sheet

**Screenshots**
![image](https://github.com/user-attachments/assets/0e049408-4b07-4a93-b904-06bcdc1db1db)

**Setup:**

- Foundry Version: [e.g. 11.315]
- System Version: [e.g. Cyberpunk RED - CORE 0.88.2]
- Item Piles Version: [e.g. 3.0.7]
- Browser & version [e.g. Google Chrome 126.0.6478.127]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- A shit ton more, but they appear to be irrelevant see next section why

**Additional context**
Small analysis done to figure out why it happens, to thwart out system or module related issues

Error happens in line 1197 of file `src/API/private-api.js`
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/2423f7b589dfd8a68ee9bac231ace4254e0c9fa2/src/API/private-api.js#L1197

There `pileActor` is undefined, I wondered why that is until I debugged through and saw the culprit. The variable is defined in case a default item pile actor already exists in line 1109 of the same file. 
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/2423f7b589dfd8a68ee9bac231ace4254e0c9fa2/src/API/private-api.js#L1109

Buuut it is defiend as such `let pileActor = ...` so that assignment is only valid for this code block. Line 1197 is already outside the codeblock so `pileActor` is undefined as it was never defined on the same or a parent code block.

**Comment by Haxxer** [comment]
Fixed in 3.0.8, cheers for the assistance!
