### ISSUE TITLE
[BUG] - [Dnd 5e] - Unable to Summon Default item Pile - Drag and Drop Works

### ISSUE THREAD

**Issue by DeadFaceHD** [fantasycalendar/FoundryVTT-ItemPiles#611]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Dropping an item on the canvas produces this error
![image](https://github.com/user-attachments/assets/2fddf4e9-7d9a-45e7-8520-d64740ac886d)

**To Reproduce**
Steps to reproduce the behavior: no idea (will fill it out once i can reproduce it, just want it to work currently)

**Expected behavior**
A item on the canvas

**Setup:**

- Foundry Version: [11.315]
- System Version: [3.2.1]
- Item Piles Version: ![image](https://github.com/user-attachments/assets/e6eaf08b-1017-4fb7-8463-9c5ce2bd55e4)
- Browser & version [tried on OperaGX and Chrome]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- [
[moduleList.json](https://github.com/user-attachments/files/16228378/moduleList.json)
]

**Additional context**
Can answer questions ofc and test.

**Comment by Haxxer** [comment]
Fixed in 3.0.8

**Comment by DeadFaceHD** [comment]
![image](https://github.com/user-attachments/assets/3c68dc06-84ef-438e-a1bd-413289511f1b)

**Comment by Haxxer** [comment]
Is this on Forge? 3.0.8 was _just released_, so it won't have caught up.

**Comment by DeadFaceHD** [comment]
Yes im on Forge, thanks so i just need to wait then?
