### ISSUE TITLE
[BUG] - [D&D5] - Changing token settings resets pile settings

### ISSUE THREAD

**Issue by ElijahaF** [fantasycalendar/FoundryVTT-ItemPiles#615]
**Are you on the latest version of Item Piles?**
Yes, 3.0.8

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When I drop pile, then change anything and update token, pile settings resets to default.

**To Reproduce**
1. Drop any item
![ItemPiles1](https://github.com/user-attachments/assets/a2b427e7-13f5-42a4-ad9d-03f32d5ad7f5)
2. Open item sheet and then token. Change anything on token and then update it.
![ItemPiles2](https://github.com/user-attachments/assets/81e03788-4e8e-496e-b7b9-7870406dda8b)
3. Check pile settings
![ItemPiles3](https://github.com/user-attachments/assets/109603ee-19ae-4b15-9f52-c1fc70599da5)

**Expected behavior**
Changing token settings shouldn't reset pile settings.

**Setup:**

- Foundry Version: 12.328
- System Version: DND5e 3.2.1
- Item Piles Version: 3.0.8
- Browser & version Google Chrome 126.0.6478.128

**Active modules:**
- Item Piles
- libwrapper
- socketlib

**Additional context**
It worked as expected on Foundry v11.

**Comment by Haxxer** [comment]
Fixed in 3.0.9
