### ISSUE TITLE
[BUG] - sfrpg - highlighting even/odd rows

### ISSUE THREAD

**Issue by ddwolf1011** [fantasycalendar/FoundryVTT-ItemPiles#616]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
The even lines are backcolored. In Starfinder with the Starfinder UI Module you can't read it.
For me as a GM, it is possible to change the backcolor via CSS Styles.
But my player can't do that.

**Expected behavior**
An option for players to change Background Color of Highlighting Even/odd rows

**Screenshots**
![players-sight-1](https://github.com/user-attachments/assets/ba012447-c691-43ae-8284-689149b610f7)
![players-sight-2](https://github.com/user-attachments/assets/0271dd55-78df-47a8-b4e7-9b44d10bb780)
![Screenshot 2024-07-21 203249](https://github.com/user-attachments/assets/6f503ad9-a031-49ea-8119-600f547a2a21)
![Screenshot 2024-07-21 203649](https://github.com/user-attachments/assets/565198d0-b359-473e-a9ee-9280da7f2f7d)
![Screenshot 2024-07-21 205650](https://github.com/user-attachments/assets/fdef2c06-7a22-4d5c-84c6-5b82491caf41)
![Screenshot 2024-07-21 205705](https://github.com/user-attachments/assets/1165ac25-8625-4181-9cd3-4c82bc78e670)
![Screenshot 2024-07-21 205714](https://github.com/user-attachments/assets/36ce835f-2180-445a-af52-a49b6b2bca6c)
![Screenshot 2024-07-21 212255](https://github.com/user-attachments/assets/0fcdf72b-def7-41f4-94bd-b949fd24870f)
![Screenshot 2024-07-22 185310](https://github.com/user-attachments/assets/f402f8fa-8ba3-46da-b345-fcff6565b586)
![Screenshot 2024-07-21 203108](https://github.com/user-attachments/assets/cbe78723-3b46-43e4-bf85-95ec4ee9957b)

**Setup:**

- Foundry Version: 12 Stable, Build 328
- System Version: SFRPG 0.26.01
- Item Piles Version: 3.0.8
- Browser & version: MS Edge Version 126.0.2592.113 (Offizielles Build) (64-Bit) & Chrome Version 126.0.6478.128 (Offizieller Build) (64-Bit)

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Starfinder - Dark UI
- and many more, without conflicting CSS Styles

**Additional context**

![players-sight-1](https://github.com/user-attachments/assets/ba012447-c691-43ae-8284-689149b610f7)
![players-sight-2](https://github.com/user-attachments/assets/0271dd55-78df-47a8-b4e7-9b44d10bb780)
![Screenshot 2024-07-21 203249](https://github.com/user-attachments/assets/6f503ad9-a031-49ea-8119-600f547a2a21)
![Screenshot 2024-07-21 203649](https://github.com/user-attachments/assets/565198d0-b359-473e-a9ee-9280da7f2f7d)
![Screenshot 2024-07-21 205650](https://github.com/user-attachments/assets/fdef2c06-7a22-4d5c-84c6-5b82491caf41)
![Screenshot 2024-07-21 205705](https://github.com/user-attachments/assets/1165ac25-8625-4181-9cd3-4c82bc78e670)
![Screenshot 2024-07-21 205714](https://github.com/user-attachments/assets/36ce835f-2180-445a-af52-a49b6b2bca6c)
![Screenshot 2024-07-21 212255](https://github.com/user-attachments/assets/0fcdf72b-def7-41f4-94bd-b949fd24870f)
![Screenshot 2024-07-22 185310](https://github.com/user-attachments/assets/f402f8fa-8ba3-46da-b345-fcff6565b586)
![Screenshot 2024-07-21 203108](https://github.com/user-attachments/assets/cbe78723-3b46-43e4-bf85-95ec4ee9957b)

**Comment by Haxxer** [comment]
The item piles styles are global for all players. Once you have changed them, they should apply for all players. Is this not the case?

**Comment by ddwolf1011** [comment]
oh damned. you are right. we had the problem yesterday and try to figure out. but only my view as a gm was correct, not for the player, who tested for me. but today, after a big reload, everything is like i needed it.
thanks for help :-)
