### ISSUE TITLE
[BUG] - [WWN/D&D 5e/Any?]- Delete when empty setting not respected

### ISSUE THREAD

**Issue by pandanielxd** [fantasycalendar/FoundryVTT-ItemPiles#617]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Putting the "Delete when empty" setting to either "Yes, delete when empty" or "Default module setting (Yes)" is not respected, as item piles are not removed when empty.

**To Reproduce**
1. Enable either setting
2. Put down an item pile
3. Remove all items
4. See that the item pile is not deleted

**Expected behavior**
The item pile is deleted

**Setup:**

- Foundry Version: 12.329
- System Version: WWN 1.4.7
- Item Piles Version: 3.0.8
- Browser & version Firefox 128.0 (but also on the app)

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Fixed in 3.0.9

**Comment by Haxxer** [comment]
https://github.com/SobranDM/foundryvtt-wwn/issues/88
