### ISSUE TITLE
[BUG] - [SWADE] - `On Interact Macro` field doesn't support UUIDs

### ISSUE THREAD

**Issue by SalieriC** [fantasycalendar/FoundryVTT-ItemPiles#619]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
The `On Interact Macro` field doesn't support the UUID of a macro, neither of a macro in the world, nor in a compendium. It seems to only match macros in the world by the name.

**To Reproduce**

1. Set up an item pile.
2. Input the UUID of a macro in the `On Interact Macro` field.
3. Press the edit button next to it.
4. The notification `Item Piles | A macro named Macro was not found in Compendium ...` will appear (or similar).

**Expected behavior**
According to our conversation on Discord, the field should support the UUID of a macro in a compendium as well as the name of a macro in the world.

**Additional context**
System shouldn't affect this as far as I can tell.

**Comment by Haxxer** [comment]
Fixed in 3.0.9
