### ISSUE TITLE
[BUG] - [PF2E] - Item inspect in merchant window does not show item details

### ISSUE THREAD

**Issue by spc-111** [fantasycalendar/FoundryVTT-ItemPiles#620]
**Are you on the latest version of Item Piles?**
Yes  (3.0.8)

**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**

When a player token wants to inspect a merchant item they get the Error: 
"You do not have sufficient permission to view the sheet for this item"

**To Reproduce**

- click on an item in a merchants inventory to inspect it. (Works as a GM , but not as a (trusted) player)

**Expected behavior**

-normally the items description should be visible.

**Screenshots**

![grafik](https://github.com/user-attachments/assets/35695c4f-ebd6-45b2-83e3-ce4dc8a25c52)

**Setup:**

- Foundry Version: 12.328
- System Version: PF2E 6.1.1
- Item Piles Version: 3.0.8
- Browser & version  --> Tested in Chrome and Firefox

**Active modules:**

Break Time 
Cze and Peku - Badger Hill 
Cze and Peku - Crossroads 
Cze and Peku Animated - Village Blacksmith 
Cze and Peku Animated - Windmill Farm 
Dice so Nice! 
Dice Tray 
EZ-Print 
Grid Scaler 
Illandril's Turn Marker 
Item Piles 
libWrapper 
Monk's Player Settings 
One Journal Handouts 
Pathfinder 2e: Abomination Vaults 
PDF to FoundryJmporter 
PF2e Companion Compendia 
Pf2E Modifiers Matter 
PF2e Workbench 
Playlist Importer 
Popout! 
socketlib 
Specters Compendium 
Token Action HUD Core 
Token Action HUD Pathfinder 2e 
Torch 

**Additional context**

Im pretty sure this worked in my last world. Player has default "Trusted Player" permissions. Might just be a weird permissions issue, but im at my wits end here.

**Comment by thejbr12** [comment]
I am having this issue too. It works for GM and Assistant GM, but not for Player or Trusted Player, and none of the core settings have any effect.

I have a long list of modules but I turned everything off except Item Piles, socketlib, and lib-wrapper, and still got the error.

Setup:
Foundry Version: 12.330
System Version: DND5e 3.3.1
Item Piles Version: 3.0.8
Browser & version: Chrome 127.0.6533.73

**Comment by Haxxer** [comment]
Fixed in 3.0.9
