### ISSUE TITLE
[REQUEST] - Macro to change token(s) to Item Pile

### ISSUE THREAD

**Issue by TrofimSelbs** [fantasycalendar/FoundryVTT-ItemPiles#621]
**Is your feature request related to a problem? Please describe.**
Currently you can't quickly convert 8 goblins players just defeated into lootable corpses.

**Describe the solution you'd like**
Would be cool to have a macro/hotkey that you can press when selecting one or more tokens and it will convert tokens into an Item Pile.

**Describe alternatives you've considered**
It can be also done through a HUD button, but this won't be as effective. Or conversion from a token into an ItemPile can be automatic when a token is marked as Dead/Defeated

**Comment by Haxxer** [comment]
https://fantasycomputer.works/FoundryVTT-ItemPiles/#/sample-macros?id=make-tokens-lootable

**Comment by TrofimSelbs** [comment]
Thank you! Didn't see those
