### ISSUE TITLE
[BUG] - [D&D 5e] - Can't inspect ItemPile as a different actor

### ISSUE THREAD

**Issue by TrofimSelbs** [fantasycalendar/FoundryVTT-ItemPiles#622]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
The player couldn't choose their steed (it is an actor that they own) as they are inspecting a pile from

**To Reproduce**
1. Create player and horse actors (the horse's token is linked to an actor, but it uses NPC stat block)
2. Create an item pile on a map
3. Add a player token
4. Login into the foundry to that player's account
5. Open the Item pile
6. Tap Change to change viewing from player to a steed
7. It says in the message (see screenshot) that the change was made. However in the Pile's window it is still stated that I am viewing as Bella, when I should be now viewing as "Bella's horse".

**Expected behavior**
It would allow players to change between owned charachters and gather different items for each of them

**Screenshots**
![SCR-20240725-pnpd](https://github.com/user-attachments/assets/6de7d478-71f3-49ad-b561-7db184e53f7a)

**Setup:**
- Foundry Version: [v11 315]
- System Version: [DND5e 3.1.2]
- Item Piles Version: [3.0.8]
- Browser & version [Google Chrome 127.0.6533.73]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Find Culprit
- Babele
- dlopen
- lib - Color Settings
- routinglib

**Comment by Haxxer** [comment]
Fixed in 3.0.9
