### ISSUE TITLE
[REQUEST] - Add ability to for "Give to character" to send items to different players and not only to your owned tokens

### ISSUE THREAD

**Issue by TrofimSelbs** [fantasycalendar/FoundryVTT-ItemPiles#623]
**Is your feature request related to a problem? Please describe.**
I am not sure if this is a feature request or a bug. When a player goes to send an item from their character sheet to another player's actor — they can't (even if both are online). In the dropdown menu, they only see their other owned actors. 

**Describe the solution you'd like**
Adding the ability to send items to any other player's actor, not only to yourself.

**Additional context**
There are two other ways to send an item. The first is to have both on a scene and they can drop items onto each other (this is not always accessible, but is the quickest). Another method is to initiate a trade, but it has way too much friction compared to just sending from their character sheet.

**Comment by Haxxer** [comment]
If you are on D&D5e, you can right click on items in your character sheet.

**Comment by TrofimSelbs** [comment]
@Haxxer yes, but I can only send them to my other owned actors. Not to other players

**Comment by Haxxer** [comment]
Users must make their characters their default ones by right clicking on their name in the bottom left of the Foundry screen (where all users are listed), and configuring their user account to have a default character. That way, they show up to other players.

**Comment by TrofimSelbs** [comment]
I just verified that and that is not enough. They still don't show up. You need to have at least "Limited" permission to the actor that you wish to send your stuff to

**Comment by Haxxer** [comment]
I cannot remember why I designed it like such, but that seems intentional. Otherwise, characters that players shouldn't know about might show up in the drop-down list.

**Comment by Haxxer** [comment]
Fixed in 3.0.9
