### ISSUE TITLE
[BUG] - [5e] - "Private - only GMs and user can see messages" does not display the message

### ISSUE THREAD

**Issue by TrofimSelbs** [fantasycalendar/FoundryVTT-ItemPiles#625]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When a player buys something from a vendor — neither they nor the GM receives a message if "Output to chat" is set to "Private - only GMs and user can see messages" or "Blind..."

**To Reproduce**

Open the game settings and locate the chat output settings.
Set "Output to chat" to "Private - only GMs and user can see messages" or "Blind...".
Attempt to buy something from a vendor as a player.

**Expected behavior**
A message will be shown in the chat to the player and GM

**Screenshots**
Here is a list of all active modules when testing. I turned off every module except required by ItemPiles or marked as libraries
![SCR-20240808-mbvq](https://github.com/user-attachments/assets/4077d4e3-f47b-4674-a1ed-e352ff993348)

**Setup:**

- Foundry Version: [v11 315]
- System Version: [e.g. DND5e 3.1.2]
- Item Piles Version: [e.g. 3.0.8]
- Browser & version [I tested in both Chrome and Edge]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- see screenshot

**Comment by TrofimSelbs** [comment]
Good day to you! I have just checked, but I unfortunately wasn't able to reproduce the fix. The problem is even worse for me now — there is no message in chat even when it is set to "Public", instead of "Private". 

All of my parameters are as they appear in previous comments. I am v11 315 and made sure to update to 3.0.10

**Comment by Haxxer** [comment]
Any errors in the console?

**Comment by TrofimSelbs** [comment]
As a matter of fact — yes. These appeared after player has purchased an item

![image](https://github.com/user-attachments/assets/13701a45-d9b2-4542-9566-e29f5acbee51)

**Comment by Haxxer** [comment]
Definitely fixed in 3.0.11 - this was a v11 only issue

**Comment by TrofimSelbs** [comment]
Thank you 🙏 
Will check later

**Comment by TrofimSelbs** [comment]
Everything works! Many thanks
