### ISSUE TITLE
[BUG] - [Fallout] - Item settings window to small to see options

### ISSUE THREAD

**Issue by Nevets1701** [fantasycalendar/FoundryVTT-ItemPiles#627]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
I cannot resize the Items setting menu for specific items in a merchant's inventory and as a result the window is to small to see most of the options.

**To Reproduce**

Open a merchant and click the item property buttons for an item.

**Setup:**

- Foundry Version: [e.g. 12.330}
- Item Piles Version: [e.g. 3.0.8]
- Browser & version [Firefox]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Dice so Nice
- less fog
- simple calendar

**Comment by Haxxer** [comment]
Fixed in 3.1.0
