### ISSUE TITLE
[BUG] - [5e] - Merchant's rolled items not assigned to custom categories

### ISSUE THREAD

**Issue by Janner3D** [fantasycalendar/FoundryVTT-ItemPiles#630]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Populating a merchant via roll tables does not assign rolled items to the custom categories that have been set in the options.

**Expected behavior**
items should be assigned to the set custom categories when rolled and added to the vendor.

**Screenshots**
![image](https://github.com/user-attachments/assets/0e821f46-d0e0-4655-94f4-07bb577b5436)
![image](https://github.com/user-attachments/assets/5ca46af7-4ccb-4459-bccf-c3f0ebb4fc84)

**Setup:**

- Foundry Version: 11.315
- System Version: 3.2.1
- Item Piles Version: 3.0.9
- Browser & version Google Chrome 127.0.6533.119

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Fixed in 3.0.10
