### ISSUE TITLE
[BUG] - [D&D5e] - Item not found....

### ISSUE THREAD

**Issue by Zarhog** [fantasycalendar/FoundryVTT-ItemPiles#633]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
when purchasing items from venders, item is not given, reason unclear. Money is taken, transaction is logged, no error shows.

**To Reproduce**

1. Go to https://vtt.tcrdnd.com/game
2. Login as player and login as GM
3. attempt to purchase item as user from Garnoor the melee master
4. notice how no item is given to player

**Expected behavior**
Money removed from player, item given to player 

**Screenshots**
 Video in Dm's with Aura
 
**Setup:**

- Foundry Version: V12
- System Version: D&D 5e

**Comment by Haxxer** [comment]
As discussed, could not reproduce on your server
