### ISSUE TITLE
[BUG] - [D&D 5e] - Vaults not updating untill closed and re-opened

### ISSUE THREAD

**Issue by Zarhog** [fantasycalendar/FoundryVTT-ItemPiles#635]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When adding or removing items from a vault, the vault dose not update untill you close and re-open the vault

**Expected behavior**
Vault updates as items are added and removed

**Comment by Haxxer** [comment]
Fixed in 3.1.0
