### ISSUE TITLE
[REQUEST] - Ability to show item images to players, like you can show token images when in pile.

### ISSUE THREAD

**Issue by SirAron111** [fantasycalendar/FoundryVTT-ItemPiles#64]
This request is simple, I think at least.
I love the way you can hover over images in the item piles, and it makes them more visible by putting an enlarged image next to it.
Is there a way to make it also able to show the used artworks for the items to the players like you can with actors and stuff?
Because I use a lot of artwork for important items, I would like to be able to put up the image from the pile or so to my players and describe what they found etc. before allowing them to go for grabs within the pile. Like basically an ability to click on the image and enlarge it and then show to all players kinda thing like with actors etc..

**Comment by Haxxer** [comment]
Added right click context menu to item piles' inventory UIs as of 1.4.4
