### ISSUE TITLE
[BUG] - [DnD5e] - Can't set an item's sell price modifier to 100%

### ISSUE THREAD

**Issue by faidlar** [fantasycalendar/FoundryVTT-ItemPiles#649]
**Are you on the latest version of Item Piles?**
Yes - Just tested after installing 3.1.2

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
I changed the sell price modifier on an item from 100 to any other value and it works ok.  However I cannot set it back to 100 using either the slider or typing it in.  After clicking update the item and reopening the configure panel the sell modifier is back to what it was before I changed it to 100.  Changing it to any other value works fine. Only 100 seems to be broken. 

**To Reproduce**

1. Edit an item
2. Click on configure in the title bar
3. Change to the Price Settings tab.
4. Drag the slider or type in any value other than 100 for the sell price modifier.
5. Click Update Item
6. Click Configure in the item title bar
7. Go to the Price Settings tab.  Note that the value for Sell Price Modifier is what you set it to.
8. Change the Sell Price Modifier value to 100 with the slider or by typing it in.
9. Click Update Item
10. Click Configure in the item title bar
11. Go to the Price Settings tab.  Note that the value for Sell Price Modifier is what you set it to before changing it back to 100.

**Expected behavior**
Setting the value to 100 should save a value of 100 for the Sell Price Modifier

**Screenshots**
Not applicable.

**Setup:**

- Foundry Version: V12 build 331
- System Version: DND5e 3.3.1
- Item Piles Version: 3.1.2
- Browser & version  Google Chrome 128.0.6613.86

**Active modules:**
- Item Piles
- libwrapper
- socketlib
Used find the Culprit and only kept these 3 active and it was still a problem

**Additional context**
nope

**Comment by Haxxer** [comment]
I cannot reproduce this, could you please get in touch through Discord? I am not able to reproduce your issues, and would like to test on your server.

My discord handle is wasp

**Comment by faidlar** [comment]
Sorry, I am not that discord literate.  Please send me a message at Faidlar

**Comment by Haxxer** [comment]
Confirmed to be caching issue on user side
