### ISSUE TITLE
Unlock DC

### ISSUE THREAD

**Issue by Orionox** [fantasycalendar/FoundryVTT-ItemPiles#65]
It would be amazing if you could set a DC for an item pile and then when a player interacted with it they could choose to attempt to pick the lock, use a key (if they have one), or try and smash the item pile.

**Comment by Haxxer** [comment]
Item Piles is a system agnostic module, so that would not be applicable for every system.

**Comment by Haxxer** [comment]
Please use the templates when requesting new features.
