### ISSUE TITLE
[BUG] - [DND5E] - Merchant: Adventuring Supplies draw results are type: Text

### ISSUE THREAD

**Issue by zero127** [fantasycalendar/FoundryVTT-ItemPiles#651]
**I confirm the following:**
- [x] I am on the latest version of Item Piles
- [x] I have tried to clear my cache (Ctrl / Cmd + F5)
- [x] I have checked the console for errors (F12 to open, Console tab)
- [x] I have tried to reset Item Piles' system settings

**Describe the bug**
The item population table given with the module (which is great, btw) was type Text, thus couldn't be used to populate merchants. I exported the table, and did a mass-replace on the JSON (attached) to turn it to type "pack" which lets the items populate. Figured i'd share the few moments of work it took to fix this.

**To Reproduce**
- Create any merchant Pile
- add table: Merchant: Adventuring Supplies
- attempt to roll items with Roll All and/or Roll icon
- Fail to see any items from table roll.

**Expected behavior**
Items are added to the table

**Setup**
- Foundry Version: 12.331
- System Version: DND5e 3.3.1
- Item Piles Version: 3.1.2
- Browser & version: self-hosted GM client

**Active modules**
- Item Piles
- libwrapper
- socketlib

**Additional context**
Attached is the exported JSON from my game's fixed table. Next release, you can either import this before you do, or if you prefer, export your current table's version of the content if say, it changed or w/e, find-replace "type": "text" with "type": "pack" - the rest of the compendium fixes itself upon re-import. Fixed my own, but figured i'd share. Feel free to close this ticket once somebody's read it ! I don't need any assistance at the moment with it. Thanks for an insanely glorious module.

[fvtt-RollTable-merchant_-adventuring-supplies-02WTBwcVhFAMOFlj.json](https://github.com/user-attachments/files/16822928/fvtt-RollTable-merchant_-adventuring-supplies-02WTBwcVhFAMOFlj.json)

**Comment by Haxxer** [comment]
Did you unlock the compendium and change the type of the rolltable? It is fine on my end - can you try to reinstall item piles?

**Comment by zero127** [comment]
Weird, no clue haha, if its just me then no biggy! I don't think so i just did an import-all when I brought it into the world. it was the only one like that i checked the other tables, maybe just a fluke then. who knows. lol, either way, its fixed for me and if its just my problem, we can probably wrap this up! Apologies if that wasted any of your time. :)
