### ISSUE TITLE
[BUG] - pvt - Missing i18n for NoCurrency

### ISSUE THREAD

**Issue by geoidesic** [fantasycalendar/FoundryVTT-ItemPiles#653]
**I confirm the following:**
- [x] I am on the latest version of Item Piles
- [x] I have tried to clear my cache (Ctrl / Cmd + F5)
- [x] I have checked the console for errors (F12 to open, Console tab)
- [x] I have tried to reset Item Piles' system settings

**Describe the bug**
Missing translation string.

**To Reproduce**
1. Drag item from game to scene
2. Click `+ Add Currency`
3. See `Editing Currencies` dialog
4. See missing translation for `ITEM-PILES.Applications.EditCurrencies.NoCurrency`

**Expected behavior**
Engrish!

**Screenshots**
![Screenshot 2024-09-01 at 08 45 14](https://github.com/user-attachments/assets/bbf4d052-f01b-4a67-97af-e52125eac8ca)

**Setup**
- Foundry Version: v12 (350)
- System Version: pvt
- Item Piles Version: 3.1.2
- Browser & version: Brave v 1.69.153

**Active modules**
- Item Piles
- libwrapper
- socketlib

**Additional context**
Occurs when no currencies are defined.

**Comment by Haxxer** [comment]
Fixed in 3.1.5
