### ISSUE TITLE
[BUG] - [DND5E] - Dragging problem with item container

### ISSUE THREAD

**Issue by escixi** [fantasycalendar/FoundryVTT-ItemPiles#654]
**I confirm the following:**
- [✔] I am on the latest version of Item Piles
- [✔] I have tried to clear my cache (Ctrl / Cmd + F5)
- [✔] I have checked the console for errors (F12 to open, Console tab)
- [✔] I have tried to reset Item Piles' system settings

**Describe the bug**
Dragging an item container with items in it onto an item pile container will duplicate the items inside the item container.
**To Reproduce**
Steps to reproduce the behavior: Same as described.

**Expected behavior**
The items inside the item container not duplicating.
**Screenshots**
Everything before dragging
![image](https://github.com/user-attachments/assets/7535b437-7631-4a08-aeed-81c70a3447b6)
Everything after dragging
![image](https://github.com/user-attachments/assets/02648b80-8483-47e6-90fe-b8b797bff46f)

**Setup**
- Foundry Version: [12.330]
- System Version: [DND5e 3.3.1]
- Item Piles Version: [3.1.4]

**Active modules**
- Item Piles
- libwrapper
- socketlib

**Additional context**
There are also no errors showing up on the console. And if the items in the item container is also an item container, it do not duplicate.

**Comment by Haxxer** [comment]
So new items should _always_ be added to contains with the same item?

**Comment by Haxxer** [comment]
Without a response, I will not action this.
