### ISSUE TITLE
[REQUEST] - Defaults apply to NPC token sharing

### ISSUE THREAD

**Issue by thystra** [fantasycalendar/FoundryVTT-ItemPiles#655]
**Is your feature request related to a problem? Please describe.**
When the PCs kill a monster, I'd like to turn their corpse into an item pile/lootable. I would like it to reference the default settings as adjusted (for example, always enable take all, share only with active players, etc). 

**Describe the solution you'd like**
When enabled (or via automation when the token dies, turn into a item pile that the PCs can loot. 

**Describe alternatives you've considered**
I've tried changing the defaults, but it doesn't seem to apply. 

**Additional context**

**Comment by Haxxer** [comment]
It should. Try turning it into an item pile with the API method shown in the sample macros in the wiki.

**Comment by thystra** [comment]
I was able to make a macro to do it, thanks. I'll have to look into how to further automate that.

**Comment by Haxxer** [comment]
Fixed in 3.1.5
