### ISSUE TITLE
[SYSTEM] - WWII:OWB 

### ISSUE THREAD

**Issue by chrisesharp** [fantasycalendar/FoundryVTT-ItemPiles#66]
# **https://foundryvtt.com/packages/owb**

**Comment by Haxxer** [comment]
Are currencies considered items in this system, or is there simply no currencies?

**Comment by chrisesharp** [comment]
Currencies are just items, like in OSE.

**Comment by Haxxer** [comment]
As of the latest version of OSE and with Item Piles 1.4.4, you will no longer get a system incompatibility warning
