### ISSUE TITLE
[BUG] - [Dragonbane]- Items in merchants are lsited as free

### ISSUE THREAD

**Issue by jcarhat** [fantasycalendar/FoundryVTT-ItemPiles#660]
**I confirm the following:**
- [x] I am on the latest version of Item Piles
- [x] I have tried to clear my cache (Ctrl / Cmd + F5)
- [x] I have checked the console for errors (F12 to open, Console tab)
- [x] I have tried to reset Item Piles' system settings

**Describe the bug**
When important an item into an item pile as a merchant, the price listed is 'Free'. Nothing I do seems to change this

**Comment by Haxxer** [comment]
In addition, your bug report does not have a lot of information, such as system version, foundry versions, item piles version, screenshots and examples. Without those, I cannot help you effectively. These things are important, or we will have to have a chat-like conversation on a platform designed for detailed discussion at length. Please fill out the full bug template, as it will help us both.
