### ISSUE TITLE
[REQUEST] - Merchant - Stackable containers

### ISSUE THREAD

**Issue by MaineKnight** [fantasycalendar/FoundryVTT-ItemPiles#661]
Version: 3.1.5
Game system: Dnd 5e (4.0.2)

* Not sure if this is due to something in Item Piles or something new in the 5e updates.

When you create a merchant and add containers (barrels, vials, pouches, kits, etc) they just keep adding. It would be nice to see them stack like the other items so instead of:

vial
vial
vial

you would get 

vial  x3

**Comment by Haxxer** [comment]
D&D 4.0.2 is not yet supported.

**Comment by Haxxer** [comment]
Are vials _containers_?

**Comment by MaineKnight** [comment]
![Screenshot 2024-09-19 153146](https://github.com/user-attachments/assets/ac69ed1c-cbda-42ad-aff9-319e254047bf)

**Comment by Haxxer** [comment]
What if a vial has contents? Would it stack with the rest of other vials? It would lose its contents.

**Comment by MaineKnight** [comment]
I believe that is why containers show differently. Like the Priest's Pack, contains 6 items, some with multiple quantities, but it is sold in the players handbook as a single set. It seems items such as a "vial of poison" is actually listed as a "potion". So in the case of containers it seems they are meant to be sold empty and then once you fill it with say a potion you would replace the empty vial in your character inventory with the appropriate potion.

I'm thinking like pouches, you can have 4 on your character for example, each with different stuff, but you would buy it empty from the store to start with, add it to your character, then start adding items to it.

**Comment by Haxxer** [comment]
I cannot distinguish between these types, since they are all type "containers". If I disable stacking for containers, backpacks will merge and spill their contents.

**Comment by MaineKnight** [comment]
Yeah, I just noticed that. If I have multiple "packs" and put items in them as they are in the official PHB compendium it duplicates the items into separate lines in the merchant inventory so you get blanket, blanket, blanket.

Was worth a shot, thanks for looking into it. I'll just add them as a single item as they are now and if they need to know what is in it they can look at the phb.
