### ISSUE TITLE
[BUG] - [DND5e 4.0.3] - Merchants - Containers with items are not handled 

### ISSUE THREAD

**Issue by lholden** [fantasycalendar/FoundryVTT-ItemPiles#663]
**I confirm the following:**
- [ X ] I am on the latest version of Item Piles
- [ X ] I have tried to clear my cache (Ctrl / Cmd + F5)
- [ X ] I have checked the console for errors (F12 to open, Console tab)
- [ X ] I have tried to reset Item Piles' system settings

**Describe the bug**
A couple issues I've noticed with containers:
1. Dragging a container with items into Populate Items results in an empty container on the merchant
2. If you drag a container with items into the merchants Character Sheet, and then have an Actor view the merchant, the container is empty for that Actor (and obviously, buying it results in an empty bag)

**To Reproduce**
Steps to reproduce Populate Item bug:

1. Create an Actor called Merchant
2. Configure Merchant to be an Item Piles Merchant
3. Navigate to Populate Items
4. Drag Explorer's Pack to Populate Items
5. Inspect the empty Explorer's Pack

Steps to reproduce the Actor viewing the merchant bug:

1. Create an Actor called Merchant
2. Create an Actor called Player who is owned by a player
3. Open Merchant's character sheet and give them an Explorer's Pack
4. Configure Merchant to be a Item Piles Merchant.
5. As as player, interact with the Merchant
6. Inspect or Buy the container

**Expected behavior**
The container to have items when purchased :)

**Setup**
- Foundry Version: 12 331
- System Version: DND5e 4.0.3
- Item Piles Version: 3.1.5
- Browser & version: Firefox 129.0.1

**Active modules**
- Item Piles
- libwrapper
- socketlib
- Players Handbook 1.1.2

**Additional context**
I know Item Piles doesn't support D&D 4.0.X yet.. Just hoping the bug report helps :D.

**Comment by Haxxer** [comment]
What should happen if a player tries to sell an item containing another item? Should it also be transferred over? This seems problematic.

**Comment by lholden** [comment]
> What should happen if a player tries to sell an item containing another item? Should it also be transferred over? This seems problematic.

A player selling containers does seem more problematic. I was more concerned with the merchant being able to sell to the player. I could see blocking the player from selling the container unless it's empty.

I think pricing becomes a big issue in this situation as well. 

The Explorer's Pack example I gave above has the pack itself priced. This makes sense some sense the merchants perspective... but not from the players perspective. I'd be half inclined to just prevent these kinds of packs from being sold back to the merchant. That, or I'd want Item Piles to let me price the item based on the container's price + the price of all of the contained items. (Then I'd just adjust the price of the pack itself on the merchant).

**Comment by lholden** [comment]
TBH, I think blocking containers containing items from even being sold or bought would be OK too. Would be easier to implement and prevent surprising behaviors.

**Comment by Haxxer** [comment]
Fixed in 3.1.6 - this fix does not prevent players from selling containers and their contents, and the sell price only takes the container's price into consideration
