### ISSUE TITLE
[BUG] - [Dnd5e] - All item piles tokens dragged onto map from sidebar or converted from dead actor tokens are missing all settings in "Other Settings"

### ISSUE THREAD

**Issue by Commander-Fayne** [fantasycalendar/FoundryVTT-ItemPiles#666]
**I confirm the following:**
- [X] I am on the latest version of Item Piles
- [X] I have tried to clear my cache (Ctrl / Cmd + F5)
- [X] I have checked the console for errors (F12 to open, Console tab)
- [X] I have tried to reset Item Piles' system settings

**Describe the bug**
I have a bunch of default actors with attached tokens for Item Piles. The default chest, for example, has been configured as a container, has image paths for open, closed, empty, and sounds for all of those changes. It's main settings have been configured as well. 

![image](https://github.com/user-attachments/assets/51dc3365-073d-4d29-99a6-8d6fc6be6ce8)
![image](https://github.com/user-attachments/assets/842aa213-1c3d-4dc4-98b2-7c5b62b19eda)

This was working for a long time just fine, so I know I've set it up properly. However, after the most recent update (to 3.1.5) this behavior is broken. Now, when I drag a new token out from the actor sidebar to represent a new chest, the main settings are still there, but "Other Settings" has been reset to a default. It's been set back to "Item Pile", and all the options are reset, meaning I have to go back through them and set all the settings up again for the chest. 

![image](https://github.com/user-attachments/assets/63440575-fd13-4e67-b114-d56aa90a4686)
![image](https://github.com/user-attachments/assets/1f3ad414-980c-4df6-9aba-bf85c2a794c5)

(ignore that the chest has been appended with a name. That's a different module, and this bug was occuring before I loaded that module)

There is no console error or any output in console when the token is generated. 

**Setup**
- Foundry Version: 12.331
- System Version: 3.3.1
- Item Piles Version: 3.1.5
- Chrome 129.0.6668.59

**Active modules**
- Item Piles
- libwrapper
- socketlib
- [I have quite a few modules, if you need the full list I've provided it in screenshot so I don't have to type all these out]
![image](https://github.com/user-attachments/assets/0171c55c-4254-48ea-849e-c50494056eba)
![image](https://github.com/user-attachments/assets/5b9659f9-da83-4ce4-a0f0-3d05308f31bc)
![image](https://github.com/user-attachments/assets/5129ffcf-4a25-4f24-8f18-39d9395a2e35)
![image](https://github.com/user-attachments/assets/288a0690-972f-49ca-ae47-e618e335d2be)

**Additional context**

**Comment by Haxxer** [comment]
Have you tried with only item piles and its dependencies enabled? You have a fair few modules enabled :D

**Comment by Commander-Fayne** [comment]
Yes, that was the first thing I tried. 

![image](https://github.com/user-attachments/assets/7d404cf5-7014-4a35-a2b1-72ea16290526)

**Comment by Haxxer** [comment]
Fixed in 3.1.6
