### ISSUE TITLE
[REQUEST] World Script or Option to Automatically Change Token to an Item Pile on Death

### ISSUE THREAD

**Issue by Red5MT** [fantasycalendar/FoundryVTT-ItemPiles#669]
I would like the option for defeated tokens to automatically be turned into an item pile when they are killed. If an automatic option would be too challenging/time-consuming, alternately, a GM-only button on the token hud would be another way to go (and the option to enable/disable the button in the config as well).

I did come across the macros on the wiki for manually changing a selected token to and from the Item Pile 'state', but I am not savy enough to turn those into a World Script.

Thank you for the consideration.
And Thank You for a very slick module.

Foundry VTT 12.331 / DnD5e 3.3.1 / Item Piles 3.1.6

**Comment by Haxxer** [comment]
Each system tracks the status of heath differently. This is beyond the scope of item piles. You can take a look at other modules, such as ironmonk's modules - I can't recall which one, but one of his modules supports what you are requesting.

**Comment by Red5MT** [comment]
Thanks for the information. I will look at Monk's stuff to see if there is a solution.

**Comment by pbromwelljr** [comment]
@Red5MT Not sure if you found a solution for this or not, but this is the World Script I came up with to create an item pile from a dead or unconscious creature's items for DnD 5e: https://gist.github.com/pbromwelljr/7a6320d843116d5a2a1145e52d04daa6
