### ISSUE TITLE
[REQUEST] - Make request trade button compatible with Minimal UI

### ISSUE THREAD

**Issue by JulieWinchester** [fantasycalendar/FoundryVTT-ItemPiles#67]
**Is your feature request related to a problem? Please describe.**
When using the Item Piles module alongside the Minimal UI module and setting "Player List Behaviour" to "Auto-Hide" in the Minimal UI settings, the Request Trade button from Item Piles minimizes in a non-ideal way:

<img width="76" alt="Screen Shot 2022-02-18 at 1 07 49 PM" src="https://user-images.githubusercontent.com/14943160/154747406-ea2a51a0-fcdd-4246-8b61-42a04ee737e5.png">

**Describe the solution you'd like**
It would be great if the button could minimize to just the handshake icon.

**Describe alternatives you've considered**
The alternatives would be to not use minimal UI, or to not have minimal UI minimize the player list. For the moment I will likely not minimize the player list in order to use Item Piles, but it would be great to be able to use the minimized version.

**Additional context**
Thanks very much for making this module, it's fantastic! A similar request to this was also made on Reddit by another user (https://www.reddit.com/r/FoundryVTT/comments/soqotb/comment/hwbzyqa/?utm_source=share&utm_medium=web2x&context=3).

**Comment by Haxxer** [comment]
Fixed in 1.4.4
