### ISSUE TITLE
[BUG] - [SYSTEM NAME] - Describe bug here

### ISSUE THREAD

**Issue by TheXeno30** [fantasycalendar/FoundryVTT-ItemPiles#671]
**I confirm the following:**
- [x ] I am on the latest version of Item Piles
- [ x] I have tried to clear my cache (Ctrl / Cmd + F5)
- [ x] I have checked the console for errors (F12 to open, Console tab)
- [x ] I have tried to reset Item Piles' system settings
- [x ] I have reproduced this bug with only item piles & its dependency modules enabled

**Describe the bug**
Vault is not showing GP in the vault overview. The gold is there but not showing.

**To Reproduce**
Steps to reproduce the behavior: look at a vault

**Expected behavior**
To show the gp count

**Screenshots**
![image](https://github.com/user-attachments/assets/36518bbd-1999-48a1-a502-d31178d68f7f)
![image](https://github.com/user-attachments/assets/6e501865-5b11-4761-b4d3-2b6ed19ba79f)

**Setup**
- Foundry Version: 12.331
- System Version: DND5E 331
- Item Piles Version: 3.1.8
- Browser & version Google Chrome

**Active modules**

**Additional context**

**Comment by Haxxer** [comment]
How can you be on a newer version than what is released? :D

**Comment by Haxxer** [comment]
Can you take a screenshot of the currency settings in the module configuration?

**Comment by TheXeno30** [comment]
I'm sorry - my eyes were deceiving me :D - 3.1.6
![image](https://github.com/user-attachments/assets/1088f830-eb87-4fd9-ac58-7dfe4b2b78db)
![image](https://github.com/user-attachments/assets/29d22b70-a539-4ff3-bcf2-d21bc592badd)

**Comment by TheXeno30** [comment]
seems like i had a container (D&D container) inside the vault with GP in it. As soon as i removed the GP from the bag the GP icon showed up :)
