### ISSUE TITLE
[BUG] - Docs: API implementation doesn't match documentation

### ISSUE THREAD

**Issue by anthonyronda** [fantasycalendar/FoundryVTT-ItemPiles#68]
**Describe the bug**
- The Item Type Filters API are documented with the wrong names
- The documentation seems to suggest the setItemFilters method takes strings but it actually takes objects? This is unclear and could use a little more explanation
- The documentation suggested that the API consumer is writing items to filter *in*, but it's actually items to filter *out*

**To Reproduce**
N/A

**Expected behavior**
This is documented as:
ITEM_TYPE_FILTERS ⇒ Array

The filters for item types eligible for interaction within this system

setItemTypeFilters(inFilters) ⇒ <code>Promise</code>

Sets the filters for item types eligible for interaction within this system

Param | Type
-- | --
inFilters | string/array

**Actual Behavior**
ITEM_FILTERS ⇒ Array of Obj

setItemFilters(inFilters) ⇒ <code>Promise</code>

Sets the filters for item types **not** eligible for interaction within this system

**Setup:**
 - Foundry Version: 9.249
 - System Version: OSE 1.4.0-dev :wink:
 - Item Piles Version: 1.4.3
 - Browser & version: Electron Wrapper

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**
No rush to answer, I've figured out what to do 👍

**Comment by Haxxer** [comment]
Fixed as of latest updates:

https://fantasycomputer.works/FoundryVTT-ItemPiles/#/api
