### ISSUE TITLE
[BUG] - Unable to Create Spell Scroll

### ISSUE THREAD

**Issue by azarius74** [fantasycalendar/FoundryVTT-ItemPiles#70]
**Describe the bug**
With Item Piles enabled, writer is unable to make spell scrolls from dragging/dropping spell onto item pile.  Writer disabled Item Pile, and spell scrolls created without issue.  

**To Reproduce**
1. Go to 'items'
2. Drag spell onto canvas
3. Spell scroll not created
4. Error "You are dropping an item that is of a type ("spell" that is not normally allowed to be dropped.  Are you sure you want to do this?"

If writer removes the filter for spells, spell shows up in item pile, but not as a spell scroll.

**Expected behavior**
Spell Scroll should be created.

**Setup:**
 - Foundry Version: p
 - System Version: DND5e 1.5.7
 - Item Piles Version: 1.4.5 -  
 - Chrome Version 98.0.4758.102 (Official Build) (32-bit)

**Comment by Haxxer** [comment]
Not a bug. D&D5e transforms spells into scrolls only when dropped into the inventory tab of actors, which is system specific. Item Piles is system agnostic, so supporting this is highly unlikely to happen.
