### ISSUE TITLE
[BUG] - Crash when attempting to create item pile with 2+ items via API

### ISSUE THREAD

**Issue by TheGiddyLimit** [fantasycalendar/FoundryVTT-ItemPiles#74]
**Describe the bug**
As per title :)

**To Reproduce**
1. Create a new scene
2.
```js
(async () => {
	const item1 = await Item.create({name: "Test", type: "loot"})
	const item2 = await Item.create({name: "Test 2", type: "loot"})

	await ItemPiles.API.createItemPile({x: 1000, y: 1000}, {items: [item1, item2]});
})();
```

**Expected behavior**
An item pile is created

**Screenshots**
A crash occurs:

```
lib.js:202 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
[Detected 1 package: item-piles]
    at Module.getItemPileTokenImage (lib.js:202:34)
    at Object._createItemPile (api.js:2342:28)
    at async <anonymous>:12:2
```

**Setup:**
 - Foundry Version: [e.g. 9.249]
 - System Version: [e.g. DND5e 1.5.7]
 - Item Piles Version: [e.g. 1.4.5]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment]
Those are not valid items. They lack all of the data needed in any Foundry game system.

**Comment by TheGiddyLimit** [comment]
Fair enough. Edited the original with a better example. Same issue occurs either way~

**Comment by Haxxer** [comment]
Thank you, I just wanted to make sure it wasn't user error.
