### ISSUE TITLE
[BUG] - Spoiler Identify Item on Loot

### ISSUE THREAD

**Issue by ArdonDaros** [fantasycalendar/FoundryVTT-ItemPiles#76]
**Describe the bug**
Unidentified items are automatically identified in chat as part of the text of who looted what.

**To Reproduce**
1. Loot an unidentified item as a player.
2. See in chat what you looted before you identified the item.

**Expected behavior**
To see the item in chat text as the unidentified item.

**Screenshots**
See screenshot

**Setup:**
 - Foundry Version: version 9
 - System Version: Pathfinder 1, version 0.80.9.
 - Item Piles Version: version 1.4.5
 - Browser & version: Google Chrome 98.0.4758.102

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - Total of 62 active modules

**Additional context**

![ItemPileIdentifyBug](https://user-images.githubusercontent.com/75624347/156405447-0adae36b-9a15-462b-a573-f429275af246.jpg)

**Comment by Haxxer** [comment]
Identification of items is a system specific thing. I do not know how a system agnostic module like Item Piles can assist in this regard. I will evaluate some potential solutions, but if the system changes the data on the fly, there's not much I can account for if I am to support the multitude of other systems that use Item Piles.

**Comment by ArdonDaros** [comment]
> Identification of items is a system specific thing. I do not know how a system agnostic module like Item Piles can assist in this regard. I will evaluate some potential solutions, but if the system changes the data on the fly, there's not much I can account for if I am to support the multitude of other systems that use Item Piles.

Fair enough. However, using PF1.LootSheetPf1NPC sheet and looting an item retains the unidentified name, hence I believed the bug would be with ItemPiles.

That said, using the PF1 LootSheet has a host of other issues why I would prefer not to use it, and opt for Item Piles instead.

![ItemPileIdentifyBug_furtherinfo](https://user-images.githubusercontent.com/75624347/156406435-78a7b752-6846-4f56-bd77-4a82811f8a2f.jpg)

**Comment by Haxxer** [comment]
As per the name, that is a system specific sheet. Item Piles is not. I will attempt my best, but I promise nothing.

**Comment by Haxxer** [comment]
Fixed this issue in the upcoming minor version update
