### ISSUE TITLE
[BUG] - Similarities look for exactly matching items, if they don't find any, they merge with existing items, even though they're not similar

### ISSUE THREAD

**Issue by gsterling** [fantasycalendar/FoundryVTT-ItemPiles#77]
**Describe the bug**
When I have a slightly broken item and pickup a new one, it just adds 1 to the broken item. Therefore making it broken, too. If I had a broken and a non-broken item, it would add it to it's matching item instead.

**To Reproduce**
1. Configure a new item similarity. I used "data.sufferedDamage" for Splittermond.
2. Create an undamaged item
3. Create copy by dropping it on the floor
4. Break the item in your inventory
5. Pickup the item
6. It gets added to the broken version of itself and is therefore broken, too
7. Delete everything in your inventory
8. Create a new undamaged item
9. Copy it, so it exists two individual times, not one item with a quantity of 2
10. Break one of the items
11. Copy both by dropping them in a pile on the ground
12. Pickup the undamaged item
13. The undamaged item increases it's quantity by 1
14. Pickup the damaged item
15. See an error, that the second item can't be picked up
![image](https://user-images.githubusercontent.com/58980630/157531963-f8ce3b17-55e4-40d9-b842-5328b40ebffb.png)
17. Close the item pile
18. Reopen the item pile
19. Pickup the damaged one again
20. You now have 2 of each item as expected.

**Expected behavior**
When picking up items, don't sort them with items not identical by the defined similarities, but instead create a new item with it's unique properties.

**Setup:**
 - Foundry Version: 9.255 (latest)
 - System Version: Splittermond 0.8.1 (latest)
 - Item Piles Version: 1.4.5 (latest)
 - Browser & version: Chromium 99 (latest) & Firefox 98 (latest)

**Active modules:**
![image](https://user-images.githubusercontent.com/58980630/157532843-e0a3f289-101f-4f90-81c3-41a65decf556.png)
![image](https://user-images.githubusercontent.com/58980630/157532900-14d4fd02-a5b4-4693-b549-acc2023fd7a7.png)
![image](https://user-images.githubusercontent.com/58980630/157532925-8c3f0317-8bd2-47a9-99a1-dc0f2f1d000b.png)

**Comment by Haxxer** [comment]
As this system that I've never played in, was made in a language that I don't understand, could you elaborate on the steps to reproduce this bug? How do I break items?

**Comment by Haxxer** [comment]
I think this is in fact a bug with the system itself - do you know of any way to get in touch with the creators of this system?

**Comment by Haxxer** [comment]
Fixed this issue in the upcoming minor version update

**Comment by gsterling** [comment]
Do you know savage worlds? I could try to reproduce bugs in that setting in the future for you.
