### ISSUE TITLE
[BUG] - ItemPiles Broken on PF2e

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-ItemPiles#78]
**Describe the bug**
ItemPiles containing items break in the Pathfinder 2nd Edition System.

**To Reproduce**
1. Create an Item Pile
2. If have not already, add an item into it
3. Attempt to open it again

**Expected behavior**
The Item Pile menu opens with items inside.

**Screenshots**
When attempting to open an item pile.
![image](https://user-images.githubusercontent.com/32039708/158019496-464bdb66-f7bf-40f1-8585-31ccf3fa82d2.png)
When attempting to create an item pile using the item drag & drop option.
![image](https://user-images.githubusercontent.com/32039708/158019497-e4c9d00e-b7ea-4079-8260-8b4cafb298d6.png)

**Setup:**
 - Foundry Version: 9.255
 - System Version: PF2e 3.7.0.10779
 - Item Piles Version: 1.4.6
 - Browser & version: Chrome 98.0.4758.102

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by jpmiers** [comment]
Greetings, I'm having this issue on only one of my worlds. The other worlds function normally. Is there anything I can do aside from scrapping the entire world?

Setup:
Foundry v9.269
PF2 3.10.4.11747
Item Piles 1.4.8

![image](https://user-images.githubusercontent.com/90874471/170847615-6c5879b2-8615-46f3-95b9-d34863e7e8ab.png)

**Comment by Haxxer** [comment]
@jpmiers 

Please create a separate bug for this.
