### ISSUE TITLE
[REQUEST] - Allow system tokens to be drop targets

### ISSUE THREAD

**Issue by dmrickey** [fantasycalendar/FoundryVTT-ItemPiles#85]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to drop existing Items on tokens that aren't necessarily Item Piles

**Describe the solution you'd like**
So right now with Item Piles when I drag an Item onto the scene, it gives me "create pile / cancel", if I drag it onto an existing Item Pile, it gives me "add to pile / cancel". I'd like to add a third case _if I drag it onto a token that is_ **not** _a pile, then give me "add to token / create pile / cancel"_?

**Describe alternatives you've considered**
There are other mods that enable this functionality, but it feels like Item Piles already has the framework to handle this and since they both would be adding drop handlers like this, I don't really want to find out what happens if they're competing for the same event. So I'd rather just have all my eggs in one basket.

**Additional context**
![image](https://user-images.githubusercontent.com/3664822/159082524-d3530dce-4540-429e-9584-14e1507cb859.png)
A quick html edit to duplicate the "create pile" button and add a third option. So basically I'm picturing this but with an icon that differs from the box icon and is still relevant

**Comment by Haxxer** [comment]
This has been added in 2.1.0
