### ISSUE TITLE
[BUG] - Initial Item Pile permissions

### ISSUE THREAD

**Issue by trioderegion** [fantasycalendar/FoundryVTT-ItemPiles#9]
**Describe the bug**
Items or item piles cannot be opened by players until the GM has "inspected" the pile first via CTRL+Double Click.

**To Reproduce**
1. GM or Player Client drops an item onto the canvas (from the sidebar or inventory)
    - Note: There appears to be some sort of history maintained, so be sure that this item is brand new and has not been dropped onto the canvas before.
2. Player Client - move next to item pile and double click. Nothing will happen.
3. GM Client - Double Click to open the item pile's *actor sheet* and close.
4. Player Client - repeat step 2, but now the item pile dialog will show and everything works as expected.

**Expected behavior**
Item Pile should be immediately openable by Players upon item drop.

**Screenshots**

https://user-images.githubusercontent.com/14878515/148391622-b278ab21-6a4f-4529-b81a-821f2fa5f872.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 96.0.1054.62 (Official build) (64-bit)

**Comment by Haxxer** [comment]
Thank you for reporting it - this is known and will be fixed in 1.0.2
