### ISSUE TITLE
[BUG] - Deadly aim (combat)

### ISSUE THREAD

**Issue by cyco-polo** [fantasycalendar/FoundryVTT-ItemPiles#91]
**Describe the bug**
 The feat "Deadly aim (combat)" has a dysfoncyion. I can't press any attack button...no reaction. But if i press on damage, i have a pop up appear normally and can even select deadly aim for damage

**To Reproduce**

Add the feat, click on any type of weapon, press attack...doesn't work

**Expected behavior**

to be able to initiate the attack roll

**Screenshots**
![Capture d’écran 2022-04-03 183611](https://user-images.githubusercontent.com/80625501/161438293-25a80d07-62df-420f-83f3-bd9e55ecf31c.png)
you can click "attaque" but nothing happens (tried with melee or other types of weapon with same result)

![Capture d’écran 2022-04-03 182707](https://user-images.githubusercontent.com/80625501/161438045-e53972ab-c688-4028-adbc-96bfeaa4df1a.png)
If you skip the attack and press "dommage" it works

**Setup:**
 - Foundry Version:9.255
 - System Version: Starfinder 0.18.2
 - Item Piles Version: [e.g. 1.0.0]
 - Browser & version Google Chrome Version 99.0.4844.84 (Build officiel) (64 bits)

**Comment by Haxxer** [comment]
How is this related to Item Piles?

**Comment by cyco-polo** [comment]
Oops...my fault clicked on the wrong github...sorry sorry
