### ISSUE TITLE
[REQUEST] - Wildcard images for containers

### ISSUE THREAD

**Issue by crazycalya** [fantasycalendar/FoundryVTT-ItemPiles#93]
**Currently:** Direct image paths are required for container states. Variant containers require discrete piles and therefore more actors to be configured/loaded. 

**Proposed:** Allow for wildcard images similar to how default prototype tokens work. An example would be a chest, where the "closed" remains the same image but the "open" would randomly select from different images and variable contents. For example:

![wildcard_example](https://user-images.githubusercontent.com/9976394/164984550-4af29ce2-4cec-46ea-b4da-2b595a8891ad.PNG)

**Alternatives:** Currently single-state piles can utilize wildcard tokens by using the default prototype token for the container. This doesn't allow for it to be "opened" or "closed" but could with a different approach. Currently if only 1 image is selected for any container state it will only show that image regardless of the item's state. For example: 

![box_example](https://user-images.githubusercontent.com/9976394/164984414-78be1ff1-16ab-4a73-acfe-e6070bbe3f9d.PNG)

This could also be changed to allow for more unique configurations by allowing a state to be "empty". With this the item could default to the prototype token which would allow for wildcard images in one state. In the above example we could have a wildcard prototype for the "closed" state of the box and keep the "open" image static. Here's a rough example of what I mean:

![prototype_example](https://user-images.githubusercontent.com/9976394/164984780-c2a2bc0d-2d10-40a2-a82a-74f11fc1ff8a.PNG)

**Comment by dmrickey** [comment]
But if my wildcard path has red/green/blue chests, what's to guarantee that the chest will remain the same color after being opened?

**Comment by crazycalya** [comment]
> 

Using my **proposed** solution you'd need to account for that with your filenames. For example rather than:
```
chest_gems_red.webp
chest_gems_green.webp
chest_coins_red.webp
chest_coins_green.webp
```
You'd use:
```
chest_red_opened_gems.webp
chest_red_opened_coins.webp
chest_green_opened_gems.webp
chest_green_opened_coins.webp
```
Meaning your Item Pile would be configured as:
```
Closed: chest_red_closed
Opened: chest_red_opened*
Empty: chest_red_empty
```
If your concern would be that chest contents would change each time they're interacted with, I would hope this would be considered in the implementation. Currently wildcard tokens do not change their image selection once dropped onto the screen. The Item Pile would need to remember what wildcard it selected between states. 

With my **alternative** solution you would only need the Item Pile to remember a random token image for a single state as the other states fall back on the vanilla token prototype.

**Comment by dmrickey** [comment]
Ah, I misunderstood. I thought you wanted a directory and pick random files
from within the directory
