### ISSUE TITLE
Quantity cannot be set to number greater than zero

### ISSUE THREAD

**Issue by jackklika** [fantasycalendar/FoundryVTT-ItemPiles#94]
Hi, I'm using GURPS 4e system which I understand is not supported, but maybe this issue has a simple resolution.

How to Reproduce:

1. Use GURPS 4e system and create a world
2. Create an item and drop into world
3. Create new Pile with that item
4. Double click on token in world. Quantity of item is zero.
5. Set quantity to number greater than 0, and click update
6. Quantity reverts back to 1. 

I've enabled the debug output and played around with some of the javascript objects with no luck. Let me know if there is any other troubleshooting I can try.

EDIT:
I'm not too familiar with this codebase, so this may be a case where since I am using an unsupported system it can't set the quantity data. In this case I can try adding Gurps 4e as a supported system via PR if it isn't too hard

**Comment by Haxxer** [comment]
Have you set your module settings to the proper attributes?

**Comment by dylanwalton18** [comment]
Could you give some guidance to what the proper attributes would be or where to find them. I’m having the same problem and I have no idea what to put.

**Comment by Haxxer** [comment]
You didn't mention the game system you play in, besides, I cannot offer support for the module for systems I don't personally use. I would recommend taking screenshots of the Item Piles system configuration interface and post it in the relevant Foundry discord server channel for that system.

**Comment by dylanwalton18** [comment]
Ok! I’ll look around and see what I can find. Thanks!
