### ISSUE TITLE
[REQUEST] - Hide Currencies list in Item Pile

### ISSUE THREAD

**Issue by aestrada4355** [fantasycalendar/FoundryVTT-ItemPiles#96]
Apologies if this is currently an option, I looked in the module and item pile settings but I couldn't find anything.

Currently, if an Item Pile is inspected the window displays Currencies regardless of whether or not the Creature/Item Pile has any Currency available.

Would it be possible to auto-hide or disable the Currencies from the Item Pile window, if either a) the creature has no Currency at all, or hide the individual currency denomination?

Current output.
![image](https://user-images.githubusercontent.com/67869538/166151816-a47fc1c0-79f7-4c5d-99c2-35665228fc1b.png)

Only display available currencies:
![image](https://user-images.githubusercontent.com/67869538/166151849-f87d26bc-3545-48e9-95b3-123c816533c3.png)

**Comment by Haxxer** [comment]
You cannot edit currencies on NPC sheets, so this is a deliberate choice. It's either this, or no currencies on NPCs

**Comment by Haxxer** [comment]
You cannot edit currencies on NPC sheets, so this is a deliberate choice. It's either this, or no currencies on NPCs

**Comment by Haxxer** [comment]
This is only visible to the GM anyway, so closing ticket.
