### ISSUE TITLE
[BUG] Currencies are not translated in chat cards in PF1

### ISSUE THREAD

**Issue by mkahvi** [fantasycalendar/FoundryVTT-ItemPiles#97]
**Describe the bug**
Currency names show translation key rather than the actual string in chat card.

They show up fine in the loot dialog.

**To Reproduce**
1. Include money & loot it

**Setup:**
 - Foundry Version: 9.269
 - System Version: PF1 0.80.22
 - Item Piles Version: 1,4.8

**Screenshots**
![Screenshot 2022-05-15 082935](https://user-images.githubusercontent.com/8120158/168458590-de8d9cfa-6586-4c5e-9189-1a8e0dd25077.png)

**Comment by joshua-igor** [comment]
You can change the currency name on the module's settings > Configure Currencies > Currency Name.

**Comment by mkahvi** [comment]
The currency name is correct there. At least the translation key is. It's just not passed through localization function.
